// Script to inject questions for Worlds 2-6
const fs = require('fs');

function serializeQuestion(q) {
  if (q.tipo === 'mini_quiz') {
    const opts = q.opciones.map(o => `"${o.replace(/"/g, '\\"')}"`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'mini_quiz', pregunta: "${q.pregunta.replace(/"/g, '\\"')}", opciones: [${opts}], respuestaCorrecta: ${q.respuestaCorrecta}, explicacion: "${q.explicacion.replace(/"/g, '\\"')}" }`;
  }
  if (q.tipo === 'true_false') {
    const stmts = q.statements.map(s => `{ text: '${s.text.replace(/'/g, "\\'")}', correct: ${s.correct}, explain: '${s.explain.replace(/'/g, "\\'")}' }`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'true_false', statements: [${stmts}] }`;
  }
  if (q.tipo === 'matching_game') {
    const pairs = q.pairs.map(p => `{ left: '${p.left.replace(/'/g, "\\'")}', right: '${p.right.replace(/'/g, "\\'")}' }`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'matching_game', instruccion: '${(q.instruccion||'Conecta los conceptos').replace(/'/g, "\\'")}', pairs: [${pairs}] }`;
  }
  return JSON.stringify(q);
}

function injectQuestions(filePath, extraQuestions) {
  let src = fs.readFileSync(filePath, 'utf-8');
  let offset = 0;
  let count = 0;
  
  for (const [moduleId, questions] of Object.entries(extraQuestions)) {
    if (!questions || questions.length === 0) continue;
    
    const idPattern = `id: '${moduleId}'`;
    const idIdx = src.indexOf(idPattern, offset);
    if (idIdx === -1) { console.log(`WARNING: ${moduleId} not found`); continue; }
    
    const ctSearch = src.indexOf('contenidoTeorico:', idIdx);
    if (ctSearch === -1 || ctSearch - idIdx > 3000) continue;
    
    const bracketStart = src.indexOf('[', ctSearch);
    if (bracketStart === -1) continue;
    
    let depth = 0, closingIdx = -1;
    for (let i = bracketStart; i < src.length; i++) {
      if (src[i] === '[') depth++;
      else if (src[i] === ']') { depth--; if (depth === 0) { closingIdx = i; break; } }
    }
    if (closingIdx === -1) continue;
    
    const insertions = questions.map(q => '\n            ' + serializeQuestion(q) + ',').join('');
    src = src.slice(0, closingIdx) + insertions + src.slice(closingIdx);
    offset = closingIdx + insertions.length;
    count += questions.length;
    console.log(`  ✅ ${moduleId}: +${questions.length}`);
  }
  
  fs.writeFileSync(filePath, src, 'utf-8');
  console.log(`  💾 Saved (${count} questions added)\n`);
}

// ============================================
// WORLD 2: La Fábrica de Autómatas
// ============================================
const W2 = {
  'w2_mod1_ultrasonico': [ // has 4, need 6
    { titulo: "✅ Quiz: Velocidad del Sonido", tipo: 'mini_quiz', pregunta: "¿A qué velocidad viaja el sonido en el aire (aproximadamente)?", opciones: ["100 m/s", "343 m/s", "1000 m/s", "3000 m/s"], respuestaCorrecta: 1, explicacion: "El sonido viaja a ~343 m/s en el aire a 20°C. El HC-SR04 usa esto para calcular distancia. 🔊" },
    { titulo: "✅ Quiz: Trigger y Echo", tipo: 'mini_quiz', pregunta: "¿Qué pin del HC-SR04 ENVÍA el pulso ultrasónico?", opciones: ["Echo", "Trigger", "VCC", "GND"], respuestaCorrecta: 1, explicacion: "Trigger envía el pulso, Echo recibe el rebote. Trigger = disparador, Echo = eco. 🦇" },
    { titulo: "✅ Quiz: Cálculo de Distancia", tipo: 'mini_quiz', pregunta: "¿Por qué se divide entre 2 el tiempo del eco en el cálculo de distancia?", opciones: ["Por error del sensor", "Porque el sonido va y VUELVE (ida y vuelta)", "Para mayor precisión", "No se divide"], respuestaCorrecta: 1, explicacion: "El sonido recorre la distancia 2 veces: va al objeto y regresa. Dividir entre 2 da la distancia real. 📏" },
    { titulo: "✅❌ Ultrasónico: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El HC-SR04 puede medir distancias de hasta 4 metros.', correct: true, explain: 'Su rango es de 2 a 400 cm (4 metros).' }, { text: 'El sensor ultrasónico funciona con luz infrarroja.', correct: false, explain: 'Usa ondas de SONIDO (ultrasonido), no luz. Por eso funciona en la oscuridad.' }] },
    { titulo: "🧩 Sensor Ultrasónico", tipo: 'matching_game', instruccion: 'Conecta cada pin con su función', pairs: [{ left: 'VCC', right: 'Alimentación 5V' }, { left: 'GND', right: 'Tierra/Negativo' }, { left: 'Trigger', right: 'Envía pulso' }, { left: 'Echo', right: 'Recibe eco' }] },
    { titulo: "✅ Quiz: Zona Muerta", tipo: 'mini_quiz', pregunta: "¿Cuál es la distancia mínima que puede medir el HC-SR04?", opciones: ["0 cm", "2 cm", "10 cm", "50 cm"], respuestaCorrecta: 1, explicacion: "El HC-SR04 tiene una zona muerta de 2 cm. Distancias menores no se miden correctamente. 📐" },
  ],
  'w2_mod2_infrarrojo': [ // has 3, need 7
    { titulo: "✅ Quiz: Principio IR", tipo: 'mini_quiz', pregunta: "¿Cómo distingue un sensor IR una línea negra del suelo blanco?", opciones: ["Por la temperatura", "El negro absorbe la luz IR y el blanco la refleja", "Por el peso", "No puede distinguir"], respuestaCorrecta: 1, explicacion: "Las superficies blancas reflejan la luz IR de vuelta al sensor; las negras la absorben. ¡Así sigue la línea! 🛤️" },
    { titulo: "✅ Quiz: Siguelíneas", tipo: 'mini_quiz', pregunta: "¿Cuántos sensores IR mínimos necesita un robot siguelíneas básico?", opciones: ["1 sensor", "2 sensores", "5 sensores", "10 sensores"], respuestaCorrecta: 1, explicacion: "Con 2 sensores (izquierdo y derecho) el robot puede seguir una línea: si el izquierdo detecta negro, gira a la izquierda. 🤖" },
    { titulo: "✅ Quiz: Calibración", tipo: 'mini_quiz', pregunta: "¿Por qué es importante calibrar los sensores IR antes de usarlos?", opciones: ["Solo por estética", "Porque la luz ambiental afecta las lecturas", "No necesitan calibración", "Para que sean más caros"], respuestaCorrecta: 1, explicacion: "La luz ambiental y el color exacto del piso afectan las lecturas. Calibrar ajusta los umbrales para cada ambiente. ⚙️" },
    { titulo: "✅ Quiz: Digital vs Analógico", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene un sensor IR con salida ANALÓGICA sobre uno digital?", opciones: ["Es más barato", "Puede medir qué tan cerca está de la línea, no solo si está o no", "No tiene ventaja", "Es más pequeño"], respuestaCorrecta: 1, explicacion: "La salida analógica da un rango de valores (0-1023), permitiendo saber la posición exacta del robot respecto a la línea. 📊" },
    { titulo: "✅❌ Sensor IR: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un sensor IR puede detectar líneas de cualquier color sobre cualquier fondo.', correct: false, explain: 'Funciona mejor con alto contraste: línea oscura sobre fondo claro.' }, { text: 'Los sensores IR emiten luz invisible al ojo humano.', correct: true, explain: 'La luz infrarroja tiene longitud de onda mayor que la luz visible, no podemos verla.' }] },
    { titulo: "🧩 Control Siguelíneas", tipo: 'matching_game', instruccion: 'Conecta la lectura del sensor con la acción', pairs: [{ left: 'Ambos en blanco', right: 'Avanzar recto' }, { left: 'Izquierdo en negro', right: 'Girar a la izquierda' }, { left: 'Derecho en negro', right: 'Girar a la derecha' }, { left: 'Ambos en negro', right: 'Detenerse o cruce' }] },
    { titulo: "✅ Quiz: Velocidad del Robot", tipo: 'mini_quiz', pregunta: "Si un robot siguelíneas va muy rápido, ¿qué puede pasar?", opciones: ["Sigue mejor la línea", "Se sale de la línea en las curvas", "Los sensores mejoran", "Nada"], respuestaCorrecta: 1, explicacion: "A alta velocidad el robot no puede reaccionar a tiempo en las curvas. ¡La velocidad debe ajustarse a la complejidad del camino! 🏎️" },
  ],
  'w2_mod3_temp_hum': [ // has 3, need 7
    { titulo: "✅ Quiz: DHT11", tipo: 'mini_quiz', pregunta: "¿Qué dos variables mide el sensor DHT11?", opciones: ["Luz y sonido", "Temperatura y humedad", "Distancia y velocidad", "Presión y altitud"], respuestaCorrecta: 1, explicacion: "DHT11 mide Temperatura (0-50°C, ±2°) y Humedad relativa (20-80%). ¡Un mini meteorólogo! 🌡️" },
    { titulo: "✅ Quiz: Rango DHT11", tipo: 'mini_quiz', pregunta: "¿Cuál es el rango de temperatura del DHT11?", opciones: ["-40°C a 80°C", "0°C a 50°C", "-20°C a 100°C", "10°C a 30°C"], respuestaCorrecta: 1, explicacion: "El DHT11 mide de 0 a 50°C. Para rangos mayores se usa el DHT22 (-40 a 80°C). 🌡️" },
    { titulo: "✅ Quiz: DHT22 vs DHT11", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene el DHT22 sobre el DHT11?", opciones: ["Es más barato", "Mayor rango y precisión", "Es más pequeño", "No necesita librería"], respuestaCorrecta: 1, explicacion: "DHT22: -40 a 80°C (±0.5°) vs DHT11: 0 a 50°C (±2°). ¡Más rango y más preciso! 📊" },
    { titulo: "✅ Quiz: Humedad", tipo: 'mini_quiz', pregunta: "¿Qué significa una humedad relativa del 80%?", opciones: ["Que el 80% del aire es agua", "Que el aire tiene el 80% de la humedad máxima que puede contener", "Que llueve al 80%", "Que la temperatura es 80°C"], respuestaCorrecta: 1, explicacion: "Humedad relativa es el porcentaje de agua en el aire respecto al máximo que puede contener a esa temperatura. 💧" },
    { titulo: "✅❌ Clima Robótico: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El DHT11 necesita una librería especial en Arduino para funcionar.', correct: true, explain: 'Usa la librería DHT.h para leer los datos digitales del sensor.' }, { text: 'Un sensor de temperatura puede sustituir completamente a un termómetro médico.', correct: false, explain: 'Los sensores como DHT11 no tienen la precisión necesaria para uso médico (±2°C de error).' }] },
    { titulo: "🧩 Sensores de Clima", tipo: 'matching_game', instruccion: 'Conecta cada sensor con su especialidad', pairs: [{ left: 'DHT11', right: 'Temp + humedad básico' }, { left: 'DHT22', right: 'Temp + humedad preciso' }, { left: 'LM35', right: 'Solo temperatura analógico' }, { left: 'BMP280', right: 'Presión + altitud' }] },
    { titulo: "✅ Quiz: Aplicaciones", tipo: 'mini_quiz', pregunta: "¿Para qué usaría un robot los datos de temperatura y humedad?", opciones: ["Para nada", "Para controlar riego automático o clima de invernadero", "Para cambiar de color", "Para ir más rápido"], respuestaCorrecta: 1, explicacion: "¡Automatización! Un robot puede activar ventiladores si hace calor o riego si la humedad es baja. 🌱" },
  ],
  'w2_mod4_luz_color': [ // has 2, need 8
    { titulo: "✅ Quiz: LDR", tipo: 'mini_quiz', pregunta: "¿Qué le pasa a la resistencia de un LDR cuando hay mucha luz?", opciones: ["Aumenta mucho", "Disminuye", "Se mantiene igual", "Se rompe"], respuestaCorrecta: 1, explicacion: "LDR = resistencia dependiente de luz. Más luz = MENOS resistencia. En oscuridad, la resistencia es muy alta. 💡" },
    { titulo: "✅ Quiz: RGB", tipo: 'mini_quiz', pregunta: "¿Qué colores primarios usa un LED RGB?", opciones: ["Cyan, Magenta, Amarillo", "Rojo, Verde, Azul", "Rojo, Amarillo, Azul", "Blanco, Negro, Gris"], respuestaCorrecta: 1, explicacion: "RGB = Red (rojo), Green (verde), Blue (azul). Mezclándolos con PWM puedes crear cualquier color. 🌈" },
    { titulo: "✅ Quiz: PWM y Color", tipo: 'mini_quiz', pregunta: "¿Qué valor PWM necesitas enviar a los 3 canales del LED RGB para obtener luz BLANCA?", opciones: ["R=255, G=0, B=0", "R=0, G=0, B=255", "R=255, G=255, B=255", "R=0, G=0, B=0"], respuestaCorrecta: 2, explicacion: "¡Los 3 al máximo! Rojo + Verde + Azul al 100% = Blanco. Con R=G=B=0 está apagado. 🤍" },
    { titulo: "✅ Quiz: Sensor de Luz Solar", tipo: 'mini_quiz', pregunta: "¿Cómo podría un robot usar un LDR para buscar la luz solar?", opciones: ["Medir temperatura", "Girar hacia donde el LDR detecte más luz", "No puede", "Medir distancia"], respuestaCorrecta: 1, explicacion: "Con 2 LDRs (izquierdo y derecho), el robot gira hacia el que detecte más luz. ¡Como un girasol robótico! 🌻" },
    { titulo: "✅❌ Luz y Color: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Mezclando rojo y verde en un LED RGB se obtiene amarillo.', correct: true, explain: 'En luz (modelo aditivo): R+G = Amarillo, R+B = Magenta, G+B = Cyan.' }, { text: 'Un LDR genera electricidad como un panel solar.', correct: false, explain: 'El LDR solo cambia su resistencia con la luz. No genera energía.' }] },
    { titulo: "🧩 Colores RGB", tipo: 'matching_game', instruccion: 'Conecta cada mezcla RGB con el color resultante', pairs: [{ left: 'R=255, G=0, B=0', right: 'Rojo' }, { left: 'R=0, G=255, B=0', right: 'Verde' }, { left: 'R=255, G=255, B=0', right: 'Amarillo' }, { left: 'R=255, G=0, B=255', right: 'Magenta' }] },
    { titulo: "✅ Quiz: Divisor de Voltaje", tipo: 'mini_quiz', pregunta: "¿Por qué se usa un divisor de voltaje con el LDR para conectarlo al Arduino?", opciones: ["Para que sea más bonito", "Para convertir el cambio de resistencia en un cambio de voltaje legible", "Para ahorrar energía", "No se necesita"], respuestaCorrecta: 1, explicacion: "El Arduino lee voltaje (0-5V), no resistencia. El divisor de voltaje con una resistencia fija convierte la variación del LDR en voltaje. 📊" },
    { titulo: "✅ Quiz: Luz Ambiental", tipo: 'mini_quiz', pregunta: "¿Qué aplicación tiene un sensor de luz en un robot?", opciones: ["Decoración", "Encender luces automáticamente cuando oscurece", "Medir peso", "Contar objetos"], respuestaCorrecta: 1, explicacion: "¡Automatización! Un robot puede encender LEDs cuando detecta oscuridad, como las luces automáticas del carro. 🚗💡" },
  ],
  'w2_mod5_chasis': [ // has 2, need 8
    { titulo: "✅ Quiz: Material del Chasis", tipo: 'mini_quiz', pregunta: "¿Qué material es más fácil para construir el primer chasis de un robot?", opciones: ["Titanio", "Cartón reciclado", "Vidrio", "Cemento"], respuestaCorrecta: 1, explicacion: "¡Cartón! Es gratis, fácil de cortar, liviano y puedes rediseñar sin gastar. Perfecto para prototipos. ♻️" },
    { titulo: "✅ Quiz: Centro de Gravedad", tipo: 'mini_quiz', pregunta: "¿Dónde debe estar el centro de gravedad de un robot con ruedas para mayor estabilidad?", opciones: ["Arriba", "Al frente", "Bajo y centrado", "Atrás"], respuestaCorrecta: 2, explicacion: "Centro de gravedad bajo y centrado = máxima estabilidad. Las baterías (lo más pesado) van en la base. ⚖️" },
    { titulo: "✅ Quiz: Tracción", tipo: 'mini_quiz', pregunta: "¿Cuántas ruedas motrices tiene un robot diferencial típico?", opciones: ["1", "2", "4", "6"], respuestaCorrecta: 1, explicacion: "Un robot diferencial tiene 2 ruedas motrices independientes + 1 rueda loca de apoyo. Gira cambiando la velocidad de cada rueda. 🛞" },
    { titulo: "✅ Quiz: Rueda Loca", tipo: 'mini_quiz', pregunta: "¿Para qué sirve la rueda loca (castor) en un robot?", opciones: ["Para ir más rápido", "Para dar soporte y equilibrio sin motor", "Para frenar", "Para girar el volante"], respuestaCorrecta: 1, explicacion: "La rueda loca solo da soporte: gira libremente en cualquier dirección. Los motores están en las otras 2 ruedas. 🔄" },
    { titulo: "✅❌ Chasis: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un robot más pesado siempre es más estable.', correct: false, explain: 'Depende de la distribución del peso. Un robot pesado mal balanceado se voltea fácilmente.' }, { text: 'Es importante dejar espacio accesible para cambiar baterías.', correct: true, explain: 'Un buen diseño permite mantenimiento fácil sin desarmar todo el robot.' }] },
    { titulo: "🧩 Materiales y Propiedades", tipo: 'matching_game', instruccion: 'Conecta cada material con su mejor característica', pairs: [{ left: '📦 Cartón', right: 'Barato y fácil de cortar' }, { left: '🧱 Acrílico', right: 'Resistente y transparente' }, { left: '🖨️ PLA (impresión 3D)', right: 'Personalizable y preciso' }, { left: '🔩 Aluminio', right: 'Liviano y muy fuerte' }] },
    { titulo: "✅ Quiz: Distribución de Componentes", tipo: 'mini_quiz', pregunta: "¿Dónde debes colocar el Arduino en el chasis?", opciones: ["Debajo de las ruedas", "En un lugar accesible y protegido", "Fuera del chasis", "No importa"], respuestaCorrecta: 1, explicacion: "El Arduino debe estar accesible (para conectar USB y sensores) y protegido de impactos o cortocircuitos. 🔧" },
    { titulo: "✅ Quiz: Tamaño Ideal", tipo: 'mini_quiz', pregunta: "¿Cuál es un buen tamaño para un robot de competencia básico?", opciones: ["5 cm x 5 cm", "15 cm x 20 cm", "1 metro x 1 metro", "50 cm x 50 cm"], respuestaCorrecta: 1, explicacion: "~15-20 cm es ideal: suficiente espacio para componentes, pero compacto y maniobrable. ¡La mayoría de torneos tienen límites de tamaño! 📐" },
  ],
  'w2_mod6_motores_avanzado': [ // has 2, need 8
    { titulo: "✅ Quiz: PWM Velocidad", tipo: 'mini_quiz', pregunta: "¿Qué valor de analogWrite() da la MÁXIMA velocidad al motor?", opciones: ["0", "127", "255", "1023"], respuestaCorrecta: 2, explicacion: "analogWrite va de 0 (parado) a 255 (máxima velocidad). 127 = velocidad media. 🏎️" },
    { titulo: "✅ Quiz: Aceleración Suave", tipo: 'mini_quiz', pregunta: "¿Por qué es mejor acelerar gradualmente un motor en vez de ponerlo al máximo de golpe?", opciones: ["Por estética", "Para proteger el motor y mejorar la tracción", "Para ir más lento", "No hay razón"], respuestaCorrecta: 1, explicacion: "La aceleración gradual protege los engranajes, evita patinaje de ruedas y reduce picos de corriente. 📈" },
    { titulo: "✅ Quiz: Giro Diferencial", tipo: 'mini_quiz', pregunta: "¿Cómo gira un robot diferencial hacia la DERECHA?", opciones: ["Ambos motores a la misma velocidad", "Motor izquierdo más rápido que el derecho", "Motor derecho más rápido que el izquierdo", "Ambos motores apagados"], respuestaCorrecta: 1, explicacion: "Para girar a la derecha: el motor izquierdo va más rápido, el derecho más lento (o al revés). ¡Diferencia de velocidad = giro! 🔄" },
    { titulo: "✅ Quiz: Giro sobre su Eje", tipo: 'mini_quiz', pregunta: "¿Cómo haces que un robot diferencial gire sobre su propio eje?", opciones: ["Un motor adelante, otro atrás", "Ambos motores adelante", "Apagando todo", "Solo un motor encendido"], respuestaCorrecta: 0, explicacion: "¡Motores girando en direcciones opuestas! Uno adelante y otro atrás hace que rote sobre su centro. ¡Giro en el lugar! 🔄" },
    { titulo: "✅❌ Motores: ¿V o F?", tipo: 'true_false', statements: [{ text: 'PWM simula voltajes intermedios encendiendo y apagando el pin muy rápido.', correct: true, explain: 'PWM = Modulación por Ancho de Pulso. Alterna HIGH/LOW muy rápido para simular voltaje medio.' }, { text: 'Para frenar un motor basta con poner PWM en 127.', correct: false, explain: 'PWM 127 es media velocidad, no freno. Para frenar: ambos IN a LOW o ambos a HIGH (freno activo).' }] },
    { titulo: "🧩 Velocidad y Control", tipo: 'matching_game', instruccion: 'Conecta cada PWM con su resultado', pairs: [{ left: 'analogWrite(0)', right: 'Motor parado' }, { left: 'analogWrite(64)', right: '25% velocidad' }, { left: 'analogWrite(127)', right: '50% velocidad' }, { left: 'analogWrite(255)', right: '100% velocidad' }] },
    { titulo: "✅ Quiz: Corriente del Motor", tipo: 'mini_quiz', pregunta: "¿Por qué un motor consume más corriente al arrancar que cuando ya está girando?", opciones: ["Error del motor", "Al inicio necesita vencer la inercia (corriente de arranque)", "Consume menos al inicio", "No hay diferencia"], respuestaCorrecta: 1, explicacion: "La corriente de arranque puede ser 3-5 veces la normal. Por eso se recomienda aceleración gradual. ⚡" },
    { titulo: "✅ Quiz: Encoders", tipo: 'mini_quiz', pregunta: "¿Para qué sirve un encoder en un motor de robot?", opciones: ["Para decorar", "Para medir la velocidad y distancia recorrida por la rueda", "Para encender LEDs", "Para medir temperatura"], respuestaCorrecta: 1, explicacion: "Los encoders cuentan las vueltas/grados del motor, permitiendo medir distancia recorrida y velocidad exacta. 📊" },
  ],
  'w2_mod7_servo_garra': [ // has 2, need 8
    { titulo: "✅ Quiz: Rango del Servo", tipo: 'mini_quiz', pregunta: "¿Cuál es el rango de movimiento típico de un micro servo SG90?", opciones: ["0° a 90°", "0° a 180°", "0° a 360°", "-90° a 90°"], respuestaCorrecta: 1, explicacion: "El SG90 se mueve de 0° a 180° con gran precisión. Para giro continuo se necesita un servo especial. 🎯" },
    { titulo: "✅ Quiz: Señal del Servo", tipo: 'mini_quiz', pregunta: "¿Qué tipo de señal controla un servo motor?", opciones: ["Voltaje analógico", "Señal PWM (pulsos de diferente ancho)", "Señal de audio", "Corriente continua directa"], respuestaCorrecta: 1, explicacion: "Los servos usan PWM: un pulso de 1ms = 0°, 1.5ms = 90°, 2ms = 180°. ¡El ancho del pulso determina el ángulo! 📏" },
    { titulo: "✅ Quiz: Servo.write()", tipo: 'mini_quiz', pregunta: "¿Qué hace Servo.write(90) en Arduino?", opciones: ["Gira el servo a 90 grados", "Apaga el servo", "Gira 90 vueltas", "Espera 90 segundos"], respuestaCorrecta: 0, explicacion: "Servo.write(90) mueve el servo exactamente a la posición de 90°. ¡Puedes poner cualquier ángulo de 0 a 180! 🎯" },
    { titulo: "✅ Quiz: Garra Robótica", tipo: 'mini_quiz', pregunta: "¿Cuántos servos necesitas como mínimo para una garra que abre y cierra?", opciones: ["0", "1", "3", "5"], respuestaCorrecta: 1, explicacion: "¡Solo 1 servo! Con un mecanismo de pinza, un servo mueve ambos dedos simultáneamente. 🦾" },
    { titulo: "✅❌ Servos: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un servo motor tiene engranajes internos y un sensor de posición.', correct: true, explain: 'Dentro tiene motor DC + engranajes + potenciómetro para saber su posición.' }, { text: 'Los servos se alimentan directamente desde los pines digitales del Arduino.', correct: false, explain: 'Necesitan alimentación de 5V separada (pin de alimentación), el pin digital solo envía la señal de control.' }] },
    { titulo: "🧩 Ángulos y Posiciones", tipo: 'matching_game', instruccion: 'Conecta cada comando con la posición del servo', pairs: [{ left: 'myServo.write(0)', right: 'Extremo izquierdo' }, { left: 'myServo.write(90)', right: 'Posición central' }, { left: 'myServo.write(180)', right: 'Extremo derecho' }, { left: 'myServo.write(45)', right: 'Medio-izquierda' }] },
    { titulo: "✅ Quiz: Brazo Robótico", tipo: 'mini_quiz', pregunta: "Para un brazo robótico con 3 grados de libertad (base, codo, garra), ¿cuántos servos necesitas?", opciones: ["1", "2", "3", "6"], respuestaCorrecta: 2, explicacion: "Un servo por articulación: 1 para la base (girar), 1 para el codo (subir/bajar), 1 para la garra (abrir/cerrar). 🤖" },
    { titulo: "✅ Quiz: Torque del Servo", tipo: 'mini_quiz', pregunta: "¿Qué significa que un servo tiene 1.8 kg·cm de torque?", opciones: ["Pesa 1.8 kg", "Puede levantar 1.8 kg a 1 cm del eje", "Gira 1.8 veces por segundo", "Mide 1.8 cm"], respuestaCorrecta: 1, explicacion: "1.8 kg·cm significa que a 1 cm del eje puede ejercer fuerza de 1.8 kg. A 2 cm serían 0.9 kg. ¡Torque es fuerza × distancia! 💪" },
  ],
  'w2_mod8_evasion': [ // has 1, need 9
    { titulo: "✅ Quiz: Algoritmo de Evasión", tipo: 'mini_quiz', pregunta: "¿Cuál es el algoritmo básico de un robot evasor de obstáculos?", opciones: ["Medir-Decidir-Actuar", "Solo avanzar siempre", "Girar aleatoriamente", "Esperar instrucciones"], respuestaCorrecta: 0, explicacion: "Medir (sensor ultrasónico) → Decidir (¿hay obstáculo?) → Actuar (avanzar o girar). ¡El ciclo se repite! 🔄" },
    { titulo: "✅ Quiz: Distancia de Seguridad", tipo: 'mini_quiz', pregunta: "¿A qué distancia debería un robot empezar a frenar para evitar chocar?", opciones: ["1 cm", "20-30 cm", "5 metros", "0 cm (al tocar)"], respuestaCorrecta: 1, explicacion: "20-30 cm da tiempo suficiente para frenar y girar. Depende de la velocidad del robot. ¡Mejor prevenir! 🛑" },
    { titulo: "✅ Quiz: Dirección de Giro", tipo: 'mini_quiz', pregunta: "Si el robot detecta un obstáculo al frente, ¿cómo decide si girar a la izquierda o derecha?", opciones: ["Siempre gira a la derecha", "Puede girar al azar o usar sensores laterales", "No puede girar", "Retrocede y se apaga"], respuestaCorrecta: 1, explicacion: "Con un solo sensor, puede girar al azar. Con sensores laterales, gira hacia el lado con más espacio libre. 🧭" },
    { titulo: "✅ Quiz: Múltiples Sensores", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene un robot evasor con 3 sensores (izquierda, centro, derecha)?", opciones: ["Es más caro", "Puede detectar obstáculos en 3 direcciones y elegir mejor camino", "Es más lento", "No tiene ventaja"], respuestaCorrecta: 1, explicacion: "Con 3 sensores el robot sabe DÓNDE está el obstáculo y elige el lado más libre. ¡Navegación inteligente! 🤖" },
    { titulo: "✅ Quiz: Velocidad Adaptativa", tipo: 'mini_quiz', pregunta: "¿Por qué un robot debería ir más lento cuando detecta objetos cerca?", opciones: ["Para ahorrar batería", "Para tener más tiempo de reacción y evitar colisiones", "Para hacer menos ruido", "No debería"], respuestaCorrecta: 1, explicacion: "Velocidad adaptativa: rápido si el camino está libre, lento cerca de obstáculos. ¡Como conducir en una calle estrecha! 🚗" },
    { titulo: "✅❌ Robot Evasor: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un robot evasor necesita al menos un sensor de distancia y dos motores.', correct: true, explain: 'El sensor detecta obstáculos, los 2 motores permiten girar y avanzar.' }, { text: 'El robot evasor necesita un mapa del ambiente para funcionar.', correct: false, explain: 'Un evasor básico reacciona en tiempo real sin mapa. Solo necesita sensores.' }] },
    { titulo: "🧩 Situación y Acción", tipo: 'matching_game', instruccion: 'Conecta cada situación con la acción correcta del robot', pairs: [{ left: 'Camino libre (>30cm)', right: 'Avanzar a velocidad normal' }, { left: 'Obstáculo cerca (<20cm)', right: 'Frenar y girar' }, { left: 'Obstáculo muy cerca (<10cm)', right: 'Retroceder y girar' }, { left: 'Espacio libre a la derecha', right: 'Girar a la derecha' }] },
    { titulo: "✅ Quiz: Mejoras del Evasor", tipo: 'mini_quiz', pregunta: "¿Cómo podrías mejorar un robot evasor básico?", opciones: ["Quitarle sensores", "Agregar más sensores, mapeo y memoria de obstáculos", "Hacerlo más pesado", "Pintarlo de otro color"], respuestaCorrecta: 1, explicacion: "Más sensores + memoria + mapeo = navegación más inteligente. ¡De evasor simple a explorador autónomo! 🚀" },
    { titulo: "✅ Quiz: Bucle Principal", tipo: 'mini_quiz', pregunta: "En el loop() de un robot evasor, ¿qué se ejecuta primero?", opciones: ["Mover los motores", "Leer el sensor de distancia", "Encender los LEDs", "Imprimir en pantalla"], respuestaCorrecta: 1, explicacion: "Primero LEER sensores, luego DECIDIR qué hacer, y finalmente ACTUAR con los motores. Sentir → Pensar → Actuar. 🔄" },
  ],
  'w2_mod9_serial': [ // has 2, need 8
    { titulo: "✅ Quiz: Baudios", tipo: 'mini_quiz', pregunta: "¿Qué son los baudios en comunicación serial?", opciones: ["Un tipo de cable", "La velocidad de transmisión de datos (bits por segundo)", "Un sensor", "Una marca de Arduino"], respuestaCorrecta: 1, explicacion: "Baudios = bits por segundo. 9600 baudios es el estándar. ¡El Arduino y la PC deben usar la misma velocidad! 📡" },
    { titulo: "✅ Quiz: Serial.println", tipo: 'mini_quiz', pregunta: "¿Cuál es la diferencia entre Serial.print() y Serial.println()?", opciones: ["No hay diferencia", "println agrega un salto de línea al final", "print es más rápido", "println solo imprime números"], respuestaCorrecta: 1, explicacion: "println = print + new line. Cada mensaje aparece en una línea nueva. print pone todo seguido en la misma línea. ↵" },
    { titulo: "✅ Quiz: Serial.parseInt", tipo: 'mini_quiz', pregunta: "¿Para qué sirve Serial.parseInt() en Arduino?", opciones: ["Para imprimir enteros", "Para leer un número entero enviado desde la PC", "Para contar caracteres", "Para borrar el buffer"], respuestaCorrecta: 1, explicacion: "parseInt lee un número entero del buffer serial. Si envías '150' desde el monitor serial, te da el entero 150. 🔢" },
    { titulo: "✅ Quiz: Monitor Serial", tipo: 'mini_quiz', pregunta: "¿Para qué es más útil el Monitor Serial durante el desarrollo?", opciones: ["Para decorar", "Para depurar (debug): ver valores de sensores y estado del programa", "Para jugar", "Para editar código"], respuestaCorrecta: 1, explicacion: "¡Es tu herramienta de debug #1! Imprime valores de sensores, estados de variables y mensajes para encontrar errores. 🔍" },
    { titulo: "✅ Quiz: Comandos Seriales", tipo: 'mini_quiz', pregunta: "Si quieres controlar un robot desde la PC enviando letras (W=adelante, S=atrás), ¿qué función usas para leer la letra?", opciones: ["analogRead()", "Serial.read()", "digitalWrite()", "pinMode()"], respuestaCorrecta: 1, explicacion: "Serial.read() lee un byte (letra) del buffer serial. if(Serial.read() == 'W') avanzar(); 📝" },
    { titulo: "✅❌ Serial: ¿V o F?", tipo: 'true_false', statements: [{ text: 'TX (transmit) y RX (receive) son los pines de comunicación serial del Arduino.', correct: true, explain: 'TX (pin 1) transmite datos, RX (pin 0) recibe. Son los pines de Serial.' }, { text: 'Puedes usar cualquier velocidad de baudios sin importar la configuración de la PC.', correct: false, explain: '¡Ambos deben coincidir! Si Arduino usa 9600 y la PC 115200, los datos se corrompen.' }] },
    { titulo: "🧩 Funciones Serial", tipo: 'matching_game', instruccion: 'Conecta cada función con su uso', pairs: [{ left: 'Serial.begin(9600)', right: 'Iniciar comunicación' }, { left: 'Serial.println()', right: 'Enviar dato + nueva línea' }, { left: 'Serial.read()', right: 'Leer un byte recibido' }, { left: 'Serial.available()', right: 'Verificar si hay datos' }] },
    { titulo: "✅ Quiz: Buffer Serial", tipo: 'mini_quiz', pregunta: "¿Qué es el buffer serial?", opciones: ["Un cable especial", "Una memoria temporal que almacena datos recibidos", "Un tipo de motor", "Un sensor de datos"], respuestaCorrecta: 1, explicacion: "El buffer guarda temporalmente los bytes recibidos hasta que tu código los lee con Serial.read(). ¡Como un buzón de correo! 📬" },
  ],
  'w2_mod10_display': [ // has 2, need 8
    { titulo: "✅ Quiz: LCD I2C", tipo: 'mini_quiz', pregunta: "¿Cuántos cables necesitas para conectar una pantalla LCD I2C al Arduino?", opciones: ["8 cables", "4 cables", "16 cables", "2 cables"], respuestaCorrecta: 1, explicacion: "I2C usa solo 4 cables: VCC, GND, SDA (datos) y SCL (reloj). ¡Mucho más simple que los 16 pines del LCD sin I2C! 🔌" },
    { titulo: "✅ Quiz: Tamaño LCD", tipo: 'mini_quiz', pregunta: "¿Qué significa LCD 16x2?", opciones: ["16 colores y 2 formas", "16 caracteres por línea, 2 líneas", "16 cm x 2 cm", "16 pines y 2 voltios"], respuestaCorrecta: 1, explicacion: "16x2 = puede mostrar 16 caracteres en 2 filas. Total: 32 caracteres. ¡Suficiente para datos de sensores! 📺" },
    { titulo: "✅ Quiz: lcd.setCursor", tipo: 'mini_quiz', pregunta: "¿Qué hace lcd.setCursor(0, 1)?", opciones: ["Borra la pantalla", "Mueve el cursor al inicio de la segunda fila", "Enciende la luz de fondo", "Apaga la pantalla"], respuestaCorrecta: 1, explicacion: "setCursor(columna, fila): (0,0) = inicio primera fila, (0,1) = inicio segunda fila. Las posiciones empiezan en 0. 📍" },
    { titulo: "✅ Quiz: Datos en Pantalla", tipo: 'mini_quiz', pregunta: "¿Cómo mostrarías la temperatura en la LCD: 'Temp: 25°C'?", opciones: ["Solo con print", "lcd.print('Temp: '); lcd.print(temperatura); lcd.print('C');", "No se puede", "Con analogWrite"], respuestaCorrecta: 1, explicacion: "Usas lcd.print() varias veces o concatenas el texto con los datos del sensor. ¡Mezcla texto fijo + variables! 📊" },
    { titulo: "✅❌ Display: ¿V o F?", tipo: 'true_false', statements: [{ text: 'I2C permite conectar múltiples dispositivos con solo 2 cables de datos.', correct: true, explain: 'I2C usa SDA y SCL. Cada dispositivo tiene una dirección única (ej: 0x27).' }, { text: 'Una LCD puede mostrar imágenes como una pantalla de celular.', correct: false, explain: 'LCD 16x2 solo muestra texto y caracteres. Para imágenes se necesita OLED o TFT.' }] },
    { titulo: "🧩 Funciones LCD", tipo: 'matching_game', instruccion: 'Conecta cada función con su efecto', pairs: [{ left: 'lcd.begin(16, 2)', right: 'Inicializar pantalla' }, { left: 'lcd.print()', right: 'Escribir texto' }, { left: 'lcd.clear()', right: 'Borrar pantalla' }, { left: 'lcd.setCursor(0,1)', right: 'Mover a fila 2' }] },
    { titulo: "✅ Quiz: Caracteres Personalizados", tipo: 'mini_quiz', pregunta: "¿Se pueden crear caracteres personalizados (emojis) en la LCD 16x2?", opciones: ["No, imposible", "Sí, se pueden crear hasta 8 caracteres de 5x8 pixeles", "Solo con otra pantalla", "Solo en color"], respuestaCorrecta: 1, explicacion: "¡Sí! Con lcd.createChar() puedes diseñar hasta 8 caracteres de 5x8 pixeles. ¡Crea caras, flechas o logos! 😊" },
    { titulo: "✅ Quiz: Dirección I2C", tipo: 'mini_quiz', pregunta: "¿Qué pasa si configuramos una dirección I2C incorrecta para la LCD?", opciones: ["Funciona igual", "La pantalla no muestra nada", "Se rompe la pantalla", "Se apaga el Arduino"], respuestaCorrecta: 1, explicacion: "Si la dirección no coincide, el Arduino envía datos a un dispositivo inexistente. La pantalla queda en blanco. Usa un I2C Scanner para encontrar la dirección correcta. 🔍" },
  ],
  'w2_mod11_bluetooth': [ // has 2, need 8
    { titulo: "✅ Quiz: HC-05 vs HC-06", tipo: 'mini_quiz', pregunta: "¿Cuál es la diferencia principal entre HC-05 y HC-06?", opciones: ["Son idénticos", "HC-05 es maestro/esclavo, HC-06 solo esclavo", "HC-06 es más caro", "HC-05 no tiene Bluetooth"], respuestaCorrecta: 1, explicacion: "HC-05 puede iniciar conexiones (maestro) o recibirlas (esclavo). HC-06 solo espera conexiones. Para control con celular, ambos sirven. 📱" },
    { titulo: "✅ Quiz: SoftwareSerial", tipo: 'mini_quiz', pregunta: "¿Por qué se usa SoftwareSerial con el módulo Bluetooth en vez del Serial normal?", opciones: ["Es más rápido", "Para no ocupar los pines TX/RX que se usan para programar", "No hay razón", "Es más barato"], respuestaCorrecta: 1, explicacion: "Los pines 0/1 (TX/RX) se usan para programar el Arduino. SoftwareSerial permite usar OTROS pines para Bluetooth. 🔌" },
    { titulo: "✅ Quiz: Conexión BT", tipo: 'mini_quiz', pregunta: "¿Qué velocidad de baudios usa normalmente el HC-05/HC-06?", opciones: ["1200", "9600", "115200", "1000000"], respuestaCorrecta: 1, explicacion: "9600 baudios es la velocidad por defecto del HC-05/HC-06. Coincide con el Serial estándar de Arduino. 📡" },
    { titulo: "✅ Quiz: App de Control", tipo: 'mini_quiz', pregunta: "¿Qué necesitas en tu celular para controlar un robot por Bluetooth?", opciones: ["Nada, solo Bluetooth", "Una app que envíe caracteres por Bluetooth serial", "Un cable USB", "WiFi"], respuestaCorrecta: 1, explicacion: "Apps como Bluetooth Terminal o creadas con MIT App Inventor envían caracteres que el Arduino lee. ¡Control remoto! 📱🤖" },
    { titulo: "✅ Quiz: Alcance Bluetooth", tipo: 'mini_quiz', pregunta: "¿Cuál es el alcance típico del HC-05 en interiores?", opciones: ["1 metro", "10 metros", "100 metros", "1 km"], respuestaCorrecta: 1, explicacion: "~10 metros en interiores, hasta 30m en espacios abiertos. Suficiente para controlar un robot en una habitación. 📏" },
    { titulo: "✅❌ Bluetooth: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El módulo HC-05 funciona con 3.3V en su pin RX.', correct: true, explain: 'El pin RX del HC-05 es de 3.3V. Se necesita divisor de voltaje desde los 5V del Arduino.' }, { text: 'Bluetooth y WiFi son la misma tecnología.', correct: false, explain: 'Son diferentes: Bluetooth es para distancias cortas (1-100m), WiFi para redes locales/internet.' }] },
    { titulo: "🧩 Bluetooth Control", tipo: 'matching_game', instruccion: 'Conecta cada comando con la acción del robot', pairs: [{ left: "Enviar 'F'", right: 'Avanzar (Forward)' }, { left: "Enviar 'B'", right: 'Retroceder (Back)' }, { left: "Enviar 'L'", right: 'Girar izquierda (Left)' }, { left: "Enviar 'S'", right: 'Detenerse (Stop)' }] },
    { titulo: "✅ Quiz: Seguridad BT", tipo: 'mini_quiz', pregunta: "¿Por qué es importante cambiar el PIN por defecto (1234) del HC-05?", opciones: ["No es importante", "Para evitar que otros se conecten y controlen tu robot", "Para ir más rápido", "Para ahorrar batería"], respuestaCorrecta: 1, explicacion: "La seguridad importa: alguien podría conectarse y tomar control de tu robot. ¡Usa un PIN único! 🔒" },
  ],
  'w2_mod12_sonido': [ // has 2, need 8
    { titulo: "✅ Quiz: Buzzer", tipo: 'mini_quiz', pregunta: "¿Qué función de Arduino genera un tono en el buzzer?", opciones: ["analogWrite()", "tone(pin, frecuencia)", "digitalRead()", "Serial.print()"], respuestaCorrecta: 1, explicacion: "tone(pin, frecuencia) genera una onda cuadrada en el pin. tone(8, 440) produce un La musical (440 Hz). 🎵" },
    { titulo: "✅ Quiz: Frecuencia Musical", tipo: 'mini_quiz', pregunta: "¿Qué frecuencia corresponde a la nota DO central?", opciones: ["100 Hz", "262 Hz", "440 Hz", "1000 Hz"], respuestaCorrecta: 1, explicacion: "DO central = 262 Hz. RE = 294, MI = 330, FA = 349, SOL = 392, LA = 440, SI = 494. 🎶" },
    { titulo: "✅ Quiz: noTone()", tipo: 'mini_quiz', pregunta: "¿Para qué sirve noTone(pin) en Arduino?", opciones: ["Sube el volumen", "Detiene el tono que se está reproduciendo", "Cambia la frecuencia", "Enciende un LED"], respuestaCorrecta: 1, explicacion: "noTone() detiene el sonido en ese pin. Es necesario para crear silencios entre notas musicales. 🔇" },
    { titulo: "✅ Quiz: Sensor de Sonido", tipo: 'mini_quiz', pregunta: "¿Para qué se usa el sensor de sonido KY-038 en un robot?", opciones: ["Para hablar", "Para detectar aplausos, golpes o niveles de ruido", "Para conectar WiFi", "Para medir distancia"], respuestaCorrecta: 1, explicacion: "El KY-038 detecta sonidos fuertes (aplausos, golpes). ¡Puedes hacer un robot que se enciende con un aplauso! 👏" },
    { titulo: "✅ Quiz: Buzzer Activo vs Pasivo", tipo: 'mini_quiz', pregunta: "¿Cuál es la diferencia entre un buzzer activo y uno pasivo?", opciones: ["No hay diferencia", "El activo solo emite un tono fijo, el pasivo puede emitir diferentes frecuencias", "El pasivo es más caro", "El activo es más grande"], respuestaCorrecta: 1, explicacion: "Buzzer activo = un solo tono (solo HIGH/LOW). Buzzer pasivo = puedes controlar la frecuencia con tone(). ¡Para melodías usa pasivo! 🎵" },
    { titulo: "✅❌ Sonido: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Con la función tone() de Arduino puedes crear melodías.', correct: true, explain: 'Combinando tone() con delay() puedes tocar secuencias de notas como canciones.' }, { text: 'Un buzzer puede reproducir música con la misma calidad que una bocina.', correct: false, explain: 'El buzzer produce tonos simples (ondas cuadradas). Para audio de calidad se necesitan parlantes con DAC.' }] },
    { titulo: "🧩 Notas Musicales", tipo: 'matching_game', instruccion: 'Conecta cada nota con su frecuencia aproximada', pairs: [{ left: 'DO (C4)', right: '262 Hz' }, { left: 'MI (E4)', right: '330 Hz' }, { left: 'SOL (G4)', right: '392 Hz' }, { left: 'LA (A4)', right: '440 Hz' }] },
    { titulo: "✅ Quiz: Alarma Robótica", tipo: 'mini_quiz', pregunta: "¿Cómo crearías una alarma que suena cuando el sensor detecta un obstáculo muy cerca?", opciones: ["Con Serial.print()", "if(distancia < 10) tone(buzzer, 1000)", "Con pinMode()", "Con delay() solo"], respuestaCorrecta: 1, explicacion: "¡Simple! Si la distancia es menor a 10 cm, activa el buzzer con tone(). Si no, apágalo con noTone(). 🚨" },
  ],
  'w2_mod13_maquina_estados': [ // has 1, need 9
    { titulo: "✅ Quiz: Qué es FSM", tipo: 'mini_quiz', pregunta: "¿Qué es una Máquina de Estados Finitos (FSM)?", opciones: ["Un motor especial", "Un modelo donde el sistema tiene estados definidos y transiciones entre ellos", "Una marca de robot", "Un tipo de sensor"], respuestaCorrecta: 1, explicacion: "FSM = sistema con estados (EXPLORAR, EVADIR, ESPERAR) y reglas de transición. ¡Organiza el comportamiento del robot! 🎛️" },
    { titulo: "✅ Quiz: Estados", tipo: 'mini_quiz', pregunta: "¿Cuáles son estados típicos de un robot autónomo?", opciones: ["Feliz, Triste, Enojado", "EXPLORAR, EVADIR, ESPERAR, CARGANDO", "A, B, C, D", "1, 2, 3, 4"], respuestaCorrecta: 1, explicacion: "Los estados representan modos de operación: explora hasta encontrar obstáculo, evade, espera comando, etc. 🤖" },
    { titulo: "✅ Quiz: Transiciones", tipo: 'mini_quiz', pregunta: "¿Qué causa una transición de estado en un robot?", opciones: ["El paso del tiempo solamente", "Un evento o condición (sensor detecta obstáculo, batería baja, etc.)", "Nada, cambian al azar", "Solo el usuario"], respuestaCorrecta: 1, explicacion: "Las transiciones ocurren por eventos: obstáculo detectado → EVADIR, batería baja → BUSCAR_CARGA, etc. 🔀" },
    { titulo: "✅ Quiz: Implementación", tipo: 'mini_quiz', pregunta: "¿Cómo se implementa una FSM básica en Arduino?", opciones: ["Con analogWrite()", "Con switch/case o if/else evaluando el estado actual", "Con Serial.print()", "No se puede"], respuestaCorrecta: 1, explicacion: "switch(estadoActual) { case EXPLORAR: ... break; case EVADIR: ... break; } ¡Simple y organizado! 💻" },
    { titulo: "✅ Quiz: Variable de Estado", tipo: 'mini_quiz', pregunta: "¿Qué tipo de variable usarías para guardar el estado actual del robot?", opciones: ["float", "String largo", "int o enum", "boolean solo"], respuestaCorrecta: 2, explicacion: "int estado = 0; // 0=EXPLORAR, 1=EVADIR, 2=ESPERAR. O mejor: enum Estado {EXPLORAR, EVADIR, ESPERAR}; 📦" },
    { titulo: "✅❌ Máquina de Estados: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un robot puede estar en varios estados al mismo tiempo en una FSM simple.', correct: false, explain: 'En una FSM simple, el robot está en UN solo estado a la vez. Para múltiples estados se usan FSM paralelas.' }, { text: 'Las FSM hacen el código más organizado y fácil de depurar.', correct: true, explain: 'Separar comportamientos en estados hace el código modular y más fácil de entender y mantener.' }] },
    { titulo: "🧩 Estados y Acciones", tipo: 'matching_game', instruccion: 'Conecta cada estado con su comportamiento', pairs: [{ left: 'EXPLORAR', right: 'Avanzar y buscar camino libre' }, { left: 'EVADIR', right: 'Girar para esquivar obstáculo' }, { left: 'ESPERAR', right: 'Detenerse hasta recibir comando' }, { left: 'ALARMA', right: 'Encender buzzer y LEDs' }] },
    { titulo: "✅ Quiz: Ventajas FSM", tipo: 'mini_quiz', pregunta: "¿Cuál es la principal ventaja de usar FSM sobre código secuencial largo?", opciones: ["Es más lento", "Es más organizado, modular y fácil de expandir", "Usa más memoria", "No tiene ventajas"], respuestaCorrecta: 1, explicacion: "FSM separa cada comportamiento en su propio bloque. Agregar un nuevo estado es agregar un nuevo case. ¡Escalable! 📈" },
    { titulo: "✅ Quiz: Diagrama de Estados", tipo: 'mini_quiz', pregunta: "¿Qué es un diagrama de estados?", opciones: ["Un circuito eléctrico", "Un dibujo que muestra los estados y las flechas de transición entre ellos", "Un tipo de sensor", "Un programa de Arduino"], respuestaCorrecta: 1, explicacion: "Es un gráfico con círculos (estados) y flechas (transiciones) que muestra cómo se comporta el sistema. ¡Dibújalo antes de programar! 📊" },
  ],
  'w2_mod14_energia': [ // has 2, need 8
    { titulo: "✅ Quiz: Voltaje de Pilas", tipo: 'mini_quiz', pregunta: "¿Cuántos voltios dan 4 pilas AA en serie?", opciones: ["1.5V", "3V", "6V", "9V"], respuestaCorrecta: 2, explicacion: "Cada pila AA da 1.5V. En serie se suman: 4 × 1.5V = 6V. ¡Perfecto para motores DC! 🔋" },
    { titulo: "✅ Quiz: mAh", tipo: 'mini_quiz', pregunta: "¿Qué significan los mAh en una batería?", opciones: ["Mili-amperios hora: cuánta energía puede entregar", "Mega amperios por hora", "Mili-amperes de altura", "Es el modelo de la batería"], respuestaCorrecta: 0, explicacion: "mAh = miliamperios-hora. Una batería de 2000mAh puede dar 2000mA por 1 hora, 1000mA por 2 horas, etc. 🔋⏱️" },
    { titulo: "✅ Quiz: Consumo de Corriente", tipo: 'mini_quiz', pregunta: "¿Qué componente del robot consume MÁS corriente?", opciones: ["Los LEDs", "Los sensores", "Los motores", "El Arduino"], respuestaCorrecta: 2, explicacion: "Los motores DC consumen 200-700mA cada uno. El Arduino ~50mA, LEDs ~20mA, sensores ~15mA. ¡Los motores son los más hambrientos! ⚡" },
    { titulo: "✅ Quiz: Autonomía", tipo: 'mini_quiz', pregunta: "Si tu robot consume 500mA y la batería tiene 2000mAh, ¿cuánto dura?", opciones: ["30 minutos", "2 horas", "4 horas", "8 horas"], respuestaCorrecta: 2, explicacion: "2000mAh ÷ 500mA = 4 horas teóricas. En la práctica es ~80% de eso por la eficiencia. 🔋⏱️" },
    { titulo: "✅ Quiz: Regulador de Voltaje", tipo: 'mini_quiz', pregunta: "¿Para qué sirve un regulador de voltaje en un robot?", opciones: ["Para hacer ruido", "Para mantener un voltaje estable aunque la batería se vaya descargando", "Para cargar la batería", "Para medir corriente"], respuestaCorrecta: 1, explicacion: "El regulador mantiene voltaje constante (ej: 5V) protegiendo el Arduino y los sensores de voltajes variables. ⚡" },
    { titulo: "✅❌ Energía: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Conectar baterías en paralelo aumenta la capacidad (mAh) pero mantiene el voltaje.', correct: true, explain: 'Paralelo = mismo voltaje, más capacidad. Serie = más voltaje, misma capacidad.' }, { text: 'Una batería LiPo se puede cargar con cualquier cargador.', correct: false, explain: 'Las LiPo necesitan cargadores específicos. Cargarlas mal puede causar incendio.' }] },
    { titulo: "🧩 Tipos de Baterías", tipo: 'matching_game', instruccion: 'Conecta cada batería con su característica principal', pairs: [{ left: '🔋 Pilas AA (1.5V)', right: 'Baratas y desechables' }, { left: '🔋 Batería 9V', right: 'Compacta, poca capacidad' }, { left: '⚡ LiPo 3.7V', right: 'Recargable y potente' }, { left: '🔌 Power Bank USB', right: 'Recargable, 5V estable' }] },
    { titulo: "✅ Quiz: Ahorro de Energía", tipo: 'mini_quiz', pregunta: "¿Cómo puede un robot ahorrar energía para durar más tiempo?", opciones: ["Usando más motores", "Reduciendo velocidad, apagando sensores no usados y usando sleep mode", "No puede ahorrar", "Usando más LEDs"], respuestaCorrecta: 1, explicacion: "¡Gestión inteligente! Velocidad reducida, sensores que se encienden solo cuando se necesitan, y modo sleep del Arduino. 💤" },
  ],
  'w2_mod15_integracion': [ // has 1, need 9
    { titulo: "✅ Quiz: Planificación de Pines", tipo: 'mini_quiz', pregunta: "¿Por qué es importante hacer una tabla de pines antes de armar el robot?", opciones: ["No es importante", "Para saber qué sensores/motores van en qué pin y evitar conflictos", "Solo por estética", "Para gastar menos cables"], respuestaCorrecta: 1, explicacion: "Una tabla de pines evita conectar 2 cosas al mismo pin y facilita la programación. ¡Planifica antes de conectar! 📋" },
    { titulo: "✅ Quiz: Conflictos de Pines", tipo: 'mini_quiz', pregunta: "¿Qué pasa si conectas un motor y un sensor al mismo pin del Arduino?", opciones: ["Ambos funcionan", "Conflicto: señales se mezclan y nada funciona bien", "El motor gana", "El sensor gana"], respuestaCorrecta: 1, explicacion: "¡Conflicto! Cada componente necesita su propio pin. Un pin no puede ser INPUT y OUTPUT al mismo tiempo. ⚠️" },
    { titulo: "✅ Quiz: Orden de Integración", tipo: 'mini_quiz', pregunta: "¿En qué orden debes integrar los subsistemas del robot?", opciones: ["Todo al mismo tiempo", "Probar cada subsistema por separado, luego combinarlos uno a uno", "Empezar por el más difícil", "Al azar"], respuestaCorrecta: 1, explicacion: "¡Integración incremental! Prueba motores solos, sensores solos, luego combina. Si algo falla, sabes qué componente es. 🔧" },
    { titulo: "✅ Quiz: Debugging Integrado", tipo: 'mini_quiz', pregunta: "Tu robot integrado no funciona. ¿Cuál es el primer paso?", opciones: ["Desarmarlo todo", "Usar Serial.println() para ver qué valores leen los sensores", "Comprar uno nuevo", "Cambiar todos los cables"], respuestaCorrecta: 1, explicacion: "Serial.println es tu mejor amigo para debug. Imprime valores de sensores y estados para encontrar el problema. 🔍" },
    { titulo: "✅ Quiz: Gestión de Cables", tipo: 'mini_quiz', pregunta: "¿Cuál es una buena práctica para organizar los cables del robot?", opciones: ["Dejarlos sueltos", "Usar cables de colores ordenados y amarrar con bridas", "Usar un solo color", "No usar cables"], respuestaCorrecta: 1, explicacion: "Convención: rojo=VCC, negro=GND, otros colores=señales. Cables ordenados = menos errores y mantenimiento fácil. 🔌" },
    { titulo: "✅❌ Integración: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Antes de integrar todo, cada subsistema debe funcionar perfecto por separado.', correct: true, explain: 'Si un componente no funciona solo, tampoco funcionará integrado. Prueba primero individualmente.' }, { text: 'La integración siempre funciona a la primera sin problemas.', correct: false, explain: 'Casi nunca funciona a la primera. Los conflictos de pines, alimentación y timing son comunes.' }] },
    { titulo: "🧩 Subsistemas del Robot", tipo: 'matching_game', instruccion: 'Conecta cada subsistema con sus componentes', pairs: [{ left: 'Navegación', right: 'Motores + driver L298N' }, { left: 'Percepción', right: 'Sensor ultrasónico + IR' }, { left: 'Comunicación', right: 'Bluetooth + LCD' }, { left: 'Alimentación', right: 'Baterías + regulador' }] },
    { titulo: "✅ Quiz: Prioridad de Alimentación", tipo: 'mini_quiz', pregunta: "Si tu robot tiene batería baja y no puede alimentar todo, ¿qué debería tener prioridad?", opciones: ["Los LEDs decorativos", "El cerebro (Arduino) y los sensores de seguridad", "El buzzer", "La pantalla LCD"], respuestaCorrecta: 1, explicacion: "¡Seguridad primero! El cerebro y sensores críticos tienen prioridad. LEDs y display son complementarios. ⚡" },
    { titulo: "✅ Quiz: Testing Final", tipo: 'mini_quiz', pregunta: "¿Qué prueba debes hacer ANTES de la demostración final de tu robot?", opciones: ["Ninguna, confiar en que funciona", "Prueba completa en condiciones similares a la demostración", "Solo verificar que enciende", "Solo probar los LEDs"], respuestaCorrecta: 1, explicacion: "¡Prueba en las mismas condiciones! Superficie, iluminación y distancias similares. ¡Evita sorpresas en la demo! 🎯" },
  ],
  'w2_mod16_proyecto_final': [ // has 1, need 9
    { titulo: "✅ Quiz: Objetivo del Proyecto", tipo: 'mini_quiz', pregunta: "¿Cuál es el primer paso para el proyecto final de robot autónomo?", opciones: ["Comprar todo", "Definir claramente qué debe hacer el robot y sus requisitos", "Empezar a programar", "Copiar otro proyecto"], respuestaCorrecta: 1, explicacion: "Define los requisitos: ¿qué misión tiene? ¿qué sensores necesita? ¿cuánto debe durar la batería? ¡Planifica! 📋" },
    { titulo: "✅ Quiz: Lista de Materiales", tipo: 'mini_quiz', pregunta: "¿Qué debe incluir la lista de materiales (BOM) de un proyecto?", opciones: ["Solo los nombres", "Componente, cantidad, costo y dónde comprarlo", "Solo el costo total", "Solo las fotos"], respuestaCorrecta: 1, explicacion: "BOM = Bill Of Materials. Lista completa con cada componente, cuántos necesitas, cuánto cuestan y dónde conseguirlos. 📝" },
    { titulo: "✅ Quiz: Esquema Eléctrico", tipo: 'mini_quiz', pregunta: "¿Por qué es importante hacer un esquema eléctrico antes de armar el robot?", opciones: ["Solo por estética", "Para visualizar todas las conexiones y evitar errores", "No es necesario", "Para impresionar"], respuestaCorrecta: 1, explicacion: "El esquema eléctrico es el mapa de conexiones. Sin él, los errores de cableado son muy probables. ¡Herramientas como Fritzing ayudan! 🔌" },
    { titulo: "✅ Quiz: Pruebas Incrementales", tipo: 'mini_quiz', pregunta: "¿Qué significa hacer pruebas incrementales durante el montaje?", opciones: ["Probar solo al final", "Probar cada componente al agregarlo, antes de agregar el siguiente", "No hacer pruebas", "Probar todo de golpe"], respuestaCorrecta: 1, explicacion: "¡Probar paso a paso! Agrega un componente → prueba → funciona → agrega el siguiente. Así identificas errores rápido. 🔧" },
    { titulo: "✅ Quiz: Presentación del Proyecto", tipo: 'mini_quiz', pregunta: "¿Qué elementos debe tener una buena presentación del proyecto final?", opciones: ["Solo el robot encendido", "Objetivo, proceso, demo en vivo, resultados y mejoras futuras", "Solo fotos", "Solo el código"], respuestaCorrecta: 1, explicacion: "Una presentación completa: ¿qué? ¿cómo? ¿funciona? ¿qué aprendiste? ¿qué mejorarías? ¡Sé un ingeniero profesional! 🎤" },
    { titulo: "✅❌ Proyecto Final: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Documentar el proceso de construcción con fotos y notas es innecesario.', correct: false, explain: 'La documentación es fundamental: permite replicar, mejorar y compartir el proyecto.' }, { text: 'Es normal que el primer prototipo tenga errores que hay que corregir.', correct: true, explain: 'Los mejores ingenieros iteran: v1 con errores → v2 mejorada → v3 optimizada.' }] },
    { titulo: "🧩 Fases del Proyecto", tipo: 'matching_game', instruccion: 'Ordena las fases del proyecto final', pairs: [{ left: '1️⃣ Fase 1', right: 'Diseño y planificación' }, { left: '2️⃣ Fase 2', right: 'Montaje del hardware' }, { left: '3️⃣ Fase 3', right: 'Programación y testing' }, { left: '4️⃣ Fase 4', right: 'Presentación y mejoras' }] },
    { titulo: "✅ Quiz: Errores Comunes", tipo: 'mini_quiz', pregunta: "¿Cuál es el error más común al construir un robot por primera vez?", opciones: ["Usar demasiados sensores", "No verificar la alimentación eléctrica y conexiones sueltas", "Programar demasiado", "Usar cables de colores"], respuestaCorrecta: 1, explicacion: "El 80% de los problemas son eléctricos: cables sueltos, polaridad incorrecta o alimentación insuficiente. ¡Revisa las conexiones! ⚡" },
    { titulo: "✅ Quiz: Mejoras Futuras", tipo: 'mini_quiz', pregunta: "Tu robot funciona pero es lento en las curvas. ¿Qué mejora implementarías?", opciones: ["Quitar sensores", "Implementar control PID para giros más suaves y rápidos", "Hacerlo más pesado", "Nada, está perfecto"], respuestaCorrecta: 1, explicacion: "¡PID! Un controlador proporcional-integral-derivativo ajusta la velocidad de los motores para giros suaves y precisos. 🎯" },
  ],
};

console.log('=== WORLD 2 ===');
injectQuestions('src/data/world2Data.js', W2);

console.log('Done with World 2!');
