const fs = require('fs');

// Read file and split by lines
let lines = fs.readFileSync('src/data/world5Data.js', 'utf8').split('\n');

// Find the line numbers of each contenidoTeorico closing bracket
const closingLines = [];
for (let i = 0; i < lines.length; i++) {
  if (lines[i].trim() === ']' && lines[i].match(/^\s{8}\]/)) {
    closingLines.push(i);
  }
}
console.log('Found', closingLines.length, 'contenidoTeorico closing brackets');

// Map module IDs to their closing bracket line
const moduleClosings = {};
for (const cl of closingLines) {
  for (let j = cl; j >= Math.max(0, cl - 80); j--) {
    const match = lines[j].match(/id:\s*'(w5_[^']+)'/);
    if (match) {
      moduleClosings[match[1]] = cl;
      break;
    }
  }
}
console.log('Module mappings:', Object.entries(moduleClosings).map(([k,v])=>`${k}:L${v+1}`).join(', '));

const questions = {
  'w5_mod1_intro_rovers': [
    `            { titulo: "✅ Quiz: Rovers Pioneros", tipo: 'mini_quiz', pregunta: "¿Cuántos años duró el rover Opportunity en Marte, siendo diseñado para solo 90 días?", opciones: ["1 año", "5 años", "Casi 15 años", "30 años"], respuestaCorrecta: 2, explicacion: "Opportunity duró casi 15 años (2004-2019), superando su vida útil por 60 veces. Una tormenta de polvo acabó su misión. 💪" },`,
    `            { titulo: "✅ Quiz: Perseverance", tipo: 'mini_quiz', pregunta: "¿Qué característica única tiene el rover Perseverance respecto a rovers anteriores?", opciones: ["Es el más pequeño", "Lleva un helicóptero (Ingenuity)", "Funciona con gasolina", "Tiene piloto humano"], respuestaCorrecta: 1, explicacion: "Perseverance llevó a Ingenuity, el primer helicóptero que voló en otro planeta. ¡Aviación interplanetaria! 🚁" },`,
    `            { titulo: "✅ Quiz: Velocidad Rover", tipo: 'mini_quiz', pregunta: "¿A qué velocidad máxima se mueve Curiosity en Marte?", opciones: ["50 km/h", "5 km/h", "Unos 0.14 km/h (140 metros por hora)", "1 km/h"], respuestaCorrecta: 2, explicacion: "Curiosity avanza a solo 140 m/h. La seguridad es más importante que la velocidad cuando no puedes reparar el robot. 🐢" },`,
    `            { titulo: "✅ Quiz: ISRU Rovers", tipo: 'mini_quiz', pregunta: "¿Qué significan las siglas ISRU?", opciones: ["International Space Robot Unit", "In-Situ Resource Utilization", "Intelligent System for Rover Updates", "Inter-Solar Robotic Union"], respuestaCorrecta: 1, explicacion: "ISRU (Utilización de Recursos In-Situ) es usar materiales locales en otro planeta para fabricar lo necesario. 🏗️" },`,
    `            { titulo: "✅ Quiz: Autonomía del Rover", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers en Marte necesitan ser autónomos?", opciones: ["Porque la NASA es perezosa", "Porque la señal tarda 4-24 minutos y no permite control en tiempo real", "Porque no hay internet en Marte", "Porque es más barato"], respuestaCorrecta: 1, explicacion: "El retraso de comunicación hace imposible el control en tiempo real. El rover debe tomar decisiones solo. 📡" },`,
    `            { titulo: "✅ Quiz: Peso del Rover", tipo: 'mini_quiz', pregunta: "¿Cuánto pesa aproximadamente el rover Perseverance?", opciones: ["50 kg", "500 kg", "Más de 1,000 kg", "5,000 kg"], respuestaCorrecta: 2, explicacion: "Perseverance pesa ~1,025 kg en la Tierra. En Marte pesaría solo 389 kg por la menor gravedad. ⚖️" },`,
    `            { titulo: "✅ Quiz: Rover Yutu-2", tipo: 'mini_quiz', pregunta: "¿Qué logro histórico tiene el rover chino Yutu-2?", opciones: ["Llegó a Venus", "Es el primer rover en la cara oculta de la Luna", "Es el rover más rápido", "Descubrió vida en la Luna"], respuestaCorrecta: 1, explicacion: "Yutu-2, de la misión Chang'e 4, aterrizó en 2019 en la cara oculta de la Luna, un logro sin precedentes. 🌑🇨🇳" },`,
    `            { titulo: "✅ Quiz: Componentes Básicos", tipo: 'mini_quiz', pregunta: "¿Cuál de estos NO es un componente esencial de un rover autónomo?", opciones: ["Sensores de navegación", "Sistema de energía", "Aire acondicionado doméstico", "Computadora de a bordo"], respuestaCorrecta: 2, explicacion: "Un rover necesita sensores, energía y computadora. No necesita un aire acondicionado doméstico, aunque sí calefacción industrial. 🔧" },`,
    `            { titulo: "✅ Quiz: Misiones Futuras", tipo: 'mini_quiz', pregunta: "¿Qué empresa planea enviar rovers para preparar Marte antes que humanos?", opciones: ["Tesla", "SpaceX", "Apple", "Microsoft"], respuestaCorrecta: 1, explicacion: "SpaceX planea enviar Starships con rovers para construir infraestructura en Marte antes de las misiones tripuladas. 🚀" },`,
  ],
  'w5_mod2_navegacion_autonoma': [
    `            { titulo: "✅ Quiz: AutoNav", tipo: 'mini_quiz', pregunta: "¿Cuántos metros por día puede recorrer Perseverance de forma autónoma con AutoNav?", opciones: ["10 metros", "50 metros", "Hasta 200 metros", "1 kilómetro"], respuestaCorrecta: 2, explicacion: "AutoNav permite a Perseverance recorrer hasta 200 metros por día sin intervención humana. 5x más que rovers anteriores. 🤖" },`,
    `            { titulo: "✅ Quiz: Odometría Visual", tipo: 'mini_quiz', pregunta: "¿Cómo funciona la odometría visual de un rover?", opciones: ["Cuenta las vueltas de las ruedas", "Compara imágenes consecutivas para estimar movimiento", "Usa satélites GPS marcianos", "Mide la velocidad del viento"], respuestaCorrecta: 1, explicacion: "La odometría visual compara imágenes sucesivas de las cámaras para calcular cuánto y hacia dónde se ha movido el rover. 📷" },`,
    `            { titulo: "✅ Quiz: IMU", tipo: 'mini_quiz', pregunta: "¿Qué mide una IMU (Unidad de Medición Inercial)?", opciones: ["Temperatura y humedad", "Rotación, inclinación y aceleración", "Composición del suelo", "Velocidad del viento"], respuestaCorrecta: 1, explicacion: "La IMU combina giroscopio y acelerómetro para medir orientación y movimiento del rover en 3 dimensiones. ⚖️" },`,
    `            { titulo: "✅ Quiz: LIDAR", tipo: 'mini_quiz', pregunta: "¿Cómo crea un mapa 3D el sensor LIDAR?", opciones: ["Tomando fotos con flash", "Emitiendo pulsos láser y midiendo el tiempo de retorno", "Usando radar de microondas", "Con ondas de sonido"], respuestaCorrecta: 1, explicacion: "LIDAR mide la distancia a miles de puntos por segundo usando pulsos láser. Cada punto forma un mapa 3D preciso. 🔴" },`,
    `            { titulo: "✅ Quiz: Terreno Peligroso", tipo: 'mini_quiz', pregunta: "¿Qué hace un rover cuando detecta un obstáculo en su ruta?", opciones: ["Se detiene para siempre", "Busca una ruta alternativa alrededor del obstáculo", "Lo destruye con un láser", "Espera a que se mueva"], respuestaCorrecta: 1, explicacion: "El rover recalcula la ruta automáticamente buscando un camino alternativo que evite el obstáculo. 🔄" },`,
    `            { titulo: "✅ Quiz: Cámaras Estéreo", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers usan cámaras estéreo (dos cámaras lado a lado)?", opciones: ["Para tomar fotos bonitas", "Para calcular la distancia a los objetos como nuestros ojos", "Para tener repuesto", "Para grabar video en 3D"], respuestaCorrecta: 1, explicacion: "Las dos cámaras dan perspectiva diferente, igual que nuestros ojos. La diferencia entre imágenes permite calcular distancias. 👀" },`,
    `            { titulo: "✅ Quiz: Mapa de Costos", tipo: 'mini_quiz', pregunta: "¿Qué es un costmap (mapa de costos) en navegación robótica?", opciones: ["Un presupuesto del proyecto", "Una cuadrícula donde cada celda tiene un valor de dificultad", "Un mapa de gasolineras", "Un inventario de costos"], respuestaCorrecta: 1, explicacion: "El costmap asigna un valor de dificultad a cada zona: 0 = fácil de cruzar, 255 = imposible. El rover elige la ruta más fácil. 🗺️" },`,
    `            { titulo: "✅ Quiz: Waypoints", tipo: 'mini_quiz', pregunta: "¿Qué son los waypoints en navegación de rovers?", opciones: ["Puntos de recarga de energía", "Puntos intermedios de la ruta que el rover debe visitar", "Puntos de comunicación con la Tierra", "Bases marcianas"], respuestaCorrecta: 1, explicacion: "Los waypoints son coordenadas intermedias que definen la ruta del rover. Puede recibirlos de la Tierra o calcularlos. 📍" },`,
    `            { titulo: "✅ Quiz: Navegación sin GPS", tipo: 'mini_quiz', pregunta: "¿Qué combinación de sensores reemplaza al GPS en Marte?", opciones: ["Solo brújula", "Cámaras + IMU + odometría visual + SLAM", "Radio AM y FM", "Solo acelerómetro"], respuestaCorrecta: 1, explicacion: "Sin GPS en Marte, los rovers combinan múltiples sensores y algoritmos SLAM para localizarse. Es complejo pero funciona. 🧭" },`,
  ],
  'w5_mod3_percepcion_entorno': [
    `            { titulo: "✅ Quiz: Cámaras de Perseverance", tipo: 'mini_quiz', pregunta: "¿Cuántas cámaras tiene el rover Perseverance?", opciones: ["5 cámaras", "12 cámaras", "23 cámaras", "50 cámaras"], respuestaCorrecta: 2, explicacion: "Perseverance tiene 23 cámaras: de navegación, científicas, de ingeniería y de descenso. El rover más observador. 📸" },`,
    `            { titulo: "✅ Quiz: Hazcam", tipo: 'mini_quiz', pregunta: "¿Qué función tienen las Hazcam (Hazard Cameras)?", opciones: ["Tomar selfies del rover", "Detectar peligros inmediatos frente a las ruedas", "Comunicarse con satélites", "Medir la temperatura"], respuestaCorrecta: 1, explicacion: "Las Hazcam miran al suelo justo delante de las ruedas para detectar rocas pequeñas y hoyos a corta distancia. ⚠️" },`,
    `            { titulo: "✅ Quiz: Espectroscopía", tipo: 'mini_quiz', pregunta: "¿Qué es la espectroscopía que usa SuperCam?", opciones: ["Tomar fotos con filtros", "Analizar la luz rebotada por un láser para saber la composición", "Ver en la oscuridad", "Medir la distancia"], respuestaCorrecta: 1, explicacion: "La espectroscopía analiza las longitudes de onda de la luz para determinar qué elementos químicos contiene una roca. 🌈" },`,
    `            { titulo: "✅ Quiz: Visión Computacional", tipo: 'mini_quiz', pregunta: "¿Qué permite a un rover la visión por computadora?", opciones: ["Ver canales de TV", "Interpretar imágenes para reconocer objetos y terrenos", "Proyectar hologramas", "Comunicarse por video"], respuestaCorrecta: 1, explicacion: "La visión por computadora procesa imágenes para que el rover 'entienda' su entorno: tipos de terreno, obstáculos, rocas. 👁️🧠" },`,
    `            { titulo: "✅ Quiz: Micrófono Marciano", tipo: 'mini_quiz', pregunta: "¿Qué captó el micrófono de Perseverance por primera vez en Marte?", opciones: ["Música alien", "El sonido del viento y del láser disparando a rocas", "Silencio absoluto", "Voces humanas"], respuestaCorrecta: 1, explicacion: "Perseverance grabó sonidos del viento marciano y los pulsos del láser SuperCam. ¡Primera vez que 'escuchamos' otro planeta! 🎤" },`,
    `            { titulo: "✅ Quiz: Mastcam-Z", tipo: 'mini_quiz', pregunta: "¿Qué significa la 'Z' en Mastcam-Z?", opciones: ["Zona", "Zoom (puede hacer zoom)", "Zenith", "Zero"], respuestaCorrecta: 1, explicacion: "La Z es por Zoom. Mastcam-Z puede acercar imágenes para ver detalles de rocas lejanas. Es la primera cámara del mástil con zoom. 🔭" },`,
    `            { titulo: "✅ Quiz: Clasificación de Terreno", tipo: 'mini_quiz', pregunta: "¿Por qué es importante clasificar el tipo de terreno?", opciones: ["Para hacer fotos bonitas", "Para saber si es seguro avanzar y a qué velocidad", "Para pintar un cuadro", "Solo para los científicos"], respuestaCorrecta: 1, explicacion: "Arena suelta, roca sólida o grava cambian la tracción y seguridad. El rover ajusta velocidad según el terreno que detecta. 🏜️" },`,
    `            { titulo: "✅ Quiz: Infrarrojo", tipo: 'mini_quiz', pregunta: "¿Para qué usan los rovers sensores infrarrojos?", opciones: ["Para ver en la oscuridad", "Para medir temperatura y detectar minerales invisibles a simple vista", "Para comunicarse", "Para calentar las ruedas"], respuestaCorrecta: 1, explicacion: "El infrarrojo revela información sobre minerales y temperatura que la fotografía normal no puede detectar. 🌡️" },`,
    `            { titulo: "✅ Quiz: Detección Automática", tipo: 'mini_quiz', pregunta: "¿Qué hace el sistema AEGIS cuando detecta una roca inusual?", opciones: ["La ignora", "Automáticamente apunta el láser y la analiza sin esperar instrucciones", "Pide permiso a la Tierra", "La marca para estudiarla después"], respuestaCorrecta: 1, explicacion: "AEGIS selecciona y analiza rocas interesantes de forma autónoma, sin esperar los 20 min de retardo de comunicación. 🔬" },`,
  ],
  'w5_mod4_toma_decisiones': [
    `            { titulo: "✅ Quiz: FSM", tipo: 'mini_quiz', pregunta: "¿Cuántos estados puede tener activos una FSM al mismo tiempo?", opciones: ["Todos los que quiera", "Solo uno", "Mínimo dos", "Depende del robot"], respuestaCorrecta: 1, explicacion: "Una Máquina de Estados Finitos (FSM) solo puede estar en UN estado a la vez. Las transiciones cambian entre estados. 🔄" },`,
    `            { titulo: "✅ Quiz: AEGIS IA", tipo: 'mini_quiz', pregunta: "¿Qué hace el software AEGIS en los rovers de la NASA?", opciones: ["Controla las ruedas", "Identifica automáticamente rocas científicamente interesantes", "Gestiona la batería", "Envía datos a la Tierra"], respuestaCorrecta: 1, explicacion: "AEGIS analiza fotos del terreno y selecciona automáticamente rocas interesantes para que el rover las analice. ¡Ciencia autónoma! 🔬" },`,
    `            { titulo: "✅ Quiz: Árbol de Decisión", tipo: 'mini_quiz', pregunta: "¿Cómo funciona un árbol de decisión?", opciones: ["Es un árbol real plantado en el rover", "Encadena preguntas sí/no para llegar a una decisión", "Solo funciona con Internet", "Es un tipo de motor"], respuestaCorrecta: 1, explicacion: "Un árbol de decisión hace preguntas binarias: ¿Hay obstáculo? → ¿Es grande? → ¿Puedo rodearlo? Cada respuesta lleva a la siguiente. 🌳" },`,
    `            { titulo: "✅ Quiz: Prioridades del Rover", tipo: 'mini_quiz', pregunta: "¿Cuál es el orden correcto de prioridades de un rover?", opciones: ["Ciencia > Energía > Seguridad", "Velocidad > Fotos > Comunicación", "Seguridad > Energía > Comunicación > Ciencia", "Comunicación > Todo lo demás"], respuestaCorrecta: 2, explicacion: "Seguridad es siempre primero. Sin rover no hay misión. Luego energía, comunicación y finalmente ciencia. 🛡️" },`,
    `            { titulo: "✅ Quiz: Replanificación", tipo: 'mini_quiz', pregunta: "¿Qué hace un rover cuando sus planes cambian por condiciones inesperadas?", opciones: ["Se apaga", "Replanifica usando la información actualizada de sus sensores", "Sigue el plan original sin importar qué", "Espera 24 horas"], respuestaCorrecta: 1, explicacion: "La replanificación dinámica es clave: el rover actualiza constantemente sus planes según nueva información. 🔄" },`,
    `            { titulo: "✅ Quiz: Planificador de Objetivos", tipo: 'mini_quiz', pregunta: "¿Qué hace un planificador de objetivos en un rover?", opciones: ["Define los colores del rover", "Divide la misión en sub-metas ordenadas y alcanzables", "Solo mide el combustible", "Es un calendario"], respuestaCorrecta: 1, explicacion: "El planificador divide la misión compleja en sub-metas simples: ir a punto A, analizar roca, enviar datos, ir a punto B. 🎯" },`,
    `            { titulo: "✅ Quiz: Modos del Rover", tipo: 'mini_quiz', pregunta: "¿Qué pasa cuando un rover entra en 'modo seguro'?", opciones: ["Acelera al máximo", "Detiene operaciones, apunta paneles al sol y espera instrucciones", "Toma más fotos", "Se autodestruye"], respuestaCorrecta: 1, explicacion: "En modo seguro, el rover para todo, asegura su energía y comunicación, y espera que la Tierra diagnostique el problema. 🆘" },`,
    `            { titulo: "✅ Quiz: Timeout", tipo: 'mini_quiz', pregunta: "¿Qué es un timeout en la toma de decisiones de un rover?", opciones: ["Una pausa para descanso", "Un límite de tiempo para completar una acción antes de cancelarla", "Un error del sistema", "Una transmisión de radio"], respuestaCorrecta: 1, explicacion: "Si una acción tarda más de lo esperado (timeout), el rover la cancela y pasa a un estado seguro. Evita quedarse atascado. ⏱️" },`,
    `            { titulo: "✅ Quiz: Decisiones en Tiempo Real", tipo: 'mini_quiz', pregunta: "¿Por qué las decisiones en tiempo real son más difíciles que las planificadas?", opciones: ["Porque son más caras", "Porque el rover debe procesar datos y decidir en milisegundos", "Porque necesitan internet", "No son más difíciles"], respuestaCorrecta: 1, explicacion: "Las decisiones reactivas (evitar obstáculo repentino) requieren procesamiento ultra-rápido, sin tiempo para analizar todas las opciones. ⚡" },`,
  ],
  'w5_mod5_chasis_movilidad': [
    `            { titulo: "✅ Quiz: Rocker-Bogie", tipo: 'mini_quiz', pregunta: "¿Qué ventaja principal tiene el sistema Rocker-Bogie?", opciones: ["Es el más rápido", "Mantiene las 6 ruedas en contacto con terreno irregular", "Es el más barato", "Usa menos energía"], respuestaCorrecta: 1, explicacion: "Rocker-Bogie permite que cada rueda se adapte independientemente al terreno, dando máxima tracción y estabilidad. 🏔️" },`,
    `            { titulo: "✅ Quiz: Ruedas de Curiosity", tipo: 'mini_quiz', pregunta: "¿Por qué se dañaron las ruedas de Curiosity más rápido de lo esperado?", opciones: ["Porque eran de plástico", "Porque las rocas marcianas son más afiladas de lo previsto", "Porque iban muy rápido", "Porque eran muy pequeñas"], respuestaCorrecta: 1, explicacion: "Las rocas marcianas, con bordes afilados sin erosión por agua, perforaron el aluminio de las ruedas. Para Perseverance las rediseñaron. 🪨" },`,
    `            { titulo: "✅ Quiz: Giro en el Sitio", tipo: 'mini_quiz', pregunta: "¿Cómo puede girar un rover en su propio lugar?", opciones: ["Levantando las ruedas frontales", "Girando las ruedas de cada lado en dirección opuesta", "Usando un cohete lateral", "Solo avanza, no puede girar"], respuestaCorrecta: 1, explicacion: "Con motores independientes, las ruedas izquierdas avanzan mientras las derechas retroceden. El rover rota sobre su centro. 🔄" },`,
    `            { titulo: "✅ Quiz: Material de Ruedas", tipo: 'mini_quiz', pregunta: "¿De qué material están hechas las ruedas de Curiosity?", opciones: ["Caucho como un auto", "Aluminio con perforaciones", "Acero inoxidable", "Plástico reforzado"], respuestaCorrecta: 1, explicacion: "Las ruedas son de aluminio ligero con un patrón de perforaciones para tracción. Pesan solo ~10 kg cada una. 🛞" },`,
    `            { titulo: "✅ Quiz: JPL en Morse", tipo: 'mini_quiz', pregunta: "¿Qué mensaje dejaban las ruedas de Curiosity en la arena marciana?", opciones: ["SOS", "JPL en código Morse", "NASA en binario", "HOLA en español"], respuestaCorrecta: 1, explicacion: "Las perforaciones de las ruedas deletreaban JPL (Jet Propulsion Laboratory) en código Morse con cada vuelta. ·--- ·--· ·-·· 🔤" },`,
    `            { titulo: "✅ Quiz: Costo por Kilogramo", tipo: 'mini_quiz', pregunta: "¿Cuánto cuesta lanzar un kilogramo al espacio aproximadamente?", opciones: ["$100", "$2,000", "$20,000 o más", "$1 millón"], respuestaCorrecta: 2, explicacion: "Cada kilogramo cuesta ~$20,000+ en lanzamiento. Por eso los rovers se diseñan lo más ligeros posible. ⚖️🚀" },`,
    `            { titulo: "✅ Quiz: Orugas vs Ruedas", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers de Marte usan ruedas en vez de orugas de tanque?", opciones: ["Porque son más rápidos", "Porque las ruedas son más eficientes en energía y más fiables", "Porque se ven mejor", "Porque las orugas no funcionan sin aire"], respuestaCorrecta: 1, explicacion: "Las ruedas consumen menos energía y tienen menos piezas que puedan fallar. En Marte, la fiabilidad es vital. 🏜️" },`,
    `            { titulo: "✅ Quiz: Inclinación Máxima", tipo: 'mini_quiz', pregunta: "¿Cuántos grados de inclinación puede superar un rover con Rocker-Bogie?", opciones: ["10 grados", "Hasta 45 grados", "90 grados", "Solo terreno plano"], respuestaCorrecta: 1, explicacion: "La suspensión Rocker-Bogie permite inclinar hasta ~45 grados sin volcarse. Los rovers suelen limitarse a 30° por seguridad. 📐" },`,
    `            { titulo: "✅ Quiz: Motor Independiente", tipo: 'mini_quiz', pregunta: "¿Por qué cada rueda del rover tiene su propio motor?", opciones: ["Para ir más rápido", "Para tener control preciso y seguir funcionando si un motor falla", "Para hacer más ruido", "No tiene motor en cada rueda"], respuestaCorrecta: 1, explicacion: "Motores independientes dan control preciso del giro y redundancia: si un motor falla, los demás pueden compensar. 🔧" },`,
  ],
  'w5_mod6_sensores_rover': [
    `            { titulo: "✅ Quiz: Ultrasónico", tipo: 'mini_quiz', pregunta: "¿Cómo mide la distancia un sensor ultrasónico?", opciones: ["Con luz láser", "Emite sonido y mide el tiempo de eco", "Con ondas de radio", "Con una regla láser"], respuestaCorrecta: 1, explicacion: "El sensor ultrasónico envía un pulso de sonido y mide el tiempo que tarda en rebotar. Distancia = velocidad × tiempo / 2. 📏" },`,
    `            { titulo: "✅ Quiz: Fusión de Sensores", tipo: 'mini_quiz', pregunta: "¿Qué es la fusión de sensores?", opciones: ["Derretir sensores juntos", "Combinar datos de múltiples sensores para mejor precisión", "Usar un solo sensor super preciso", "Conectar sensores por WiFi"], respuestaCorrecta: 1, explicacion: "La fusión de sensores combina datos de cámaras, LIDAR, IMU y más para tomar decisiones más precisas y confiables. 🔗" },`,
    `            { titulo: "✅ Quiz: Redundancia de Sensores", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers llevan sensores redundantes?", opciones: ["Para gastar más dinero", "Para tener respaldo si un sensor falla", "Porque sobra espacio", "Para comparar marcas"], respuestaCorrecta: 1, explicacion: "Si un sensor falla en Marte, nadie puede reemplazarlo. Los sensores redundantes aseguran que la misión continúe. 🛡️" },`,
    `            { titulo: "✅ Quiz: Espectrómetro", tipo: 'mini_quiz', pregunta: "¿Qué información da un espectrómetro al rover?", opciones: ["La temperatura del aire", "La composición química de rocas y suelo", "La velocidad del viento", "La presión atmosférica"], respuestaCorrecta: 1, explicacion: "Los espectrómetros analizan la luz reflejada por las rocas para identificar minerales y elementos químicos. 🔬" },`,
    `            { titulo: "✅ Quiz: Sensor de Temperatura", tipo: 'mini_quiz', pregunta: "¿Por qué un rover necesita sensores de temperatura internos?", opciones: ["Para predecir el clima", "Para proteger la electrónica del frío o calor extremo", "Para cocinar comida", "Solo por curiosidad"], respuestaCorrecta: 1, explicacion: "La electrónica tiene rangos operativos. Si la temperatura interna baja demasiado, el rover activa calentadores para sobrevivir. 🌡️" },`,
    `            { titulo: "✅ Quiz: Sensor RIMFAX", tipo: 'mini_quiz', pregunta: "¿Qué hace el radar RIMFAX de Perseverance?", opciones: ["Rastrea satélites", "Mira debajo de la superficie marciana con ondas de radar", "Comunica con la Tierra", "Mide la velocidad del rover"], respuestaCorrecta: 1, explicacion: "RIMFAX es un radar que penetra el suelo hasta 10 metros de profundidad para ver capas geológicas y posible hielo. 📡" },`,
    `            { titulo: "✅ Quiz: Oxígeno en Marte", tipo: 'mini_quiz', pregunta: "¿Cuánto oxígeno produjo MOXIE en su primera demostración?", opciones: ["1 gramo", "5 gramos (10 minutos de respiración)", "1 kilogramo", "100 gramos"], respuestaCorrecta: 1, explicacion: "MOXIE produjo 5 gramos de O₂, suficientes para que un astronauta respire 10 minutos. ¡Un paso histórico! 🫁" },`,
    `            { titulo: "✅ Quiz: Calibración", tipo: 'mini_quiz', pregunta: "¿Por qué los sensores del rover necesitan calibración periódica?", opciones: ["Para gastar energía", "Porque los sensores pueden cambiar su precisión con el tiempo", "Para divertir a los ingenieros", "No necesitan calibración"], respuestaCorrecta: 1, explicacion: "La radiación, temperatura y desgaste pueden alterar las lecturas. La calibración ajusta los sensores para mantener precisión. 🎯" },`,
    `            { titulo: "✅ Quiz: Sensor Wind", tipo: 'mini_quiz', pregunta: "¿Qué instrumento de Perseverance mide el clima marciano?", opciones: ["SuperCam", "MEDA (Mars Environmental Dynamics Analyzer)", "MOXIE", "Mastcam-Z"], respuestaCorrecta: 1, explicacion: "MEDA mide viento, temperatura, humedad, presión y radiación. Es la estación meteorológica del rover. ☀️🌬️" },`,
  ],
  'w5_mod7_energia_autonomia': [
    `            { titulo: "✅ Quiz: RTG vs Solar", tipo: 'mini_quiz', pregunta: "¿Cuál es la principal ventaja de un RTG sobre paneles solares?", opciones: ["Es más barato", "Funciona día y noche, en tormentas, durante décadas", "Es más liviano", "Genera más electricidad"], respuestaCorrecta: 1, explicacion: "Un RTG usa plutonio-238 y funciona independiente de la luz solar. Curiosity opera de noche y en tormentas sin problemas. ☢️" },`,
    `            { titulo: "✅ Quiz: Potencia Curiosity", tipo: 'mini_quiz', pregunta: "¿Cuánta potencia eléctrica genera el RTG de Curiosity?", opciones: ["10 watts", "110 watts (menos que una lámpara)", "1000 watts", "5000 watts"], respuestaCorrecta: 1, explicacion: "Solo 110 watts, menos que una lámpara de lectura. Pero con gestión inteligente, es suficiente para toda la misión. ⚡" },`,
    `            { titulo: "✅ Quiz: Muerte de Opportunity", tipo: 'mini_quiz', pregunta: "¿Qué causó el fin de la misión del rover Opportunity?", opciones: ["Un choque contra una roca", "Una tormenta de polvo cubrió sus paneles solares", "Se le acabó el RTG", "La NASA lo apagó intencionalmente"], respuestaCorrecta: 1, explicacion: "En 2018, una tormenta global de polvo bloqueó la luz solar. Sin energía, Opportunity se congeló y dejó de funcionar. 😢" },`,
    `            { titulo: "✅ Quiz: Hibernación", tipo: 'mini_quiz', pregunta: "¿Qué sistemas mantiene activos un rover en modo hibernación?", opciones: ["Todos los sistemas", "Solo calefacción y reloj para sobrevivir", "Solo las cámaras", "Absolutamente nada"], respuestaCorrecta: 1, explicacion: "En hibernación, el rover apaga cámaras e instrumentos. Solo mantiene calentadores y el reloj para despertar y sobrevivir. 😴" },`,
    `            { titulo: "✅ Quiz: Baterías", tipo: 'mini_quiz', pregunta: "¿Qué tipo de batería usan los rovers modernos?", opciones: ["Pilas alcalinas AA", "Baterías de litio-ion recargables", "Baterías de plomo-ácido", "Pilas de botón"], respuestaCorrecta: 1, explicacion: "Las baterías de litio-ion son ligeras, recargables y tienen alta densidad energética. Perfectas para rovers. 🔋" },`,
    `            { titulo: "✅ Quiz: Paneles Marcianos", tipo: 'mini_quiz', pregunta: "¿Por qué los paneles solares generan menos energía en Marte que en la Tierra?", opciones: ["Porque Marte es más frío", "Porque Marte está 1.5 veces más lejos del Sol", "Porque no hay oxígeno", "Porque el sol es diferente"], respuestaCorrecta: 1, explicacion: "Marte recibe solo el 43% de la luz solar que recibe la Tierra debido a su mayor distancia al Sol. ☀️" },`,
    `            { titulo: "✅ Quiz: Gestión Inteligente", tipo: 'mini_quiz', pregunta: "¿Por qué el rover nunca enciende todos sus instrumentos al mismo tiempo?", opciones: ["Porque no quiere", "Porque la energía es limitada y debe priorizarse", "Porque los instrumentos se interfieren", "Porque la NASA lo prohíbe"], respuestaCorrecta: 1, explicacion: "Con solo 110W disponibles, el rover secuencia el uso de instrumentos. Motor, cámara y láser nunca operan juntos. ⚡" },`,
    `            { titulo: "✅ Quiz: Calefacción", tipo: 'mini_quiz', pregunta: "¿Qué porcentaje de la energía del rover se usa en calefacción?", opciones: ["Casi nada, 1%", "Hasta el 50% o más en las noches frías", "10% exacto", "No usa calefacción"], respuestaCorrecta: 1, explicacion: "A -120°C en las noches marcianas, la calefacción puede consumir más de la mitad de la energía disponible. ¡Sobrevivir tiene un costo! 🥶" },`,
    `            { titulo: "✅ Quiz: Duración RTG", tipo: 'mini_quiz', pregunta: "¿Cuántos años puede funcionar un RTG en un rover?", opciones: ["1-2 años", "5 años", "Más de 14 años y potencialmente décadas", "Exactamente 10 años"], respuestaCorrecta: 2, explicacion: "Curiosity lleva 14+ años con su RTG. Voyager 1 y 2 llevan más de 48 años. Los RTGs son increíblemente duraderos. ⚛️" },`,
  ],
  'w5_mod8_comunicacion_rover': [
    `            { titulo: "✅ Quiz: HGA", tipo: 'mini_quiz', pregunta: "¿Qué velocidad de transmisión tiene la antena HGA del rover?", opciones: ["56 Kbps como internet antiguo", "Hasta 2 Mbps directo a la Tierra", "100 Mbps como fibra óptica", "Solo 1 byte por segundo"], respuestaCorrecta: 1, explicacion: "La HGA (High Gain Antenna) transmite hasta 2 Mbps a la Tierra. Lento comparado con tu WiFi, pero suficiente para Marte. 📡" },`,
    `            { titulo: "✅ Quiz: MRO Relay", tipo: 'mini_quiz', pregunta: "¿Cuántas veces al día pasa el MRO sobre un rover?", opciones: ["Continuamente", "2-3 veces al día", "Una vez por semana", "Cada hora"], respuestaCorrecta: 1, explicacion: "El Mars Reconnaissance Orbiter sobrevuela al rover 2-3 veces al día, con ventanas de 8-10 minutos cada una. 🛰️" },`,
    `            { titulo: "✅ Quiz: DTN", tipo: 'mini_quiz', pregunta: "¿Qué es DTN (Delay-Tolerant Networking)?", opciones: ["Una red social espacial", "Un protocolo diseñado para funcionar con minutos u horas de retraso", "El WiFi de Marte", "Un tipo de antena"], respuestaCorrecta: 1, explicacion: "DTN almacena datos y los reenvía cuando hay conexión. Diseñado para la Internet Interplanetaria con retrasos enormes. 📨" },`,
    `            { titulo: "✅ Quiz: Compresión de Datos", tipo: 'mini_quiz', pregunta: "¿Por qué el rover comprime las fotos antes de enviarlas?", opciones: ["Para que se vean mejor", "Porque el ancho de banda es limitado y tarda mucho en enviar", "Por seguridad", "Para ahorrar espacio en la memoria terrestre"], respuestaCorrecta: 1, explicacion: "Con solo 250 MB/día de transmisión, cada byte cuenta. Comprimir una foto de 5MB a 500KB ahorra tiempo vital. 📦" },`,
    `            { titulo: "✅ Quiz: Datos por Día", tipo: 'mini_quiz', pregunta: "¿Cuántos datos puede enviar Perseverance a la Tierra por día?", opciones: ["1 GB", "Aproximadamente 250 MB", "10 GB", "Solo 1 MB"], respuestaCorrecta: 1, explicacion: "Perseverance envía ~250 MB/día. Menos de lo que usas navegando redes sociales, pero suficiente para ciencia increíble. 📊" },`,
    `            { titulo: "✅ Quiz: Prioridad de Datos", tipo: 'mini_quiz', pregunta: "¿Qué datos envía un rover PRIMERO cuando tiene ventana de comunicación?", opciones: ["Las fotos más bonitas", "Estado del rover, alertas y datos científicos críticos", "Videos en HD", "Selfies"], respuestaCorrecta: 1, explicacion: "La salud del rover y alertas van primero. Luego datos científicos prioritarios. Las fotos panorámicas van al final si hay espacio. 📋" },`,
    `            { titulo: "✅ Quiz: Deep Space Network", tipo: 'mini_quiz', pregunta: "¿Cuántas estaciones tiene la Deep Space Network de la NASA?", opciones: ["1 en California", "3 estaciones distribuidas en el mundo", "10 estaciones", "Solo una en cada continente"], respuestaCorrecta: 1, explicacion: "La DSN tiene 3 estaciones: Goldstone (EEUU), Madrid (España) y Canberra (Australia), espaciadas 120° para cobertura 24/7. 📡" },`,
    `            { titulo: "✅ Quiz: Protocolo de Emergencia", tipo: 'mini_quiz', pregunta: "¿Qué hace el rover si pierde contacto con la Tierra por varios días?", opciones: ["Sigue normal", "Activa protocolo de seguridad: se detiene y reintenta comunicación", "Se apaga permanentemente", "Busca otros rovers"], respuestaCorrecta: 1, explicacion: "El rover entra en modo seguro, apunta su antena a la Tierra y envía señales periódicas esperando reconexión. 🆘" },`,
    `            { titulo: "✅ Quiz: Comunicación Óptica", tipo: 'mini_quiz', pregunta: "¿Qué tecnología promete 10-100x más velocidad de transmisión que las ondas de radio?", opciones: ["5G espacial", "Comunicación óptica láser (DSOC)", "Bluetooth 6.0", "Cables de fibra óptica al espacio"], respuestaCorrecta: 1, explicacion: "DSOC usa láseres para transmitir datos, logrando velocidades hasta 100 veces mayores que la radio. Probado exitosamente en 2023. 💡" },`,
  ],
  'w5_mod9_planificacion_rutas': [
    `            { titulo: "✅ Quiz: Dijkstra", tipo: 'mini_quiz', pregunta: "¿Cuál es la limitación principal del algoritmo de Dijkstra?", opciones: ["No encuentra la ruta más corta", "Explora en todas las direcciones, haciéndolo más lento que A*", "Solo funciona en línea recta", "No puede manejar obstáculos"], respuestaCorrecta: 1, explicacion: "Dijkstra explora uniformemente en todas direcciones. A* añade una heurística que lo guía hacia el destino, haciéndolo más eficiente. 🔍" },`,
    `            { titulo: "✅ Quiz: Heurística Admisible", tipo: 'mini_quiz', pregunta: "¿Qué hace que una heurística sea 'admisible' en A*?", opciones: ["Que sea la más rápida", "Que nunca sobreestime la distancia real al destino", "Que sea gratuita", "Que funcione en cualquier terreno"], respuestaCorrecta: 1, explicacion: "Una heurística admisible nunca dice que estás más lejos de lo que realmente estás. Esto garantiza que A* encuentra la ruta óptima. ⭐" },`,
    `            { titulo: "✅ Quiz: D* Lite", tipo: 'mini_quiz', pregunta: "¿Cuándo es mejor usar D* Lite en lugar de A*?", opciones: ["Siempre", "Cuando el mapa cambia mientras el rover se mueve", "Cuando hay poca energía", "Cuando el terreno es plano"], respuestaCorrecta: 1, explicacion: "D* Lite recalcula la ruta eficientemente cuando se detectan nuevos obstáculos, sin empezar de cero como A*. 🔄" },`,
    `            { titulo: "✅ Quiz: RRT", tipo: 'mini_quiz', pregunta: "¿Cómo funciona el algoritmo RRT?", opciones: ["Calcula la línea recta al destino", "Genera árboles de exploración aleatoria para encontrar caminos", "Sigue siempre la pared izquierda", "Solo funciona con GPS"], respuestaCorrecta: 1, explicacion: "RRT (Rapidly-exploring Random Trees) genera ramas aleatorias que exploran el espacio rápidamente, ideal para entornos complejos. 🌳" },`,
    `            { titulo: "✅ Quiz: GESTALT", tipo: 'mini_quiz', pregunta: "¿Qué algoritmo usa Perseverance para planificar rutas en Marte?", opciones: ["Google Maps", "GESTALT del JPL", "Waze", "Dijkstra puro"], respuestaCorrecta: 1, explicacion: "GESTALT analiza el terreno, clasifica zonas por peligro y encuentra la ruta que minimiza riesgo, distancia y energía. 🧮" },`,
    `            { titulo: "✅ Quiz: Distancia Manhattan", tipo: 'mini_quiz', pregunta: "¿Qué es la distancia Manhattan usada como heurística en A*?", opciones: ["La distancia al río Manhattan", "La suma de diferencias horizontales y verticales (sin diagonales)", "La distancia en línea recta", "La distancia en kilómetros"], respuestaCorrecta: 1, explicacion: "Se llama Manhattan porque es como caminar por calles en cuadrícula: solo arriba/abajo/izquierda/derecha, sin atajos diagonales. 🏙️" },`,
    `            { titulo: "✅ Quiz: Replanificación Local", tipo: 'mini_quiz', pregunta: "¿Qué pasa si el rover encuentra un obstáculo NO mapeado durante su ruta?", opciones: ["Se detiene permanentemente", "Replanifica localmente usando sus sensores actualizados", "Vuelve al inicio", "Espera instrucciones de la Tierra"], respuestaCorrecta: 1, explicacion: "El rover actualiza su mapa local y recalcula la ruta alrededor del nuevo obstáculo, todo de forma autónoma. 🔄" },`,
    `            { titulo: "✅ Quiz: Exploración vs Explotación", tipo: 'mini_quiz', pregunta: "¿Qué dilema enfrenta un rover entre explorar nuevas áreas y usar rutas conocidas?", opciones: ["El dilema del prisionero", "Exploración vs Explotación", "Velocidad vs Seguridad", "Izquierda vs Derecha"], respuestaCorrecta: 1, explicacion: "El rover debe balancear entre descubrir rutas nuevas (exploración) y usar caminos seguros ya conocidos (explotación). 🤔" },`,
    `            { titulo: "✅ Quiz: Coste Energético", tipo: 'mini_quiz', pregunta: "¿Qué factores incluye el costmap de un rover para calcular una ruta?", opciones: ["Solo distancia", "Distancia, pendiente, tipo de terreno y riesgo", "Solo el color del suelo", "Solo la temperatura"], respuestaCorrecta: 1, explicacion: "El costmap combina múltiples factores: distancia, inclinación, rugosidad del terreno y nivel de riesgo para cada celda. 🗺️" },`,
  ],
  'w5_mod10_ml_rovers': [
    `            { titulo: "✅ Quiz: SPOC Precisión", tipo: 'mini_quiz', pregunta: "¿Con cuántas imágenes fue entrenada la red neuronal SPOC de la NASA?", opciones: ["100 imágenes", "1,000 imágenes", "16,000 imágenes de Curiosity", "1 millón de imágenes"], respuestaCorrecta: 2, explicacion: "SPOC fue entrenada con 16,000 imágenes reales del rover Curiosity, logrando 97% de precisión en clasificación de terreno. 📷" },`,
    `            { titulo: "✅ Quiz: KNN", tipo: 'mini_quiz', pregunta: "¿Cómo funciona el algoritmo K-Nearest Neighbors?", opciones: ["Busca puntos lejanos", "Clasifica comparando con los K datos más cercanos (similares)", "Genera datos nuevos", "Solo funciona con imágenes"], respuestaCorrecta: 1, explicacion: "KNN encuentra los K ejemplos más parecidos a la nueva observación y usa la clase mayoritaria como predicción. 📊" },`,
    `            { titulo: "✅ Quiz: Entrenamiento", tipo: 'mini_quiz', pregunta: "¿Dónde se entrena el modelo de ML de un rover?", opciones: ["En el rover en Marte", "En la Tierra con datos recolectados por misiones previas", "En satélites orbitales", "En la Luna"], respuestaCorrecta: 1, explicacion: "Los modelos se entrenan en la Tierra con computadoras potentes usando datos de misiones anteriores, luego se suben al rover. 🌍💻" },`,
    `            { titulo: "✅ Quiz: Redes Neuronales", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tienen las redes neuronales sobre KNN para clasificar rocas?", opciones: ["Son más simples", "Pueden aprender patrones complejos en imágenes de muchas dimensiones", "Son más rápidas siempre", "No necesitan datos"], respuestaCorrecta: 1, explicacion: "Las redes neuronales extraen automáticamente características de imágenes (bordes, texturas, formas) que KNN no puede procesar. 🧠" },`,
    `            { titulo: "✅ Quiz: Aprendizaje por Refuerzo", tipo: 'mini_quiz', pregunta: "¿Cómo aprende un rover con aprendizaje por refuerzo?", opciones: ["Leyendo un manual", "Recibiendo recompensas por acciones exitosas y penalizaciones por errores", "Copiando a otros rovers", "Descargando actualizaciones"], respuestaCorrecta: 1, explicacion: "El rover 'aprende' qué acciones funcionan mejor: llegar sin problemas = recompensa, chocar = penalización. 🎮" },`,
    `            { titulo: "✅ Quiz: Detección de Anomalías", tipo: 'mini_quiz', pregunta: "¿Por qué es útil la detección de anomalías en rovers?", opciones: ["Para encontrar aliens", "Para identificar cosas inusuales que podrían ser científicamente interesantes", "Para reparar el rover", "Para mejorar la comunicación"], respuestaCorrecta: 1, explicacion: "Una roca con forma o color inusual podría indicar procesos geológicos interesantes o incluso evidencia de agua pasada. 🔍" },`,
    `            { titulo: "✅ Quiz: Chips en el Espacio", tipo: 'mini_quiz', pregunta: "¿Por qué es difícil ejecutar redes neuronales grandes en un rover?", opciones: ["Porque no hay WiFi", "Porque los procesadores resistentes a radiación son mucho más lentos", "Porque las redes neuronales son muy grandes", "No es difícil"], respuestaCorrecta: 1, explicacion: "Los chips rad-hard son 100x más lentos que los comerciales. Los ingenieros deben optimizar modelos ML para hardware limitado. 💾" },`,
    `            { titulo: "✅ Quiz: Datos de Entrenamiento", tipo: 'mini_quiz', pregunta: "¿Qué pasa si el rover encuentra terreno muy diferente a sus datos de entrenamiento?", opciones: ["Funciona igual de bien", "Puede cometer errores de clasificación y necesita precaución adicional", "Se apaga", "Llama a la Tierra"], respuestaCorrecta: 1, explicacion: "Un modelo ML solo es tan bueno como sus datos. Terreno no visto puede producir predicciones incorrectas. Por eso necesita margen de seguridad. ⚠️" },`,
    `            { titulo: "✅ Quiz: Transfer Learning", tipo: 'mini_quiz', pregunta: "¿Qué es transfer learning y cómo ayuda a rovers?", opciones: ["Transferir el rover a otro planeta", "Usar un modelo entrenado en un contexto y adaptarlo a otro", "Copiar software entre rovers", "Enviar datos entre planetas"], respuestaCorrecta: 1, explicacion: "Un modelo entrenado con fotos terrestres puede adaptarse para rocas marcianas con menos datos. Ahorra tiempo y recursos. 🔄" },`,
  ],
  'w5_mod11_sistemas_seguridad': [
    `            { titulo: "✅ Quiz: Curiosity Safe Mode", tipo: 'mini_quiz', pregunta: "¿Cuántas veces entró Curiosity en modo seguro en sus primeros años?", opciones: ["0 veces", "3 veces", "7 veces", "50 veces"], respuestaCorrecta: 2, explicacion: "Curiosity entró en modo seguro 7 veces. Cada vez se recuperó exitosamente gracias a sus sistemas de seguridad. 🛡️" },`,
    `            { titulo: "✅ Quiz: Computadora de Respaldo", tipo: 'mini_quiz', pregunta: "¿Qué pasa si la computadora principal del rover falla?", opciones: ["La misión termina", "La computadora de respaldo toma el control automáticamente", "Un astronauta la repara", "El rover espera una actualización"], respuestaCorrecta: 1, explicacion: "Curiosity cambió a su computadora de respaldo cuando una tormenta estática corrompió la memoria de la principal. ¡Redundancia salvavidas! 💻" },`,
    `            { titulo: "✅ Quiz: Auto-diagnóstico", tipo: 'mini_quiz', pregunta: "¿Con qué frecuencia se auto-diagnostica un rover?", opciones: ["Una vez al año", "Regularmente, antes de cada operación importante", "Nunca se diagnostica solo", "Solo cuando la Tierra lo pide"], respuestaCorrecta: 1, explicacion: "El auto-diagnóstico corre continuamente: verifica sensores, batería, temperatura y comunicaciones antes de actuar. 🔍" },`,
    `            { titulo: "✅ Quiz: Radiación Cósmica", tipo: 'mini_quiz', pregunta: "¿Qué daño puede causar la radiación cósmica a un rover?", opciones: ["Lo derrite", "Puede corromper datos en memoria y alterar circuitos", "Lo hace más fuerte", "Solo afecta a humanos"], respuestaCorrecta: 1, explicacion: "Los rayos cósmicos pueden cambiar bits en la memoria (bit-flip), corrompiendo datos o software. La memoria ECC corrige estos errores. ☢️" },`,
    `            { titulo: "✅ Quiz: Watchdog Aplicaciones", tipo: 'mini_quiz', pregunta: "¿Dónde más se usan Watchdog Timers además del espacio?", opciones: ["Solo en rovers", "En Arduino, servidores, teléfonos y sistemas embebidos", "Solo en la NASA", "En videojuegos"], respuestaCorrecta: 1, explicacion: "Los Watchdog Timers son estándar en cualquier sistema que necesite auto-recuperarse: desde un Arduino hasta un servidor web. ⏱️" },`,
    `            { titulo: "✅ Quiz: Tolerancia a Fallas", tipo: 'mini_quiz', pregunta: "¿Qué significa 'fail-safe' en diseño de rovers?", opciones: ["Que nunca falla", "Que cuando falla, lo hace de forma segura sin causar daño", "Que es indestructible", "Que es muy barato"], respuestaCorrecta: 1, explicacion: "Fail-safe significa que si algo sale mal, el sistema queda en un estado seguro en vez de causar más problemas. 🔒" },`,
    `            { titulo: "✅ Quiz: Recuperación", tipo: 'mini_quiz', pregunta: "¿Cómo se recupera un rover del modo seguro?", opciones: ["Solo puede hacerlo la Tierra", "Ingenieros analizan el problema y envían comandos de recuperación", "Se reinicia solo", "No puede recuperarse"], respuestaCorrecta: 1, explicacion: "Los ingenieros en la Tierra diagnostican el problema, desarrollan una solución y envían nueva secuencia de comandos. Puede tardar días. 🔧" },`,
    `            { titulo: "✅ Quiz: ECC Memory", tipo: 'mini_quiz', pregunta: "¿Qué hace la memoria ECC (Error-Correcting Code)?", opciones: ["Hace la memoria más rápida", "Detecta y corrige automáticamente errores de bits causados por radiación", "Comprime datos", "Encripta información"], respuestaCorrecta: 1, explicacion: "La memoria ECC detecta cuando un bit cambia por radiación y lo corrige automáticamente, vital para la fiabilidad en el espacio. 🛡️" },`,
    `            { titulo: "✅ Quiz: Protección de Software", tipo: 'mini_quiz', pregunta: "¿Cómo protege un rover su software de actualizaciones fallidas?", opciones: ["No acepta actualizaciones", "Mantiene una copia del software anterior para volver a la versión estable", "Descarga de internet", "Usa antivirus"], respuestaCorrecta: 1, explicacion: "El rover guarda su software anterior. Si una actualización falla, puede volver a la versión que funcionaba. Rollback espacial. 🔄" },`,
  ],
  'w5_mod12_simulacion_testing': [
    `            { titulo: "✅ Quiz: Mars Yard", tipo: 'mini_quiz', pregunta: "¿Dónde está el Mars Yard de la NASA?", opciones: ["En Marte", "En el JPL, Pasadena, California", "En la Luna", "En Florida"], respuestaCorrecta: 1, explicacion: "El Mars Yard está en el Jet Propulsion Laboratory en Pasadena. Es un terreno que replica rocas y suelo marciano. 🏜️" },`,
    `            { titulo: "✅ Quiz: Gemelo Testbed", tipo: 'mini_quiz', pregunta: "¿Para qué sirve tener una copia exacta del rover en la Tierra?", opciones: ["Como pieza de museo", "Para reproducir problemas y probar soluciones antes de enviarlas al rover real", "Para venderla", "Solo como repuesto"], respuestaCorrecta: 1, explicacion: "Cuando Curiosity tuvo problemas, los ingenieros reprodujeron la situación exacta en el testbed para encontrar la solución. 🔧" },`,
    `            { titulo: "✅ Quiz: Cámara de Vacío", tipo: 'mini_quiz', pregunta: "¿Qué condiciones simula una cámara de vacío para pruebas?", opciones: ["Solo vacío", "Vacío, temperaturas extremas y radiación del espacio", "Solo temperatura", "Solo presión"], respuestaCorrecta: 1, explicacion: "Las cámaras de vacío recrean el vacío del espacio, temperaturas de -180°C a +150°C y a veces radiación. Todo junto. 🌡️" },`,
    `            { titulo: "✅ Quiz: Tests de Vibración", tipo: 'mini_quiz', pregunta: "¿Por qué se somete al rover a vibraciones extremas?", opciones: ["Para ver si se rompe", "Para simular las fuerzas del lanzamiento del cohete y asegurar que nada se suelte", "Para calibrar sensores", "Para limpiarlo"], respuestaCorrecta: 1, explicacion: "El lanzamiento somete al rover a vibraciones violentas. Las pruebas verifican que cada tornillo, cable y componente resist. 🚀" },`,
    `            { titulo: "✅ Quiz: Simulación Monte Carlo", tipo: 'mini_quiz', pregunta: "¿Qué técnica ejecuta miles de simulaciones con variables aleatorias?", opciones: ["Prueba A/B", "Simulación Monte Carlo", "Test unitario", "Benchmark"], respuestaCorrecta: 1, explicacion: "Monte Carlo ejecuta miles de escenarios con condiciones aleatorias para evaluar la probabilidad de éxito de la misión. 🎰" },`,
    `            { titulo: "✅ Quiz: Reproducibilidad", tipo: 'mini_quiz', pregunta: "¿Por qué las simulaciones usan semillas (seeds) para números aleatorios?", opciones: ["Para crecer plantas virtuales", "Para poder repetir exactamente la misma simulación y depurar errores", "Para hacer trampas", "Para ahorrar memoria"], respuestaCorrecta: 1, explicacion: "Con la misma semilla, la simulación produce los mismos resultados. Esencial para encontrar y corregir errores reproducibles. 🔁" },`,
    `            { titulo: "✅ Quiz: Testing Unitario", tipo: 'mini_quiz', pregunta: "¿Qué es un test unitario en software de rovers?", opciones: ["Probar todo el rover junto", "Probar cada función o componente individual por separado", "Un test que se hace una sola vez", "Un examen para ingenieros"], respuestaCorrecta: 1, explicacion: "Los tests unitarios verifican que cada función individual funcione correctamente antes de integrar todo. Catch bugs temprano. 🧪" },`,
    `            { titulo: "✅ Quiz: HIL", tipo: 'mini_quiz', pregunta: "¿Qué es Hardware-In-the-Loop (HIL) testing?", opciones: ["Probar software con hardware real conectado", "Probar hardware sin software", "Una prueba de resistencia física", "Un tipo de cable"], respuestaCorrecta: 0, explicacion: "HIL conecta el software del rover a hardware real (motores, sensores) en un entorno controlado. Mezcla simulación con realidad. 🔌" },`,
    `            { titulo: "✅ Quiz: Costo del Fallo", tipo: 'mini_quiz', pregunta: "¿Por qué el testing exhaustivo es tan importante en misiones espaciales?", opciones: ["Porque es divertido", "Porque un fallo en Marte NO se puede reparar y la misión cuesta miles de millones", "Para justificar el presupuesto", "No es importante"], respuestaCorrecta: 1, explicacion: "Perseverance costó $2.7 mil millones. No hay segunda oportunidad ni servicio técnico en Marte. Cada test prevenido es un desastre evitado. 💸" },`,
  ],
  'w5_mod13_swarm_rovers': [
    `            { titulo: "✅ Quiz: CADRE", tipo: 'mini_quiz', pregunta: "¿Qué es el proyecto CADRE de la NASA?", opciones: ["Un nuevo cohete", "3 mini-rovers cooperativos que explorarán la Luna como enjambre", "Un telescopio", "Una estación espacial"], respuestaCorrecta: 1, explicacion: "CADRE (Cooperative Autonomous Distributed Robotic Explorers) será el primer enjambre robótico en explorar otro cuerpo celeste. 📦🌙" },`,
    `            { titulo: "✅ Quiz: Descentralización", tipo: 'mini_quiz', pregunta: "¿Qué significa que un enjambre es descentralizado?", opciones: ["Que hay un rover líder", "Que ningún rover es el jefe; cada uno decide localmente", "Que están muy separados", "Que no se comunican"], respuestaCorrecta: 1, explicacion: "Sin líder central, cada rover toma decisiones basándose en información local. Si uno falla, no arrastra a los demás. 🌐" },`,
    `            { titulo: "✅ Quiz: Comunicación Local", tipo: 'mini_quiz', pregunta: "¿Cómo se comunican los rovers en un enjambre?", opciones: ["A través de un satélite central", "Solo con vecinos cercanos, como las hormigas con feromonas", "Por internet global", "No se comunican"], respuestaCorrecta: 1, explicacion: "La comunicación local es eficiente y escalable. Cada rover habla solo con sus vecinos cercanos y la información se propaga gradualmente. 📡" },`,
    `            { titulo: "✅ Quiz: Escalabilidad", tipo: 'mini_quiz', pregunta: "¿Qué pasa si agregas más rovers al enjambre?", opciones: ["Se vuelve más lento", "Se explora más terreno y la misión es más robusta", "Se confunden", "No funciona con más de 5"], respuestaCorrecta: 1, explicacion: "Los enjambres escalan naturalmente: más rovers = más cobertura de terreno, sin necesidad de cambiar el software. 📈" },`,
    `            { titulo: "✅ Quiz: Inspiración Biológica", tipo: 'mini_quiz', pregunta: "¿En qué seres vivos se inspiran los enjambres robóticos?", opciones: ["Elefantes y ballenas", "Hormigas, abejas y bandadas de pájaros", "Solo perros", "Plantas y árboles"], respuestaCorrecta: 1, explicacion: "Las hormigas, abejas y bandadas muestran inteligencia colectiva: comportamiento complejo emergente de reglas individuales simples. 🐜🐝" },`,
    `            { titulo: "✅ Quiz: Tolerancia a Fallos", tipo: 'mini_quiz', pregunta: "¿Qué pasa si 3 de 10 rovers del enjambre fallan?", opciones: ["La misión fracasa", "Los 7 restantes redistribuyen el trabajo y continúan", "Todos se detienen", "Esperan reparación"], respuestaCorrecta: 1, explicacion: "La redundancia natural del enjambre permite que los rovers restantes cubran las zonas de los que fallaron. 🛡️" },`,
    `            { titulo: "✅ Quiz: Mapeo Cooperativo", tipo: 'mini_quiz', pregunta: "¿Cómo crean los rovers del enjambre un mapa compartido?", opciones: ["Cada uno guarda su propio mapa aislado", "Comparten sus mapas locales con vecinos que los fusionan", "Un satélite les da el mapa", "Usan Google Maps"], respuestaCorrecta: 1, explicacion: "Cada rover mapea su entorno y comparte con vecinos. Los mapas se fusionan gradualmente hasta crear uno global completo. 🗺️" },`,
    `            { titulo: "✅ Quiz: Comportamiento Emergente", tipo: 'mini_quiz', pregunta: "¿Qué es 'comportamiento emergente' en enjambres?", opciones: ["Comportamiento de emergencia", "Patrones complejos que surgen de reglas individuales simples", "Cuando los robots se activan", "Un tipo de programación"], respuestaCorrecta: 1, explicacion: "De reglas simples (evitar colisiones, seguir vecinos) emerge comportamiento grupal complejo: formaciones, exploración eficiente. 🌊" },`,
    `            { titulo: "✅ Quiz: Coste del Enjambre", tipo: 'mini_quiz', pregunta: "¿Por qué un enjambre de mini-rovers puede ser más económico que un gran rover?", opciones: ["Porque son de plástico", "Porque cada mini-rover es simple y barato, y la redundancia reduce riesgo", "No son más baratos", "Porque no necesitan energía"], respuestaCorrecta: 1, explicacion: "Un rover de $2.7B es un punto de fallo. 20 mini-rovers de $50M cada uno cuestan menos y sobreviven a la pérdida de unidades. 💰" },`,
  ],
  'w5_mod14_construccion_isru': [
    `            { titulo: "✅ Quiz: Reacción de Sabatier", tipo: 'mini_quiz', pregunta: "¿Qué produce la reacción de Sabatier con CO₂ e hidrógeno?", opciones: ["Oxígeno puro", "Metano (CH₄) y agua (H₂O)", "Nitrógeno", "Helio"], respuestaCorrecta: 1, explicacion: "4H₂ + CO₂ → CH₄ + 2H₂O. Produce metano (combustible para Starship) y agua. ¡La clave de la colonización! ⛽" },`,
    `            { titulo: "✅ Quiz: Agua Marciana", tipo: 'mini_quiz', pregunta: "¿Dónde hay mayor cantidad de hielo de agua en Marte?", opciones: ["En el ecuador", "En los polos y bajo la superficie", "En la atmósfera", "No hay agua en Marte"], respuestaCorrecta: 1, explicacion: "Los polos marcianos tienen casquetes de hielo y radares han detectado hielo subterráneo. Fuente vital para colonias. 🧊" },`,
    `            { titulo: "✅ Quiz: Impresión 3D", tipo: 'mini_quiz', pregunta: "¿Qué material marciano se usaría en impresión 3D de hábitats?", opciones: ["Madera marciana", "Regolito (suelo marciano) mezclado con aglutinante", "Arena de playa", "Metal puro"], respuestaCorrecta: 1, explicacion: "El regolito marciano puede mezclarse con polímeros o sinterizarse para crear ladrillos y estructuras impresas en 3D. 🖨️" },`,
    `            { titulo: "✅ Quiz: Propelente de Retorno", tipo: 'mini_quiz', pregunta: "¿Cuántas toneladas de propelente necesita Starship para volver de Marte?", opciones: ["10 toneladas", "100 toneladas", "~1,000 toneladas", "10,000 toneladas"], respuestaCorrecta: 2, explicacion: "Starship necesita unas 1,000 toneladas de metano y oxígeno líquido. Fabricarlo in-situ es esencial; traerlo de la Tierra sería imposible. 🚀" },`,
    `            { titulo: "✅ Quiz: Electrólisis", tipo: 'mini_quiz', pregunta: "¿Qué proceso separa el agua en hidrógeno y oxígeno?", opciones: ["Evaporación", "Electrólisis (pasar corriente eléctrica por el agua)", "Filtración", "Destilación"], respuestaCorrecta: 1, explicacion: "La electrólisis usa electricidad para separar H₂O en H₂ y O₂. El hidrógeno se usa para la reacción de Sabatier y el oxígeno para respirar. ⚡" },`,
    `            { titulo: "✅ Quiz: Blindaje de Radiación", tipo: 'mini_quiz', pregunta: "¿Cómo protegerían los hábitats marcianos de la radiación?", opciones: ["Con un campo magnético artificial", "Cubriendo con capas de regolito que bloquea la radiación", "Con pintura especial", "No es necesario protegerse"], respuestaCorrecta: 1, explicacion: "Capas gruesas de regolito sobre el hábitat absorben la radiación cósmica, como la atmósfera terrestre nos protege. ☢️" },`,
    `            { titulo: "✅ Quiz: Rovers Constructores", tipo: 'mini_quiz', pregunta: "¿Qué harían los rovers antes de que lleguen los humanos a Marte?", opciones: ["Solo explorar", "Construir hábitats, producir oxígeno y fabricar combustible", "Plantar árboles", "Solo tomar fotos"], respuestaCorrecta: 1, explicacion: "Los rovers de avanzada prepararán toda la infraestructura: base, aire, combustible de retorno. Todo listo para cuando lleguen humanos. 🏗️" },`,
    `            { titulo: "✅ Quiz: Producción de Oxígeno", tipo: 'mini_quiz', pregunta: "¿Cuánto oxígeno necesita un astronauta al día para respirar?", opciones: ["100 gramos", "Aproximadamente 840 gramos (0.84 kg)", "10 kilogramos", "1 gramo"], respuestaCorrecta: 1, explicacion: "Un humano necesita ~0.84 kg de O₂ al día. MOXIE produjo 5g en su prueba. Hay que escalar la producción enormemente. 🫁" },`,
    `            { titulo: "✅ Quiz: Invernadero Marciano", tipo: 'mini_quiz', pregunta: "¿Qué desafío principal tiene cultivar plantas en Marte?", opciones: ["No hay semillas", "La radiación, baja presión, suelo tóxico y poca luz solar", "Hace demasiado calor", "Hay demasiada agua"], respuestaCorrecta: 1, explicacion: "El suelo marciano tiene percloratos tóxicos, la presión es 1% de la terrestre y hay radiación. Necesitas invernaderos cerrados. 🌱" },`,
  ],
  'w5_mod15_competencias_rovers': [
    `            { titulo: "✅ Quiz: URC Categorías", tipo: 'mini_quiz', pregunta: "¿Cuántas categorías evalúa el University Rover Challenge?", opciones: ["Solo 1: velocidad", "5 categorías principales", "10 categorías", "Solo 2"], respuestaCorrecta: 1, explicacion: "El URC evalúa: navegación autónoma, manipulación, ciencia, presentación del diseño y nivel de autonomía. 🏆" },`,
    `            { titulo: "✅ Quiz: ERC Europa", tipo: 'mini_quiz', pregunta: "¿En qué país europeo se realiza el European Rover Challenge?", opciones: ["España", "Francia", "Polonia", "Alemania"], respuestaCorrecta: 2, explicacion: "El ERC se realiza en Polonia y es una de las competencias de rovers más importantes de Europa. 🇵🇱" },`,
    `            { titulo: "✅ Quiz: Reclutamiento", tipo: 'mini_quiz', pregunta: "¿Por qué los reclutadores de SpaceX y NASA asisten a competencias de rovers?", opciones: ["Para hacer turismo", "Para encontrar talento joven con experiencia práctica en robótica", "Para vender productos", "Para criticar los robots"], respuestaCorrecta: 1, explicacion: "Las competencias muestran habilidades reales: diseño, trabajo en equipo, resolución de problemas bajo presión. El CV perfecto. 🎓" },`,
    `            { titulo: "✅ Quiz: Equipo de Competencia", tipo: 'mini_quiz', pregunta: "¿Qué roles necesita un equipo de competencia de rovers?", opciones: ["Solo programadores", "Mecánicos, electrónicos, programadores, diseñadores y comunicadores", "Solo un líder", "Solo ingenieros civiles"], respuestaCorrecta: 1, explicacion: "Un rover es multidisciplinario: necesita mecánica, electrónica, software, diseño CAD, gestión y comunicación. ¡Trabajo en equipo! 🤝" },`,
    `            { titulo: "✅ Quiz: Presupuesto", tipo: 'mini_quiz', pregunta: "¿Cuál es el rango de presupuesto típico para un equipo de URC?", opciones: ["$50 - $100", "$1,000 - $10,000", "$100,000 o más", "No cuesta nada"], respuestaCorrecta: 1, explicacion: "Los equipos suelen gastar $1,000-$10,000 en componentes. Los mejores buscan patrocinadores para cubrir costos. 💰" },`,
    `            { titulo: "✅ Quiz: Navegación Autónoma", tipo: 'mini_quiz', pregunta: "¿Qué prueba de competencia requiere que el rover navegue sin intervención humana?", opciones: ["Presentación oral", "La prueba de navegación autónoma con waypoints GPS", "La prueba de ciencia", "La de manipulación"], respuestaCorrecta: 1, explicacion: "En la prueba de autonomía, el rover debe navegar solo entre puntos GPS sin ningún control humano. La más desafiante. 🧭" },`,
    `            { titulo: "✅ Quiz: Preparación", tipo: 'mini_quiz', pregunta: "¿Cuánto tiempo típicamente tarda un equipo en preparar un rover para competencia?", opciones: ["1 semana", "1 mes", "6-12 meses", "3 años"], respuestaCorrecta: 2, explicacion: "Los equipos competitivos trabajan 6-12 meses: diseño (3 meses), construcción (3 meses), testeo (3 meses), iteración constante. ⏳" },`,
    `            { titulo: "✅ Quiz: Sample Return", tipo: 'mini_quiz', pregunta: "¿Qué debe hacer un rover en el desafío NASA Sample Return?", opciones: ["Solo avanzar rápido", "Encontrar y recolectar muestras de forma completamente autónoma", "Solo tomar fotos", "Levantar pesas"], respuestaCorrecta: 1, explicacion: "El rover debe localizar, recoger y traer muestras sin ayuda humana. Combina navegación, visión y manipulación. 🏅" },`,
    `            { titulo: "✅ Quiz: Habilidades Valoradas", tipo: 'mini_quiz', pregunta: "¿Qué habilidad valoran MÁS los jueces en las competencias?", opciones: ["Que el rover sea bonito", "La resolución creativa de problemas bajo presión", "Que sea el más caro", "Que sea el más grande"], respuestaCorrecta: 1, explicacion: "Los jueces valoran cómo los equipos solucionan problemas inesperados durante la competencia. La creatividad supera al presupuesto. 💡" },`,
  ],
  'w5_mod16_proyecto_rover_final': [
    `            { titulo: "✅ Quiz: Fases de Diseño", tipo: 'mini_quiz', pregunta: "¿Qué fase va ANTES de construir el rover?", opciones: ["Testing", "Diseño y planificación con especificaciones claras", "Programación", "Competencia"], respuestaCorrecta: 1, explicacion: "Siempre se diseña primero: objetivos, planos, materiales, presupuesto. Construir sin diseño es desperdiciar tiempo y recursos. 📋" },`,
    `            { titulo: "✅ Quiz: Documentación", tipo: 'mini_quiz', pregunta: "¿Por qué es importante documentar el diseño de tu rover?", opciones: ["Para hacer tarea", "Para que otros puedan entender, replicar y mejorar tu trabajo", "Solo por burocracia", "No es importante"], respuestaCorrecta: 1, explicacion: "La documentación permite que tú y otros entiendan las decisiones de diseño. Los rovers de la NASA tienen miles de páginas. 📄" },`,
    `            { titulo: "✅ Quiz: Iteración", tipo: 'mini_quiz', pregunta: "¿Qué significa iterar en el desarrollo de un rover?", opciones: ["Hacerlo perfecto a la primera", "Construir, probar, mejorar y repetir el ciclo", "Copiar de internet", "Rendirse si falla"], respuestaCorrecta: 1, explicacion: "La iteración es el corazón de la ingeniería: construyes, pruebas, encuentras problemas, mejoras y repites hasta que funcione. 🔄" },`,
    `            { titulo: "✅ Quiz: Prototipo", tipo: 'mini_quiz', pregunta: "¿Por qué se construyen prototipos antes del producto final?", opciones: ["Para desperdiciar material", "Para probar ideas rápido y barato antes de invertir en el diseño final", "Porque el final siempre falla", "Solo en la NASA"], respuestaCorrecta: 1, explicacion: "Un prototipo de cartón y servos cuesta $20 y muestra si la idea funciona. El diseño final cuesta miles. ¡Prototipa primero! 🛠️" },`,
    `            { titulo: "✅ Quiz: Presupuesto Rover", tipo: 'mini_quiz', pregunta: "¿Cuál es el componente MÁS caro típicamente en un rover estudiantil?", opciones: ["Las ruedas", "La computadora de a bordo (Raspberry Pi/Jetson) y sensores LIDAR", "La pintura", "Los cables"], respuestaCorrecta: 1, explicacion: "La computadora principal y los sensores avanzados como LIDAR suelen ser los componentes más costosos del presupuesto. 💻" },`,
    `            { titulo: "✅ Quiz: Integración", tipo: 'mini_quiz', pregunta: "¿Qué es la integración de sistemas en robótica?", opciones: ["Juntar cables al azar", "Conectar y hacer funcionar juntos mecánica, electrónica y software", "Solo programar", "Solo construir el chasis"], respuestaCorrecta: 1, explicacion: "La integración asegura que los motores respondan al software, los sensores alimenten las decisiones y todo funcione como un sistema. 🧩" },`,
    `            { titulo: "✅ Quiz: Multidisciplinario", tipo: 'mini_quiz', pregunta: "¿Por qué un rover es un proyecto multidisciplinario?", opciones: ["Porque son muchas piezas", "Porque necesita mecánica, electrónica, programación, energía y comunicaciones", "Porque es caro", "Porque lo hacen varias personas"], respuestaCorrecta: 1, explicacion: "Un rover combina ingeniería mecánica, electrónica, software, gestión energética y telecomunicaciones. ¡Muchas disciplinas en un robot! 🎓" },`,
    `            { titulo: "✅ Quiz: Plan de Testing", tipo: 'mini_quiz', pregunta: "¿Qué debe incluir un buen plan de testing para tu rover?", opciones: ["Solo encenderlo y ver si funciona", "Escenarios de prueba, criterios de éxito, pruebas de fallo y resultados documentados", "Solo probarlo una vez", "Nada, si lo construiste bien funciona"], respuestaCorrecta: 1, explicacion: "Un plan de testing define QUÉ probar, CÓMO medirlo, cuándo PASA la prueba y qué hacer si FALLA. Documentar todo. 🧪" },`,
    `            { titulo: "✅ Quiz: Mensaje Final", tipo: 'mini_quiz', pregunta: "¿Cuál es la lección más importante del Desierto de los Rovers?", opciones: ["Los rovers son caros", "Con conocimiento, creatividad y perseverancia puedes construir robots que exploren el universo", "Solo los adultos pueden hacer rovers", "Es imposible hacer un rover"], respuestaCorrecta: 1, explicacion: "¡Exacto! Desde Lunokhod hasta Perseverance, cada rover empezó como una idea. Tu rover puede ser el próximo. ¡Sigue construyendo! 🏆🚀" },`,
  ],
};

// Insert questions before each module's contenidoTeorico closing bracket
let offset = 0;
let total = 0;
for (const [moduleId, qLines] of Object.entries(questions)) {
  const lineIdx = moduleClosings[moduleId];
  if (lineIdx === undefined) { console.log('NOT FOUND:', moduleId); continue; }

  const insertAt = lineIdx + offset;
  lines.splice(insertAt, 0, ...qLines);
  offset += qLines.length;
  total += qLines.length;
  console.log(`${moduleId}: +${qLines.length} questions`);
}

fs.writeFileSync('src/data/world5Data.js', lines.join('\n'));
console.log(`\nTotal: ${total} questions injected into World 5`);
