const fs = require('fs');

let lines = fs.readFileSync('src/data/world6Data.js', 'utf8').split('\n');

// Find closing brackets at 8-space indent
const closingLines = [];
for (let i = 0; i < lines.length; i++) {
  if (lines[i].replace(/\r$/, '').match(/^\s{8}\]\s*$/)) {
    closingLines.push(i);
  }
}
console.log('Found', closingLines.length, 'contenidoTeorico closing brackets');

// Map module IDs to their closing bracket line
const moduleClosings = {};
for (const cl of closingLines) {
  for (let j = cl; j >= Math.max(0, cl - 100); j--) {
    const match = lines[j].match(/id:\s*'(w6_[^']+)'/);
    if (match) {
      moduleClosings[match[1]] = cl;
      break;
    }
  }
}
console.log('Mapped', Object.keys(moduleClosings).length, 'modules');

const questions = {
  'w6_mod1_intro_aerobiosfera': [
    `            { titulo: "✅ Quiz: Concepto Aero-Biosfera", tipo: 'mini_quiz', pregunta: "¿Qué combina la Aero-Biosfera?", opciones: ["Solo drones", "Drones, sensores y agricultura sostenible para proteger ecosistemas", "Solo plantas", "Solo energía solar"], respuestaCorrecta: 1, explicacion: "La Aero-Biosfera une tecnología aérea (drones), sensores ambientales y agricultura inteligente para un futuro verde. 🌍" },`,
    `            { titulo: "✅ Quiz: Agricultura de Precisión", tipo: 'mini_quiz', pregunta: "¿Qué es la agricultura de precisión?", opciones: ["Plantar en línea recta", "Usar tecnología para aplicar recursos exactos donde y cuando se necesitan", "Solo usar tractores", "Regar todo por igual"], respuestaCorrecta: 1, explicacion: "La agricultura de precisión optimiza agua, fertilizantes y pesticidas usando GPS, drones y sensores. Menos desperdicio, más producción. 🎯" },`,
    `            { titulo: "✅ Quiz: Impacto Ambiental", tipo: 'mini_quiz', pregunta: "¿Cómo ayudan los drones agrícolas al medio ambiente?", opciones: ["Contaminan más", "Reducen el uso de químicos hasta un 90% al aplicarlos solo donde se necesitan", "No ayudan", "Solo toman fotos"], respuestaCorrecta: 1, explicacion: "Los drones aplican pesticidas con precisión milimétrica solo donde hay plagas. Menos químicos = menos contaminación del suelo y agua. 🌱" },`,
    `            { titulo: "✅ Quiz: Revolución Verde Digital", tipo: 'mini_quiz', pregunta: "¿Qué tecnologías incluye la revolución verde digital?", opciones: ["Solo Internet", "IoT, drones, IA, sensores y big data aplicados a la agricultura", "Solo redes sociales", "Solo robots grandes"], respuestaCorrecta: 1, explicacion: "La AgTech combina IoT (sensores conectados), drones, inteligencia artificial y big data para cultivos más eficientes y sostenibles. 📊" },`,
    `            { titulo: "✅ Quiz: ODS y Robótica", tipo: 'mini_quiz', pregunta: "¿Con qué Objetivo de Desarrollo Sostenible (ODS) se relaciona la Aero-Biosfera?", opciones: ["ODS 1: Sin pobreza", "ODS 2: Hambre Cero y ODS 15: Vida de ecosistemas terrestres", "ODS 4: Educación", "ODS 10: Desigualdades"], respuestaCorrecta: 1, explicacion: "La Aero-Biosfera contribuye a ODS 2 (acabar con el hambre) y ODS 15 (proteger ecosistemas terrestres). ¡Tecnología con propósito! 🎯" },`,
    `            { titulo: "✅ Quiz: Drones vs Satélites", tipo: 'mini_quiz', pregunta: "¿Cuál es la ventaja de un dron agrícola sobre un satélite para monitoreo de cultivos?", opciones: ["Es más barato de fabricar", "Mayor resolución, puede volar bajo nubes y opera bajo demanda", "Tiene más alcance", "No tiene ventajas"], respuestaCorrecta: 1, explicacion: "Los drones vuelan a 50-100m, dando imágenes de resolución centimétrica vs metros del satélite. Además, no les afectan las nubes. 📸" },`,
    `            { titulo: "✅ Quiz: Sensores Multiespectral", tipo: 'mini_quiz', pregunta: "¿Para qué se usan cámaras multiespectrales en drones agrícolas?", opciones: ["Para hacer selfies", "Para detectar estrés hídrico y enfermedades de plantas invisibles al ojo humano", "Para grabar videos bonitos", "Para medir velocidad del viento"], respuestaCorrecta: 1, explicacion: "Las cámaras multiespectrales ven en infrarrojo y otras bandas. Las plantas estresadas reflejan diferente y se detecta antes de que sea visible. 🌿" },`,
    `            { titulo: "✅ Quiz: Sostenibilidad", tipo: 'mini_quiz', pregunta: "¿Qué significa agricultura sostenible?", opciones: ["Producir lo más barato posible", "Producir alimentos sin agotar recursos naturales para futuras generaciones", "Solo usar máquinas", "Eliminar toda tecnología"], respuestaCorrecta: 1, explicacion: "Sostenible = satisfacer necesidades actuales sin comprometer las de futuras generaciones. Equilibrio entre producción y planeta. ♻️" },`,
    `            { titulo: "✅ Quiz: Población Mundial", tipo: 'mini_quiz', pregunta: "¿Por qué es urgente mejorar la agricultura con tecnología?", opciones: ["Por moda", "Porque para 2050 habrá 10 mil millones de personas y se necesita 60% más comida", "No es urgente", "Solo por negocio"], respuestaCorrecta: 1, explicacion: "La ONU estima que necesitaremos 60% más alimentos para 2050. Sin tecnología agrícola no podremos alimentar al mundo. ¡Es vital! 🌾" },`,
  ],
  'w6_mod2_fundamentos_drones': [
    `            { titulo: "✅ Quiz: Tipos de Drones", tipo: 'mini_quiz', pregunta: "¿Qué tipo de dron es más estable para fotografía aérea?", opciones: ["Ala fija", "Multirotor (cuadricóptero) por su capacidad de hover", "Helicóptero", "Globo aerostático"], respuestaCorrecta: 1, explicacion: "Los multirotores pueden quedarse quietos en el aire (hover), ideal para fotos y mapeo. Los de ala fija son mejores para grandes áreas. 🚁" },`,
    `            { titulo: "✅ Quiz: Sustentación", tipo: 'mini_quiz', pregunta: "¿Cómo genera sustentación un dron multirotor?", opciones: ["Con helio", "Las hélices empujan aire hacia abajo, creando una fuerza hacia arriba", "Con alas fijas", "Con cohetes"], respuestaCorrecta: 1, explicacion: "Tercera ley de Newton: las hélices empujan aire abajo → el aire empuja el dron arriba. Más RPM = más sustentación. ⬆️" },`,
    `            { titulo: "✅ Quiz: Cuadricóptero", tipo: 'mini_quiz', pregunta: "¿Cómo gira un cuadricóptero hacia la derecha?", opciones: ["Todas las hélices giran más rápido", "Los motores izquierdos giran más rápido que los derechos", "Se inclina con el viento", "Usa un timón"], respuestaCorrecta: 1, explicacion: "Al aumentar velocidad de motores izquierdos, el dron se inclina a la derecha y se mueve en esa dirección. ¡Diferencial de empuje! 🔄" },`,
    `            { titulo: "✅ Quiz: ESC", tipo: 'mini_quiz', pregunta: "¿Qué función tiene el ESC (Electronic Speed Controller) en un dron?", opciones: ["Medir altura", "Controlar la velocidad de giro de cada motor sin escobillas", "Transmitir video", "Cargar la batería"], respuestaCorrecta: 1, explicacion: "El ESC convierte señales del controlador de vuelo en pulsos trifásicos para cada motor brushless. ¡Es el driver de los motores! ⚡" },`,
    `            { titulo: "✅ Quiz: Controlador de Vuelo", tipo: 'mini_quiz', pregunta: "¿Qué hace el controlador de vuelo (flight controller)?", opciones: ["Solo graba video", "Lee IMU y GPS, calcula ajustes de motores para mantener estabilidad", "Solo enciende LEDs", "Controla la cámara"], respuestaCorrecta: 1, explicacion: "El FC (como Pixhawk o F4) lee acelerómetro, giroscopio, barómetro y GPS. Ajusta miles de veces por segundo cada motor. 🧠" },`,
    `            { titulo: "✅ Quiz: Batería LiPo Dron", tipo: 'mini_quiz', pregunta: "¿Qué significa una batería '4S 5000mAh' para un dron?", opciones: ["4 segundos de vuelo", "4 celdas en serie (14.8V) con capacidad de 5000mAh", "4 baterías separadas", "5000 metros de alcance"], respuestaCorrecta: 1, explicacion: "4S = 4 celdas × 3.7V = 14.8V nominal. 5000mAh = capacidad. Más S = más voltaje. Más mAh = más tiempo de vuelo. 🔋" },`,
    `            { titulo: "✅ Quiz: PID en Drones", tipo: 'mini_quiz', pregunta: "¿Por qué es crucial el tuneo PID en un dron?", opciones: ["Para que vuele más alto", "Para que responda suavemente sin oscilar ni vibrar", "Para aumentar la velocidad", "No es importante"], respuestaCorrecta: 1, explicacion: "PID mal configurado = dron que vibra, oscila o no responde. Bien tuneado = vuelo suave y estable. ¡Es el alma del vuelo! 🎯" },`,
    `            { titulo: "✅ Quiz: Payload", tipo: 'mini_quiz', pregunta: "¿Qué es el payload de un dron?", opciones: ["Su peso total", "La carga útil que puede transportar (cámaras, sensores, líquidos)", "La velocidad máxima", "El alcance del control"], respuestaCorrecta: 1, explicacion: "Payload = carga útil. Un dron agrícola puede cargar 10-20L de pesticida. A más payload, más potentes deben ser los motores. ⚖️" },`,
    `            { titulo: "✅ Quiz: Regulaciones", tipo: 'mini_quiz', pregunta: "¿Por qué existen regulaciones para volar drones?", opciones: ["Para vender más licencias", "Para seguridad aérea: evitar colisiones con aviones y proteger personas", "No existen regulaciones", "Solo por impuestos"], respuestaCorrecta: 1, explicacion: "Los drones comparten espacio aéreo con aviones. Regulaciones como no volar sobre 120m o cerca de aeropuertos previenen accidentes graves. ✈️" },`,
  ],
  'w6_mod3_sensores_ambientales': [
    `            { titulo: "✅ Quiz: Sensor de Humedad del Suelo", tipo: 'mini_quiz', pregunta: "¿Cómo funciona un sensor capacitivo de humedad del suelo?", opciones: ["Mide la temperatura", "Mide cambios de capacitancia eléctrica causados por el agua en el suelo", "Mide el pH", "Mide la luz"], respuestaCorrecta: 1, explicacion: "El agua cambia la constante dieléctrica del suelo. El sensor capacitivo detecta este cambio sin corroerse como los resistivos. 💧" },`,
    `            { titulo: "✅ Quiz: Estación Meteorológica", tipo: 'mini_quiz', pregunta: "¿Qué datos mide una estación meteorológica agrícola completa?", opciones: ["Solo temperatura", "Temperatura, humedad, presión, viento, lluvia y radiación solar", "Solo si llueve o no", "Solo la hora"], respuestaCorrecta: 1, explicacion: "Una estación completa mide 6+ variables: temp, humedad, presión barométrica, velocidad/dirección del viento, lluvia y radiación UV. 🌤️" },`,
    `            { titulo: "✅ Quiz: NDVI", tipo: 'mini_quiz', pregunta: "¿Qué mide el índice NDVI en agricultura?", opciones: ["La temperatura del suelo", "La salud y vigor de la vegetación usando luz roja e infrarroja", "La humedad del aire", "La velocidad del viento"], respuestaCorrecta: 1, explicacion: "NDVI = (NIR - Rojo) / (NIR + Rojo). Plantas sanas reflejan mucho infrarrojo cercano. Valores altos = vegetación vigorosa. 🌿" },`,
    `            { titulo: "✅ Quiz: Sensor de pH", tipo: 'mini_quiz', pregunta: "¿Por qué es importante medir el pH del suelo?", opciones: ["Por curiosidad", "Porque cada cultivo necesita un rango específico de pH para absorber nutrientes", "Para saber el color del suelo", "No es importante"], respuestaCorrecta: 1, explicacion: "pH ácido o alcalino bloquean nutrientes. Tomates prefieren pH 6.0-6.8. Arándanos pH 4.5-5.5. ¡Sin pH correcto, no hay cosecha! 🍅" },`,
    `            { titulo: "✅ Quiz: Sensor de CO2", tipo: 'mini_quiz', pregunta: "¿Para qué se mide CO2 en un invernadero?", opciones: ["Para purificar el aire", "Para optimizar la fotosíntesis: las plantas necesitan CO2 para crecer", "Para evitar incendios", "Para medir olores"], respuestaCorrecta: 1, explicacion: "Las plantas usan CO2 para fotosíntesis. En invernaderos, inyectar CO2 extra (de 400 a 1000 ppm) puede aumentar el crecimiento 30%. 🌱" },`,
    `            { titulo: "✅ Quiz: Anemómetro", tipo: 'mini_quiz', pregunta: "¿Qué mide un anemómetro y por qué importa en agricultura?", opciones: ["La presión del agua", "La velocidad del viento, que afecta evaporación y aplicación de pesticidas", "La temperatura del suelo", "La dureza del terreno"], respuestaCorrecta: 1, explicacion: "El viento acelera la evaporación y dispersa pesticidas. Con viento >15 km/h no se recomienda fumigar. ¡Los datos del viento son críticos! 💨" },`,
    `            { titulo: "✅ Quiz: Pluviómetro", tipo: 'mini_quiz', pregunta: "¿Cómo funciona un pluviómetro de balancín (tipping bucket)?", opciones: ["Pesa las nubes", "Un pequeño balde bascula al llenarse, contando los basculamientos como pulsos", "Mide la presión de lluvia", "Usa ultrasonido"], respuestaCorrecta: 1, explicacion: "El agua llena un mini-balde que bascula al llenarse (ej: cada 0.2mm). Cada basculamiento genera un pulso digital. Arduino cuenta los pulsos. 🌧️" },`,
    `            { titulo: "✅ Quiz: Sensor NPK", tipo: 'mini_quiz', pregunta: "¿Qué miden los sensores NPK del suelo?", opciones: ["Temperatura del suelo", "Nitrógeno, Fósforo y Potasio: los 3 nutrientes principales de las plantas", "La humedad del aire", "El dióxido de carbono"], respuestaCorrecta: 1, explicacion: "NPK = los 3 macronutrientes esenciales. N para hojas verdes, P para raíces/flores, K para frutos y resistencia. ¡El ABC de la fertilización! 🧪" },`,
    `            { titulo: "✅ Quiz: Datalogger", tipo: 'mini_quiz', pregunta: "¿Para qué se usa un datalogger en agricultura?", opciones: ["Para jugar", "Para registrar datos de sensores continuamente y analizarlos después", "Para encender luces", "Para controlar motores"], respuestaCorrecta: 1, explicacion: "Un datalogger (con SD card + RTC) guarda lecturas cada 5-15 min. Permite ver tendencias de temp, humedad, etc. durante semanas. 📊" },`,
  ],
  'w6_mod4_riego_precision': [
    `            { titulo: "✅ Quiz: Riego por Goteo", tipo: 'mini_quiz', pregunta: "¿Cuál es la ventaja del riego por goteo sobre el riego por aspersión?", opciones: ["Es más barato siempre", "Ahorra hasta 70% de agua al aplicarla directamente en la raíz", "Cubre más área", "Es más fácil de instalar"], respuestaCorrecta: 1, explicacion: "El goteo entrega agua gota a gota directamente a la zona de raíces. Menos evaporación = hasta 70% menos agua vs aspersión. 💧" },`,
    `            { titulo: "✅ Quiz: Evapotranspiración", tipo: 'mini_quiz', pregunta: "¿Qué es la evapotranspiración (ET) y por qué importa para riego?", opciones: ["La temperatura del agua", "La cantidad de agua que pierde un cultivo por evaporación y transpiración", "La velocidad de riego", "La presión del agua"], respuestaCorrecta: 1, explicacion: "ET = agua que la planta transpira + la que se evapora del suelo. Si ET > riego, la planta se estresa. Los sensores miden ET para regar exacto. 🌡️" },`,
    `            { titulo: "✅ Quiz: Electroválvula", tipo: 'mini_quiz', pregunta: "¿Cómo controla Arduino una electroválvula de riego?", opciones: ["Directamente con un pin digital", "Mediante un relé o MOSFET que activa la electroválvula de 12V/24V", "Con WiFi", "Con Bluetooth"], respuestaCorrecta: 1, explicacion: "Las electroválvulas necesitan 12-24V y alta corriente. Arduino usa un relé como interruptor. digitalWrite(RELE, HIGH) abre el agua. 🔌" },`,
    `            { titulo: "✅ Quiz: Sensor de Flujo", tipo: 'mini_quiz', pregunta: "¿Para qué se usa un sensor de flujo de agua en un sistema de riego?", opciones: ["Para medir temperatura", "Para medir exactamente cuántos litros de agua se aplican", "Para medir presión", "Para filtrar el agua"], respuestaCorrecta: 1, explicacion: "El sensor de flujo cuenta pulsos proporcionales al caudal. Permite saber exactamente cuántos litros usaste y detectar fugas. 📏" },`,
    `            { titulo: "✅ Quiz: Programación de Riego", tipo: 'mini_quiz', pregunta: "¿Qué datos necesita un sistema de riego inteligente para decidir cuándo regar?", opciones: ["Solo la hora", "Humedad del suelo, temperatura, lluvia reciente y necesidades del cultivo", "Solo el día de la semana", "Solo la presión del agua"], respuestaCorrecta: 1, explicacion: "Un sistema inteligente NO riega por horario fijo. Riega cuando la humedad del suelo baja del umbral del cultivo. ¡Cada planta es diferente! 🌿" },`,
    `            { titulo: "✅ Quiz: Zonas de Riego", tipo: 'mini_quiz', pregunta: "¿Por qué se divide un campo en zonas de riego independientes?", opciones: ["Por estética", "Porque diferentes zonas tienen distintas necesidades según suelo, pendiente y cultivo", "Para gastar más agua", "No se divide"], respuestaCorrecta: 1, explicacion: "Cada zona puede tener diferente tipo de suelo, exposición solar y cultivo. Regar igual en todas partes es ineficiente. ¡Personalización! 🗺️" },`,
    `            { titulo: "✅ Quiz: Mulching", tipo: 'mini_quiz', pregunta: "¿Cómo complementa el mulching (acolchado) al riego de precisión?", opciones: ["Aumenta la evaporación", "Reduce la evaporación del suelo hasta un 70%, ahorrando agua", "Elimina la necesidad de riego", "Solo mejora la estética"], respuestaCorrecta: 1, explicacion: "El acolchado (paja, plástico, corteza) cubre el suelo y reduce drásticamente la evaporación. Combinado con goteo = máximo ahorro de agua. 🌾" },`,
    `            { titulo: "✅ Quiz: Tensiómetro", tipo: 'mini_quiz', pregunta: "¿Qué mide un tensiómetro de suelo?", opciones: ["La temperatura del suelo", "La tensión hídrica: cuánto esfuerzo necesita la planta para absorber agua", "La acidez del suelo", "La velocidad del viento"], respuestaCorrecta: 1, explicacion: "El tensiómetro mide la succión del suelo en centibares. Valores altos = suelo seco, la planta sufre. Regar cuando supera el umbral del cultivo. 📐" },`,
    `            { titulo: "✅ Quiz: Fertirrigación", tipo: 'mini_quiz', pregunta: "¿Qué es la fertirrigación?", opciones: ["Regar con agua pura", "Aplicar fertilizantes disueltos en el agua de riego directamente a las raíces", "Fertilizar sin agua", "Usar solo abono orgánico"], respuestaCorrecta: 1, explicacion: "La fertirrigación combina riego + fertilización. Los nutrientes llegan disueltos directamente a la raíz. Máxima eficiencia y mínimo desperdicio. 💧🧪" },`,
  ],
  'w6_mod5_vuelo_autonomo': [
    `            { titulo: "✅ Quiz: GPS Diferencial", tipo: 'mini_quiz', pregunta: "¿Qué es RTK-GPS y por qué se usa en drones agrícolas?", opciones: ["Un tipo de batería", "GPS de precisión centimétrica (2cm) para vuelo y mapeo exacto", "Un protocolo WiFi", "Un tipo de motor"], respuestaCorrecta: 1, explicacion: "RTK (Real Time Kinematic) mejora el GPS de ±3m a ±2cm de precisión. Esencial para mapeo preciso y fumigación sin solapamiento. 📍" },`,
    `            { titulo: "✅ Quiz: Waypoints", tipo: 'mini_quiz', pregunta: "¿Qué son los waypoints en un plan de vuelo autónomo?", opciones: ["Marcas en el mapa", "Puntos GPS predefinidos que el dron sigue automáticamente en secuencia", "Señales de radio", "Obstáculos a evitar"], respuestaCorrecta: 1, explicacion: "Los waypoints son coordenadas GPS (lat, lon, alt) que definen la ruta. El dron vuela de uno a otro automáticamente. ¡Una ruta programada! 🗺️" },`,
    `            { titulo: "✅ Quiz: Failsafe", tipo: 'mini_quiz', pregunta: "¿Qué hace el modo failsafe de un dron?", opciones: ["Aumenta la velocidad", "Si pierde señal o batería baja, regresa al punto de despegue automáticamente", "Se apaga inmediatamente", "Vuela más alto"], respuestaCorrecta: 1, explicacion: "RTH (Return To Home) se activa si se pierde radiocontrol, batería <20%, o GPS falla. El dron regresa solo. ¡Seguridad primero! 🏠" },`,
    `            { titulo: "✅ Quiz: IMU en Drones", tipo: 'mini_quiz', pregunta: "¿Qué parámetros mide la IMU de un dron?", opciones: ["Solo velocidad", "Aceleración (3 ejes), giro (3 ejes) y campo magnético para orientación", "Solo temperatura", "Solo altitud"], respuestaCorrecta: 1, explicacion: "IMU = acelerómetro + giroscopio + magnetómetro. Mide rotación, inclinación y orientación. El dron sabe su actitud 1000+ veces/segundo. 📐" },`,
    `            { titulo: "✅ Quiz: Geofence", tipo: 'mini_quiz', pregunta: "¿Qué es un geofence en drones?", opciones: ["Un tipo de antena", "Un límite geográfico virtual que restringe el vuelo a una zona permitida", "Un sensor de proximidad", "Un tipo de batería"], respuestaCorrecta: 1, explicacion: "El geofence crea un muro invisible. Si el dron intenta salir de la zona definida, frena automáticamente. Evita invasión de espacio aéreo restringido. 🚧" },`,
    `            { titulo: "✅ Quiz: Altímetro Barométrico", tipo: 'mini_quiz', pregunta: "¿Cómo mide la altitud un dron usando un barómetro?", opciones: ["Con GPS solamente", "Calcula altitud a partir de cambios de presión atmosférica (menos presión = más alto)", "Con sensores de luz", "Con cámara"], respuestaCorrecta: 1, explicacion: "La presión baja ~1 hPa cada 8.5m de ascenso. El barómetro mide esto con precisión de ~50cm. Más preciso que GPS para altitud. 📊" },`,
    `            { titulo: "✅ Quiz: Vuelo en Patrón", tipo: 'mini_quiz', pregunta: "¿Qué patrón de vuelo usa un dron para fumigar un campo rectangular?", opciones: ["Circular", "Pasadas paralelas (lawnmower pattern) para cobertura total sin huecos", "Zigzag aleatorio", "Solo ida y vuelta"], respuestaCorrecta: 1, explicacion: "El patrón de pasadas paralelas (como cortar césped) asegura cobertura del 100% del campo. El espaciado entre pasadas depende del ancho de fumigación. 🌾" },`,
    `            { titulo: "✅ Quiz: LIDAR en Drones", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene el LIDAR sobre una cámara en un dron agrícola?", opciones: ["Es más barato", "Puede medir elevación del terreno y altura de cultivos con precisión milimétrica", "Toma mejores fotos", "Usa menos batería"], respuestaCorrecta: 1, explicacion: "LIDAR mide distancias con láser creando mapas 3D precisos. Puede medir la altura de cada planta individualmente. ¡Rayos X para el campo! 🔦" },`,
    `            { titulo: "✅ Quiz: Mission Planner", tipo: 'mini_quiz', pregunta: "¿Para qué se usa software como Mission Planner o QGroundControl?", opciones: ["Para editar fotos", "Para planificar rutas de vuelo, configurar drones y monitorear telemetría en tiempo real", "Para juegos", "Para editar código"], respuestaCorrecta: 1, explicacion: "Mission Planner permite dibujar rutas en mapa, configurar failsafe, ver telemetría en vivo y analizar logs de vuelo. ¡Centro de control! 🖥️" },`,
  ],
  'w6_mod6_mapeo_aereo': [
    `            { titulo: "✅ Quiz: Fotogrametría", tipo: 'mini_quiz', pregunta: "¿Qué es la fotogrametría aérea?", opciones: ["Fotografía con flash", "Crear modelos 3D y mapas a partir de múltiples fotos aéreas superpuestas", "Fotografía nocturna", "Un filtro de cámara"], respuestaCorrecta: 1, explicacion: "La fotogrametría une cientos de fotos superpuestas (60-80% overlap) para crear mapas 2D y modelos 3D precisos del terreno. ¡Magia matemática! 🗺️" },`,
    `            { titulo: "✅ Quiz: GSD", tipo: 'mini_quiz', pregunta: "¿Qué es el GSD (Ground Sample Distance)?", opciones: ["La distancia del GPS", "El tamaño real en cm que representa cada pixel de la imagen aérea", "La velocidad del dron", "La altura de vuelo"], respuestaCorrecta: 1, explicacion: "GSD de 2 cm/pixel = cada pixel cubre 2×2 cm del suelo. Más bajo el dron = menor GSD = mayor detalle. Para agricultura: 3-5 cm/px es ideal. 📏" },`,
    `            { titulo: "✅ Quiz: Ortomosaico", tipo: 'mini_quiz', pregunta: "¿Qué es un ortomosaico?", opciones: ["Un tipo de cultivo", "Un mapa aéreo completo corregido geométricamente donde se pueden medir distancias reales", "Una foto normal", "Un diseño artístico"], respuestaCorrecta: 1, explicacion: "El ortomosaico corrige la perspectiva de cada foto para crear un mapa donde 1cm en pantalla = 1cm real en el campo. Mediciones exactas. 📐" },`,
    `            { titulo: "✅ Quiz: Modelo Digital de Elevación", tipo: 'mini_quiz', pregunta: "¿Para qué sirve un DEM (Digital Elevation Model) en agricultura?", opciones: ["Para juegos", "Para identificar zonas bajas donde se acumula agua o altas con erosión", "Para decoración", "No tiene uso agrícola"], respuestaCorrecta: 1, explicacion: "El DEM muestra la topografía exacta. Las zonas bajas acumulan agua (posible encharcamiento), las altas tienen erosión. ¡Planifica con datos! ⛰️" },`,
    `            { titulo: "✅ Quiz: Overlap en Fotografía Aérea", tipo: 'mini_quiz', pregunta: "¿Por qué las fotos aéreas necesitan al menos 70% de superposición (overlap)?", opciones: ["Para usar más memoria", "Para que el software pueda identificar puntos comunes y crear el mapa 3D", "Por estética", "No necesitan overlap"], respuestaCorrecta: 1, explicacion: "El software necesita ver cada punto del suelo en al menos 3 fotos distintas para triangular y crear el modelo 3D preciso. ¡Geometría del aire! 📷" },`,
    `            { titulo: "✅ Quiz: Índice de Vegetación", tipo: 'mini_quiz', pregunta: "¿Qué colores muestra un mapa NDVI típico?", opciones: ["Solo blanco y negro", "Rojo/amarillo = vegetación estresada, verde = vegetación sana", "Solo azul", "Colores aleatorios"], respuestaCorrecta: 1, explicacion: "En mapas NDVI: verde oscuro = planta sana y vigorosa, amarillo = estrés moderado, rojo = planta muy enferma o suelo sin vegetación. 🟢🟡🔴" },`,
    `            { titulo: "✅ Quiz: Nube de Puntos", tipo: 'mini_quiz', pregunta: "¿Qué es una nube de puntos 3D generada por fotogrametría?", opciones: ["Datos meteorológicos", "Millones de puntos con coordenadas XYZ que representan la superficie del terreno", "Puntos en un diagrama", "Un tipo de sensor"], respuestaCorrecta: 1, explicacion: "Cada punto tiene X,Y,Z + color. Millones de puntos crean un modelo 3D detallado. Se puede medir altura de árboles, volumen de tierra, etc. 🌐" },`,
    `            { titulo: "✅ Quiz: Cámara RGB vs Multiespectral", tipo: 'mini_quiz', pregunta: "¿Cuándo usar cámara multiespectral en vez de RGB en un dron?", opciones: ["Siempre", "Cuando necesitas detectar estrés hídrico o enfermedades antes de que sean visibles", "Nunca", "Solo de noche"], respuestaCorrecta: 1, explicacion: "RGB ve lo que ven nuestros ojos. La multiespectral ve infrarrojo que revela estrés invisible al ojo humano. Detecta problemas 2 semanas antes. 📸" },`,
    `            { titulo: "✅ Quiz: Georeferenciación", tipo: 'mini_quiz', pregunta: "¿Qué significa que un mapa esté georeferenciado?", opciones: ["Que tiene colores bonitos", "Que cada pixel tiene coordenadas GPS reales (latitud, longitud)", "Que fue tomado desde el espacio", "Que está en blanco y negro"], respuestaCorrecta: 1, explicacion: "Georeferenciado = cada punto del mapa tiene coordenadas GPS. Puedes ubicar exactamente dónde está cada problema del cultivo. 📍" },`,
  ],
  'w6_mod7_fumigacion_inteligente': [
    `            { titulo: "✅ Quiz: Fumigación por Zonas", tipo: 'mini_quiz', pregunta: "¿Qué es la fumigación variable o por zonas?", opciones: ["Fumigar todo igual", "Aplicar diferentes dosis según las necesidades de cada zona del campo", "Solo fumigar de noche", "Solo fumigar por la mañana"], respuestaCorrecta: 1, explicacion: "Con mapas de NDVI, el dron aplica más pesticida donde hay más plaga y nada donde no se necesita. ¡Ahorro y menor impacto ambiental! 🎯" },`,
    `            { titulo: "✅ Quiz: Boquillas de Fumigación", tipo: 'mini_quiz', pregunta: "¿Por qué son importantes las boquillas en un dron fumigador?", opciones: ["Solo por estética", "Determinan el tamaño de gota: gotas finas cubren más pero el viento las arrastra", "No son importantes", "Solo por el color"], respuestaCorrecta: 1, explicacion: "Gotas finas (<150μm) cubren más pero derivan con el viento. Gotas gruesas (>300μm) son más pesadas pero cubren menos. ¡Balance perfecto! 💨" },`,
    `            { titulo: "✅ Quiz: Deriva de Pesticidas", tipo: 'mini_quiz', pregunta: "¿Qué es la deriva de pesticidas y cómo la minimizan los drones?", opciones: ["El precio del pesticida", "El arrastre de gotas por el viento; los drones vuelan bajo (2-3m) para reducirla", "La cantidad usada", "El color del pesticida"], respuestaCorrecta: 1, explicacion: "La deriva = gotas que el viento lleva fuera del objetivo. Los drones vuelan a 2-3m del cultivo vs tractores a mayor altura. Menos deriva = menos contaminación. ⬇️" },`,
    `            { titulo: "✅ Quiz: Eficiencia de Drones Fumigadores", tipo: 'mini_quiz', pregunta: "¿Cuántas hectáreas puede fumigar un dron agrícola por hora?", opciones: ["0.1 hectáreas", "8-15 hectáreas por hora (con tanque de 10-20L)", "100 hectáreas", "Solo 1 metro cuadrado"], respuestaCorrecta: 1, explicacion: "Los drones agro modernos (DJI Agras) cubren 8-15 ha/hora. Con recarga rápida de batería y tanque, un equipo cubre 50+ ha/día. 🚀" },`,
    `            { titulo: "✅ Quiz: IPM", tipo: 'mini_quiz', pregunta: "¿Qué es el Manejo Integrado de Plagas (IPM)?", opciones: ["Fumigar todo el campo cada semana", "Combinar métodos biológicos, culturales y químicos, usando pesticidas solo como último recurso", "Eliminar todos los insectos", "Usar solo insecticidas"], respuestaCorrecta: 1, explicacion: "IPM = prevención + monitoreo + control biológico + químico solo si es necesario. Los drones con cámaras ayudan en el monitoreo. 🐛" },`,
    `            { titulo: "✅ Quiz: Calibración del Sistema", tipo: 'mini_quiz', pregunta: "¿Por qué es crucial calibrar el sistema de fumigación del dron?", opciones: ["Para que vuele más rápido", "Para asegurar que la dosis por hectárea sea exacta y uniforme", "No es necesario", "Para ahorrar batería"], respuestaCorrecta: 1, explicacion: "Sin calibración, puedes aplicar más o menos de lo necesario. Demasiado = contaminación y desperdicio. Poco = la plaga no se controla. 📏" },`,
    `            { titulo: "✅ Quiz: Momento de Aplicación", tipo: 'mini_quiz', pregunta: "¿Cuál es el mejor momento del día para fumigar con dron?", opciones: ["Mediodía", "Temprano en la mañana o al atardecer: menos viento y evaporación", "Medianoche", "No importa el momento"], respuestaCorrecta: 1, explicacion: "Mañana temprano (6-9am) o atardecer: menos viento, menos evaporación, mejor adherencia. Evitar calor y viento fuerte del mediodía. ☀️" },`,
    `            { titulo: "✅ Quiz: Mapa de Prescripción", tipo: 'mini_quiz', pregunta: "¿Qué es un mapa de prescripción en fumigación de precisión?", opciones: ["Un mapa de carreteras", "Un mapa que indica qué dosis aplicar en cada zona del campo", "Un mapa meteorológico", "Un mapa turístico"], respuestaCorrecta: 1, explicacion: "El mapa de prescripción se genera a partir de datos NDVI/sensores. Cada zona tiene su dosis recomendada. ¡Receta personalizada para cada metro! 🗺️" },`,
    `            { titulo: "✅ Quiz: Control Biológico Aéreo", tipo: 'mini_quiz', pregunta: "¿Cómo pueden los drones dispersar agentes de control biológico?", opciones: ["No pueden", "Lanzando cápsulas con insectos benéficos o asperjando bacterias Bt", "Solo con bombas", "Solo con humo"], respuestaCorrecta: 1, explicacion: "Los drones lanzan tricogramas (avispitas que atacan plagas) o asperjan Bacillus thuringiensis (Bt). ¡Control natural desde el aire! 🐝" },`,
  ],
  'w6_mod8_polinizacion_robotica': [
    `            { titulo: "✅ Quiz: Crisis de Polinizadores", tipo: 'mini_quiz', pregunta: "¿Por qué están desapareciendo las abejas en muchos países?", opciones: ["Se van de vacaciones", "Pesticidas, parásitos, pérdida de hábitat y cambio climático", "Se esconden mejor", "No están desapareciendo"], respuestaCorrecta: 1, explicacion: "El síndrome de colapso de colonias (CCD) reduce poblaciones un 30-40% anual en algunos países. Sin abejas, no hay frutas ni verduras. 🐝⚠️" },`,
    `            { titulo: "✅ Quiz: Importancia de la Polinización", tipo: 'mini_quiz', pregunta: "¿Qué porcentaje de cultivos depende de la polinización animal?", opciones: ["10%", "Aproximadamente 75% de los cultivos alimentarios del mundo", "100%", "0%"], respuestaCorrecta: 1, explicacion: "El 75% de los cultivos dependen de polinizadores. Sin ellos: no más manzanas, chocolate, café, almendras, fresas... ¡Bye bye a tu comida favorita! 🍎" },`,
    `            { titulo: "✅ Quiz: RoboBee", tipo: 'mini_quiz', pregunta: "¿Qué es el proyecto RoboBee de Harvard?", opciones: ["Un videojuego", "Un micro-robot del tamaño de una abeja que puede volar y polinizar flores", "Un tipo de miel", "Una app de celular"], respuestaCorrecta: 1, explicacion: "RoboBee pesa solo 80mg y vuela con alas piezoeléctricas. Aún no puede polinizar individualmente, pero demuestra el potencial. ¡Ingeniería a escala insecto! 🔬" },`,
    `            { titulo: "✅ Quiz: Polinización con Drones", tipo: 'mini_quiz', pregunta: "¿Cómo puede un dron ayudar a polinizar un cultivo?", opciones: ["Aplastando las flores", "Dispersando polen usando corrientes de aire o cepillos especiales", "No puede", "Solo fotografiando las flores"], respuestaCorrecta: 1, explicacion: "Los drones dispersan nubes de polen seco sobre los cultivos. En Japón, drones con pelo de caballo pegajoso transfieren polen entre flores. 🌸" },`,
    `            { titulo: "✅ Quiz: Monitoreo de Colmenas", tipo: 'mini_quiz', pregunta: "¿Cómo puede la tecnología IoT ayudar a las abejas?", opciones: ["Reemplazándolas", "Monitoreando peso, temperatura y sonido de colmenas para detectar problemas temprano", "Eliminando colmenas", "No puede ayudar"], respuestaCorrecta: 1, explicacion: "Sensores en colmenas miden peso (miel), temp (salud), sonido (ánimo de la colonia). El apicultor recibe alertas en su celular. ¡Apicultura 4.0! 📱" },`,
    `            { titulo: "✅ Quiz: Flores Robot", tipo: 'mini_quiz', pregunta: "¿Qué son las flores artificiales con sensores?", opciones: ["Decoración", "Dispositivos que imitan flores para atraer y estudiar polinizadores", "Flores de plástico", "Robots que huelen"], respuestaCorrecta: 1, explicacion: "Las flores robot liberan néctar artificial y aromas para atraer polinizadores. Los sensores estudian su comportamiento. ¡Ciencia disfrazada! 🌺" },`,
    `            { titulo: "✅ Quiz: Jardines para Polinizadores", tipo: 'mini_quiz', pregunta: "¿Cómo puede la robótica ayudar a crear corredores de polinización?", opciones: ["Construyendo muros", "Drones siembran semillas de flores nativas en áreas degradadas para alimentar polinizadores", "Eliminando flores", "No puede"], respuestaCorrecta: 1, explicacion: "Los drones de reforestación lanzan seed balls (bolas de semillas) de flores nativas. Crean corredores que conectan poblaciones de polinizadores. 🌻" },`,
    `            { titulo: "✅ Quiz: Polen Artificial", tipo: 'mini_quiz', pregunta: "¿Es posible crear polen artificial para robots polinizadores?", opciones: ["No, es imposible", "Sí: investigadores japoneses crearon gel pegajoso que transfiere polen entre flores", "Solo en ciencia ficción", "Solo funcionaría en Marte"], respuestaCorrecta: 1, explicacion: "Dr. Eijiro Miyako creó un gel iónico que adhiere y libera polen. Drones con este gel polinizan lirios japoneses. ¡Gel con superpoderes! 🧪" },`,
    `            { titulo: "✅ Quiz: Servicios Ecosistémicos", tipo: 'mini_quiz', pregunta: "¿Cuánto valor económico tiene la polinización animal anualmente?", opciones: ["$1,000", "Más de $200 mil millones de dólares al año mundialmente", "$1 millón", "No tiene valor económico"], respuestaCorrecta: 1, explicacion: "La polinización vale >$200 mil millones/año. Sin polinizadores, los precios de frutas y verduras se dispararían. ¡Son el mejor ROI de la naturaleza! 💰" },`,
  ],
  'w6_mod9_invernadero_smart': [
    `            { titulo: "✅ Quiz: Ventajas del Invernadero", tipo: 'mini_quiz', pregunta: "¿Cuál es la principal ventaja de un invernadero inteligente?", opciones: ["Es más bonito", "Control total de temperatura, humedad, luz y CO2 para maximizar producción", "Es más barato que aire libre", "Solo protege de la lluvia"], respuestaCorrecta: 1, explicacion: "En un invernadero smart, cada variable se controla con sensores y actuadores. Producción 5-10x mayor que a campo abierto. ¡Fábrica de plantas! 🏭" },`,
    `            { titulo: "✅ Quiz: Ventilación Automática", tipo: 'mini_quiz', pregunta: "¿Cómo funciona la ventilación automática de un invernadero?", opciones: ["Siempre abierta", "Sensores de temp/humedad activan extractores y compuertas según umbrales programados", "Solo manual", "Con aire acondicionado"], respuestaCorrecta: 1, explicacion: "Si temp>28°C → abrir compuertas + encender extractores. Si temp<18°C → cerrar. Si humedad>80% → ventilar para evitar hongos. ¡Automatización! 🌡️" },`,
    `            { titulo: "✅ Quiz: Iluminación Suplementaria", tipo: 'mini_quiz', pregunta: "¿Qué tipo de luz usan los invernaderos modernos para complementar la luz solar?", opciones: ["Incandescentes", "LED rojo y azul que coinciden con los picos de absorción de la fotosíntesis", "Luz ultravioleta", "Velas"], respuestaCorrecta: 1, explicacion: "Las plantas absorben principalmente luz roja (660nm) y azul (450nm). LEDs de estos colores son ultra-eficientes para fotosíntesis. ¡Luz a medida! 💡" },`,
    `            { titulo: "✅ Quiz: Hidroponía", tipo: 'mini_quiz', pregunta: "¿Qué es la hidroponía y cuál es su ventaja?", opciones: ["Cultivo en arena", "Cultivo sin suelo, con raíces en solución nutritiva: 90% menos agua", "Solo riego por goteo", "Cultivo en maceta"], respuestaCorrecta: 1, explicacion: "En hidroponía, las raíces crecen en agua con nutrientes disueltos. No hay suelo. Usa 90% menos agua y crece 2x más rápido. ¡Revolución agrícola! 💧" },`,
    `            { titulo: "✅ Quiz: Sistema de Alertas", tipo: 'mini_quiz', pregunta: "¿Qué debe hacer un invernadero smart si la temperatura sube peligrosamente?", opciones: ["Nada", "Enviar alerta al celular, activar ventilación de emergencia y registrar el evento", "Apagar todo", "Solo registrar datos"], respuestaCorrecta: 1, explicacion: "Alarma por SMS/app + ventilación automática + registro del evento. Sin alerta, una ola de calor puede destruir toda la cosecha en horas. 🚨" },`,
    `            { titulo: "✅ Quiz: Controlador de Clima", tipo: 'mini_quiz', pregunta: "¿Qué hace un controlador de clima de invernadero?", opciones: ["Solo muestra la hora", "Integra datos de todos los sensores y coordina actuadores para mantener condiciones ideales", "Solo mide temperatura", "Solo controla riego"], respuestaCorrecta: 1, explicacion: "Un controlador de clima lee temp, humedad, CO2, luz y viento. Coordina calefacción, ventilación, riego, iluminación y CO2 como un director de orquesta. 🎼" },`,
    `            { titulo: "✅ Quiz: Pantalla de Control", tipo: 'mini_quiz', pregunta: "¿Por qué es útil un dashboard (panel de control) para un invernadero?", opciones: ["Solo se ve bonito", "Visualiza datos en tiempo real y tendencias históricas para tomar decisiones informadas", "Solo para impresionar visitas", "No es útil"], respuestaCorrecta: 1, explicacion: "Un dashboard muestra gráficas de temp, humedad, etc. en tiempo real. Permite ver tendencias y predecir problemas antes de que ocurran. 📊" },`,
    `            { titulo: "✅ Quiz: Invernadero Solar Pasivo", tipo: 'mini_quiz', pregunta: "¿Cómo ahorra energía un invernadero solar pasivo?", opciones: ["Usando mucho combustible", "Usando masa térmica (agua, piedras) que absorbe calor de día y lo libera de noche", "No ahorra energía", "Usando generadores eléctricos"], respuestaCorrecta: 1, explicacion: "Bidones de agua pintados de negro absorben calor solar del día. De noche, liberan ese calor lentamente. ¡Calefacción gratis! ☀️" },`,
    `            { titulo: "✅ Quiz: Recirculación de Nutrientes", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene un sistema hidropónico recirculante?", opciones: ["Gasta más agua", "Recoge y reutiliza la solución nutritiva, reduciendo desperdicio", "Es más difícil", "No tiene ventaja"], respuestaCorrecta: 1, explicacion: "Los sistemas recirculantes recogen el agua que drena, ajustan pH y nutrientes, y la reutilizan. ¡Cero desperdicio de agua y fertilizantes! ♻️" },`,
  ],
  'w6_mod10_agricultura_vertical': [
    `            { titulo: "✅ Quiz: Concepto Vertical", tipo: 'mini_quiz', pregunta: "¿Qué es la agricultura vertical?", opciones: ["Cultivar en montañas", "Cultivar en múltiples niveles apilados dentro de edificios controlados", "Cultivar muy alto", "Solo usar escaleras"], respuestaCorrecta: 1, explicacion: "La agricultura vertical apila capas de cultivo en edificios. Usa LEDs, hidroponía y control climático. ¡10x más producción por m² de terreno! 🏢" },`,
    `            { titulo: "✅ Quiz: LEDs en Granjas Verticales", tipo: 'mini_quiz', pregunta: "¿Por qué las granjas verticales usan LEDs en lugar de luz solar?", opciones: ["Porque es más barato", "Para controlar exactamente el espectro, duración e intensidad lumínica", "Porque no hay ventanas", "Por estética"], respuestaCorrecta: 1, explicacion: "Los LEDs dan control total: más rojo para frutas, más azul para hojas, 16h de 'sol' artificial. Cada cultivo recibe su receta de luz ideal. 💡" },`,
    `            { titulo: "✅ Quiz: Ahorro de Agua", tipo: 'mini_quiz', pregunta: "¿Cuánta agua ahorra la agricultura vertical comparada con la tradicional?", opciones: ["10%", "Hasta 95% por recirculación y ambiente cerrado", "50%", "No ahorra"], respuestaCorrecta: 1, explicacion: "En ambiente cerrado no hay evaporación al aire libre. El agua se recircula continuamente. 1L de lechuga vertical usa solo 1L vs 20L en campo. 💧" },`,
    `            { titulo: "✅ Quiz: Aeroponía", tipo: 'mini_quiz', pregunta: "¿Cómo funciona la aeroponía?", opciones: ["Las plantas flotan en agua", "Las raíces cuelgan en el aire y se rocían con niebla nutritiva", "Se plantan en arena", "Se usan macetas grandes"], respuestaCorrecta: 1, explicacion: "En aeroponía, las raíces cuelgan en cámaras oscuras y se rocían con niebla de nutrientes cada pocos minutos. 0 suelo, 0 sustrato. ¡Pura eficiencia! 🌫️" },`,
    `            { titulo: "✅ Quiz: Desafíos Energéticos", tipo: 'mini_quiz', pregunta: "¿Cuál es el mayor desafío de la agricultura vertical?", opciones: ["No produce suficiente", "El alto costo energético de la iluminación LED y climatización", "La falta de espacio", "La falta de agua"], respuestaCorrecta: 1, explicacion: "La energía eléctrica para LEDs y HVAC puede ser 50-60% del costo operativo. Por eso se buscan LEDs más eficientes y energía solar. ⚡" },`,
    `            { titulo: "✅ Quiz: Cultivos Ideales", tipo: 'mini_quiz', pregunta: "¿Qué cultivos son más rentables en agricultura vertical?", opciones: ["Trigo y maíz", "Lechugas, hierbas aromáticas, fresas y microgreens", "Árboles frutales", "Papas y zanahorias"], respuestaCorrecta: 1, explicacion: "Cultivos de ciclo corto, alto valor y poco espacio: lechugas (30 días), albahaca, fresas, microgreens. El trigo necesita demasiado espacio. 🥬" },`,
    `            { titulo: "✅ Quiz: Robots en Granjas Verticales", tipo: 'mini_quiz', pregunta: "¿Qué tareas automatizan los robots en granjas verticales?", opciones: ["Solo limpieza", "Siembra, transplante, monitoreo de crecimiento, cosecha y empaque", "Solo riego", "Ninguna"], respuestaCorrecta: 1, explicacion: "Los robots siembran semillas, trasplantan plántulas, inspeccionan con cámaras, cosechan lechugas y las empacan. ¡100% automatizado! 🤖" },`,
    `            { titulo: "✅ Quiz: Seguridad Alimentaria Urbana", tipo: 'mini_quiz', pregunta: "¿Cómo contribuye la agricultura vertical a la seguridad alimentaria urbana?", opciones: ["No contribuye", "Produce alimentos frescos dentro de la ciudad, reduciendo transporte y desperdicio", "Solo mejora la estética", "Aumenta los precios"], respuestaCorrecta: 1, explicacion: "Alimentos producidos en la ciudad llegan frescos sin camiones de miles de km. Menos CO2 por transporte, menos desperdicio, más frescura. 🏙️" },`,
    `            { titulo: "✅ Quiz: Recetas de Luz", tipo: 'mini_quiz', pregunta: "¿Qué es una 'receta de luz' en agricultura vertical?", opciones: ["Un libro de cocina", "La combinación específica de espectro, intensidad y fotoperiodo óptima para cada cultivo", "El precio de los LEDs", "El color del invernadero"], respuestaCorrecta: 1, explicacion: "Cada planta tiene su receta: albahaca = 16h de rojo:azul 3:1 a 300 μmol/m²s. ¡Ingeniería lumínica personalizada para cada especie! 🔬" },`,
  ],
  'w6_mod11_robots_cosecha': [
    `            { titulo: "✅ Quiz: Visión Artificial para Cosecha", tipo: 'mini_quiz', pregunta: "¿Cómo detecta un robot cosechador cuándo una fruta está madura?", opciones: ["Por el peso", "Analizando color, tamaño y forma con cámaras y algoritmos de IA", "Preguntando al agricultor", "No puede detectarlo"], respuestaCorrecta: 1, explicacion: "Cámaras RGB + algoritmos de deep learning identifican color (rojo maduro vs verde), tamaño y forma. ¡El robot 've' la madurez como tú! 📸" },`,
    `            { titulo: "✅ Quiz: Gripper para Frutas", tipo: 'mini_quiz', pregunta: "¿Por qué los robots de cosecha usan grippers blandos (soft grippers)?", opciones: ["Porque son más baratos", "Para no dañar frutas delicadas durante la recolección", "Porque son más rápidos", "Por estética"], respuestaCorrecta: 1, explicacion: "Un gripper rígido aplasta fresas y tomates. Los grippers blandos de silicona aplican presión uniforme y suave. ¡Cosecha sin moretones! 🍓" },`,
    `            { titulo: "✅ Quiz: Velocidad de Cosecha", tipo: 'mini_quiz', pregunta: "¿Cuál es el desafío de velocidad en robots cosechadores?", opciones: ["Son demasiado rápidos", "Un humano cosecha una fresa cada 3s; los robots actuales necesitan 6-8s", "No tiene desafío", "Son más rápidos que humanos"], respuestaCorrecta: 1, explicacion: "La velocidad es el gran reto. Pero los robots trabajan 24/7 sin cansarse. Con 8s/fresa × 24h = miles por día. ¡La constancia gana! ⏱️" },`,
    `            { titulo: "✅ Quiz: Navegación en Huertos", tipo: 'mini_quiz', pregunta: "¿Cómo navega un robot autónomo entre filas de cultivo?", opciones: ["Con control remoto", "Con LIDAR y cámaras que detectan filas, GPS-RTK y algoritmos SLAM", "Con cuerdas guía", "Aleatoriamente"], respuestaCorrecta: 1, explicacion: "SLAM (Localización y Mapeo Simultáneo) + GPS-RTK + LIDAR = el robot sabe exactamente dónde está y hacia dónde ir. ¡GPS centimétrico! 🗺️" },`,
    `            { titulo: "✅ Quiz: Cosecha Selectiva", tipo: 'mini_quiz', pregunta: "¿Qué significa cosecha selectiva robótica?", opciones: ["Cosechar todo junto", "Recoger solo los frutos maduros y dejar los verdes para más tarde", "Solo cosechar los más grandes", "Cosechar aleatoriamente"], respuestaCorrecta: 1, explicacion: "El robot identifica cada fruto: maduro → cosechar, verde → dejar. Vuelve en 2-3 días por los que maduran después. ¡Menos desperdicio! 🍅" },`,
    `            { titulo: "✅ Quiz: Categorización Automática", tipo: 'mini_quiz', pregunta: "¿Cómo clasifica un robot las frutas después de cosecharlas?", opciones: ["A mano", "Con visión artificial que mide tamaño, color, forma y detecta defectos", "Por peso solamente", "No las clasifica"], respuestaCorrecta: 1, explicacion: "Cámaras + IA clasifican en fracciones de segundo: tamaño (grande/mediana/chica), calidad (premium/estándar/defectuosa). ¡Control de calidad 24/7! 📊" },`,
    `            { titulo: "✅ Quiz: Robot de Deshierbe", tipo: 'mini_quiz', pregunta: "¿Cómo distingue un robot de deshierbe entre maleza y cultivo?", opciones: ["No puede", "Con deep learning entrenado con miles de imágenes de cada especie", "Por el color", "Solo por tamaño"], respuestaCorrecta: 1, explicacion: "Redes neuronales entrenadas con 100,000+ imágenes reconocen cada especie. El robot elimina la maleza con láser o micro-dosis de herbicida. 🎯" },`,
    `            { titulo: "✅ Quiz: Cosecha de Lechugas", tipo: 'mini_quiz', pregunta: "¿Cómo cosecha un robot lechugas en una granja vertical?", opciones: ["Las arranca de raíz", "Un brazo robótico corta la base y la coloca en empaque automáticamente", "Las aspira", "Con agua a presión"], respuestaCorrecta: 1, explicacion: "El brazo con cuchilla limpia corta la base de la lechuga, la levanta con ventosa suave y la coloca en su empaque. ¡De la planta a la bolsa en 5s! 🥬" },`,
    `            { titulo: "✅ Quiz: Robots para Poda", tipo: 'mini_quiz', pregunta: "¿Por qué es difícil automatizar la poda de árboles frutales?", opciones: ["Es fácil", "Cada árbol tiene forma única y el robot debe decidir qué ramas cortar", "No se necesita podar", "Solo se requiere fuerza"], respuestaCorrecta: 1, explicacion: "La poda necesita juicio: ¿qué rama quitar? ¿cuánto cortar? La IA con visión 3D está aprendiendo a tomar estas decisiones. ¡Experiencia artificial! 🌳" },`,
  ],
  'w6_mod12_iot_agricultura': [
    `            { titulo: "✅ Quiz: IoT Agrícola", tipo: 'mini_quiz', pregunta: "¿Qué significa IoT en el contexto de la agricultura?", opciones: ["Internet of Trees", "Red de sensores y dispositivos conectados que monitorean cultivos en tiempo real", "Un tipo de fertilizante", "Internet of Things sin aplicación agrícola"], respuestaCorrecta: 1, explicacion: "IoT agro = sensores de suelo, clima, cámaras y actuadores conectados por WiFi/LoRa que envían datos a la nube para análisis. ¡El campo conectado! 📡" },`,
    `            { titulo: "✅ Quiz: LoRa", tipo: 'mini_quiz', pregunta: "¿Qué es LoRa y por qué se usa en agricultura?", opciones: ["Un tipo de planta", "Tecnología de radio de largo alcance (10km+) y bajo consumo para sensores remotos", "Una red social", "Un tipo de dron"], respuestaCorrecta: 1, explicacion: "LoRa transmite datos a 10-15 km con baterías que duran años. Perfecto para campos remotos sin WiFi ni cobertura celular. ¡Conectividad rural! 📻" },`,
    `            { titulo: "✅ Quiz: Cloud Computing", tipo: 'mini_quiz', pregunta: "¿Por qué se envían los datos agrícolas a la nube?", opciones: ["Por moda", "Para almacenar grandes volúmenes, procesar con IA y acceder desde cualquier lugar", "No se necesita la nube", "Solo para hacer backup"], respuestaCorrecta: 1, explicacion: "Miles de sensores generan millones de datos. La nube los almacena, la IA los analiza y el agricultor los ve en su celular desde cualquier parte. ☁️" },`,
    `            { titulo: "✅ Quiz: Edge Computing", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene el edge computing sobre enviar todo a la nube?", opciones: ["Es más caro", "Procesa datos localmente para respuesta rápida sin depender de Internet", "No tiene ventaja", "Solo funciona en oficina"], respuestaCorrecta: 1, explicacion: "En edge computing, un microcontrolador local decide: humedad baja → regar YA, sin esperar respuesta de la nube. ¡Latencia cero! ⚡" },`,
    `            { titulo: "✅ Quiz: API de Clima", tipo: 'mini_quiz', pregunta: "¿Cómo pueden las APIs de clima mejorar la agricultura?", opciones: ["Cambiando el clima", "Proporcionando pronósticos para planificar riego, cosecha y protección contra heladas", "No sirven para agricultura", "Solo muestran la hora"], respuestaCorrecta: 1, explicacion: "APIs como OpenWeather predicen lluvias (no regar), heladas (proteger) y calor extremo (regar más). ¡Planificación con datos del futuro! 🌤️" },`,
    `            { titulo: "✅ Quiz: MQTT", tipo: 'mini_quiz', pregunta: "¿Qué es MQTT y por qué se usa en IoT agrícola?", opciones: ["Un tipo de sensor", "Un protocolo de mensajería ligero ideal para dispositivos con poca energía y ancho de banda", "Un lenguaje de programación", "Una marca de drones"], respuestaCorrecta: 1, explicacion: "MQTT usa mínimo ancho de banda para enviar datos sensor→broker→nube. Perfecto para ESP32 con batería solar en medio del campo. 📨" },`,
    `            { titulo: "✅ Quiz: Digital Twin", tipo: 'mini_quiz', pregunta: "¿Qué es un gemelo digital en agricultura?", opciones: ["Una copia del agricultor", "Una réplica virtual del campo que simula y predice el comportamiento de los cultivos", "Un clon de plantas", "Un robot idéntico"], respuestaCorrecta: 1, explicacion: "El gemelo digital del campo recibe datos reales de sensores y simula: ¿qué pasa si riego más? ¿si fertilizo? Predicciones SIN experimentar en real. 🖥️" },`,
    `            { titulo: "✅ Quiz: Hardware RSB", tipo: 'mini_quiz', pregunta: "¿Qué microcontrolador es ideal para un nodo IoT agrícola solar?", opciones: ["Arduino UNO", "ESP32: WiFi/BLE integrado, bajo consumo, modo deep sleep y económico", "Raspberry Pi 5", "Un PC de escritorio"], respuestaCorrecta: 1, explicacion: "ESP32 tiene WiFi, BLE, 18 ADC, modo deep sleep (10μA). Con panel solar + batería LiPo, funciona indefinidamente en el campo. ¡El rey del IoT agrícola! 📟" },`,
    `            { titulo: "✅ Quiz: Trazabilidad", tipo: 'mini_quiz', pregunta: "¿Cómo contribuye IoT a la trazabilidad alimentaria?", opciones: ["No contribuye", "Registra cada etapa desde la siembra hasta la mesa: origen, tratamientos y condiciones", "Solo mejora el sabor", "Solo ahorra dinero"], respuestaCorrecta: 1, explicacion: "Con IoT + blockchain, cada tomate tiene historial: dónde creció, qué riego/fertilizante recibió, cuándo se cosechó. ¡Del campo a la mesa con certificado! 📋" },`,
  ],
  'w6_mod13_energia_renovable_robots': [
    `            { titulo: "✅ Quiz: Panel Solar para Robots", tipo: 'mini_quiz', pregunta: "¿Qué tipo de panel solar es mejor para un robot agrícola móvil?", opciones: ["Panel de 100kg", "Panel flexible CIGS o monocristalino ligero de alta eficiencia", "Panel de vidrio pesado", "No necesita panel"], respuestaCorrecta: 1, explicacion: "Los paneles flexibles CIGS se pegan al techo del robot. Ligeros (200g), eficientes (15-18%) y resistentes a vibraciones. ¡Energía portátil! ☀️" },`,
    `            { titulo: "✅ Quiz: MPPT", tipo: 'mini_quiz', pregunta: "¿Qué hace un controlador MPPT para paneles solares?", opciones: ["Los limpia", "Encuentra el punto de máxima potencia para extraer la máxima energía del panel", "Los enciende y apaga", "Solo mide voltaje"], respuestaCorrecta: 1, explicacion: "MPPT (Maximum Power Point Tracking) ajusta el voltaje/corriente para extraer siempre el máximo de watts del panel. Hasta 30% más eficiente que un regulador PWM. ⚡" },`,
    `            { titulo: "✅ Quiz: Micro-eólica", tipo: 'mini_quiz', pregunta: "¿Cómo puede la energía eólica alimentar sensores agrícolas remotos?", opciones: ["Con grandes molinos", "Con micro-turbinas eólicas que generan 10-50W para cargar baterías de nodos IoT", "No es posible", "Solo con turbinas industriales"], respuestaCorrecta: 1, explicacion: "Micro-turbinas de 30-50cm generan suficiente energía para mantener un nodo IoT (ESP32 + sensores) funcionando indefinidamente. ¡Viento productivo! 💨" },`,
    `            { titulo: "✅ Quiz: Almacenamiento de Energía", tipo: 'mini_quiz', pregunta: "¿Por qué es importante el almacenamiento de energía en robots solares?", opciones: ["No es importante", "Para que el robot funcione de noche y en días nublados cuando no hay sol", "Solo por emergencias", "Para que sea más pesado"], respuestaCorrecta: 1, explicacion: "Baterías LiPo almacenan la energía solar del día para operación nocturna. Un robot con panel de 100W + batería de 20Ah trabaja 24/7. 🔋" },`,
    `            { titulo: "✅ Quiz: Eficiencia Energética", tipo: 'mini_quiz', pregunta: "¿Cómo se optimiza el consumo energético de un robot agrícola?", opciones: ["Usando más motores", "Con modos sleep, motores eficientes, rutas optimizadas y procesamiento edge", "Aumentando la velocidad", "No se puede optimizar"], respuestaCorrecta: 1, explicacion: "Deep sleep cuando no opera, motores brushless eficientes, rutas A* para mínima distancia, y procesamiento local en vez de WiFi constante. ⚡" },`,
    `            { titulo: "✅ Quiz: Balance Energético", tipo: 'mini_quiz', pregunta: "¿Qué es el balance energético de un robot solar?", opciones: ["Su peso", "La relación entre energía generada por el panel y energía consumida por el robot", "Su velocidad", "Su temperatura"], respuestaCorrecta: 1, explicacion: "Si el panel genera más energía que la que consume el robot cada día, tiene balance positivo = autonomía infinita. ¡Auto-suficiencia energética! ♻️" },`,
    `            { titulo: "✅ Quiz: Celdas de Combustible", tipo: 'mini_quiz', pregunta: "¿Qué son las celdas de combustible de hidrógeno para robots?", opciones: ["Celdas solares", "Generadores que producen electricidad combinando hidrógeno y oxígeno", "Baterías normales", "Motores de gasolina"], respuestaCorrecta: 1, explicacion: "Las fuel cells H2 producen electricidad + agua como único subproducto. Mayor densidad energética que LiPo. ¡Energía limpia del futuro! 🧪" },`,
    `            { titulo: "✅ Quiz: Carga Inalámbrica", tipo: 'mini_quiz', pregunta: "¿Cómo funciona la carga inalámbrica para robots agrícolas?", opciones: ["Con cables largos", "Bobinas inductivas en una base de carga transfieren energía al robot sin contacto físico", "Con combustible", "No existe"], respuestaCorrecta: 1, explicacion: "El robot se estaciona sobre una plataforma con bobina. La inductancia magnética transfiere energía. ¡Como cargar un celular pero para un robot! ⚡" },`,
    `            { titulo: "✅ Quiz: Grid-Tie", tipo: 'mini_quiz', pregunta: "¿Qué es un sistema grid-tie en una granja solar?", opciones: ["Una cerca eléctrica", "Un sistema solar conectado a la red eléctrica que vende excedentes", "Un tipo de riego", "Un alambre para plantas"], respuestaCorrecta: 1, explicacion: "Los paneles solares de la granja producen electricidad. Lo que sobra se inyecta a la red y se 'vende'. ¡La granja genera ingresos por energía! 💰" },`,
  ],
  'w6_mod14_etica_robotica_verde': [
    `            { titulo: "✅ Quiz: Impacto Social", tipo: 'mini_quiz', pregunta: "¿Cuál es la preocupación social principal de la automatización agrícola?", opciones: ["Los robots se rebelan", "El desplazamiento de trabajadores agrícolas por máquinas", "No hay preocupación", "Los robots son feos"], respuestaCorrecta: 1, explicacion: "Millones de personas trabajan en agricultura. La automatización crea eficiencia pero puede eliminar empleos. Se necesita capacitación y transición justa. 👥" },`,
    `            { titulo: "✅ Quiz: Soberanía Alimentaria", tipo: 'mini_quiz', pregunta: "¿Cómo puede la tecnología amenazar la soberanía alimentaria?", opciones: ["No puede", "Si solo grandes empresas pueden pagar la tecnología, los pequeños agricultores quedan excluidos", "La mejora para todos", "Solo afecta a las ciudades"], respuestaCorrecta: 1, explicacion: "Si un dron cuesta $10,000, solo grandes empresas lo compran. Se necesita tecnología accesible y open source para todos. ¡Democracia tecnológica! ⚖️" },`,
    `            { titulo: "✅ Quiz: Huella de Carbono", tipo: 'mini_quiz', pregunta: "¿Cómo se reduce la huella de carbono de los robots agrícolas?", opciones: ["No se puede", "Usando energía solar, materiales reciclables y optimizando rutas para menor consumo", "Usando más combustible", "Fabricando más robots"], respuestaCorrecta: 1, explicacion: "Un robot solar con rutas optimizadas tiene huella de carbono casi cero vs tractores diésel. Materiales reciclables cierran el ciclo. 🌍" },`,
    `            { titulo: "✅ Quiz: Biodiversidad", tipo: 'mini_quiz', pregunta: "¿Cómo pueden los robots agrícolas proteger la biodiversidad?", opciones: ["No pueden", "Aplicando pesticidas solo donde se necesita y monitoreando especies con cámaras", "Eliminando toda la fauna", "Produciendo más comida"], respuestaCorrecta: 1, explicacion: "Fumigación de precisión reduce químicos 90%. Cámaras en drones monitorean aves, insectos y polinizadores. ¡Tecnología aliada de la naturaleza! 🦋" },`,
    `            { titulo: "✅ Quiz: Open Source Agro", tipo: 'mini_quiz', pregunta: "¿Qué es FarmBot y por qué es importante?", opciones: ["Una marca de pesticida", "Un robot agrícola open source que cualquier persona puede construir y modificar", "Un videojuego", "Un tipo de semilla"], respuestaCorrecta: 1, explicacion: "FarmBot es hardware y software 100% open source. Los planos están en Internet gratis. ¡Democratiza la agricultura de precisión! 🌱" },`,
    `            { titulo: "✅ Quiz: Privacidad de Datos Agrícolas", tipo: 'mini_quiz', pregunta: "¿Por qué es importante proteger los datos agrícolas de un agricultor?", opciones: ["No es importante", "Los datos de rendimiento y prácticas son valiosos comercialmente y pueden explotarse", "Solo son números", "Los datos no tienen valor"], respuestaCorrecta: 1, explicacion: "Los datos agrícolas revelan rendimientos, prácticas y finanzas. Empresas podrían usarlos para manipular precios o competir deslealmente. ¡Los datos son poder! 🔒" },`,
    `            { titulo: "✅ Quiz: Derecho a Reparar", tipo: 'mini_quiz', pregunta: "¿Qué es el 'derecho a reparar' en robótica agrícola?", opciones: ["Que los robots se reparen solos", "Que los agricultores puedan reparar y modificar sus robots sin restricciones del fabricante", "Un tipo de garantía", "No existe este derecho"], respuestaCorrecta: 1, explicacion: "Algunos fabricantes bloquean reparaciones para monopolizar el servicio técnico. El derecho a reparar permite que el agricultor arregle SU robot. 🔧" },`,
    `            { titulo: "✅ Quiz: Economía Circular", tipo: 'mini_quiz', pregunta: "¿Cómo aplica la economía circular a los robots agrícolas?", opciones: ["No aplica", "Diseñar robots con componentes reciclables, reparables y actualizables", "Comprar robots nuevos cada año", "Solo reciclar las baterías"], respuestaCorrecta: 1, explicacion: "Diseño modular: actualizar solo la cámara, reemplazar solo el motor, reciclar la estructura. ¡Menos basura electrónica, más vida útil! ♻️" },`,
    `            { titulo: "✅ Quiz: Agricultura Justa", tipo: 'mini_quiz', pregunta: "¿Cómo puede la robótica agrícola contribuir a la justicia social?", opciones: ["No puede", "Haciendo tecnología accesible para pequeños agricultores en países en desarrollo", "Solo beneficia a ricos", "Aumentando desigualdad"], respuestaCorrecta: 1, explicacion: "Proyectos como drones DIY de $500 y apps gratuitas de monitoreo llevan tecnología a agricultores de bajos recursos. ¡Inclusión tecnológica! 🤝" },`,
  ],
  'w6_mod15_competencias_aerobio': [
    `            { titulo: "✅ Quiz: FIRST Robotics", tipo: 'mini_quiz', pregunta: "¿Qué aprenden los jóvenes participando en competencias de robótica como FIRST?", opciones: ["Solo a ganar trofeos", "Trabajo en equipo, programación, diseño mecánico y resolución de problemas", "Solo a seguir instrucciones", "Nada útil"], respuestaCorrecta: 1, explicacion: "FIRST integra STEM con habilidades blandas: liderazgo, comunicación, gestión de proyectos. ¡Los 'deportes del cerebro'! 🏆" },`,
    `            { titulo: "✅ Quiz: Competencias de Drones", tipo: 'mini_quiz', pregunta: "¿Qué habilidades se evalúan en competencias de drones agrícolas?", opciones: ["Solo velocidad de vuelo", "Precisión de mapeo, eficiencia de fumigación, autonomía y presentación técnica", "Solo el precio del dron", "Solo la altura máxima"], respuestaCorrecta: 1, explicacion: "Se evalúa: calidad del mapa generado, precisión de aplicación, tiempo de vuelo, y la calidad de la documentación técnica del equipo. 📊" },`,
    `            { titulo: "✅ Quiz: Hackathon Agrícola", tipo: 'mini_quiz', pregunta: "¿Qué es un hackathon agrícola?", opciones: ["Un concurso de hackers", "Un evento donde equipos crean soluciones tecnológicas para problemas agrícolas en 24-48 horas", "Una feria de tractores", "Un concurso de cocina"], respuestaCorrecta: 1, explicacion: "En un hackathon agro, equipos desarrollan prototipos (apps, sensores, drones) que resuelven problemas reales de agricultores. ¡Innovación express! 💡" },`,
    `            { titulo: "✅ Quiz: Documentación de Proyecto", tipo: 'mini_quiz', pregunta: "¿Por qué la documentación es tan importante en competencias de robótica?", opciones: ["No es importante", "Los jueces evalúan el proceso de diseño, no solo el producto final", "Solo para hacer tarea", "Solo si ganas"], respuestaCorrecta: 1, explicacion: "La documentación muestra pensamiento crítico, iteración, análisis de errores y aprendizaje. En FIRST, vale tanto como el robot mismo. 📝" },`,
    `            { titulo: "✅ Quiz: Pitch Técnico", tipo: 'mini_quiz', pregunta: "¿Qué elementos debe tener un buen pitch (presentación) de proyecto de agro-robótica?", opciones: ["Solo fotos bonitas", "Problema identificado, solución propuesta, tecnología usada, prototipo y plan de negocios", "Solo el nombre del equipo", "Solo el presupuesto"], respuestaCorrecta: 1, explicacion: "Un pitch ganador: 1) Problema real, 2) Solución innovadora, 3) Cómo funciona (demo), 4) Impacto esperado, 5) Viabilidad económica. ¡3 minutos para convencer! 🎤" },`,
    `            { titulo: "✅ Quiz: Design Thinking", tipo: 'mini_quiz', pregunta: "¿Cuáles son las 5 fases del Design Thinking aplicado a agro-robótica?", opciones: ["Comprar, armar, pintar, vender, celebrar", "Empatizar, Definir, Idear, Prototipar, Testear", "Pensar, diseñar, construir, pintar, exhibir", "Solo construir y probar"], respuestaCorrecta: 1, explicacion: "Design Thinking: 1) Entender al agricultor, 2) Definir el problema, 3) Generar ideas, 4) Construir prototipo, 5) Probarlo con usuarios reales. 🎯" },`,
    `            { titulo: "✅ Quiz: Lean Startup Agro", tipo: 'mini_quiz', pregunta: "¿Cómo se aplica Lean Startup a un proyecto de robótica agrícola?", opciones: ["Construir un robot perfecto", "Construir un MVP rápido, medir resultados con agricultores, aprender e iterar", "Solo planificar sin construir", "Copiar otro proyecto"], respuestaCorrecta: 1, explicacion: "MVP (Mínimo Producto Viable) → medir si resuelve el problema → pivotear o perseverar. ¡No inviertas 1 año en algo que nadie necesita! 🔄" },`,
    `            { titulo: "✅ Quiz: Mentoría", tipo: 'mini_quiz', pregunta: "¿Qué rol tiene un mentor en un equipo de competencia de robótica?", opciones: ["Hace todo el trabajo", "Guía al equipo, comparte experiencia y ayuda a superar obstáculos sin dar respuestas directas", "Solo observa", "Solo evalúa"], respuestaCorrecta: 1, explicacion: "El mentor no construye el robot. Hace preguntas que guían: '¿consideraste...?' '¿qué pasaría si...?'. El aprendizaje está en el proceso. 🧭" },`,
    `            { titulo: "✅ Quiz: Networking", tipo: 'mini_quiz', pregunta: "¿Por qué es valioso el networking en competencias de robótica?", opciones: ["Solo para socializar", "Para conocer personas que pueden ser futuros socios, mentores o contactos profesionales", "No es valioso", "Solo para intercambiar piezas"], respuestaCorrecta: 1, explicacion: "En competencias conoces ingenieros, investigadores, emprendedores y futuros colegas. Muchas startups exitosas nacieron en competencias. 🤝" },`,
  ],
  'w6_mod16_proyecto_aerobiosfera_final': [
    `            { titulo: "✅ Quiz: Planificación del Proyecto", tipo: 'mini_quiz', pregunta: "¿Cuál es el primer paso para diseñar un sistema Aero-Biosfera completo?", opciones: ["Comprar un dron", "Identificar el problema agrícola específico a resolver y los requisitos del sistema", "Empezar a programar", "Construir los sensores"], respuestaCorrecta: 1, explicacion: "Todo empieza con una pregunta: ¿qué problema resuelvo? ¿riego? ¿plagas? ¿monitoreo? Los requisitos definen la solución. 📋" },`,
    `            { titulo: "✅ Quiz: Integración de Sistemas", tipo: 'mini_quiz', pregunta: "¿Cuál es el mayor desafío al integrar drones, sensores IoT y robótica en un solo sistema?", opciones: ["El costo", "La comunicación y compatibilidad entre todos los componentes y protocolos", "El peso", "El color"], respuestaCorrecta: 1, explicacion: "Drones usan MAVLink, sensores MQTT, robots ROS. La integración requiere puentes de comunicación, APIs comunes y estándares compartidos. 🔗" },`,
    `            { titulo: "✅ Quiz: MVP Agrícola", tipo: 'mini_quiz', pregunta: "¿Qué incluiría el MVP (Mínimo Producto Viable) de un sistema Aero-Biosfera?", opciones: ["Todo perfecto", "1 sensor de suelo + 1 dron con cámara + 1 actuador de riego + dashboard básico", "Solo un logo", "Solo una presentación"], respuestaCorrecta: 1, explicacion: "El MVP prueba la idea con lo mínimo: un sensor mide, un dron mapea, un actuador riega y un dashboard muestra datos. ¡Funcional antes que perfecto! 🎯" },`,
    `            { titulo: "✅ Quiz: Escalabilidad", tipo: 'mini_quiz', pregunta: "¿Qué significa que un sistema sea escalable?", opciones: ["Que sea grande", "Que pueda crecer de 1 hectárea a 100+ sin rediseñar todo el sistema", "Que sea pesado", "Que use muchos cables"], respuestaCorrecta: 1, explicacion: "Un sistema escalable: agregar más sensores = solo agregar nodos. Más área = más drones con la misma plataforma de datos. ¡Crecer sin reconstruir! 📈" },`,
    `            { titulo: "✅ Quiz: ROI Tecnológico", tipo: 'mini_quiz', pregunta: "¿Cómo se calcula el retorno de inversión (ROI) de un sistema agro-robótico?", opciones: ["No se puede calcular", "Comparando el costo del sistema vs ahorros en agua, pesticidas, mano de obra y aumento de producción", "Solo por el precio del dron", "Sumando todos los gastos"], respuestaCorrecta: 1, explicacion: "ROI = (Beneficios - Costos) / Costos × 100. Si un dron de $5000 ahorra $15000/año en pesticidas, ROI = 200%. ¡Inversión inteligente! 💰" },`,
    `            { titulo: "✅ Quiz: Pruebas de Campo", tipo: 'mini_quiz', pregunta: "¿Por qué las pruebas de campo son diferentes a las pruebas en laboratorio?", opciones: ["No son diferentes", "El campo tiene variables impredecibles: viento, lluvia, terreno irregular y fauna", "Solo cambia la luz", "Solo cambia el suelo"], respuestaCorrecta: 1, explicacion: "En el campo: viento mueve el dron, lluvia daña electrónica, barro atasca ruedas, insectos tapan sensores. ¡La realidad es más compleja que el laboratorio! 🌧️" },`,
    `            { titulo: "✅ Quiz: Mantenimiento Preventivo", tipo: 'mini_quiz', pregunta: "¿Qué incluye el mantenimiento preventivo de un dron agrícola?", opciones: ["Solo cargar la batería", "Inspeccionar hélices, calibrar sensores, limpiar cámara, verificar firmware y revisar baterías", "Solo limpiarlo", "No necesita mantenimiento"], respuestaCorrecta: 1, explicacion: "Antes de cada vuelo: revisar hélices (grietas), calibrar IMU, limpiar lente, verificar voltaje de batería y actualizar firmware. ¡Prevenir > reparar! 🔧" },`,
    `            { titulo: "✅ Quiz: Presentación Final", tipo: 'mini_quiz', pregunta: "¿Qué debe demostrar la presentación final de un proyecto Aero-Biosfera?", opciones: ["Solo que funciona", "El problema, la solución, la tecnología, los resultados medibles y el impacto ambiental/social", "Solo fotos bonitas", "Solo el código"], respuestaCorrecta: 1, explicacion: "Una presentación completa: ¿qué problema? ¿cómo lo resuelves? ¿funciona? ¿cuánto mejora? ¿qué impacto tiene? ¡Datos + demostración + visión! 🎤" },`,
    `            { titulo: "✅ Quiz: Futuro de la AgTech", tipo: 'mini_quiz', pregunta: "¿Cuál es la tendencia más prometedora en AgTech para los próximos 10 años?", opciones: ["Menos tecnología", "Granjas autónomas completamente operadas por robots e IA sin intervención humana directa", "Solo tractores más grandes", "Volver a los métodos ancestrales"], respuestaCorrecta: 1, explicacion: "Granjas autónomas con flotas de robots, drones y sensores coordinados por IA. El agricultor será un 'director de datos'. ¡La revolución apenas empieza! 🚀" },`,
  ],
};

// Insert questions before each module's contenidoTeorico closing bracket
// Process in reverse order of line number to avoid offset issues
const entries = Object.entries(moduleClosings).sort((a, b) => b[1] - a[1]);
let total = 0;
for (const [moduleId, lineIdx] of entries) {
  const qLines = questions[moduleId];
  if (!qLines) { console.log('No questions for:', moduleId); continue; }

  lines.splice(lineIdx, 0, ...qLines);
  total += qLines.length;
  console.log(`${moduleId}: +${qLines.length} questions`);
}

fs.writeFileSync('src/data/world6Data.js', lines.join('\n'));
console.log(`\nTotal: ${total} questions injected into World 6`);
