// Script to inject ONLY the missing World 3 questions (modules that failed in first run)
const fs = require('fs');

function serializeQuestion(q) {
  if (q.tipo === 'mini_quiz') {
    const opts = q.opciones.map(o => `"${o.replace(/"/g, '\\"')}"`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'mini_quiz', pregunta: "${q.pregunta.replace(/"/g, '\\"')}", opciones: [${opts}], respuestaCorrecta: ${q.respuestaCorrecta}, explicacion: "${q.explicacion.replace(/"/g, '\\"')}" }`;
  }
  if (q.tipo === 'true_false') {
    const stmts = q.statements.map(s => `{ text: '${s.text.replace(/'/g, "\\'")}', correct: ${s.correct}, explain: '${s.explain.replace(/'/g, "\\'")}' }`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'true_false', statements: [${stmts}] }`;
  }
  if (q.tipo === 'matching_game') {
    const pairs = q.pairs.map(p => `{ left: '${p.left.replace(/'/g, "\\'")}', right: '${p.right.replace(/'/g, "\\'")}' }`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'matching_game', instruccion: '${(q.instruccion||'Conecta los conceptos').replace(/'/g, "\\'")}', pairs: [${pairs}] }`;
  }
  return JSON.stringify(q);
}

function injectQuestions(filePath, extraQuestions) {
  let src = fs.readFileSync(filePath, 'utf-8');
  let offset = 0;
  let count = 0;
  for (const [moduleId, questions] of Object.entries(extraQuestions)) {
    if (!questions || questions.length === 0) continue;
    const idPattern = `id: '${moduleId}'`;
    const idIdx = src.indexOf(idPattern, offset);
    if (idIdx === -1) { console.log(`WARNING: ${moduleId} not found`); continue; }
    const ctSearch = src.indexOf('contenidoTeorico:', idIdx);
    if (ctSearch === -1 || ctSearch - idIdx > 3000) continue;
    const bracketStart = src.indexOf('[', ctSearch);
    if (bracketStart === -1) continue;
    let depth = 0, closingIdx = -1;
    for (let i = bracketStart; i < src.length; i++) {
      if (src[i] === '[') depth++;
      else if (src[i] === ']') { depth--; if (depth === 0) { closingIdx = i; break; } }
    }
    if (closingIdx === -1) continue;
    const insertions = questions.map(q => '\n            ' + serializeQuestion(q) + ',').join('');
    src = src.slice(0, closingIdx) + insertions + src.slice(closingIdx);
    offset = closingIdx + insertions.length;
    count += questions.length;
    console.log(`  ✅ ${moduleId}: +${questions.length}`);
  }
  fs.writeFileSync(filePath, src, 'utf-8');
  console.log(`  💾 Saved (${count} questions added)\n`);
}

const W3_FIX = {
  'w3_mod3_musculos_artificiales': [
    { titulo: "✅ Quiz: Músculos Artificiales", tipo: 'mini_quiz', pregunta: "¿Qué son los músculos artificiales en robótica?", opciones: ["Músculos humanos trasplantados", "Actuadores que imitan la contracción y expansión de músculos biológicos", "Motores comunes", "Solo existen en ciencia ficción"], respuestaCorrecta: 1, explicacion: "Son actuadores que se contraen como músculos reales. Más suaves y flexibles que los motores. 💪" },
    { titulo: "✅ Quiz: SMA", tipo: 'mini_quiz', pregunta: "¿Cómo funcionan los cables SMA (Shape Memory Alloy)?", opciones: ["Con imanes", "Se contraen al calentarse y vuelven a su forma original al enfriarse", "Con aire comprimido", "Con luz"], respuestaCorrecta: 1, explicacion: "Las aleaciones con memoria de forma (como Nitinol) recuerdan su forma. Al calentarlas con corriente, se contraen como un músculo. 🔥" },
    { titulo: "✅ Quiz: Neumático", tipo: 'mini_quiz', pregunta: "¿Qué tipo de músculo artificial usa aire comprimido para moverse?", opciones: ["SMA", "Músculo neumático (McKibben)", "Motor servo", "Electroimán"], respuestaCorrecta: 1, explicacion: "Los músculos neumáticos McKibben se inflan con aire y se acortan, imitando la contracción muscular. ¡Fuertes y ligeros! 💨" },
    { titulo: "✅ Quiz: DEA", tipo: 'mini_quiz', pregunta: "¿Qué son los actuadores de elastómero dieléctrico (DEA)?", opciones: ["Resortes", "Membranas que se deforman al aplicar voltaje eléctrico", "Cables magnéticos", "Motores pequeños"], respuestaCorrecta: 1, explicacion: "Los DEA son polímeros que cambian de forma con electricidad. ¡Músculos artificiales ultra-delgados y flexibles! ⚡" },
    { titulo: "✅ Quiz: Ventaja", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tienen los músculos artificiales sobre los motores tradicionales?", opciones: ["Son más baratos", "Son más flexibles, silenciosos y livianos, ideales para interacción con humanos", "Son más rápidos", "Usan menos energía"], respuestaCorrecta: 1, explicacion: "Los músculos artificiales hacen que los robots sean más suaves y seguros para interactuar con personas. 🤝" },
    { titulo: "✅❌ Músculos: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los músculos neumáticos pueden generar fuerzas comparables a un músculo humano de tamaño similar.', correct: true, explain: 'Los McKibben pueden generar fuerzas impresionantes para su tamaño y peso.' }, { text: 'Los músculos artificiales actuales ya son mejores que los biológicos en todo.', correct: false, explain: 'Los biológicos aún superan en eficiencia energética, autorecuperación y control preciso.' }] },
    { titulo: "🧩 Tipos de Músculos Artificiales", tipo: 'matching_game', instruccion: 'Conecta cada tecnología con su principio', pairs: [{ left: 'SMA (Nitinol)', right: 'Memoria de forma con calor' }, { left: 'Neumático (McKibben)', right: 'Aire comprimido' }, { left: 'DEA', right: 'Voltaje en elastómero' }, { left: 'Hidráulico', right: 'Fluido presurizado' }] },
  ],
  'w3_mod4_sentidos_bio': [
    { titulo: "✅ Quiz: Biosensor", tipo: 'mini_quiz', pregunta: "¿Qué hace un biosensor en un robot?", opciones: ["Detecta robots", "Mide señales biológicas como pulso, temperatura corporal o sudoración", "Solo mide la batería", "Detecta metales"], respuestaCorrecta: 1, explicacion: "Los biosensores detectan señales del cuerpo humano. ¡Un robot puede saber si estás cansado o estresado! 💓" },
    { titulo: "✅ Quiz: Sensor de Pulso", tipo: 'mini_quiz', pregunta: "¿Cómo funciona un sensor de pulso cardíaco óptico?", opciones: ["Escucha el corazón", "Emite luz y mide cuánta se refleja; la sangre cambia la reflexión con cada latido", "Mide la presión", "Detecta electricidad"], respuestaCorrecta: 1, explicacion: "Un LED emite luz al dedo. La hemoglobina absorbe más luz con cada latido. ¡Fotopletismografía! 💓💡" },
    { titulo: "✅ Quiz: EMG", tipo: 'mini_quiz', pregunta: "¿Qué tipo de señal detecta un sensor EMG?", opciones: ["Ondas de sonido", "Señales eléctricas de los músculos", "Luz infrarroja", "Señales WiFi"], respuestaCorrecta: 1, explicacion: "EMG = Electromiografía. Detecta las señales eléctricas de los músculos al contraerse. ¡Control muscular de robots! 💪⚡" },
    { titulo: "✅ Quiz: GSR", tipo: 'mini_quiz', pregunta: "Un sensor GSR (Respuesta Galvánica de la Piel) detecta:", opciones: ["Color de piel", "Nivel de sudoración (indica estrés o emociones)", "Temperatura del aire", "Movimiento"], respuestaCorrecta: 1, explicacion: "La piel cambia su conductividad con el sudor. Más estrés = más sudor = menos resistencia eléctrica. 😰" },
    { titulo: "✅ Quiz: Aplicación", tipo: 'mini_quiz', pregunta: "¿Cómo podría un robot usar datos de biosensores?", opciones: ["Para nada", "Adaptar su comportamiento al estado emocional o físico del usuario", "Solo para mostrar datos", "Para ir más rápido"], respuestaCorrecta: 1, explicacion: "Un robot podría ir más lento si detecta que el usuario está cansado, o alertar si el pulso es anormal. ¡Robótica empática! 🤖❤️" },
    { titulo: "✅❌ Biosensores: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un smartwatch usa biosensores para medir el pulso cardíaco.', correct: true, explain: 'Los smartwatches usan sensores ópticos de pulso (PPG) en la muñeca.' }, { text: 'Los biosensores pueden leer los pensamientos de las personas.', correct: false, explain: 'Los biosensores miden señales físicas (pulso, sudor, temperatura). No leen pensamientos.' }] },
    { titulo: "🧩 Biosensores y Señales", tipo: 'matching_game', instruccion: 'Conecta cada biosensor con lo que mide', pairs: [{ left: 'Sensor PPG', right: 'Pulso cardíaco' }, { left: 'Sensor EMG', right: 'Actividad muscular' }, { left: 'Sensor GSR', right: 'Nivel de estrés/sudor' }, { left: 'Termistor corporal', right: 'Temperatura del cuerpo' }] },
  ],
  'w3_mod5_protesis_intro': [
    { titulo: "✅ Quiz: Prótesis Biónica", tipo: 'mini_quiz', pregunta: "¿Qué diferencia una prótesis biónica de una prótesis pasiva?", opciones: ["El color", "La biónica tiene sensores y actuadores que permiten movimiento activo", "El material", "El tamaño"], respuestaCorrecta: 1, explicacion: "Las prótesis biónicas detectan señales musculares (EMG) y mueven dedos/articulaciones con motores. 🦾" },
    { titulo: "✅ Quiz: Control EMG", tipo: 'mini_quiz', pregunta: "¿Cómo controla una persona su prótesis biónica de mano?", opciones: ["Con la mente directamente", "Contrayendo músculos del muñón que envían señales EMG a la prótesis", "Con un control remoto", "Con la voz"], respuestaCorrecta: 1, explicacion: "Electrodos en el muñón detectan cuándo el usuario contrae músculos. Cada contracción activa un movimiento. 💪🤖" },
    { titulo: "✅ Quiz: Retroalimentación", tipo: 'mini_quiz', pregunta: "¿Por qué es importante que una prótesis dé retroalimentación sensorial al usuario?", opciones: ["Solo por estética", "Para que el usuario sienta presión/temperatura y no aplaste objetos", "No es importante", "Para hacer ruido"], respuestaCorrecta: 1, explicacion: "Sin retroalimentación, el usuario puede aplastar un vaso. ¡Los sensores de presión devuelven el sentido del tacto! 🤚" },
    { titulo: "✅ Quiz: Impresión 3D", tipo: 'mini_quiz', pregunta: "¿Cómo revolucionó la impresión 3D las prótesis?", opciones: ["No cambió nada", "Redujo el costo de miles de dólares a cientos, haciéndolas accesibles", "Solo cambia el color", "Las hace más pesadas"], respuestaCorrecta: 1, explicacion: "¡De $50,000 a $50! Proyectos como e-NABLE crean prótesis 3D funcionales para niños. 🖨️" },
    { titulo: "✅ Quiz: Open Bionics", tipo: 'mini_quiz', pregunta: "¿Qué es el proyecto Open Bionics Hero Arm?", opciones: ["Un videojuego", "Una prótesis biónica accesible diseñada para ser atractiva para niños", "Un robot industrial", "Una app"], respuestaCorrecta: 1, explicacion: "Hero Arm es una prótesis multifuncional con diseños de superhéroes. ¡Los niños se sienten empoderados! 🦸" },
    { titulo: "✅❌ Prótesis: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Existen prótesis de pierna que permiten correr e incluso competir en deportes.', correct: true, explain: 'Las prótesis blade permiten sprint. ¡Atletas paralímpicos compiten al más alto nivel!' }, { text: 'Las prótesis biónicas actuales restauran el 100% de la funcionalidad natural.', correct: false, explain: 'Aunque avanzan mucho, aún no igualan la precisión y sensibilidad de un miembro natural.' }] },
    { titulo: "🧩 Tipos de Prótesis", tipo: 'matching_game', instruccion: 'Conecta cada tipo de prótesis con su característica', pairs: [{ left: 'Prótesis pasiva', right: 'Solo estética, sin movimiento' }, { left: 'Prótesis mecánica', right: 'Movimiento por cables/poleas' }, { left: 'Prótesis mioeléctrica', right: 'Control por señales EMG' }, { left: 'Prótesis 3D', right: 'Bajo costo y personalizable' }] },
  ],
  'w3_mod8_interfaz_cerebro': [
    { titulo: "✅ Quiz: BCI", tipo: 'mini_quiz', pregunta: "¿Qué es una BCI (Interfaz Cerebro-Computadora)?", opciones: ["Un chip en el cerebro", "Un sistema que traduce señales cerebrales en comandos para dispositivos", "Un tipo de pantalla", "Una red de computadoras"], respuestaCorrecta: 1, explicacion: "BCI lee las ondas cerebrales (EEG) y las convierte en acciones: mover un cursor, brazo robótico o silla de ruedas. 🧠💻" },
    { titulo: "✅ Quiz: EEG", tipo: 'mini_quiz', pregunta: "¿Qué es un EEG en el contexto de las BCI?", opciones: ["Un tipo de motor", "Un electroencefalograma que mide la actividad eléctrica del cerebro", "Una batería", "Un protocolo de internet"], respuestaCorrecta: 1, explicacion: "EEG usa electrodos en el cuero cabelludo para detectar ondas cerebrales. ¡No invasivo y accesible! 🧠📊" },
    { titulo: "✅ Quiz: Ondas Cerebrales", tipo: 'mini_quiz', pregunta: "¿Qué ondas cerebrales se asocian con la concentración?", opciones: ["Delta (sueño profundo)", "Beta (concentración activa)", "Theta (somnolencia)", "No tiene ondas"], respuestaCorrecta: 1, explicacion: "Beta (13-30 Hz) = concentración. Alpha = relajación. Delta = sueño profundo. ¡Cada estado tiene su onda! 🌊" },
    { titulo: "✅ Quiz: Neuralink", tipo: 'mini_quiz', pregunta: "¿Qué tipo de BCI es Neuralink de Elon Musk?", opciones: ["No invasivo", "Invasivo (implante cerebral con electrodos)", "Solo software", "Un videojuego"], respuestaCorrecta: 1, explicacion: "Neuralink implanta chips con miles de electrodos directamente en el cerebro para señales más precisas. 🧠🔌" },
    { titulo: "✅ Quiz: Aplicación BCI", tipo: 'mini_quiz', pregunta: "¿Cómo puede una BCI ayudar a una persona con parálisis total?", opciones: ["No puede", "Permitiéndole controlar computadora, silla o brazo robótico con el pensamiento", "Solo mide ondas", "Solo para investigación"], respuestaCorrecta: 1, explicacion: "¡Libertad a través del pensamiento! Personas con ELA pueden comunicarse y controlar dispositivos con BCIs. 🎯" },
    { titulo: "✅❌ BCI: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El EEG puede detectar si una persona está concentrada, relajada o dormida.', correct: true, explain: 'Diferentes estados mentales producen ondas cerebrales con frecuencias distintas.' }, { text: 'Las BCI actuales pueden leer pensamientos específicos como palabras.', correct: false, explain: 'Las BCI detectan patrones generales (concentración, imaginación motora), no pensamientos específicos.' }] },
    { titulo: "🧩 Tipos de BCI", tipo: 'matching_game', instruccion: 'Conecta cada tipo de BCI con su método', pairs: [{ left: 'EEG (no invasivo)', right: 'Electrodos en el cuero cabelludo' }, { left: 'ECoG (semi-invasivo)', right: 'Electrodos sobre la corteza' }, { left: 'Implante (invasivo)', right: 'Electrodos dentro del cerebro' }, { left: 'fNIRS', right: 'Luz infrarroja en la cabeza' }] },
  ],
  'w3_mod9_robots_blandos': [
    { titulo: "✅ Quiz: Soft Robot", tipo: 'mini_quiz', pregunta: "¿Qué es un soft robot (robot blando)?", opciones: ["Un robot de peluche", "Un robot hecho de materiales flexibles sin estructura rígida", "Un robot pequeño", "Un robot lento"], respuestaCorrecta: 1, explicacion: "Los soft robots usan silicona y elastómeros en vez de metal. ¡Se deforman y adaptan como un pulpo! 🐙" },
    { titulo: "✅ Quiz: Material Principal", tipo: 'mini_quiz', pregunta: "¿Cuál es el material más usado para fabricar soft robots?", opciones: ["Acero", "Silicona y elastómeros", "Madera", "Vidrio"], respuestaCorrecta: 1, explicacion: "La silicona es flexible, biocompatible y se puede moldear con canales internos para actuación neumática. 🧪" },
    { titulo: "✅ Quiz: Actuación Neumática", tipo: 'mini_quiz', pregunta: "¿Cómo se mueve un tentáculo de soft robot?", opciones: ["Con motores internos", "Inflando y desinflando cámaras de aire dentro del material", "Con imanes", "Con cables"], respuestaCorrecta: 1, explicacion: "Al inflar diferentes cámaras, el tentáculo se curva en distintas direcciones. ¡Como un pulpo! 🐙💨" },
    { titulo: "✅ Quiz: Seguridad", tipo: 'mini_quiz', pregunta: "¿Por qué los soft robots son más seguros para interactuar con humanos?", opciones: ["Son más lentos", "No tienen bordes duros ni partes rígidas que causen lesiones", "Son más caros", "Son más pequeños"], respuestaCorrecta: 1, explicacion: "Al ser blandos, pueden tocar personas sin hacer daño. ¡Ideales para medicina y rescate! 🤝" },
    { titulo: "✅ Quiz: Cirugía", tipo: 'mini_quiz', pregunta: "¿En qué campo son especialmente útiles los soft robots?", opciones: ["Construcción pesada", "Cirugía mínimamente invasiva y manipular objetos frágiles", "Minería", "Solo en laboratorios"], respuestaCorrecta: 1, explicacion: "En cirugía navegan por el cuerpo sin dañar tejidos. También agarran frutas sin aplastarlas. 🍓🏥" },
    { titulo: "✅❌ Soft Robots: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un soft robot puede cambiar de forma para pasar por espacios estrechos.', correct: true, explain: 'Al ser deformables, pueden comprimirse y adaptarse a espacios reducidos.' }, { text: 'Los soft robots son tan precisos como los brazos industriales rígidos.', correct: false, explain: 'La flexibilidad dificulta el control preciso. Los robots rígidos son más precisos.' }] },
    { titulo: "🧩 Soft vs Rigid Robots", tipo: 'matching_game', instruccion: 'Conecta cada característica con el tipo de robot', pairs: [{ left: 'Manipular objetos frágiles', right: 'Soft robot (flexible)' }, { left: 'Ensamblar piezas con precisión', right: 'Robot rígido' }, { left: 'Adaptarse a formas desconocidas', right: 'Soft robot (flexible)' }, { left: 'Alta velocidad y repetibilidad', right: 'Robot rígido' }] },
  ],
  'w3_mod12_enjambres': [
    { titulo: "✅ Quiz: Robótica de Enjambre", tipo: 'mini_quiz', pregunta: "¿Qué es la robótica de enjambre (swarm robotics)?", opciones: ["Un solo robot grande", "Muchos robots simples que cooperan para lograr tareas complejas", "Robots que atacan en grupo", "Robots de colección"], respuestaCorrecta: 1, explicacion: "¡Como hormigas o abejas! Cada robot es simple, pero juntos logran cosas complejas. 🐜🤖" },
    { titulo: "✅ Quiz: Reglas Locales", tipo: 'mini_quiz', pregunta: "¿Cómo coordinan su comportamiento los robots de enjambre?", opciones: ["Un líder central da órdenes", "Cada robot sigue reglas locales y el comportamiento colectivo emerge", "Por internet", "No se coordinan"], respuestaCorrecta: 1, explicacion: "Sin líder central. Cada robot solo sabe de sus vecinos. ¡El comportamiento inteligente emerge! 🧠" },
    { titulo: "✅ Quiz: Inspiración Natural", tipo: 'mini_quiz', pregunta: "¿Qué animal inspira más la robótica de enjambre?", opciones: ["El águila", "Las hormigas (colonias organizadas sin líder)", "El león", "El elefante"], respuestaCorrecta: 1, explicacion: "Las hormigas encuentran caminos óptimos, transportan cargas enormes y construyen. ¡Todo con reglas simples! 🐜" },
    { titulo: "✅ Quiz: Tolerancia a Fallos", tipo: 'mini_quiz', pregunta: "¿Qué pasa si un robot del enjambre se rompe?", opciones: ["Todo falla", "Los demás continúan la tarea, el sistema es tolerante a fallos", "Hay que reprogramar todo", "Los otros se detienen"], respuestaCorrecta: 1, explicacion: "¡Resiliencia! Como en una colonia de hormigas, si algunas mueren, la colonia sigue. No hay punto único de fallo. 💪" },
    { titulo: "✅ Quiz: Aplicaciones", tipo: 'mini_quiz', pregunta: "¿En qué situación sería ideal usar robots de enjambre?", opciones: ["Lavar platos", "Buscar supervivientes en un área grande de desastre", "Cocinar", "Pintar una pared"], respuestaCorrecta: 1, explicacion: "¡Búsqueda y rescate! 100 drones pueden cubrir un área enorme rápidamente. 🚁🔍" },
    { titulo: "✅❌ Enjambre: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los robots de enjambre son más baratos individualmente que un solo robot complejo.', correct: true, explain: 'Cada robot es simple y barato. La inteligencia viene de la cantidad y cooperación.' }, { text: 'Los robots de enjambre necesitan un computador central.', correct: false, explain: 'No hay control centralizado. Cada robot toma decisiones locales.' }] },
    { titulo: "🧩 Conceptos de Enjambre", tipo: 'matching_game', instruccion: 'Conecta cada concepto con su significado', pairs: [{ left: 'Emergencia', right: 'Comportamiento complejo de reglas simples' }, { left: 'Estigmergia', right: 'Comunicación indirecta por el ambiente' }, { left: 'Escalabilidad', right: 'Funciona con 10 o 10,000 robots' }, { left: 'Resiliencia', right: 'Tolerancia a fallos individuales' }] },
  ],
  'w3_mod13_micro_robots': [
    { titulo: "✅ Quiz: Micro Robot", tipo: 'mini_quiz', pregunta: "¿Qué tamaño tiene un micro robot?", opciones: ["1 metro", "Milímetros a centímetros", "10 metros", "100 metros"], respuestaCorrecta: 1, explicacion: "Los micro robots miden milímetros a pocos centímetros. Los nano robots serían de tamaño molecular. ¡Diminutos! 🔬" },
    { titulo: "✅ Quiz: Nanomedicina", tipo: 'mini_quiz', pregunta: "¿Cómo podrían los nano robots revolucionar la medicina?", opciones: ["Siendo doctores", "Navegando por el cuerpo para entregar medicamentos directamente a células enfermas", "Reemplazando hospitales", "Solo investigación"], respuestaCorrecta: 1, explicacion: "¡Nanomedicina! Robots microscópicos que atacan células cancerosas sin dañar las sanas. 💊🔬" },
    { titulo: "✅ Quiz: Propulsión", tipo: 'mini_quiz', pregunta: "¿Cómo se propulsan los micro robots dentro del cuerpo?", opciones: ["Con motores diesel", "Con campos magnéticos externos o reacciones químicas", "Con baterías", "Con WiFi"], respuestaCorrecta: 1, explicacion: "¡Sin baterías! Los campos magnéticos externos los guían y las reacciones químicas generan movimiento. 🧲" },
    { titulo: "✅ Quiz: MEMS", tipo: 'mini_quiz', pregunta: "¿Qué son los MEMS?", opciones: ["Un tipo de motor", "Sistemas micro-electromecánicos: sensores y actuadores microscópicos", "Una marca de robot", "Un software"], respuestaCorrecta: 1, explicacion: "MEMS = Micro Electro-Mechanical Systems. El acelerómetro de tu celular es un MEMS. 📱🔬" },
    { titulo: "✅ Quiz: Retos", tipo: 'mini_quiz', pregunta: "¿Cuál es un gran reto de los micro/nano robots?", opciones: ["Son muy caros", "Energía: no pueden llevar baterías y son difíciles de rastrear", "Son ruidosos", "Se oxidan"], respuestaCorrecta: 1, explicacion: "A escala nano no hay baterías. La energía viene del exterior y el rastreo es difícil. 🔋🔬" },
    { titulo: "✅❌ Micro/Nano: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Ya existen micro robots experimentales que nadan dentro de vasos sanguíneos.', correct: true, explain: 'Investigadores han creado micro robots que navegan por fluidos corporales con campos magnéticos.' }, { text: 'Los nano robots ya se usan rutinariamente en hospitales.', correct: false, explain: 'Aún están en fase de investigación. Los ensayos clínicos apenas comienzan.' }] },
    { titulo: "🧩 Escalas de Robot", tipo: 'matching_game', instruccion: 'Conecta cada escala con su aplicación típica', pairs: [{ left: 'Nano (nm)', right: 'Entregar medicamentos a células' }, { left: 'Micro (mm)', right: 'Cirugía mínimamente invasiva' }, { left: 'Mini (cm)', right: 'Inspección de tuberías' }, { left: 'Macro (m)', right: 'Robots industriales' }] },
  ],
  'w3_mod16_proyecto_bio_final': [
    { titulo: "✅ Quiz: Proyecto Biónico", tipo: 'mini_quiz', pregunta: "¿Qué define a un proyecto de robótica biónica?", opciones: ["Usar robots grandes", "Integrar principios biológicos en un robot que resuelve un problema real", "Solo hacer un robot bonito", "Copiar otro proyecto"], respuestaCorrecta: 1, explicacion: "Un proyecto biónico combina biología + robótica para resolver un problema real. 🦾🌿" },
    { titulo: "✅ Quiz: Planificación Biónica", tipo: 'mini_quiz', pregunta: "¿Qué debe incluir la fase de planificación?", opciones: ["Solo el presupuesto", "Investigación biológica, diseño del robot, lista de materiales y cronograma", "Solo el código", "Solo dibujos"], respuestaCorrecta: 1, explicacion: "Investiga el organismo, diseña el mecanismo, lista componentes y planifica las fases. ¡Ingeniería profesional! 📋" },
    { titulo: "✅ Quiz: Documentación", tipo: 'mini_quiz', pregunta: "¿Por qué documentar un proyecto biónico como un paper científico?", opciones: ["No es importante", "Para que otros puedan replicar, mejorar y contribuir al conocimiento", "Solo para la calificación", "Para vender más"], respuestaCorrecta: 1, explicacion: "La documentación permite replicabilidad, mejoras futuras y compartir con la comunidad. ¡Ciencia abierta! 📝" },
    { titulo: "✅ Quiz: Prototipo", tipo: 'mini_quiz', pregunta: "¿Qué es un prototipo rápido y por qué es útil?", opciones: ["Un robot final", "Una versión simple para probar ideas rápido antes de la versión final", "Un robot rápido", "Un robot de carreras"], respuestaCorrecta: 1, explicacion: "¡Falla rápido, aprende rápido! Un prototipo con cartón te muestra si tu idea funciona antes de invertir. 🔧" },
    { titulo: "✅ Quiz: Métricas", tipo: 'mini_quiz', pregunta: "¿Cómo mides si tu proyecto biónico fue exitoso?", opciones: ["Si se ve bonito", "Comparando métricas medibles del robot vs los objetivos definidos", "Si funciona a veces", "Si cuesta mucho"], respuestaCorrecta: 1, explicacion: "Define métricas: ¿puede la garra levantar X gramos? ¿se mueve en Y grados? ¡Mide y compara! 📊" },
    { titulo: "✅❌ Proyecto Biónico: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los mejores proyectos biónicos combinan investigación biológica con ingeniería.', correct: true, explain: 'La fusión de biología e ingeniería produce las soluciones más innovadoras.' }, { text: 'Un proyecto biónico exitoso siempre debe ser comercializable.', correct: false, explain: 'Un proyecto exitoso resuelve un problema o genera conocimiento, no necesariamente se vende.' }] },
    { titulo: "🧩 Fases del Proyecto", tipo: 'matching_game', instruccion: 'Ordena las fases del proyecto final biónico', pairs: [{ left: '1️⃣ Investigar', right: 'Estudiar el organismo y el problema' }, { left: '2️⃣ Diseñar', right: 'Crear planos y lista de materiales' }, { left: '3️⃣ Construir', right: 'Montar y programar el robot' }, { left: '4️⃣ Evaluar', right: 'Medir resultados y documentar' }] },
  ],
};

console.log('=== WORLD 3: Fix Missing Modules ===');
injectQuestions('src/data/world3Data.js', W3_FIX);
console.log('Done!');
