const fs = require('fs');

// Read file and split by lines
let lines = fs.readFileSync('src/data/world4Data.js', 'utf8').split('\n');

// Find the line numbers of each contenidoTeorico closing bracket
// Pattern: "        ]" (8 spaces + ]) possibly with \r
const closingLines = [];
for (let i = 0; i < lines.length; i++) {
  if (lines[i].trim() === ']' && lines[i].match(/^\s{8}\]/)) {
    closingLines.push(i);
  }
}
console.log('Found', closingLines.length, 'contenidoTeorico closing brackets at lines:', closingLines.map(l=>l+1).join(','));

// Map module IDs to their closing bracket line
const moduleClosings = {};
for (const cl of closingLines) {
  // Search backwards for the module id
  for (let j = cl; j >= Math.max(0, cl - 30); j--) {
    const match = lines[j].match(/id:\s*'(w4_[^']+)'/);
    if (match) {
      moduleClosings[match[1]] = cl;
      break;
    }
  }
}
console.log('Module mappings:', Object.entries(moduleClosings).map(([k,v])=>`${k}:L${v+1}`).join(', '));

const questions = {
  'w4_mod1_robots_espacio': [
    `            { titulo: "✅ Quiz: Robots Espaciales", tipo: 'mini_quiz', pregunta: "¿Cuál fue el primer rover en explorar exitosamente la superficie de Marte?", opciones: ["Curiosity", "Sojourner", "Perseverance", "Spirit"], respuestaCorrecta: 1, explicacion: "Sojourner fue el primer rover en operar exitosamente en Marte en 1997, como parte de la misión Mars Pathfinder. 🚀" },`,
    `            { titulo: "✅ Quiz: Desafíos Espaciales", tipo: 'mini_quiz', pregunta: "¿Por qué los robots espaciales deben ser extremadamente confiables?", opciones: ["Porque son muy caros", "Porque no se pueden reparar fácilmente en el espacio", "Porque necesitan ser bonitos", "Porque van muy rápido"], respuestaCorrecta: 1, explicacion: "En el espacio no hay técnicos que puedan reparar un robot si falla. Deben funcionar perfectamente por años. 🛰️" },`,
    `            { titulo: "✅ Quiz: Tipos de Robots Espaciales", tipo: 'mini_quiz', pregunta: "¿Qué tipo de robot es el Mars Helicopter Ingenuity?", opciones: ["Rover terrestre", "Satélite orbital", "Dron aéreo", "Brazo robótico"], respuestaCorrecta: 2, explicacion: "Ingenuity es un dron/helicóptero robótico que logró el primer vuelo controlado en otro planeta. 🚁" },`,
    `            { titulo: "✅ Quiz: Entorno Espacial", tipo: 'mini_quiz', pregunta: "¿Cuál es la temperatura más baja que puede enfrentar un rover en Marte?", opciones: ["-20°C", "-60°C", "-120°C", "-200°C"], respuestaCorrecta: 2, explicacion: "Las noches marcianas pueden bajar a -120°C. Los rovers necesitan calentadores internos para sobrevivir. 🥶" },`,
    `            { titulo: "✅ Quiz: Comunicación Espacial", tipo: 'mini_quiz', pregunta: "¿Cuánto tarda una señal de radio en viajar de Marte a la Tierra?", opciones: ["1 segundo", "1 minuto", "4-24 minutos", "1 hora"], respuestaCorrecta: 2, explicacion: "Dependiendo de la distancia orbital, una señal tarda entre 4 y 24 minutos. Por eso los rovers deben tomar decisiones solos. 📡" },`,
    `            { titulo: "✅ Quiz: Energía en Marte", tipo: 'mini_quiz', pregunta: "¿Qué fuente de energía usa el rover Perseverance?", opciones: ["Paneles solares", "Baterías de litio", "Generador nuclear (RTG)", "Energía eólica"], respuestaCorrecta: 2, explicacion: "Perseverance usa un Generador Termoeléctrico de Radioisótopos (RTG) que convierte calor nuclear en electricidad. ☢️" },`,
    `            { titulo: "✅ Quiz: Brazos Robóticos", tipo: 'mini_quiz', pregunta: "¿Para qué sirve el brazo robótico Canadarm2 en la ISS?", opciones: ["Para saludar astronautas", "Para mover módulos y capturar naves", "Para cocinar comida", "Para generar electricidad"], respuestaCorrecta: 1, explicacion: "El Canadarm2 es un brazo robótico de 17 metros que mueve módulos, atrapa naves de carga y ayuda en caminatas espaciales. 🦾" },`,
    `            { titulo: "✅ Quiz: Diseño de Rovers", tipo: 'mini_quiz', pregunta: "¿Por qué el rover Curiosity tiene 6 ruedas en vez de 4?", opciones: ["Para ir más rápido", "Para mejor tracción y estabilidad en terreno irregular", "Porque se ve mejor", "Para gastar menos energía"], respuestaCorrecta: 1, explicacion: "Las 6 ruedas con suspensión rocker-bogie permiten trepar rocas de 65cm y mantener estabilidad en terreno irregular. 🛞" },`,
    `            { titulo: "✅ Quiz: Historia Espacial", tipo: 'mini_quiz', pregunta: "¿Qué sonda robótica fue la primera en salir del sistema solar?", opciones: ["Hubble", "Voyager 1", "New Horizons", "Cassini"], respuestaCorrecta: 1, explicacion: "Voyager 1, lanzada en 1977, cruzó el límite del sistema solar en 2012. Lleva un disco de oro con sonidos de la Tierra. 🌌" },`,
  ],
  'w4_mod2_gravedad_cero': [
    `            { titulo: "✅ Quiz: Gravedad Cero", tipo: 'mini_quiz', pregunta: "¿Por qué un robot no puede usar ruedas normales en gravedad cero?", opciones: ["Porque pesan mucho", "Porque no hay superficie donde hacer tracción", "Porque se oxidan", "Porque giran muy rápido"], respuestaCorrecta: 1, explicacion: "En microgravedad no hay peso que presione las ruedas contra el suelo, así que no pueden generar tracción. 🌀" },`,
    `            { titulo: "✅ Quiz: Robots de la ISS", tipo: 'mini_quiz', pregunta: "¿Qué robot cúbico flota libremente dentro de la Estación Espacial Internacional?", opciones: ["R2-D2", "Astrobee", "Roomba", "Spot"], respuestaCorrecta: 1, explicacion: "Astrobee son robots cúbicos que flotan usando ventiladores y ayudan a los astronautas con inventarios dentro de la ISS. 🧊" },`,
    `            { titulo: "✅ Quiz: Movimiento", tipo: 'mini_quiz', pregunta: "¿Qué ley de Newton explica cómo se mueve un robot en el espacio expulsando gas?", opciones: ["Primera ley", "Segunda ley", "Tercera ley", "Ley de gravedad"], respuestaCorrecta: 2, explicacion: "La tercera ley: acción y reacción. Al expulsar gas hacia atrás, el robot se mueve hacia adelante. 🚀" },`,
    `            { titulo: "✅ Quiz: Peligros", tipo: 'mini_quiz', pregunta: "¿Por qué un tornillo suelto es peligroso en la Estación Espacial?", opciones: ["Porque pesa mucho", "Porque flota y puede dañar equipos o tapar ventilaciones", "Porque hace ruido", "Porque se derrite"], respuestaCorrecta: 1, explicacion: "En microgravedad, cualquier objeto suelto flota y puede meterse en ventilaciones o dañar instrumentos sensibles. 🔩" },`,
    `            { titulo: "✅ Quiz: Refrigeración", tipo: 'mini_quiz', pregunta: "¿Por qué la refrigeración de robots es difícil en el espacio?", opciones: ["Porque hace mucho frío", "Porque no hay aire para disipar calor por convección", "Porque no hay electricidad", "Porque los robots no se calientan"], respuestaCorrecta: 1, explicacion: "Sin aire, no hay convección. El calor solo se disipa por radiación. Los robots espaciales necesitan radiadores especiales. 🌡️" },`,
    `            { titulo: "✅ Quiz: Propulsión", tipo: 'mini_quiz', pregunta: "¿Qué sistema usan los satélites pequeños para moverse con precisión?", opciones: ["Motores de gasolina", "Propulsores de gas frío", "Velas de barco", "Turbinas"], respuestaCorrecta: 1, explicacion: "Los propulsores de gas frío liberan nitrógeno comprimido en pequeñas ráfagas para ajustar posición y orientación. ⛽" },`,
    `            { titulo: "✅ Quiz: Giroscopios", tipo: 'mini_quiz', pregunta: "¿Para qué usan giroscopios los satélites y robots espaciales?", opciones: ["Para generar energía", "Para mantener y cambiar su orientación sin combustible", "Para comunicarse con la Tierra", "Para medir temperatura"], respuestaCorrecta: 1, explicacion: "Los giroscopios de reacción giran para cambiar la orientación del satélite sin gastar combustible. 🔄" },`,
    `            { titulo: "✅ Quiz: Anclaje Espacial", tipo: 'mini_quiz', pregunta: "¿Cómo se sujetan los robots al exterior de la estación espacial?", opciones: ["Con pegamento", "Con pies magnéticos o ganchos en pasamanos", "Con cuerdas normales", "Con ventosas"], respuestaCorrecta: 1, explicacion: "La ISS tiene pasamanos especiales y los robots usan ganchos o efectores para sujetarse y moverse por el exterior. 🧲" },`,
    `            { titulo: "✅ Quiz: Inercia", tipo: 'mini_quiz', pregunta: "¿Qué pasa si un robot en el espacio enciende su propulsor una vez y lo apaga?", opciones: ["Se detiene inmediatamente", "Sigue moviéndose para siempre en esa dirección", "Gira en círculos", "Vuelve al punto de inicio"], respuestaCorrecta: 1, explicacion: "Sin fricción ni gravedad significativa, un objeto en movimiento sigue moviéndose indefinidamente. Primera ley de Newton. 🌌" },`,
  ],
  'w4_mod3_comunicacion': [
    `            { titulo: "✅ Quiz: Velocidad de la Luz", tipo: 'mini_quiz', pregunta: "¿A qué velocidad viajan las señales de radio en el espacio?", opciones: ["Velocidad del sonido", "Velocidad de la luz (300,000 km/s)", "1,000 km/s", "Instantáneamente"], respuestaCorrecta: 1, explicacion: "Las señales de radio viajan a la velocidad de la luz: 300,000 km por segundo. 💡" },`,
    `            { titulo: "✅ Quiz: Red DSN", tipo: 'mini_quiz', pregunta: "¿Cómo se llama la red de antenas gigantes que la NASA usa para comunicarse con sondas lejanas?", opciones: ["Red WiFi Global", "Deep Space Network (DSN)", "Starlink", "Red Telefónica"], respuestaCorrecta: 1, explicacion: "La Deep Space Network tiene antenas de hasta 70 metros en 3 ubicaciones del mundo. 📡" },`,
    `            { titulo: "✅ Quiz: Errores", tipo: 'mini_quiz', pregunta: "¿Por qué las comunicaciones espaciales usan corrección de errores?", opciones: ["Para ir más rápido", "Porque las señales se degradan en distancias enormes", "Para ahorrar batería", "Porque son secretas"], respuestaCorrecta: 1, explicacion: "Las señales se debilitan con la distancia y el ruido cósmico puede alterar bits. La corrección de errores repara datos corruptos. 🛡️" },`,
    `            { titulo: "✅ Quiz: Banda X", tipo: 'mini_quiz', pregunta: "¿Qué banda de frecuencia se usa para comunicaciones con sondas en espacio profundo?", opciones: ["Banda AM de radio", "Banda X y Banda Ka", "WiFi 5GHz", "Bluetooth"], respuestaCorrecta: 1, explicacion: "Las bandas X (8-12 GHz) y Ka (26-40 GHz) penetran la atmósfera y transmiten a grandes distancias. 📻" },`,
    `            { titulo: "✅ Quiz: Latencia", tipo: 'mini_quiz', pregunta: "Si la latencia a Marte es 20 minutos, ¿cuánto tarda un rover en responder a un comando?", opciones: ["20 minutos", "40 minutos (ida + vuelta)", "1 hora", "Instantáneamente"], respuestaCorrecta: 1, explicacion: "20 minutos de ida + 20 minutos de vuelta = 40 minutos para enviar un comando y recibir confirmación. ⏳" },`,
    `            { titulo: "✅ Quiz: Compresión", tipo: 'mini_quiz', pregunta: "¿Por qué Perseverance comprime las fotos antes de enviarlas a la Tierra?", opciones: ["Para que se vean mejor", "Porque el ancho de banda es limitado", "Para ocultar información", "Porque Marte es pequeño"], respuestaCorrecta: 1, explicacion: "El rover transmite a solo ~2 Mbps. Una foto sin comprimir tardaría mucho. Comprimida cabe en segundos. 📸" },`,
    `            { titulo: "✅ Quiz: Relay Orbital", tipo: 'mini_quiz', pregunta: "¿Cómo envían datos los rovers de Marte cuando no ven directamente la Tierra?", opciones: ["Esperan hasta verla", "Usan satélites orbitales de Marte como relay", "Usan un cable", "No pueden comunicarse"], respuestaCorrecta: 1, explicacion: "Los rovers envían datos al Mars Reconnaissance Orbiter que luego retransmite a la Tierra con antenas más potentes. 🛰️" },`,
    `            { titulo: "✅ Quiz: Pérdida de Señal", tipo: 'mini_quiz', pregunta: "¿Qué hace un rover si pierde comunicación con la Tierra?", opciones: ["Se apaga inmediatamente", "Sigue un protocolo de seguridad preprogramado y espera reconexión", "Explota", "Se mueve al azar"], respuestaCorrecta: 1, explicacion: "Los rovers tienen modos de seguridad: detienen movimiento, apuntan la antena a la Tierra y esperan instrucciones. 🛡️" },`,
    `            { titulo: "✅ Quiz: Datos Diarios", tipo: 'mini_quiz', pregunta: "¿Cuántos datos puede enviar el rover Perseverance por día a la Tierra?", opciones: ["1 GB", "Unos 250 MB", "10 GB", "100 KB"], respuestaCorrecta: 1, explicacion: "Perseverance envía ~250 MB/día a través de orbitadores. Menos que lo que usas en tu celular, pero suficiente para la ciencia. 📊" },`,
  ],
  'w4_mod4_energia_espacial': [
    `            { titulo: "✅ Quiz: RTG", tipo: 'mini_quiz', pregunta: "¿Qué es un RTG (Generador Termoeléctrico de Radioisótopos)?", opciones: ["Un panel solar grande", "Un dispositivo que convierte calor de material radiactivo en electricidad", "Una batería recargable", "Un generador eólico"], respuestaCorrecta: 1, explicacion: "Un RTG usa plutonio-238 que genera calor al desintegrarse. Termopares convierten ese calor en electricidad. ☢️" },`,
    `            { titulo: "✅ Quiz: Paneles en Marte", tipo: 'mini_quiz', pregunta: "¿Por qué los paneles solares generan MENOS energía en Marte que en la Tierra?", opciones: ["Porque Marte es más caliente", "Porque Marte está más lejos del Sol y recibe menos luz", "Porque los paneles se rompen", "Porque no hay oxígeno"], respuestaCorrecta: 1, explicacion: "Marte está 1.5 veces más lejos del Sol. Recibe solo el 43% de la luz solar que recibe la Tierra. ☀️" },`,
    `            { titulo: "✅ Quiz: Gestión Energética", tipo: 'mini_quiz', pregunta: "¿Qué hace un rover cuando su batería está baja?", opciones: ["Sigue normal", "Entra en modo hibernación: apaga sistemas no esenciales", "Se autodestruye", "Pide ayuda"], respuestaCorrecta: 1, explicacion: "En modo hibernación, el rover apaga cámaras e instrumentos. Solo mantiene calentadores y el reloj para sobrevivir. 💤" },`,
    `            { titulo: "✅ Quiz: Baterías", tipo: 'mini_quiz', pregunta: "¿Qué tipo de batería usan la mayoría de los satélites modernos?", opciones: ["Pilas alcalinas", "Baterías de litio-ion", "Baterías de plomo", "Pilas de botón"], respuestaCorrecta: 1, explicacion: "Las baterías de litio-ion son livianas y tienen alta densidad energética. La ISS tiene baterías Li-ion. 🔋" },`,
    `            { titulo: "✅ Quiz: Potencia ISS", tipo: 'mini_quiz', pregunta: "¿Cuánta potencia eléctrica generan los paneles solares de la ISS?", opciones: ["100 watts", "1,000 watts", "Hasta 120,000 watts (120 kW)", "1 millón de watts"], respuestaCorrecta: 2, explicacion: "Los paneles solares de la ISS cubren ~2,500 m² y generan hasta 120 kW. Suficiente para 40 casas. ☀️" },`,
    `            { titulo: "✅ Quiz: Eclipse Orbital", tipo: 'mini_quiz', pregunta: "¿Qué pasa con la energía de un satélite cuando pasa por la sombra de la Tierra?", opciones: ["Se apaga", "Usa baterías almacenadas hasta que vuelve al sol", "Usa combustible", "No le afecta"], respuestaCorrecta: 1, explicacion: "Los satélites en órbita baja pasan ~35 min en sombra por cada órbita de 90 min. Las baterías alimentan todos los sistemas. 🌑" },`,
    `            { titulo: "✅ Quiz: Eficiencia Solar", tipo: 'mini_quiz', pregunta: "¿Qué eficiencia tienen los paneles solares más avanzados usados en el espacio?", opciones: ["10%", "30-32%", "50%", "90%"], respuestaCorrecta: 1, explicacion: "Los paneles multi-junction de triple unión alcanzan ~30-32% de eficiencia, optimizados para el espacio. 🔬" },`,
    `            { titulo: "✅ Quiz: Polvo y Energía", tipo: 'mini_quiz', pregunta: "¿Cómo terminó la misión del rover Opportunity en Marte?", opciones: ["Se le acabó el combustible", "Una tormenta de polvo cubrió sus paneles solares", "Chocó contra una roca", "La NASA lo apagó"], respuestaCorrecta: 1, explicacion: "En 2018, una tormenta de polvo cubrió los paneles de Opportunity. Sin luz solar, sin electricidad, sin calentadores. 😢" },`,
    `            { titulo: "✅ Quiz: Duración RTG", tipo: 'mini_quiz', pregunta: "¿Cuántos años puede funcionar un RTG?", opciones: ["1 año", "5 años", "Más de 14 años", "100 años"], respuestaCorrecta: 2, explicacion: "Curiosity lleva más de 14 años con su RTG. Voyager 1 y 2 llevan 48+ años. Increíble durabilidad. ⚛️" },`,
  ],
  'w4_mod5_satelites': [
    `            { titulo: "✅ Quiz: Órbita GEO", tipo: 'mini_quiz', pregunta: "¿A qué altitud orbita un satélite geoestacionario?", opciones: ["200 km", "2,000 km", "35,786 km", "384,000 km"], respuestaCorrecta: 2, explicacion: "A 35,786 km, el satélite orbita a la misma velocidad que la Tierra rota. Parece fijo sobre un punto. 🛰️" },`,
    `            { titulo: "✅ Quiz: Órbita Polar", tipo: 'mini_quiz', pregunta: "¿Qué tipo de órbita usan los satélites de observación que fotografían cada rincón de la Tierra?", opciones: ["Geoestacionaria", "Polar", "Ecuatorial", "Lunar"], respuestaCorrecta: 1, explicacion: "La órbita polar pasa por ambos polos. Como la Tierra rota debajo, el satélite ve toda la superficie en pocos días. 🌍" },`,
    `            { titulo: "✅ Quiz: CubeSats", tipo: 'mini_quiz', pregunta: "¿Qué es un CubeSat?", opciones: ["Un satélite de 10cm×10cm×10cm que pesa ~1kg", "Un satélite del tamaño de una casa", "Una estación espacial cúbica", "Un tipo de telescopio"], respuestaCorrecta: 0, explicacion: "Los CubeSats son mini satélites estandarizados. Son económicos y las universidades pueden construirlos. 📦" },`,
    `            { titulo: "✅ Quiz: GPS", tipo: 'mini_quiz', pregunta: "¿Cuántos satélites GPS necesitas para calcular tu posición en la Tierra?", opciones: ["1 satélite", "2 satélites", "Al menos 4 satélites", "10 satélites"], respuestaCorrecta: 2, explicacion: "Se necesitan 4 satélites: 3 para trilaterar (X, Y, Z) y 1 para corregir el error del reloj. 📱" },`,
    `            { titulo: "✅ Quiz: Starlink", tipo: 'mini_quiz', pregunta: "¿Cuántos satélites tiene la constelación Starlink de SpaceX aproximadamente?", opciones: ["100", "1,000", "Más de 5,000", "50"], respuestaCorrecta: 2, explicacion: "Starlink tiene más de 5,000 satélites en órbita baja para dar internet global. Es la constelación más grande. 🌐" },`,
    `            { titulo: "✅ Quiz: Velocidad Orbital", tipo: 'mini_quiz', pregunta: "¿A qué velocidad viaja un satélite en órbita baja terrestre?", opciones: ["1,000 km/h", "8,000 km/h", "28,000 km/h", "300,000 km/h"], respuestaCorrecta: 2, explicacion: "A ~28,000 km/h (7.8 km/s). Da la vuelta a la Tierra en solo 90 minutos. 🏃" },`,
    `            { titulo: "✅ Quiz: Propulsión Iónica", tipo: 'mini_quiz', pregunta: "¿Qué propulsión usan muchos satélites modernos para ajustar su órbita eficientemente?", opciones: ["Motores de gasolina", "Propulsión iónica", "Hélices", "Velas de tela"], respuestaCorrecta: 1, explicacion: "Los propulsores iónicos aceleran iones con electricidad. Poco empuje pero pueden funcionar meses continuos. ⚡" },`,
    `            { titulo: "✅ Quiz: Vida Útil", tipo: 'mini_quiz', pregunta: "¿Cuál es la vida útil típica de un satélite de comunicaciones?", opciones: ["1 año", "5-7 años", "15-20 años", "100 años"], respuestaCorrecta: 2, explicacion: "Los satélites geoestacionarios duran 15-20 años. Luego se mueven a una órbita cementerio. 🪦" },`,
    `            { titulo: "✅ Quiz: Lanzamiento", tipo: 'mini_quiz', pregunta: "¿Por qué los cohetes se lanzan cerca del ecuador?", opciones: ["Porque hace calor", "Porque la rotación de la Tierra da velocidad extra al cohete", "Porque hay más espacio", "Porque está más cerca del espacio"], respuestaCorrecta: 1, explicacion: "En el ecuador la Tierra gira a 1,670 km/h. Esa velocidad se suma a la del cohete, ahorrando combustible. 🌍" },`,
  ],
  'w4_mod6_estacion_espacial': [
    `            { titulo: "✅ Quiz: Tripulación ISS", tipo: 'mini_quiz', pregunta: "¿Cuántas personas viven normalmente en la Estación Espacial Internacional?", opciones: ["2", "6-7", "20", "50"], respuestaCorrecta: 1, explicacion: "La ISS normalmente tiene una tripulación de 6-7 astronautas de diferentes países que rotan cada 6 meses. 🧑‍🚀" },`,
    `            { titulo: "✅ Quiz: Tamaño ISS", tipo: 'mini_quiz', pregunta: "¿Qué tan grande es la Estación Espacial Internacional?", opciones: ["Como un auto", "Como una casa", "Como un campo de fútbol", "Como una ciudad"], respuestaCorrecta: 2, explicacion: "La ISS mide 109m × 73m, como un campo de fútbol. Pesa 420 toneladas. ⚽" },`,
    `            { titulo: "✅ Quiz: Robonaut", tipo: 'mini_quiz', pregunta: "¿Qué robot humanoide fue enviado a la ISS para probar trabajo junto a astronautas?", opciones: ["ASIMO", "Robonaut 2", "Atlas", "Pepper"], respuestaCorrecta: 1, explicacion: "Robonaut 2 fue enviado a la ISS en 2011. Tiene manos que pueden usar herramientas humanas. 🤖" },`,
    `            { titulo: "✅ Quiz: Mantenimiento", tipo: 'mini_quiz', pregunta: "¿Cuánto tiempo al día dedican los astronautas al mantenimiento de la ISS?", opciones: ["10 minutos", "Unas 2.5 horas diarias", "8 horas", "No hacen mantenimiento"], respuestaCorrecta: 1, explicacion: "Los astronautas dedican ~2.5 horas al día a reparaciones, limpieza de filtros y revisión de sistemas. 🔧" },`,
    `            { titulo: "✅ Quiz: Caminatas EVA", tipo: 'mini_quiz', pregunta: "¿Cuánto dura una caminata espacial (EVA) típica?", opciones: ["30 minutos", "2 horas", "6-7 horas", "24 horas"], respuestaCorrecta: 2, explicacion: "Una EVA típica dura 6-7 horas. Los astronautas preparan sus trajes durante 4 horas antes. 🚶‍♂️" },`,
    `            { titulo: "✅ Quiz: Reciclaje", tipo: 'mini_quiz', pregunta: "¿Qué porcentaje del agua se recicla en la ISS?", opciones: ["50%", "75%", "Más del 90%", "No se recicla"], respuestaCorrecta: 2, explicacion: "La ISS recicla más del 90% del agua, incluyendo la humedad del aire. Sistemas de filtración increíbles. 💧" },`,
    `            { titulo: "✅ Quiz: Órbitas por Día", tipo: 'mini_quiz', pregunta: "¿Cuántos amaneceres ven los astronautas de la ISS por día?", opciones: ["1", "8", "16", "24"], respuestaCorrecta: 2, explicacion: "La ISS orbita la Tierra cada 90 minutos. Los astronautas ven 16 amaneceres y 16 atardeceres cada 24 horas. 🌅" },`,
    `            { titulo: "✅ Quiz: Kibo", tipo: 'mini_quiz', pregunta: "¿Qué brazo robótico japonés puede mover experimentos dentro y fuera de la ISS?", opciones: ["Canadarm2", "JEMRMS (Kibo)", "Dextre", "ERA"], respuestaCorrecta: 1, explicacion: "El JEMRMS del módulo Kibo tiene un brazo grande y uno pequeño para mover experimentos. 🇯🇵" },`,
    `            { titulo: "✅ Quiz: Gravedad Artificial", tipo: 'mini_quiz', pregunta: "¿Cómo se podría crear gravedad artificial en una estación espacial futura?", opciones: ["Con imanes", "Rotando la estación para generar fuerza centrífuga", "Con ventiladores", "No es posible"], respuestaCorrecta: 1, explicacion: "Una estación rotante crearía fuerza centrífuga que simula gravedad. Mayor radio y velocidad = más gravedad. 🌀" },`,
  ],
  'w4_mod7_basura_espacial': [
    `            { titulo: "✅ Quiz: Basura en Órbita", tipo: 'mini_quiz', pregunta: "¿Cuántos objetos de basura espacial rastreables hay en órbita?", opciones: ["Unos 100", "Unos 1,000", "Más de 30,000", "Menos de 50"], respuestaCorrecta: 2, explicacion: "Hay más de 30,000 objetos rastreables (>10cm) y millones de fragmentos pequeños. 🗑️" },`,
    `            { titulo: "✅ Quiz: Velocidad Impacto", tipo: 'mini_quiz', pregunta: "¿A qué velocidad puede impactar un fragmento de basura espacial contra un satélite?", opciones: ["100 km/h", "1,000 km/h", "Hasta 28,000 km/h o más", "10 km/h"], respuestaCorrecta: 2, explicacion: "En órbitas opuestas, la velocidad relativa puede superar 50,000 km/h. Un fragmento de 1cm tiene la energía de una granada. 💥" },`,
    `            { titulo: "✅ Quiz: Kessler", tipo: 'mini_quiz', pregunta: "¿Qué es el Síndrome de Kessler?", opciones: ["Una enfermedad de astronautas", "Una reacción en cadena donde la basura genera más basura", "Un tipo de combustible", "Un módulo de la ISS"], respuestaCorrecta: 1, explicacion: "Las colisiones generan fragmentos que causan más colisiones, creando una cascada exponencial de basura. 😱" },`,
    `            { titulo: "✅ Quiz: Maniobras ISS", tipo: 'mini_quiz', pregunta: "¿Cuántas maniobras de evasión realiza la ISS al año para evitar basura espacial?", opciones: ["0", "1-3 maniobras", "20-30", "100"], respuestaCorrecta: 1, explicacion: "La ISS realiza 1-3 maniobras de evitación al año. Si no hay tiempo, los astronautas se refugian en cápsulas. 🛡️" },`,
    `            { titulo: "✅ Quiz: ClearSpace", tipo: 'mini_quiz', pregunta: "¿Qué misión planea la ESA para limpiar basura espacial con un robot?", opciones: ["Hubble 2", "ClearSpace-1", "Mars Express", "Galileo"], respuestaCorrecta: 1, explicacion: "ClearSpace-1 usará brazos robóticos para capturar un objeto abandonado y desintegrarlo en la atmósfera. 🤖" },`,
    `            { titulo: "✅ Quiz: Escudo Whipple", tipo: 'mini_quiz', pregunta: "¿Cómo protege la ISS sus módulos del impacto de basura pequeña?", opciones: ["Con un campo de fuerza", "Con escudos Whipple de múltiples capas", "Con un láser", "No tiene protección"], respuestaCorrecta: 1, explicacion: "Los escudos Whipple tienen capas separadas que fragmentan y dispersan el impacto antes del casco presurizado. 🛡️" },`,
    `            { titulo: "✅ Quiz: Deorbitar", tipo: 'mini_quiz', pregunta: "¿Qué significa deorbitar un satélite al final de su vida útil?", opciones: ["Ponerlo más alto", "Reducir su velocidad para que caiga y se desintegre en la atmósfera", "Apagarlo y dejarlo flotando", "Mandarlo a la Luna"], respuestaCorrecta: 1, explicacion: "Deorbitar es la mejor práctica: el satélite se desintegra en la atmósfera. Evita basura permanente. 🔥" },`,
    `            { titulo: "✅ Quiz: Rastreo", tipo: 'mini_quiz', pregunta: "¿Qué tecnología usan para rastrear basura espacial desde la Tierra?", opciones: ["Telescopios ópticos solamente", "Radares y telescopios", "GPS", "Satélites espía"], respuestaCorrecta: 1, explicacion: "La Space Surveillance Network usa radares potentes y telescopios ópticos para rastrear objetos de más de 10cm. 📡" },`,
    `            { titulo: "✅ Quiz: Redes de Captura", tipo: 'mini_quiz', pregunta: "¿Qué método propuesto usaría redes para capturar basura espacial?", opciones: ["Redes de pesca normales", "Redes robóticas lanzadas desde un satélite cazador", "Redes magnéticas", "Telarañas espaciales"], respuestaCorrecta: 1, explicacion: "La misión RemoveDEBRIS probó exitosamente una red lanzada desde un satélite para capturar objetivos. 🕸️" },`,
  ],
  'w4_mod8_fabricacion_espacio': [
    `            { titulo: "✅ Quiz: Impresión 3D ISS", tipo: 'mini_quiz', pregunta: "¿Qué lograron imprimir en 3D por primera vez en la ISS?", opciones: ["Una pizza", "Una herramienta (llave de tuercas)", "Un robot completo", "Un traje espacial"], respuestaCorrecta: 1, explicacion: "En 2014, Made In Space imprimió la primera herramienta en el espacio. El diseño fue enviado por email. 🔧" },`,
    `            { titulo: "✅ Quiz: Microgravedad", tipo: 'mini_quiz', pregunta: "¿Cuál es una ventaja de fabricar en microgravedad?", opciones: ["Todo es más barato", "Se pueden crear aleaciones y fibras ópticas perfectas", "Es más rápido", "Los materiales pesan menos"], respuestaCorrecta: 1, explicacion: "Sin gravedad, los materiales se mezclan uniformemente. Las fibras ópticas hechas en el espacio son hasta 100x mejores. 🔬" },`,
    `            { titulo: "✅ Quiz: ISRU", tipo: 'mini_quiz', pregunta: "¿Qué significa ISRU en el contexto de colonización espacial?", opciones: ["International Space Robot Unit", "In-Situ Resource Utilization (uso de recursos locales)", "Internet Space Relay Unit", "Isolated System Recovery Unit"], respuestaCorrecta: 1, explicacion: "ISRU significa usar materiales del lugar para construir y producir combustible, sin traer todo desde la Tierra. 🏗️" },`,
    `            { titulo: "✅ Quiz: Regolito Lunar", tipo: 'mini_quiz', pregunta: "¿Qué material lunar podrían usar robots para construir hábitats?", opciones: ["Madera", "Regolito (polvo lunar) sinterizado o mezclado", "Plástico traído de la Tierra", "Agua"], respuestaCorrecta: 1, explicacion: "El regolito se puede compactar o sinterizar con microondas para crear ladrillos. Robots albañiles en la Luna. 🌙" },`,
    `            { titulo: "✅ Quiz: Soldadura Fría", tipo: 'mini_quiz', pregunta: "¿Qué fenómeno hace que dos metales se suelden solos al tocarse en el vacío?", opciones: ["El frío", "Cold welding (soldadura fría)", "La radiación", "La gravedad"], respuestaCorrecta: 1, explicacion: "En el vacío, sin óxido ni aire, los átomos metálicos se unen espontáneamente al contacto. 🔗" },`,
    `            { titulo: "✅ Quiz: Ensamblaje ISS", tipo: 'mini_quiz', pregunta: "¿Cómo se ensambló la ISS?", opciones: ["Se construyó completa y se lanzó", "Se ensambló pieza por pieza en órbita durante más de 10 años", "Se infló como un globo", "Se teletransportó"], respuestaCorrecta: 1, explicacion: "La ISS se ensambló con más de 40 misiones entre 1998 y 2011. Cada módulo fue acoplado por robots y astronautas. 🧩" },`,
    `            { titulo: "✅ Quiz: Bio-impresión", tipo: 'mini_quiz', pregunta: "¿Qué tipo de tejido se ha logrado bio-imprimir en la ISS?", opciones: ["Ropa", "Tejido cardíaco (del corazón)", "Pelo", "Uñas"], respuestaCorrecta: 1, explicacion: "En microgravedad, la bioimpresión funciona mejor porque las células no colapsan por su peso. ❤️" },`,
    `            { titulo: "✅ Quiz: Minería Espacial", tipo: 'mini_quiz', pregunta: "¿Qué recurso valioso se cree que hay en cantidades enormes en los asteroides?", opciones: ["Madera", "Metales preciosos (platino, oro) y agua", "Petróleo", "Arena"], respuestaCorrecta: 1, explicacion: "Un solo asteroide tipo-M podría contener más platino que todas las reservas terrestres. 💎" },`,
    `            { titulo: "✅ Quiz: Oxígeno Lunar", tipo: 'mini_quiz', pregunta: "¿Qué gas vital se puede extraer del regolito lunar mediante calentamiento?", opciones: ["Nitrógeno", "Oxígeno", "Helio", "Hidrógeno puro"], respuestaCorrecta: 1, explicacion: "El regolito contiene ~45% de óxido. Calentándolo a alta temperatura se puede extraer oxígeno. 🌬️" },`,
  ],
  'w4_mod9_ia_espacial': [
    `            { titulo: "✅ Quiz: AutoNav", tipo: 'mini_quiz', pregunta: "¿Qué sistema de IA usa Perseverance para conducir de forma autónoma en Marte?", opciones: ["ChatGPT", "AutoNav", "Tesla Autopilot", "Siri"], respuestaCorrecta: 1, explicacion: "AutoNav permite a Perseverance planificar rutas y esquivar rocas sin esperar comandos de la Tierra. 🧠" },`,
    `            { titulo: "✅ Quiz: Visión Computacional", tipo: 'mini_quiz', pregunta: "¿Para qué usan visión por computador los robots espaciales?", opciones: ["Para ver películas", "Para identificar rocas, navegar terreno y acoplar naves", "Para hacer selfies", "Para pintar"], respuestaCorrecta: 1, explicacion: "La visión computacional permite a robots reconocer objetivos y navegar de forma autónoma. 👁️" },`,
    `            { titulo: "✅ Quiz: Redes Neuronales", tipo: 'mini_quiz', pregunta: "¿Cómo ayudan las redes neuronales a clasificar rocas marcianas?", opciones: ["Las pintan", "Analizan fotos y distinguen tipos de roca por textura y color", "Las rompen", "Las transportan"], respuestaCorrecta: 1, explicacion: "Redes neuronales entrenadas con miles de imágenes pueden clasificar tipos de roca y detectar minerales interesantes. 🪨" },`,
    `            { titulo: "✅ Quiz: Planificación IA", tipo: 'mini_quiz', pregunta: "¿Por qué la IA de planificación es crucial para misiones más allá de Marte?", opciones: ["Para ahorrar dinero", "Porque la latencia es tan grande que el robot debe decidir solo durante días", "Para hacer más fotos", "No es necesaria"], respuestaCorrecta: 1, explicacion: "Una sonda en Júpiter tiene 33-53 min de latencia. El robot debe tomar decisiones complejas sin supervisión. 🕐" },`,
    `            { titulo: "✅ Quiz: Chips Rad-Hard", tipo: 'mini_quiz', pregunta: "¿Qué desafío tiene ejecutar IA potente en un rover?", opciones: ["No hay internet", "Los procesadores deben ser resistentes a radiación y son más lentos", "Hace mucho frío", "Es ilegal"], respuestaCorrecta: 1, explicacion: "Los chips rad-hard son mucho más lentos y costosos. Un chip de rover equivale a un celular de hace 15 años. 💾" },`,
    `            { titulo: "✅ Quiz: AEGIS", tipo: 'mini_quiz', pregunta: "¿Qué hace el sistema AEGIS del rover Curiosity?", opciones: ["Lo protege de asteroides", "Selecciona rocas interesantes y las analiza con láser automáticamente", "Le da oxígeno", "Controla la temperatura"], respuestaCorrecta: 1, explicacion: "AEGIS identifica rocas inusuales en las fotos y dispara el láser ChemCam para analizarlas. Ciencia autónoma. 🔬" },`,
    `            { titulo: "✅ Quiz: Autodiagnóstico", tipo: 'mini_quiz', pregunta: "¿Por qué los robots espaciales necesitan IA para autodiagnosticarse?", opciones: ["Para divertirse", "Para detectar fallos y reconfigurar sistemas sin esperar ayuda", "Para hablar con aliens", "No lo necesitan"], respuestaCorrecta: 1, explicacion: "Si un sensor falla, el robot debe detectarlo y redistribuir funciones entre los sensores restantes. Todo en segundos. 🏥" },`,
    `            { titulo: "✅ Quiz: Filtrado de Datos", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers procesan datos a bordo en vez de enviar todo a la Tierra?", opciones: ["Porque es más divertido", "Porque el ancho de banda es limitado", "Porque no quieren compartir", "Porque los datos son secretos"], respuestaCorrecta: 1, explicacion: "Perseverance genera gigabytes pero solo envía ~250 MB/día. La IA filtra y prioriza qué datos enviar. 📊" },`,
    `            { titulo: "✅ Quiz: Enjambres", tipo: 'mini_quiz', pregunta: "¿Qué concepto propone la NASA para explorar lunas heladas como Europa?", opciones: ["Enviar un astronauta", "Enjambres de mini-robots autónomos que cooperan bajo el hielo", "Un telescopio gigante", "Un cohete nuclear"], respuestaCorrecta: 1, explicacion: "El concepto SWIM propone mini-robots que naden bajo el hielo de Europa buscando vida en su océano subterráneo. 🏊" },`,
  ],
  'w4_mod10_autonomia': [
    `            { titulo: "✅ Quiz: Niveles Autonomía", tipo: 'mini_quiz', pregunta: "¿Cuál es el nivel más alto de autonomía robótica?", opciones: ["Control remoto directo", "Semiautónomo con supervisión", "Totalmente autónomo sin intervención humana", "Manual con botones"], respuestaCorrecta: 2, explicacion: "La autonomía total significa que el robot percibe, decide y actúa sin supervisión humana. 🤖" },`,
    `            { titulo: "✅ Quiz: Autonomía vs Teleop", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene la autonomía sobre la teleoperación en el espacio?", opciones: ["Es más barata", "Reacciona inmediatamente sin esperar señales que tardan minutos", "Es más segura siempre", "No tiene ventajas"], respuestaCorrecta: 1, explicacion: "Con 20+ min de latencia, un rover teloperado no puede esquivar obstáculos a tiempo. La autonomía reacciona en milisegundos. ⚡" },`,
    `            { titulo: "✅ Quiz: SLAM", tipo: 'mini_quiz', pregunta: "¿Qué es SLAM en robótica?", opciones: ["Un ataque robot", "Localización y Mapeo Simultáneos", "Un tipo de sensor", "Un juego"], respuestaCorrecta: 1, explicacion: "SLAM permite al robot crear un mapa del entorno mientras calcula su propia posición. Fundamental para navegación autónoma. 🗺️" },`,
    `            { titulo: "✅ Quiz: Función Costo", tipo: 'mini_quiz', pregunta: "¿Qué algoritmo usa un rover para elegir el mejor camino?", opciones: ["Random walk", "Árboles de decisión y funciones de costo", "Piedra-papel-tijera", "Línea recta siempre"], respuestaCorrecta: 1, explicacion: "El rover evalúa cada ruta con una función de costo que considera distancia, pendiente y riesgo. 🌳" },`,
    `            { titulo: "✅ Quiz: Safe Mode", tipo: 'mini_quiz', pregunta: "¿Qué es un safe mode en un robot espacial?", opciones: ["Modo de juego", "Estado de emergencia donde el robot detiene operaciones y espera instrucciones", "Modo de alta velocidad", "Modo de ataque"], respuestaCorrecta: 1, explicacion: "En safe mode, el robot cancela actividades, orienta paneles al sol y apunta la antena a la Tierra. Supervivencia primero. 🛡️" },`,
    `            { titulo: "✅ Quiz: Costmap", tipo: 'mini_quiz', pregunta: "¿Qué hace un rover con un mapa de costos (costmap)?", opciones: ["Lo colorea", "Asigna un valor de dificultad a cada celda del terreno para planificar rutas", "Lo envía a la Tierra", "Lo borra"], respuestaCorrecta: 1, explicacion: "Cada celda tiene un costo: 0=fácil, 255=imposible. El planificador encuentra la ruta que minimiza el costo total. 🗺️" },`,
    `            { titulo: "✅ Quiz: Multi-agente", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene un sistema multi-agente (varios robots cooperando)?", opciones: ["Es más bonito", "Cubren más terreno y si uno falla los otros continúan", "Hacen más ruido", "No tiene ventajas"], respuestaCorrecta: 1, explicacion: "Múltiples robots exploran en paralelo, comparten mapas y un fallo individual no arruina toda la misión. 🤝" },`,
    `            { titulo: "✅ Quiz: Cámaras Estéreo", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers usan cámaras estéreo (dos lado a lado)?", opciones: ["Para hacer fotos 3D", "Para calcular distancia a objetos por la diferencia entre las dos imágenes", "Para tener repuesto", "Para zoom"], respuestaCorrecta: 1, explicacion: "Las cámaras estéreo funcionan como nuestros ojos: la diferencia en imágenes permite calcular distancias. 👀" },`,
    `            { titulo: "✅ Quiz: Reflejo Robótico", tipo: 'mini_quiz', pregunta: "¿Qué es un comportamiento reactivo en robótica?", opciones: ["Cuando el robot se enoja", "Una respuesta inmediata a un estímulo del sensor", "Un tipo de batería", "Un protocolo de comunicación"], respuestaCorrecta: 1, explicacion: "Como un reflejo: si detecta un precipicio, frena inmediatamente. No necesita pensar, solo reacciona. ⚡" },`,
  ],
  'w4_mod11_telescopios': [
    `            { titulo: "✅ Quiz: Hubble", tipo: 'mini_quiz', pregunta: "¿Cuántos años lleva el telescopio Hubble en órbita?", opciones: ["10 años", "20 años", "Más de 35 años", "5 años"], respuestaCorrecta: 2, explicacion: "El Hubble fue lanzado en 1990 y sigue funcionando. Ha sido reparado 5 veces por astronautas. 🔭" },`,
    `            { titulo: "✅ Quiz: JWST Segmentos", tipo: 'mini_quiz', pregunta: "¿Cuántos segmentos de espejo tiene el telescopio James Webb?", opciones: ["1 espejo", "6 espejos", "18 segmentos hexagonales", "100 espejos"], respuestaCorrecta: 2, explicacion: "El JWST tiene 18 segmentos hexagonales de berilio bañados en oro que se desplegaron robóticamente. ✨" },`,
    `            { titulo: "✅ Quiz: Infrarrojo", tipo: 'mini_quiz', pregunta: "¿Por qué el JWST observa en infrarrojo en vez de luz visible?", opciones: ["Porque es más barato", "Porque la luz de galaxias lejanas se ha desplazado al infrarrojo", "Porque no hay luz visible en el espacio", "Por accidente"], respuestaCorrecta: 1, explicacion: "El corrimiento al rojo hace que la luz lejana se estire al infrarrojo. El JWST ve las primeras galaxias. 🌌" },`,
    `            { titulo: "✅ Quiz: Punto L2", tipo: 'mini_quiz', pregunta: "¿Dónde está ubicado el telescopio James Webb?", opciones: ["En órbita baja terrestre", "En la Luna", "En el punto de Lagrange L2 a 1.5 millones de km", "En Marte"], respuestaCorrecta: 2, explicacion: "En L2, la gravedad del Sol y la Tierra se equilibran y el telescopio está siempre en sombra. 🌑" },`,
    `            { titulo: "✅ Quiz: Despliegue JWST", tipo: 'mini_quiz', pregunta: "¿Por qué el JWST tuvo que desplegarse robóticamente en el espacio?", opciones: ["Para impresionar", "Porque plegado cabía en el cohete y extendido es más grande que una cancha de tenis", "Porque se rompió al despegar", "Porque es flexible"], respuestaCorrecta: 1, explicacion: "El parasol mide 21m × 14m. Plegado cabía en el cohete Ariane 5. Se desplegó con 344 pasos robóticos. 🎾" },`,
    `            { titulo: "✅ Quiz: Enfriamiento JWST", tipo: 'mini_quiz', pregunta: "¿A qué temperatura debe enfriarse el JWST para funcionar?", opciones: ["0°C", "-100°C", "-233°C (40 Kelvin)", "Temperatura ambiente"], respuestaCorrecta: 2, explicacion: "Para detectar infrarrojo débil, los sensores deben estar a -233°C. Un parasol gigante lo protege del Sol. 🥶" },`,
    `            { titulo: "✅ Quiz: Interferometría", tipo: 'mini_quiz', pregunta: "¿Qué técnica combina señales de múltiples telescopios para mayor resolución?", opciones: ["Fotografía", "Interferometría", "Espectroscopía", "Polarimetría"], respuestaCorrecta: 1, explicacion: "La interferometría combinó telescopios en 6 continentes para fotografiar un agujero negro. 🕳️" },`,
    `            { titulo: "✅ Quiz: Radio Telescopios", tipo: 'mini_quiz', pregunta: "¿Qué detectan los radio telescopios que los ópticos no pueden ver?", opciones: ["Colores", "Ondas de radio de púlsares y nubes de gas frío", "Sonido", "Temperatura"], respuestaCorrecta: 1, explicacion: "Las ondas de radio atraviesan polvo cósmico que bloquea la luz visible. Ven lo invisible. 📻" },`,
    `            { titulo: "✅ Quiz: Reparación JWST", tipo: 'mini_quiz', pregunta: "¿Por qué el JWST NO puede ser reparado como el Hubble?", opciones: ["Porque es delicado", "Porque está a 1.5 millones de km, demasiado lejos", "Porque no tiene tornillos", "Porque es automático"], respuestaCorrecta: 1, explicacion: "A 1.5 millones de km, no hay nave tripulada que pueda llegar. Cada componente tenía que ser perfecto. 🎯" },`,
  ],
  'w4_mod12_colonias': [
    `            { titulo: "✅ Quiz: Hábitats Inflables", tipo: 'mini_quiz', pregunta: "¿Qué tipo de estructura propone la NASA para hábitats lunares?", opciones: ["Casas de madera", "Hábitats inflables con protección de regolito", "Rascacielos de vidrio", "Cuevas naturales"], respuestaCorrecta: 1, explicacion: "Los hábitats inflables son livianos para transportar y se cubren con regolito para proteger de radiación. 🏠" },`,
    `            { titulo: "✅ Quiz: Tubos de Lava", tipo: 'mini_quiz', pregunta: "¿Qué estructuras naturales en la Luna podrían servir como refugio?", opciones: ["Volcanes activos", "Tubos de lava (túneles formados por lava antigua)", "Lagos subterráneos", "Bosques"], respuestaCorrecta: 1, explicacion: "Los tubos de lava son túneles naturales que protegen de radiación, micrometeoritos y temperaturas extremas. 🌋" },`,
    `            { titulo: "✅ Quiz: Agricultura ISS", tipo: 'mini_quiz', pregunta: "¿Qué cultivo se ha logrado cultivar exitosamente en la ISS?", opciones: ["Trigo", "Lechuga (proyecto Veggie)", "Tomates gigantes", "Papas marcianas"], respuestaCorrecta: 1, explicacion: "El proyecto Veggie cultiva lechuga, rábanos y chiles en la ISS con luces LED especiales. 🥬" },`,
    `            { titulo: "✅ Quiz: Radiación", tipo: 'mini_quiz', pregunta: "¿Por qué la radiación cósmica es un problema grave para colonias fuera de la Tierra?", opciones: ["Porque hace calor", "Porque daña el ADN sin la protección de la atmósfera terrestre", "Porque hace ruido", "Porque cambia el color"], respuestaCorrecta: 1, explicacion: "Sin atmósfera ni campo magnético, la radiación cósmica penetra sin protección. Los hábitats necesitan blindaje. ☢️" },`,
    `            { titulo: "✅ Quiz: Agua Lunar", tipo: 'mini_quiz', pregunta: "¿Dónde se ha confirmado hielo de agua en la Luna?", opciones: ["En los mares lunares", "En cráteres permanentemente en sombra en los polos", "En la superficie visible", "No hay agua en la Luna"], respuestaCorrecta: 1, explicacion: "La misión LCROSS confirmó hielo en cráteres polares que nunca reciben luz solar. Temperaturas de -250°C. 🧊" },`,
    `            { titulo: "✅ Quiz: MOXIE", tipo: 'mini_quiz', pregunta: "¿Qué dispositivo de Perseverance produce oxígeno a partir de la atmósfera marciana?", opciones: ["Un ventilador", "MOXIE", "Un filtro de carbón", "Electrólisis de agua"], respuestaCorrecta: 1, explicacion: "MOXIE separa CO₂ de la atmósfera de Marte en CO + O₂. Prueba de concepto para futuras colonias. 🌬️" },`,
    `            { titulo: "✅ Quiz: Gravedad de Marte", tipo: 'mini_quiz', pregunta: "¿Cuánta gravedad tiene Marte comparada con la Tierra?", opciones: ["La misma", "38% de la gravedad terrestre", "0%", "200%"], respuestaCorrecta: 1, explicacion: "Marte tiene 38% de la gravedad terrestre. Una persona de 70kg pesaría solo 26.6kg. ⚖️" },`,
    `            { titulo: "✅ Quiz: Impresión Lunar", tipo: 'mini_quiz', pregunta: "¿Qué rol tendrían robots de impresión 3D en una colonia lunar?", opciones: ["Hacer juguetes", "Construir hábitats y pistas usando regolito", "Decorar la base", "Cocinar"], respuestaCorrecta: 1, explicacion: "La NASA y ESA desarrollan robots que imprimen estructuras usando regolito como material. 🖨️" },`,
    `            { titulo: "✅ Quiz: Comunicación Láser", tipo: 'mini_quiz', pregunta: "¿Qué tecnología se desarrolla para comunicaciones de alta velocidad con Marte?", opciones: ["5G", "Comunicación óptica láser (DSOC)", "Bluetooth 6.0", "Cables submarinos"], respuestaCorrecta: 1, explicacion: "DSOC usa láseres para transmitir datos 10-100x más rápido que ondas de radio. Probado exitosamente en 2023. 💡" },`,
  ],
  'w4_mod13_mision_luna': [
    `            { titulo: "✅ Quiz: Artemis", tipo: 'mini_quiz', pregunta: "¿Cuál es el objetivo principal del programa Artemis de la NASA?", opciones: ["Construir un hotel lunar", "Llevar humanos a la Luna y preparar la ida a Marte", "Lanzar satélites", "Estudiar el Sol"], respuestaCorrecta: 1, explicacion: "Artemis busca presencia permanente en la Luna con la estación Gateway orbital. Es el trampolín a Marte. 🌙" },`,
    `            { titulo: "✅ Quiz: Gateway", tipo: 'mini_quiz', pregunta: "¿Qué es la estación Gateway en el programa Artemis?", opciones: ["Una puerta de entrada", "Una mini estación espacial en órbita lunar", "Un cohete", "Un rover lunar"], respuestaCorrecta: 1, explicacion: "Gateway será una pequeña estación en órbita lunar donde los astronautas harán escala. 🛸" },`,
    `            { titulo: "✅ Quiz: Polo Sur", tipo: 'mini_quiz', pregunta: "¿Por qué Artemis planea aterrizar en el polo sur de la Luna?", opciones: ["Porque es más fácil", "Porque hay hielo de agua que los colonos pueden usar", "Porque es más bonito", "Porque está más cerca"], respuestaCorrecta: 1, explicacion: "El polo sur tiene hielo de agua y zonas con luz solar casi continua. Combinación perfecta para una base. ❄️" },`,
    `            { titulo: "✅ Quiz: VIPER", tipo: 'mini_quiz', pregunta: "¿Qué rover de la NASA buscará hielo de agua en la Luna?", opciones: ["Curiosity 2", "VIPER", "Lunokhod 3", "Sojourner 2"], respuestaCorrecta: 1, explicacion: "VIPER exploraría cráteres en sombra permanente con taladro y sensores para mapear hielo de agua. 🏔️" },`,
    `            { titulo: "✅ Quiz: SLS", tipo: 'mini_quiz', pregunta: "¿Qué cohete impulsa las misiones Artemis hacia la Luna?", opciones: ["Falcon 9", "Space Launch System (SLS)", "Saturn V", "Starship solo"], respuestaCorrecta: 1, explicacion: "El SLS es el cohete más potente jamás construido. Genera 39.1 millones de Newtons de empuje. 🚀" },`,
    `            { titulo: "✅ Quiz: Orion", tipo: 'mini_quiz', pregunta: "¿Para cuántos astronautas está diseñada la cápsula Orion?", opciones: ["2", "4", "8", "12"], respuestaCorrecta: 1, explicacion: "Orion puede llevar hasta 4 astronautas a la Luna. Tiene escudo térmico para re-entrada a 40,000 km/h. 🛡️" },`,
    `            { titulo: "✅ Quiz: Trajes Lunares", tipo: 'mini_quiz', pregunta: "¿Qué mejora tienen los nuevos trajes lunares sobre los de Apollo?", opciones: ["Son más bonitos", "Mayor movilidad y mejor protección", "Son más baratos", "Son transparentes"], respuestaCorrecta: 1, explicacion: "Los nuevos trajes permiten caminar, arrodillarse y recoger rocas. Los de Apollo eran muy rígidos. 🧑‍🚀" },`,
    `            { titulo: "✅ Quiz: Red Lunar", tipo: 'mini_quiz', pregunta: "¿Por qué se necesita una red de satélites alrededor de la Luna?", opciones: ["Para WiFi", "Para mantener comunicación continua en el lado lejano", "Para TV", "Para GPS lunar"], respuestaCorrecta: 1, explicacion: "Sin satélites relay, astronautas en el lado lejano estarían incomunicados. También se planea GPS lunar. 📡" },`,
    `            { titulo: "✅ Quiz: Polvo Lunar", tipo: 'mini_quiz', pregunta: "¿Por qué el polvo lunar es peligroso para astronautas y robots?", opciones: ["Porque es venenoso", "Porque es abrasivo con bordes afilados y se pega por estática", "Porque es radiactivo", "Porque explota"], respuestaCorrecta: 1, explicacion: "El regolito no ha sido erosionado. Sus partículas son como vidrio molido que se adhiere por carga estática. 🫁" },`,
  ],
  'w4_mod14_mision_marte': [
    `            { titulo: "✅ Quiz: Duración del Viaje", tipo: 'mini_quiz', pregunta: "¿Cuánto dura un viaje de la Tierra a Marte?", opciones: ["1 semana", "1 mes", "6-9 meses", "5 años"], respuestaCorrecta: 2, explicacion: "El viaje tarda entre 6 y 9 meses. Solo hay ventanas de lanzamiento cada 26 meses. 🚀" },`,
    `            { titulo: "✅ Quiz: Atmósfera Marte", tipo: 'mini_quiz', pregunta: "¿De qué está compuesta principalmente la atmósfera de Marte?", opciones: ["Oxígeno y nitrógeno", "95% dióxido de carbono (CO₂)", "100% hidrógeno", "No tiene atmósfera"], respuestaCorrecta: 1, explicacion: "Marte tiene una atmósfera muy delgada (1% de la terrestre) compuesta en 95% de CO₂. No respirable. 🌬️" },`,
    `            { titulo: "✅ Quiz: 7 Minutos Terror", tipo: 'mini_quiz', pregunta: "¿Por qué aterrizar en Marte se llama los 7 minutos de terror?", opciones: ["Porque da miedo", "Porque la nave frena de 20,000 km/h a 0 y la señal no llega a tiempo", "Porque solo tiene 7 min de combustible", "Porque Marte gira muy rápido"], respuestaCorrecta: 1, explicacion: "El retardo de comunicación es ~14 min, pero el aterrizaje dura 7. Todo debe ser completamente autónomo. 😰" },`,
    `            { titulo: "✅ Quiz: Sky Crane", tipo: 'mini_quiz', pregunta: "¿Qué sistema único usó Curiosity para aterrizar suavemente en Marte?", opciones: ["Solo paracaídas", "Sky crane: una grúa voladora que lo bajó con cables", "Un colchón inflable", "Retrocohetes directos"], respuestaCorrecta: 1, explicacion: "El sky crane flotó con retrocohetes y bajó a Curiosity con cables. Luego se alejó volando para estrellarse lejos. 🏗️" },`,
    `            { titulo: "✅ Quiz: Tormentas Marte", tipo: 'mini_quiz', pregunta: "¿Qué tan grandes pueden ser las tormentas de polvo en Marte?", opciones: ["Pequeñas como en un desierto", "Pueden cubrir TODO el planeta durante meses", "No hay tormentas", "Solo cubren un cráter"], respuestaCorrecta: 1, explicacion: "Las tormentas de polvo globales de Marte pueden cubrir todo el planeta y durar meses. 🌪️" },`,
    `            { titulo: "✅ Quiz: Ingenuity Vuelos", tipo: 'mini_quiz', pregunta: "¿Cuántos vuelos completó el helicóptero Ingenuity en Marte?", opciones: ["5 vuelos", "72 vuelos", "200 vuelos", "1 vuelo"], respuestaCorrecta: 1, explicacion: "Ingenuity completó 72 vuelos (diseñado para solo 5). Voló 128 minutos y recorrió 17 km. 🚁" },`,
    `            { titulo: "✅ Quiz: Mars Sample Return", tipo: 'mini_quiz', pregunta: "¿Qué misión planea traer muestras de Marte a la Tierra?", opciones: ["Apollo 20", "Mars Sample Return (MSR)", "New Horizons 2", "Voyager 3"], respuestaCorrecta: 1, explicacion: "MSR es una misión NASA/ESA para recoger tubos de muestras dejados por Perseverance y traerlos a la Tierra. 🧪" },`,
    `            { titulo: "✅ Quiz: Hielo Marciano", tipo: 'mini_quiz', pregunta: "¿Dónde se ha encontrado hielo de agua en Marte?", opciones: ["En los océanos", "En los polos y bajo la superficie", "Solo en la atmósfera", "No hay agua en Marte"], respuestaCorrecta: 1, explicacion: "Marte tiene casquetes polares de hielo y radares han detectado hielo subterráneo. Crucial para futuras colonias. 🧊" },`,
    `            { titulo: "✅ Quiz: Terraformación", tipo: 'mini_quiz', pregunta: "¿Qué es la terraformación de Marte?", opciones: ["Conquistarlo militarmente", "Modificar Marte para hacerlo habitable", "Destruirlo", "Pintarlo de azul"], respuestaCorrecta: 1, explicacion: "La terraformación es un concepto teórico que tomaría siglos. Involucraría crear atmósfera y calentar el planeta. 🌍" },`,
  ],
  'w4_mod15_competencia_espacial': [
    `            { titulo: "✅ Quiz: ISRO", tipo: 'mini_quiz', pregunta: "¿Cuál agencia espacial de la India llegó a la Luna en 2023?", opciones: ["NASA", "ESA", "ISRO", "CNSA"], respuestaCorrecta: 2, explicacion: "ISRO aterrizo Chandrayaan-3 exitosamente en el polo sur de la Luna en agosto 2023. 🇮🇳" },`,
    `            { titulo: "✅ Quiz: Cohetes Reutilizables", tipo: 'mini_quiz', pregunta: "¿Qué innovación revolucionaria logró SpaceX?", opciones: ["Cohetes más grandes", "Cohetes reutilizables que aterrizan verticalmente", "Combustible más barato", "Naves más pequeñas"], respuestaCorrecta: 1, explicacion: "Los boosters del Falcon 9 aterrizan verticalmente y se reusan 15+ veces. Redujo costos de ~$200M a ~$67M. 🚀" },`,
    `            { titulo: "✅ Quiz: Competencias NASA", tipo: 'mini_quiz', pregunta: "¿Qué competencia de robótica espacial para estudiantes organiza la NASA?", opciones: ["FIFA World Cup", "FIRST Robotics / NASA challenges", "Copa América", "League of Legends"], respuestaCorrecta: 1, explicacion: "NASA organiza Lunabotics, Rover Challenge y patrocina FIRST Robotics para estudiantes. 🏆" },`,
    `            { titulo: "✅ Quiz: Base Lunar China", tipo: 'mini_quiz', pregunta: "¿Qué país planea construir una International Lunar Research Station?", opciones: ["Solo Estados Unidos", "China y Rusia", "Japón", "Brasil"], respuestaCorrecta: 1, explicacion: "China y Rusia anunciaron la ILRS, una base lunar permanente planeada para la década de 2030. 🌙" },`,
    `            { titulo: "✅ Quiz: Blue Origin", tipo: 'mini_quiz', pregunta: "¿Qué empresa de Jeff Bezos ofrece vuelos turísticos suborbitales?", opciones: ["SpaceX", "Blue Origin", "Virgin Galactic", "Boeing"], respuestaCorrecta: 1, explicacion: "Blue Origin con New Shepard ha llevado turistas a 100km de altitud. El vuelo dura ~11 minutos. 💰" },`,
    `            { titulo: "✅ Quiz: Starship", tipo: 'mini_quiz', pregunta: "¿Para qué está siendo diseñado el Starship de SpaceX?", opciones: ["Vuelos domésticos", "Nave para llevar hasta 100 personas a Marte", "Avión supersónico", "Submarino"], respuestaCorrecta: 1, explicacion: "Starship será la nave más grande: 120m de altura, reutilizable, capaz de llevar 100+ personas a Marte. 🚀" },`,
    `            { titulo: "✅ Quiz: NewSpace", tipo: 'mini_quiz', pregunta: "¿Qué es el movimiento NewSpace?", opciones: ["Un género musical", "La industria espacial privada que complementa a agencias gubernamentales", "Un videojuego", "Una red social"], respuestaCorrecta: 1, explicacion: "NewSpace incluye SpaceX, Blue Origin, Rocket Lab y Planet. Democratizan el acceso al espacio. 🏢" },`,
    `            { titulo: "✅ Quiz: Cooperación ISS", tipo: 'mini_quiz', pregunta: "¿Cuántos países participaron en la construcción de la ISS?", opciones: ["Solo USA", "5 agencias de 15 países", "Todos los países", "Solo Rusia"], respuestaCorrecta: 1, explicacion: "NASA, Roscosmos, ESA, JAXA y CSA representando 15 países. El proyecto internacional más grande. 🌍" },`,
    `            { titulo: "✅ Quiz: Economía Espacial", tipo: 'mini_quiz', pregunta: "¿Cuánto vale la economía espacial global actualmente?", opciones: ["$1 millón", "$1 mil millones", "Más de $500 mil millones", "No genera dinero"], respuestaCorrecta: 2, explicacion: "La economía espacial supera los $500 mil millones al año. Se proyecta a $1.8 trillones para 2035. 💰" },`,
  ],
  'w4_mod16_proyecto_orbital_final': [
    `            { titulo: "✅ Quiz: Diseño de Misión", tipo: 'mini_quiz', pregunta: "¿Cuál es el primer paso al diseñar una misión espacial robótica?", opciones: ["Construir el robot", "Definir los objetivos científicos y requisitos", "Pintar el cohete", "Vender boletos"], respuestaCorrecta: 1, explicacion: "Todo empieza con la pregunta: ¿qué queremos descubrir? Los objetivos dictan el diseño del robot. 🎯" },`,
    `            { titulo: "✅ Quiz: Costo Perseverance", tipo: 'mini_quiz', pregunta: "¿Cuánto costó la misión del rover Perseverance?", opciones: ["$1 millón", "$2.7 mil millones", "$100 mil millones", "$100,000"], respuestaCorrecta: 1, explicacion: "Perseverance costó ~$2.7 mil millones. Menos de $1 por persona en la Tierra. La ciencia es invaluable. 💸" },`,
    `            { titulo: "✅ Quiz: Redundancia", tipo: 'mini_quiz', pregunta: "¿Qué es la redundancia en diseño espacial?", opciones: ["Repetir lo mismo", "Tener componentes de respaldo en caso de falla", "Usar menos componentes", "Hablar mucho por radio"], respuestaCorrecta: 1, explicacion: "Si una computadora falla, otra idéntica toma su lugar automáticamente. Perseverance tiene dos computadoras principales. 🔄" },`,
    `            { titulo: "✅ Quiz: Testing", tipo: 'mini_quiz', pregunta: "¿Cómo se prueba un rover antes de enviarlo a Marte?", opciones: ["Se ruega que funcione", "Se prueba en cámaras de vacío, temperaturas extremas y terreno simulado", "Se prueba una vez", "No se prueba"], respuestaCorrecta: 1, explicacion: "Los rovers pasan años de pruebas: vacío, temperaturas extremas, vibración y terreno rocoso simulado. 🧪" },`,
    `            { titulo: "✅ Quiz: Ventana Lanzamiento", tipo: 'mini_quiz', pregunta: "¿Por qué solo se puede lanzar a Marte cada 26 meses?", opciones: ["Por regulaciones", "Porque cada 26 meses Tierra y Marte se alinean para viaje eficiente", "Por vacaciones de la NASA", "Porque el cohete tarda 26 meses"], respuestaCorrecta: 1, explicacion: "La mecánica orbital dicta que cada 26 meses los planetas están en posición ideal. Perder la ventana = esperar 2+ años. 🌍" },`,
    `            { titulo: "✅ Quiz: Cuarto Limpio", tipo: 'mini_quiz', pregunta: "¿Por qué los rovers se ensamblan en cuartos limpios (cleanrooms)?", opciones: ["Para que se vean bonitos", "Para evitar contaminar Marte con bacterias terrestres", "Porque los ingenieros son ordenados", "Por moda"], respuestaCorrecta: 1, explicacion: "La protección planetaria exige evitar contaminar otros mundos con vida terrestre. Una partícula puede arruinar un sensor. 🧹" },`,
    `            { titulo: "✅ Quiz: Instrumentos", tipo: 'mini_quiz', pregunta: "¿Cuántos instrumentos científicos lleva el rover Perseverance?", opciones: ["1", "7 instrumentos principales", "50", "Ninguno"], respuestaCorrecta: 1, explicacion: "Perseverance tiene 7 instrumentos: Mastcam-Z, SuperCam, SHERLOC, PIXL, RIMFAX, MEDA y MOXIE. 🔬" },`,
    `            { titulo: "✅ Quiz: Datos Abiertos", tipo: 'mini_quiz', pregunta: "¿Puedes acceder a las fotos de los rovers de la NASA?", opciones: ["No, son secretas", "Sí, la NASA publica todos los datos libremente", "Solo si pagas", "Solo científicos"], respuestaCorrecta: 1, explicacion: "La NASA publica todas las imágenes públicamente. Puedes ver las fotos de Perseverance en mars.nasa.gov. 🌐" },`,
    `            { titulo: "✅ Quiz: Ingeniería Sistemas", tipo: 'mini_quiz', pregunta: "¿Qué disciplina integra todos los subsistemas de un rover?", opciones: ["Ingeniería civil", "Ingeniería de sistemas", "Ingeniería de sonido", "Ingeniería culinaria"], respuestaCorrecta: 1, explicacion: "La ingeniería de sistemas integra mecánica, electrónica, software y ciencia en un diseño coherente. 🎵" },`,
  ],
};

// Insert questions before each module's contenidoTeorico closing bracket
let offset = 0;
let total = 0;
for (const [moduleId, qLines] of Object.entries(questions)) {
  const lineIdx = moduleClosings[moduleId];
  if (lineIdx === undefined) { console.log('NOT FOUND:', moduleId); continue; }
  
  const insertAt = lineIdx + offset;
  // Insert question lines before the closing bracket
  lines.splice(insertAt, 0, ...qLines);
  offset += qLines.length;
  total += qLines.length;
  console.log(`${moduleId}: +${qLines.length} questions`);
}

fs.writeFileSync('src/data/world4Data.js', lines.join('\n'));
console.log(`\nTotal: ${total} questions injected into World 4`);
