// Script to inject questions for World 3: Nexo Biónico
const fs = require('fs');

function serializeQuestion(q) {
  if (q.tipo === 'mini_quiz') {
    const opts = q.opciones.map(o => `"${o.replace(/"/g, '\\"')}"`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'mini_quiz', pregunta: "${q.pregunta.replace(/"/g, '\\"')}", opciones: [${opts}], respuestaCorrecta: ${q.respuestaCorrecta}, explicacion: "${q.explicacion.replace(/"/g, '\\"')}" }`;
  }
  if (q.tipo === 'true_false') {
    const stmts = q.statements.map(s => `{ text: '${s.text.replace(/'/g, "\\'")}', correct: ${s.correct}, explain: '${s.explain.replace(/'/g, "\\'")}' }`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'true_false', statements: [${stmts}] }`;
  }
  if (q.tipo === 'matching_game') {
    const pairs = q.pairs.map(p => `{ left: '${p.left.replace(/'/g, "\\'")}', right: '${p.right.replace(/'/g, "\\'")}' }`).join(', ');
    return `{ titulo: "${q.titulo}", tipo: 'matching_game', instruccion: '${(q.instruccion||'Conecta los conceptos').replace(/'/g, "\\'")}', pairs: [${pairs}] }`;
  }
  return JSON.stringify(q);
}

function injectQuestions(filePath, extraQuestions) {
  let src = fs.readFileSync(filePath, 'utf-8');
  let offset = 0;
  let count = 0;
  for (const [moduleId, questions] of Object.entries(extraQuestions)) {
    if (!questions || questions.length === 0) continue;
    const idPattern = `id: '${moduleId}'`;
    const idIdx = src.indexOf(idPattern, offset);
    if (idIdx === -1) { console.log(`WARNING: ${moduleId} not found`); continue; }
    const ctSearch = src.indexOf('contenidoTeorico:', idIdx);
    if (ctSearch === -1 || ctSearch - idIdx > 3000) continue;
    const bracketStart = src.indexOf('[', ctSearch);
    if (bracketStart === -1) continue;
    let depth = 0, closingIdx = -1;
    for (let i = bracketStart; i < src.length; i++) {
      if (src[i] === '[') depth++;
      else if (src[i] === ']') { depth--; if (depth === 0) { closingIdx = i; break; } }
    }
    if (closingIdx === -1) continue;
    const insertions = questions.map(q => '\n            ' + serializeQuestion(q) + ',').join('');
    src = src.slice(0, closingIdx) + insertions + src.slice(closingIdx);
    offset = closingIdx + insertions.length;
    count += questions.length;
    console.log(`  ✅ ${moduleId}: +${questions.length}`);
  }
  fs.writeFileSync(filePath, src, 'utf-8');
  console.log(`  💾 Saved (${count} questions added)\n`);
}

const W3 = {
  'w3_mod1_biomimetica': [
    { titulo: "✅ Quiz: Qué es Biomimética", tipo: 'mini_quiz', pregunta: "¿Qué es la biomimética en robótica?", opciones: ["Construir robots biológicos", "Diseñar robots inspirados en la naturaleza y animales", "Usar animales como robots", "Hacer robots microscópicos"], respuestaCorrecta: 1, explicacion: "Biomimética = imitar la naturaleza. Robots que nadan como peces, vuelan como aves o caminan como insectos. 🦎" },
    { titulo: "✅ Quiz: Gecko Robot", tipo: 'mini_quiz', pregunta: "¿Qué animal inspira robots que escalan paredes lisas?", opciones: ["Araña", "Gecko (lagartija)", "Gato", "Serpiente"], respuestaCorrecta: 1, explicacion: "Los geckos tienen millones de pelos microscópicos que generan fuerzas de Van der Waals. ¡Robots con patas adhesivas! 🦎" },
    { titulo: "✅ Quiz: Robot Pez", tipo: 'mini_quiz', pregunta: "¿Por qué un robot con forma de pez es más eficiente que un submarino tradicional?", opciones: ["Es más bonito", "El movimiento ondulatorio del pez genera menos turbulencia y usa menos energía", "No es más eficiente", "Es más rápido"], respuestaCorrecta: 1, explicacion: "El movimiento biomimético de los peces es más eficiente que las hélices. ¡Millones de años de evolución optimizaron el diseño! 🐟" },
    { titulo: "✅ Quiz: Ventajas", tipo: 'mini_quiz', pregunta: "¿Cuál es la principal ventaja de la biomimética?", opciones: ["Es más barata", "Aprovecha soluciones que la evolución ya optimizó durante millones de años", "Solo es estética", "No tiene ventajas"], respuestaCorrecta: 1, explicacion: "La evolución ha probado diseños por millones de años. ¡La naturaleza es el mejor ingeniero! 🌿" },
    { titulo: "✅ Quiz: Ejemplo Real", tipo: 'mini_quiz', pregunta: "El tren bala de Japón mejoró su diseño imitando a:", opciones: ["Un tiburón", "Un martín pescador (kingfisher)", "Un águila", "Un delfín"], respuestaCorrecta: 1, explicacion: "El pico del martín pescador corta el aire sin ruido. El tren bala Shinkansen copió esa forma para reducir el estampido sónico. 🚄" },
    { titulo: "✅❌ Biomimética: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El velcro fue inventado imitando las semillas que se pegaban al pelo de un perro.', correct: true, explain: 'George de Mestral observó las semillas de bardana y creó el velcro. ¡Biomimética clásica!' }, { text: 'La biomimética solo se aplica en robótica.', correct: false, explain: 'Se aplica en arquitectura, medicina, materiales, aeronáutica y muchos otros campos.' }] },
    { titulo: "🧩 Animal y Robot", tipo: 'matching_game', instruccion: 'Conecta cada animal con la capacidad que inspira', pairs: [{ left: '🐙 Pulpo', right: 'Brazos flexibles/suaves' }, { left: '🦅 Águila', right: 'Drones con garras' }, { left: '🐜 Hormiga', right: 'Robots que trabajan en equipo' }, { left: '🐍 Serpiente', right: 'Robots que reptan por espacios estrechos' }] },
  ],
  'w3_mod2_locomocion': [
    { titulo: "✅ Quiz: Tipos de Locomoción", tipo: 'mini_quiz', pregunta: "¿Cuáles son los principales tipos de locomoción en robots?", opciones: ["Solo ruedas", "Ruedas, patas, orugas, vuelo, natación y reptación", "Solo caminar y volar", "Solo patas"], respuestaCorrecta: 1, explicacion: "¡Hay muchas formas de moverse! Cada tipo es mejor para un terreno diferente. 🦿" },
    { titulo: "✅ Quiz: Patas vs Ruedas", tipo: 'mini_quiz', pregunta: "¿Cuándo son mejores las PATAS que las ruedas?", opciones: ["En carreteras lisas", "En terreno irregular con rocas y escalones", "En pisos planos", "Nunca"], respuestaCorrecta: 1, explicacion: "Las patas superan obstáculos, escalan superficies irregulares y cruzan zanjas. ¡Las ruedas fallan en terreno difícil! 🏔️" },
    { titulo: "✅ Quiz: Bípedo vs Cuadrúpedo", tipo: 'mini_quiz', pregunta: "¿Por qué los robots cuadrúpedos (4 patas) son más estables que los bípedos (2)?", opciones: ["Son más bonitos", "Tienen más puntos de apoyo y un centro de gravedad más estable", "Pesan menos", "No son más estables"], respuestaCorrecta: 1, explicacion: "4 puntos de apoyo = mayor estabilidad. Los bípedos necesitan complejos algoritmos de equilibrio. ¡Como aprender a caminar! 🤖" },
    { titulo: "✅ Quiz: Robot Hexápodo", tipo: 'mini_quiz', pregunta: "¿Por qué 6 patas es una configuración popular para robots caminadores?", opciones: ["Es más bonito", "Puede mover 3 patas mientras las otras 3 mantienen estabilidad", "Usa menos motores", "Es más barato"], respuestaCorrecta: 1, explicacion: "¡Trípode alterno! Mueve 3 patas a la vez mientras las otras 3 dan soporte. Inspirado en insectos como cucarachas. 🐜" },
    { titulo: "✅ Quiz: Grados de Libertad", tipo: 'mini_quiz', pregunta: "¿Qué son los grados de libertad (DOF) en una pata robótica?", opciones: ["Los ángulos de giro", "El número de articulaciones independientes que puede mover", "La velocidad máxima", "El peso de la pata"], respuestaCorrecta: 1, explicacion: "Cada articulación con servo = 1 DOF. Una pata con 3 servos (cadera, rodilla, tobillo) tiene 3 DOF. 🦿" },
    { titulo: "✅❌ Locomoción: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un robot con orugas puede subir escaleras más fácilmente que uno con ruedas.', correct: true, explain: 'Las orugas distribuyen el peso y tienen tracción continua, ideal para escaleras.' }, { text: 'Todos los robots caminadores necesitan al menos 4 patas para moverse.', correct: false, explain: 'Existen robots bípedos (2 patas) e incluso monópodos (1 pata que salta).' }] },
    { titulo: "🧩 Terreno y Locomoción", tipo: 'matching_game', instruccion: 'Conecta el mejor tipo de locomoción para cada terreno', pairs: [{ left: '🏙️ Piso liso', right: 'Ruedas (rápidas y eficientes)' }, { left: '🏔️ Terreno rocoso', right: 'Patas (superan obstáculos)' }, { left: '🏖️ Arena/barro', right: 'Orugas (no se hunden)' }, { left: '🌊 Agua', right: 'Aletas o propulsión' }] },
  ],
  'w3_mod3_musculos_artificiales': [
    { titulo: "✅ Quiz: Músculos Artificiales", tipo: 'mini_quiz', pregunta: "¿Qué son los músculos artificiales en robótica?", opciones: ["Músculos humanos trasplantados", "Actuadores que imitan la contracción y expansión de músculos biológicos", "Motores comunes", "Solo existen en ciencia ficción"], respuestaCorrecta: 1, explicacion: "Son actuadores que se contraen como músculos reales. Más suaves y flexibles que los motores. 💪" },
    { titulo: "✅ Quiz: SMA", tipo: 'mini_quiz', pregunta: "¿Cómo funcionan los cables SMA (Shape Memory Alloy)?", opciones: ["Con imanes", "Se contraen al calentarse y vuelven a su forma original al enfriarse", "Con aire comprimido", "Con luz"], respuestaCorrecta: 1, explicacion: "Las aleaciones con memoria de forma (como Nitinol) recuerdan su forma. Al calentarlas con corriente, se contraen como un músculo. 🔥" },
    { titulo: "✅ Quiz: Neumático", tipo: 'mini_quiz', pregunta: "¿Qué tipo de músculo artificial usa aire comprimido para moverse?", opciones: ["SMA", "Músculo neumático (McKibben)", "Motor servo", "Electroimán"], respuestaCorrecta: 1, explicacion: "Los músculos neumáticos McKibben se inflan con aire y se acortan, imitando la contracción muscular. ¡Fuertes y ligeros! 💨" },
    { titulo: "✅ Quiz: DEA", tipo: 'mini_quiz', pregunta: "¿Qué son los actuadores de elastómero dieléctrico (DEA)?", opciones: ["Resortes", "Membranas que se deforman al aplicar voltaje eléctrico", "Cables magnéticos", "Motores pequeños"], respuestaCorrecta: 1, explicacion: "Los DEA son polímeros que cambian de forma con electricidad. ¡Músculos artificiales ultra-delgados y flexibles! ⚡" },
    { titulo: "✅ Quiz: Ventaja de Músculos Artificiales", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tienen los músculos artificiales sobre los motores tradicionales?", opciones: ["Son más baratos", "Son más flexibles, silenciosos y livianos, ideales para interacción con humanos", "Son más rápidos", "Usan menos energía"], respuestaCorrecta: 1, explicacion: "Los músculos artificiales hacen que los robots sean más suaves y seguros para interactuar con personas. ¡Robots amigables! 🤝" },
    { titulo: "✅❌ Músculos: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los músculos neumáticos pueden generar fuerzas comparables a un músculo humano de tamaño similar.', correct: true, explain: 'Los McKibben pueden generar fuerzas impresionantes para su tamaño y peso.' }, { text: 'Los músculos artificiales actuales ya son mejores que los músculos biológicos en todo.', correct: false, explain: 'Los biológicos aún superan en eficiencia energética, autorecuperación y control preciso.' }] },
    { titulo: "🧩 Tipos de Músculos Artificiales", tipo: 'matching_game', instruccion: 'Conecta cada tecnología con su principio', pairs: [{ left: 'SMA (Nitinol)', right: 'Memoria de forma con calor' }, { left: 'Neumático (McKibben)', right: 'Aire comprimido' }, { left: 'DEA', right: 'Voltaje en elastómero' }, { left: 'Hidráulico', right: 'Fluido presurizado' }] },
  ],
  'w3_mod4_sentidos_bio': [
    { titulo: "✅ Quiz: Biosensor", tipo: 'mini_quiz', pregunta: "¿Qué hace un biosensor en un robot?", opciones: ["Detecta robots", "Mide señales biológicas como pulso, temperatura corporal o sudoración", "Solo mide la batería", "Detecta metales"], respuestaCorrecta: 1, explicacion: "Los biosensores detectan señales del cuerpo humano. ¡Un robot puede saber si estás cansado o estresado! 💓" },
    { titulo: "✅ Quiz: Sensor de Pulso", tipo: 'mini_quiz', pregunta: "¿Cómo funciona un sensor de pulso cardíaco óptico?", opciones: ["Escucha el corazón", "Emite luz y mide cuánta se refleja; la sangre cambia la reflexión con cada latido", "Mide la presión", "Detecta electricidad"], respuestaCorrecta: 1, explicacion: "Un LED emite luz al dedo/muñeca. La hemoglobina absorbe más luz con cada latido. ¡Fotopletismografía! 💓💡" },
    { titulo: "✅ Quiz: EMG", tipo: 'mini_quiz', pregunta: "¿Qué tipo de señal detecta un sensor EMG?", opciones: ["Ondas de sonido", "Señales eléctricas de los músculos", "Luz infrarroja", "Señales WiFi"], respuestaCorrecta: 1, explicacion: "EMG = Electromiografía. Detecta las señales eléctricas que generan los músculos al contraerse. ¡Control muscular de robots! 💪⚡" },
    { titulo: "✅ Quiz: GSR", tipo: 'mini_quiz', pregunta: "Un sensor GSR (Respuesta Galvánica de la Piel) detecta:", opciones: ["Color de piel", "Nivel de sudoración (indica estrés o emociones)", "Temperatura del aire", "Movimiento"], respuestaCorrecta: 1, explicacion: "La piel cambia su conductividad con el sudor. Más estrés = más sudor = menos resistencia eléctrica. 😰" },
    { titulo: "✅ Quiz: Aplicación", tipo: 'mini_quiz', pregunta: "¿Cómo podría un robot usar datos de biosensores?", opciones: ["Para nada", "Adaptar su comportamiento al estado emocional/físico del usuario", "Solo para mostrar datos", "Para ir más rápido"], respuestaCorrecta: 1, explicacion: "Un robot podría ir más lento si detecta que el usuario está cansado, o alertar si el pulso es anormal. ¡Robótica empática! 🤖❤️" },
    { titulo: "✅❌ Biosensores: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un smartwatch usa biosensores para medir el pulso cardíaco.', correct: true, explain: 'Los smartwatches usan sensores ópticos de pulso (PPG) en la muñeca.' }, { text: 'Los biosensores pueden leer los pensamientos de las personas.', correct: false, explain: 'Los biosensores miden señales físicas (pulso, sudor, temperatura). No leen pensamientos.' }] },
    { titulo: "🧩 Biosensores y Señales", tipo: 'matching_game', instruccion: 'Conecta cada biosensor con lo que mide', pairs: [{ left: 'Sensor PPG', right: 'Pulso cardíaco' }, { left: 'Sensor EMG', right: 'Actividad muscular' }, { left: 'Sensor GSR', right: 'Nivel de estrés/sudor' }, { left: 'Termistor corporal', right: 'Temperatura del cuerpo' }] },
  ],
  'w3_mod5_protesis_intro': [
    { titulo: "✅ Quiz: Prótesis Biónica", tipo: 'mini_quiz', pregunta: "¿Qué diferencia una prótesis biónica de una prótesis pasiva?", opciones: ["El color", "La biónica tiene sensores y actuadores que permiten movimiento activo", "El material", "El tamaño"], respuestaCorrecta: 1, explicacion: "Las prótesis biónicas detectan señales musculares (EMG) y mueven dedos/articulaciones con motores. ¡Manos que responden al pensamiento! 🦾" },
    { titulo: "✅ Quiz: Control EMG", tipo: 'mini_quiz', pregunta: "¿Cómo controla una persona su prótesis biónica de mano?", opciones: ["Con la mente directamente", "Contrayendo músculos del muñón que envían señales EMG a la prótesis", "Con un control remoto", "Con la voz"], respuestaCorrecta: 1, explicacion: "Electrodos en el muñón detectan cuándo el usuario contrae músculos. Cada contracción activa un movimiento de la mano. 💪🤖" },
    { titulo: "✅ Quiz: Retroalimentación", tipo: 'mini_quiz', pregunta: "¿Por qué es importante que una prótesis dé retroalimentación sensorial al usuario?", opciones: ["Solo por estética", "Para que el usuario sienta presión/temperatura y no aplaste objetos", "No es importante", "Para hacer ruido"], respuestaCorrecta: 1, explicacion: "Sin retroalimentación, el usuario puede aplastar un vaso o soltar objetos. ¡Los sensores de presión devuelven el sentido del tacto! 🤚" },
    { titulo: "✅ Quiz: Impresión 3D", tipo: 'mini_quiz', pregunta: "¿Cómo ha revolucionado la impresión 3D el campo de las prótesis?", opciones: ["No ha cambiado nada", "Ha reducido el costo de miles de dólares a cientos, haciéndolas accesibles", "Solo cambia el color", "Las hace más pesadas"], respuestaCorrecta: 1, explicacion: "¡De $50,000 a $50! Proyectos como e-NABLE crean prótesis 3D funcionales para niños que crecen rápidamente. 🖨️" },
    { titulo: "✅ Quiz: Open Bionics", tipo: 'mini_quiz', pregunta: "¿Qué es el proyecto Open Bionics Hero Arm?", opciones: ["Un videojuego", "Una prótesis biónica accesible diseñada para ser atractiva para niños", "Un robot industrial", "Una app"], respuestaCorrecta: 1, explicacion: "Hero Arm es una prótesis multifuncional con diseños de superhéroes. ¡Los niños se sienten empoderados, no limitados! 🦸" },
    { titulo: "✅❌ Prótesis: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Existen prótesis de pierna que permiten correr e incluso competir en deportes.', correct: true, explain: 'Las prótesis blade (como las de Oscar Pistorius) permiten sprint. ¡Atletas paralímpicos compiten al más alto nivel!' }, { text: 'Las prótesis biónicas actuales restauran el 100% de la funcionalidad de un miembro natural.', correct: false, explain: 'Aunque avanzan mucho, aún no igualan la precisión, fuerza y sensibilidad de un miembro natural.' }] },
    { titulo: "🧩 Tipos de Prótesis", tipo: 'matching_game', instruccion: 'Conecta cada tipo de prótesis con su característica', pairs: [{ left: 'Prótesis pasiva', right: 'Solo estética, sin movimiento' }, { left: 'Prótesis mecánica', right: 'Movimiento por cables/poleas' }, { left: 'Prótesis mioeléctrica', right: 'Control por señales EMG' }, { left: 'Prótesis 3D', right: 'Bajo costo y personalizable' }] },
  ],
  'w3_mod6_exoesqueletos': [
    { titulo: "✅ Quiz: Exoesqueleto", tipo: 'mini_quiz', pregunta: "¿Qué es un exoesqueleto robótico?", opciones: ["Un disfraz de robot", "Una estructura externa motorizada que aumenta la fuerza o movilidad del usuario", "Un esqueleto artificial interno", "Un casco de protección"], respuestaCorrecta: 1, explicacion: "Un exoesqueleto se coloca SOBRE el cuerpo y amplifica los movimientos. ¡Como una armadura de Iron Man! 🦾" },
    { titulo: "✅ Quiz: Aplicación Médica", tipo: 'mini_quiz', pregunta: "¿Cómo ayuda un exoesqueleto a personas con parálisis?", opciones: ["Les da superpoderes", "Les permite ponerse de pie y caminar con asistencia robótica", "No puede ayudar", "Solo es para ejercicio"], respuestaCorrecta: 1, explicacion: "Exoesqueletos como ReWalk y Ekso permiten que personas con lesión medular se pongan de pie y caminen. ¡Tecnología que cambia vidas! 🚶" },
    { titulo: "✅ Quiz: Industrial", tipo: 'mini_quiz', pregunta: "¿Para qué se usan exoesqueletos en fábricas?", opciones: ["Para decoración", "Para reducir la fatiga y lesiones al levantar objetos pesados", "Para reemplazar trabajadores", "No se usan"], respuestaCorrecta: 1, explicacion: "Los exoesqueletos industriales soportan parte del peso, reduciendo lesiones de espalda hasta un 60%. ¡Protección laboral! 🏭" },
    { titulo: "✅ Quiz: Sensores del Exo", tipo: 'mini_quiz', pregunta: "¿Qué sensores necesita un exoesqueleto para funcionar correctamente?", opciones: ["Solo cámaras", "IMU (movimiento), encoders (posición) y sensores de fuerza (interacción)", "Solo GPS", "Ningún sensor"], respuestaCorrecta: 1, explicacion: "Múltiples sensores detectan la intención del usuario: IMU mide inclinación, encoders la posición de las articulaciones, y sensores de fuerza la presión del usuario. 📡" },
    { titulo: "✅ Quiz: Retos del Exo", tipo: 'mini_quiz', pregunta: "¿Cuál es el mayor reto actual de los exoesqueletos?", opciones: ["El color", "La duración de la batería y el peso del dispositivo", "El ruido", "El precio de la pintura"], respuestaCorrecta: 1, explicacion: "Los motores potentes necesitan mucha energía, y la estructura debe ser fuerte pero ligera. ¡Balance peso-potencia-autonomía! ⚖️" },
    { titulo: "✅❌ Exoesqueletos: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los exoesqueletos militares pueden permitir a los soldados cargar hasta 90 kg sin fatiga.', correct: true, explain: 'Proyectos como HULC (Lockheed Martin) permiten cargar peso extremo sin esfuerzo del usuario.' }, { text: 'Un exoesqueleto puede funcionar indefinidamente sin recargar.', correct: false, explain: 'La autonomía actual es limitada (2-8 horas). La batería es una de las mayores limitaciones.' }] },
    { titulo: "🧩 Exoesqueletos por Uso", tipo: 'matching_game', instruccion: 'Conecta cada exoesqueleto con su aplicación', pairs: [{ left: 'ReWalk', right: 'Rehabilitación de parálisis' }, { left: 'HULC', right: 'Militar: cargar peso' }, { left: 'EksoVest', right: 'Industrial: reducir fatiga' }, { left: 'HAL', right: 'Asistencia de movilidad' }] },
    { titulo: "✅ Quiz: Grados de Asistencia", tipo: 'mini_quiz', pregunta: "¿Qué significa un exoesqueleto de asistencia parcial?", opciones: ["No funciona", "Amplifica el movimiento del usuario sin reemplazarlo completamente", "Reemplaza las piernas", "Solo protege"], respuestaCorrecta: 1, explicacion: "Asistencia parcial = el usuario mueve las piernas y el exo amplifica. Asistencia total = el exo hace todo el movimiento. 🦿" },
  ],
  'w3_mod7_wearables': [
    { titulo: "✅ Quiz: Wearable", tipo: 'mini_quiz', pregunta: "¿Qué es un dispositivo wearable?", opciones: ["Un robot grande", "Tecnología electrónica que se lleva puesta en el cuerpo", "Un celular normal", "Una computadora de escritorio"], respuestaCorrecta: 1, explicacion: "Wearables: smartwatches, bandas fitness, lentes inteligentes, ropa con sensores. ¡Tecnología que vistes! ⌚" },
    { titulo: "✅ Quiz: Acelerómetro", tipo: 'mini_quiz', pregunta: "¿Qué mide el acelerómetro en un smartwatch?", opciones: ["La presión del aire", "El movimiento y la orientación en 3 ejes (X, Y, Z)", "La temperatura", "El pulso"], respuestaCorrecta: 1, explicacion: "El acelerómetro detecta movimiento en 3D. Así cuenta pasos, detecta caídas y sabe si estás acostado o de pie. 📱" },
    { titulo: "✅ Quiz: Arduino Wearable", tipo: 'mini_quiz', pregunta: "¿Qué placa Arduino está diseñada específicamente para proyectos wearable?", opciones: ["Arduino Mega", "Arduino LilyPad", "Arduino UNO", "Arduino Due"], respuestaCorrecta: 1, explicacion: "LilyPad es circular, plana y cosible con hilo conductor. ¡Perfecta para integrar electrónica en ropa! 🧶" },
    { titulo: "✅ Quiz: Hilo Conductor", tipo: 'mini_quiz', pregunta: "¿Qué es el hilo conductor en wearables?", opciones: ["Hilo normal de algodón", "Hilo que contiene fibras metálicas y conduce electricidad", "Cable de cobre", "Lana"], respuestaCorrecta: 1, explicacion: "Hilo con fibras de acero inoxidable que se puede coser normalmente pero conduce electricidad. ¡Circuitos cosidos! 🧵⚡" },
    { titulo: "✅ Quiz: IoT Wearable", tipo: 'mini_quiz', pregunta: "¿Cómo se conectan la mayoría de wearables al celular?", opciones: ["Cable USB", "Bluetooth Low Energy (BLE)", "WiFi", "Infrarrojos"], respuestaCorrecta: 1, explicacion: "BLE consume muy poca energía, perfecto para dispositivos pequeños con batería limitada. ¡Conexión eficiente! 📶" },
    { titulo: "✅❌ Wearables: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los LEDs cosibles (flora NeoPixel) pueden integrarse en ropa con hilo conductor.', correct: true, explain: 'Los LEDs tipo Flora tienen agujeros para coser y funcionan con hilo conductor. ¡Ropa LED!' }, { text: 'Los wearables solo sirven para fitness y salud.', correct: false, explain: 'También se usan en moda, seguridad, navegación, realidad aumentada y muchas áreas más.' }] },
    { titulo: "🧩 Sensores Wearable", tipo: 'matching_game', instruccion: 'Conecta cada sensor con lo que detecta en un wearable', pairs: [{ left: 'Acelerómetro', right: 'Pasos y movimiento' }, { left: 'Giroscopio', right: 'Rotación y orientación' }, { left: 'PPG (óptico)', right: 'Pulso cardíaco' }, { left: 'Sensor UV', right: 'Exposición solar' }] },
  ],
  'w3_mod8_interfaz_cerebro': [
    { titulo: "✅ Quiz: BCI", tipo: 'mini_quiz', pregunta: "¿Qué es una BCI (Interfaz Cerebro-Computadora)?", opciones: ["Un chip en el cerebro", "Un sistema que traduce señales cerebrales en comandos para controlar dispositivos", "Un tipo de pantalla", "Una red de computadoras"], respuestaCorrecta: 1, explicacion: "BCI lee las ondas cerebrales (EEG) y las convierte en acciones: mover un cursor, un brazo robótico o una silla de ruedas. 🧠💻" },
    { titulo: "✅ Quiz: EEG", tipo: 'mini_quiz', pregunta: "¿Qué es un EEG en el contexto de las BCI?", opciones: ["Un tipo de motor", "Un electroencefalograma que mide la actividad eléctrica del cerebro", "Una batería", "Un protocolo de internet"], respuestaCorrecta: 1, explicacion: "EEG usa electrodos en el cuero cabelludo para detectar ondas cerebrales. ¡No invasivo y accesible! 🧠📊" },
    { titulo: "✅ Quiz: Ondas Cerebrales", tipo: 'mini_quiz', pregunta: "¿Qué tipo de ondas cerebrales se asocian con la concentración?", opciones: ["Delta (sueño profundo)", "Beta (concentración activa)", "Theta (somnolencia)", "No tiene ondas"], respuestaCorrecta: 1, explicacion: "Beta (13-30 Hz) = concentración. Alpha (8-13 Hz) = relajación. Delta (<4 Hz) = sueño profundo. ¡Cada estado mental tiene su onda! 🌊" },
    { titulo: "✅ Quiz: Neuralink", tipo: 'mini_quiz', pregunta: "¿Qué tipo de BCI es Neuralink de Elon Musk?", opciones: ["No invasivo (usa gorra)", "Invasivo (implante cerebral con electrodos)", "Solo software", "Un videojuego"], respuestaCorrecta: 1, explicacion: "Neuralink implanta chips con miles de electrodos directamente en el cerebro, logrando señales mucho más precisas que el EEG. 🧠🔌" },
    { titulo: "✅ Quiz: Aplicación BCI", tipo: 'mini_quiz', pregunta: "¿Cómo puede una BCI ayudar a una persona con parálisis total?", opciones: ["No puede ayudar", "Permitiéndole controlar una computadora, silla de ruedas o brazo robótico con el pensamiento", "Solo mide ondas", "Solo para investigación"], respuestaCorrecta: 1, explicacion: "¡Libertad a través del pensamiento! Personas con ELA o tetraplejia pueden comunicarse y controlar dispositivos con BCIs. 🎯" },
    { titulo: "✅❌ BCI: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El EEG puede detectar si una persona está concentrada, relajada o dormida.', correct: true, explain: 'Diferentes estados mentales producen ondas cerebrales con frecuencias distintas y detectables.' }, { text: 'Las BCI actuales pueden leer pensamientos específicos como palabras o imágenes.', correct: false, explain: 'Las BCI actuales detectan patrones generales (concentración, imaginación motora), no pensamientos específicos.' }] },
    { titulo: "🧩 Tipos de BCI", tipo: 'matching_game', instruccion: 'Conecta cada tipo de BCI con su método', pairs: [{ left: 'EEG (no invasivo)', right: 'Electrodos en el cuero cabelludo' }, { left: 'ECoG (semi-invasivo)', right: 'Electrodos sobre la corteza' }, { left: 'Implante (invasivo)', right: 'Electrodos dentro del cerebro' }, { left: 'fNIRS', right: 'Luz infrarroja en la cabeza' }] },
  ],
  'w3_mod9_robots_blandos': [
    { titulo: "✅ Quiz: Soft Robot", tipo: 'mini_quiz', pregunta: "¿Qué es un soft robot (robot blando)?", opciones: ["Un robot de peluche", "Un robot hecho de materiales flexibles/deformables, sin estructura rígida", "Un robot pequeño", "Un robot lento"], respuestaCorrecta: 1, explicacion: "Los soft robots usan silicona, elastómeros y materiales flexibles en vez de metal. ¡Se deforman y adaptan como un pulpo! 🐙" },
    { titulo: "✅ Quiz: Material Principal", tipo: 'mini_quiz', pregunta: "¿Cuál es el material más usado para fabricar soft robots?", opciones: ["Acero", "Silicona y elastómeros", "Madera", "Vidrio"], respuestaCorrecta: 1, explicacion: "La silicona es flexible, biocompatible y se puede moldear en formas complejas con canales internos para actuación neumática. 🧪" },
    { titulo: "✅ Quiz: Actuación Neumática", tipo: 'mini_quiz', pregunta: "¿Cómo se mueve un tentáculo de soft robot?", opciones: ["Con motores internos", "Inflando y desinflando cámaras de aire dentro del material flexible", "Con imanes", "Con cables"], respuestaCorrecta: 1, explicacion: "Al inflar diferentes cámaras, el tentáculo se curva en distintas direcciones. ¡Como los tentáculos del pulpo! 🐙💨" },
    { titulo: "✅ Quiz: Ventaja Principal", tipo: 'mini_quiz', pregunta: "¿Por qué los soft robots son más seguros para interactuar con humanos?", opciones: ["Son más lentos", "No tienen bordes duros ni partes rígidas que puedan causar lesiones", "Son más caros", "Son más pequeños"], respuestaCorrecta: 1, explicacion: "Al ser blandos, pueden tocar personas y objetos delicados sin hacer daño. ¡Ideales para medicina y rescate! 🤝" },
    { titulo: "✅ Quiz: Aplicaciones", tipo: 'mini_quiz', pregunta: "¿En qué campo son especialmente útiles los soft robots?", opciones: ["Construcción pesada", "Cirugía minimamente invasiva y manipulación de objetos frágiles", "Minería", "Solo en laboratorios"], respuestaCorrecta: 1, explicacion: "En cirugía, pueden navegar por el cuerpo sin dañar tejidos. También pueden agarrar frutas sin aplastarlas. 🍓🏥" },
    { titulo: "✅❌ Soft Robots: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Un soft robot puede cambiar de forma para pasar por espacios estrechos.', correct: true, explain: 'Al ser deformables, pueden comprimirse y adaptarse a espacios reducidos, como en rescate.' }, { text: 'Los soft robots son tan precisos como los brazos robóticos industriales rígidos.', correct: false, explain: 'La flexibilidad dificulta el control preciso. Los robots rígidos son más precisos pero menos adaptables.' }] },
    { titulo: "🧩 Soft vs Rigid Robots", tipo: 'matching_game', instruccion: 'Conecta cada característica con el tipo de robot', pairs: [{ left: 'Manipular objetos frágiles', right: 'Soft robot (flexible)' }, { left: 'Ensamblar piezas con precisión', right: 'Robot rígido' }, { left: 'Adaptarse a formas desconocidas', right: 'Soft robot (flexible)' }, { left: 'Alta velocidad y repetibilidad', right: 'Robot rígido' }] },
  ],
  'w3_mod10_bioimpresion': [
    { titulo: "✅ Quiz: Bioimpresión", tipo: 'mini_quiz', pregunta: "¿Qué es la bioimpresión 3D?", opciones: ["Imprimir fotos de animales", "Imprimir estructuras usando células vivas y biomateriales capa por capa", "Imprimir robots de plástico", "Escanear organismos"], respuestaCorrecta: 1, explicacion: "La bioimpresión usa bio-tintas (células + hidrogel) para crear tejidos vivos capa por capa. ¡Hacia órganos artificiales! 🧬🖨️" },
    { titulo: "✅ Quiz: Bio-tinta", tipo: 'mini_quiz', pregunta: "¿Qué contiene una bio-tinta para bioimpresión?", opciones: ["Plástico y metal", "Células vivas mezcladas con un gel biocompatible (hidrogel)", "Tinta de impresora normal", "Solo agua"], respuestaCorrecta: 1, explicacion: "La bio-tinta es una mezcla de células vivas + hidrogel que las mantiene vivas y en su lugar durante la impresión. 🧫" },
    { titulo: "✅ Quiz: Aplicación Actual", tipo: 'mini_quiz', pregunta: "¿Qué ya se ha logrado bioimprimir exitosamente?", opciones: ["Cerebros completos", "Tejido de piel, cartílago y vasos sanguíneos", "Corazones funcionales completos", "Huesos enteros"], respuestaCorrecta: 1, explicacion: "Ya se bioimprimen parches de piel para quemaduras, cartílago para orejas y vasos sanguíneos. ¡Órganos completos aún están en investigación! 🧬" },
    { titulo: "✅ Quiz: Robot Bioimpresora", tipo: 'mini_quiz', pregunta: "¿Qué tipo de robot se usa como bioimpresora?", opciones: ["Un robot caminador", "Un robot cartesiano o delta con jeringa de precisión", "Un dron", "Un robot submarino"], respuestaCorrecta: 1, explicacion: "La bioimpresora es un robot de posicionamiento preciso (como una impresora 3D) con una jeringa que deposita bio-tinta con precisión micrométrica. 🤖🔬" },
    { titulo: "✅ Quiz: Desafíos", tipo: 'mini_quiz', pregunta: "¿Cuál es el mayor reto de la bioimpresión actualmente?", opciones: ["El color de los tejidos", "Mantener las células vivas y crear redes de vasos sanguíneos dentro del tejido", "La velocidad de impresión", "El costo del papel"], respuestaCorrecta: 1, explicacion: "Sin vasos sanguíneos, las células internas no reciben nutrientes y mueren. ¡La vascularización es el gran reto! 🩸" },
    { titulo: "✅❌ Bioimpresión: ¿V o F?", tipo: 'true_false', statements: [{ text: 'La bioimpresión podría eliminar las listas de espera para trasplantes de órganos en el futuro.', correct: true, explain: 'El objetivo final es imprimir órganos personalizados para cada paciente. ¡Sin rechazo y sin espera!' }, { text: 'Ya se pueden bioimprimir órganos completos funcionales como riñones o hígados.', correct: false, explain: 'Aún no. Se imprimen tejidos simples. Los órganos completos con toda su complejidad siguen en investigación.' }] },
    { titulo: "🧩 Bioimpresión 3D", tipo: 'matching_game', instruccion: 'Conecta cada elemento con su función en bioimpresión', pairs: [{ left: 'Bio-tinta', right: 'Material con células vivas' }, { left: 'Hidrogel', right: 'Soporte que mantiene las células' }, { left: 'Bioimpresora (robot)', right: 'Deposita bio-tinta con precisión' }, { left: 'Biorreactor', right: 'Incuba el tejido impreso' }] },
  ],
  'w3_mod11_ecosistemas': [
    { titulo: "✅ Quiz: Robot Ecológico", tipo: 'mini_quiz', pregunta: "¿Cómo pueden los robots ayudar a proteger ecosistemas?", opciones: ["Destruyendo hábitats", "Monitoreando fauna, plantando árboles y limpiando contaminación", "No pueden ayudar", "Solo con fotografías"], respuestaCorrecta: 1, explicacion: "Drones monitores de fauna, robots plantadores de manglares, robots limpiadores de océanos. ¡Tecnología verde! 🌱🤖" },
    { titulo: "✅ Quiz: Dron Ambiental", tipo: 'mini_quiz', pregunta: "¿Cómo ayuda un dron a los ecólogos?", opciones: ["Cazando animales", "Haciendo censos de fauna, mapeando bosques y detectando incendios", "Solo para fotos bonitas", "Repartiendo comida"], respuestaCorrecta: 1, explicacion: "Los drones cuentan animales, miden la salud de bosques con cámaras multiespectrales y detectan incendios temprano. 🦜📸" },
    { titulo: "✅ Quiz: Robot Submarino", tipo: 'mini_quiz', pregunta: "¿Para qué se usan robots submarinos (ROV) en conservación?", opciones: ["Para pescar", "Para explorar fondos marinos, estudiar arrecifes y limpiar basura", "Solo para turismo", "Para mover corales"], respuestaCorrecta: 1, explicacion: "ROVs documentan arrecifes de coral, rastrean poblaciones de peces y recolectan muestras sin dañar el ecosistema. 🐠🤖" },
    { titulo: "✅ Quiz: Sensor Ambiental IoT", tipo: 'mini_quiz', pregunta: "¿Qué parámetros mide una estación ambiental robótica?", opciones: ["Solo temperatura", "Temperatura, humedad, CO2, calidad del aire, nivel de agua y más", "Solo luz", "Solo sonido"], respuestaCorrecta: 1, explicacion: "Las estaciones IoT miden múltiples variables y envían datos a la nube 24/7. ¡Monitoreo ambiental continuo! 📊🌍" },
    { titulo: "✅ Quiz: Reforestación Robótica", tipo: 'mini_quiz', pregunta: "¿Cómo funciona un dron de reforestación?", opciones: ["Tala árboles", "Lanza cápsulas de semillas sobre áreas deforestadas desde el aire", "Riega con lluvia artificial", "Transporta árboles adultos"], respuestaCorrecta: 1, explicacion: "Los drones de BioCarbon Engineering lanzan cápsulas biodegradables con semillas y nutrientes. ¡1 dron puede plantar 10,000 árboles/día! 🌳✈️" },
    { titulo: "✅❌ Robots y Ecosistemas: ¿V o F?", tipo: 'true_false', statements: [{ text: 'El robot SeaBin puede recolectar hasta 1.5 kg de basura marina por día.', correct: true, explain: 'SeaBin es una papelera flotante robótica que filtra basura, microplásticos y aceite del agua.' }, { text: 'Los robots pueden reemplazar completamente a los ecólogos humanos.', correct: false, explain: 'Los robots son herramientas que amplifican la capacidad de los ecólogos, no los reemplazan.' }] },
    { titulo: "🧩 Robots Ambientales", tipo: 'matching_game', instruccion: 'Conecta cada robot con su función ambiental', pairs: [{ left: 'Dron con cámara térmica', right: 'Detectar incendios forestales' }, { left: 'ROV submarino', right: 'Monitorear arrecifes de coral' }, { left: 'Robot plantador', right: 'Reforestación automatizada' }, { left: 'SeaBin', right: 'Limpiar basura marina' }] },
  ],
  'w3_mod12_enjambres': [
    { titulo: "✅ Quiz: Robótica de Enjambre", tipo: 'mini_quiz', pregunta: "¿Qué es la robótica de enjambre (swarm robotics)?", opciones: ["Un solo robot muy grande", "Muchos robots simples que cooperan para lograr tareas complejas", "Robots que atacan en grupo", "Robots de colección"], respuestaCorrecta: 1, explicacion: "¡Como hormigas o abejas! Cada robot es simple, pero juntos logran cosas complejas: buscar, transportar, construir. 🐜🤖" },
    { titulo: "✅ Quiz: Reglas Locales", tipo: 'mini_quiz', pregunta: "¿Cómo coordinan su comportamiento los robots de enjambre?", opciones: ["Un líder central da órdenes", "Cada robot sigue reglas locales simples y el comportamiento colectivo emerge", "Por internet", "No se coordinan"], respuestaCorrecta: 1, explicacion: "Sin líder central. Cada robot solo sabe de sus vecinos cercanos. ¡El comportamiento inteligente emerge de interacciones simples! 🧠" },
    { titulo: "✅ Quiz: Inspiración Natural", tipo: 'mini_quiz', pregunta: "¿Qué animal inspira más la robótica de enjambre?", opciones: ["El águila", "Las hormigas (colonias organizadas sin líder central)", "El león", "El elefante"], respuestaCorrecta: 1, explicacion: "Las hormigas encuentran caminos óptimos, transportan cargas enormes y construyen estructuras complejas. ¡Todo con reglas simples! 🐜" },
    { titulo: "✅ Quiz: Tolerancia a Fallos", tipo: 'mini_quiz', pregunta: "¿Qué pasa si un robot del enjambre se rompe?", opciones: ["Todo el enjambre falla", "Los demás continúan la tarea, el sistema es tolerante a fallos", "Hay que reprogramar todo", "Los otros se detienen"], respuestaCorrecta: 1, explicacion: "¡Resiliencia! Como en una colonia de hormigas, si algunas mueren, la colonia sigue funcionando. No hay punto único de fallo. 💪" },
    { titulo: "✅ Quiz: Aplicaciones", tipo: 'mini_quiz', pregunta: "¿En qué situación sería ideal usar robots de enjambre?", opciones: ["Lavar platos", "Buscar supervivientes en un área grande de desastre", "Cocinar", "Pintar una pared"], respuestaCorrecta: 1, explicacion: "¡Búsqueda y rescate! 100 drones pequeños pueden cubrir un área enorme simultáneamente, encontrando víctimas mucho más rápido que 1 robot grande. 🚁🔍" },
    { titulo: "✅❌ Enjambre: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los robots de enjambre son más baratos individualmente que un solo robot complejo.', correct: true, explain: 'Cada robot del enjambre es simple y barato. La inteligencia viene de la cantidad y cooperación.' }, { text: 'Los robots de enjambre necesitan un computador central potente para coordinarse.', correct: false, explain: 'No hay control centralizado. Cada robot toma decisiones locales basadas en sus sensores y vecinos.' }] },
    { titulo: "🧩 Conceptos de Enjambre", tipo: 'matching_game', instruccion: 'Conecta cada concepto con su significado', pairs: [{ left: 'Emergencia', right: 'Comportamiento complejo de reglas simples' }, { left: 'Estigmergia', right: 'Comunicación indirecta por el ambiente' }, { left: 'Escalabilidad', right: 'Funciona con 10 o 10,000 robots' }, { left: 'Resiliencia', right: 'Tolerancia a fallos individuales' }] },
  ],
  'w3_mod13_micro_robots': [
    { titulo: "✅ Quiz: Micro Robot", tipo: 'mini_quiz', pregunta: "¿Qué tamaño tiene un micro robot?", opciones: ["1 metro", "Milímetros a centímetros", "10 metros", "100 metros"], respuestaCorrecta: 1, explicacion: "Los micro robots miden milímetros a pocos centímetros. Los nano robots serían del tamaño de moléculas (nanómetros). ¡Diminutos! 🔬" },
    { titulo: "✅ Quiz: Aplicación Médica", tipo: 'mini_quiz', pregunta: "¿Cómo podrían los nano robots revolucionar la medicina?", opciones: ["Siendo doctores diminutos", "Navegando por el cuerpo para entregar medicamentos directamente a las células enfermas", "Reemplazando hospitales", "Solo para investigación"], respuestaCorrecta: 1, explicacion: "¡Nanomedicina! Robots microscópicos que atacan células cancerosas directamente, sin dañar las sanas. ¡Tratamiento de precisión! 💊🔬" },
    { titulo: "✅ Quiz: Propulsión", tipo: 'mini_quiz', pregunta: "¿Cómo se propulsan los micro robots dentro del cuerpo?", opciones: ["Con motores diesel", "Con campos magnéticos externos, flagelos artificiales o reacciones químicas", "Con baterías", "Con WiFi"], respuestaCorrecta: 1, explicacion: "¡Sin baterías! Los campos magnéticos externos los guían, los flagelos los impulsan, y las reacciones químicas generan movimiento. 🧲" },
    { titulo: "✅ Quiz: MEMS", tipo: 'mini_quiz', pregunta: "¿Qué son los MEMS en el contexto de micro robótica?", opciones: ["Un tipo de motor", "Sistemas micro-electromecánicos: sensores y actuadores microscópicos", "Una marca de robot", "Un software"], respuestaCorrecta: 1, explicacion: "MEMS = Micro Electro-Mechanical Systems. El acelerómetro de tu celular es un MEMS. ¡Máquinas microscópicas! 📱🔬" },
    { titulo: "✅ Quiz: Retos", tipo: 'mini_quiz', pregunta: "¿Cuál es un gran reto de los micro/nano robots?", opciones: ["Son muy caros", "Energía: no pueden llevar baterías y son difíciles de rastrear dentro del cuerpo", "Son muy ruidosos", "Se oxidan"], respuestaCorrecta: 1, explicacion: "A escala nano no hay baterías. La energía viene del exterior (magnética, ultrasónica) y el rastreo es difícil. ¡Retos miniatura! 🔋🔬" },
    { titulo: "✅❌ Micro/Nano: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Ya existen micro robots experimentales que pueden nadar dentro de vasos sanguíneos.', correct: true, explain: 'Investigadores han creado micro robots de tamaño celular que navegan por fluidos corporales con campos magnéticos.' }, { text: 'Los nano robots ya se usan rutinariamente en hospitales.', correct: false, explain: 'Aún están en fase de investigación. Los ensayos clínicos en humanos apenas están comenzando.' }] },
    { titulo: "🧩 Escalas de Robot", tipo: 'matching_game', instruccion: 'Conecta cada escala con su aplicación típica', pairs: [{ left: 'Nano (nm)', right: 'Entregar medicamentos a células' }, { left: 'Micro (mm)', right: 'Cirugía mínimamente invasiva' }, { left: 'Mini (cm)', right: 'Inspección de tuberías' }, { left: 'Macro (m)', right: 'Robots industriales' }] },
  ],
  'w3_mod14_bioetica': [
    { titulo: "✅ Quiz: Bioética Robótica", tipo: 'mini_quiz', pregunta: "¿Qué estudia la bioética en robótica?", opciones: ["Los circuitos", "Las implicaciones morales de crear tecnología que interactúa con el cuerpo humano", "Solo los costos", "La velocidad de los robots"], respuestaCorrecta: 1, explicacion: "La bioética pregunta: ¿es correcto implantar chips? ¿quién controla los datos corporales? ¿dónde está el límite humano-máquina? 🤔" },
    { titulo: "✅ Quiz: Privacidad de Datos", tipo: 'mini_quiz', pregunta: "¿Por qué son sensibles los datos que recolectan biosensores y prótesis biónicas?", opciones: ["No son sensibles", "Son datos íntimos sobre la salud y el cuerpo de la persona", "Solo son números", "Son públicos"], respuestaCorrecta: 1, explicacion: "Tu pulso, actividad cerebral y datos de salud son extremadamente personales. ¿Quién tiene acceso? ¿Se pueden vender? ¡Privacidad crítica! 🔒" },
    { titulo: "✅ Quiz: Transhumanismo", tipo: 'mini_quiz', pregunta: "¿Qué es el transhumanismo?", opciones: ["Una religión", "La idea de mejorar las capacidades humanas con tecnología más allá de lo natural", "Un deporte", "Un tipo de motor"], respuestaCorrecta: 1, explicacion: "El transhumanismo propone usar tecnología para superar límites humanos. ¿Es ético tener visión nocturna o fuerza sobrehumana? 🤖🧬" },
    { titulo: "✅ Quiz: Accesibilidad", tipo: 'mini_quiz', pregunta: "¿Cuál es un dilema ético sobre prótesis biónicas avanzadas?", opciones: ["Son feas", "Solo los ricos pueden pagarlas, creando desigualdad tecnológica", "Son demasiado livianas", "No son útiles"], respuestaCorrecta: 1, explicacion: "Si las prótesis biónicas cuestan $100,000, solo los ricos las tendrán. ¿Debería la tecnología ser accesible para todos? ¡Justicia social! ⚖️" },
    { titulo: "✅ Quiz: Regulación", tipo: 'mini_quiz', pregunta: "¿Por qué se necesitan leyes que regulen los implantes robóticos?", opciones: ["Para vender más", "Para proteger a las personas de riesgos médicos, privacidad y mal uso", "No se necesitan", "Para hacer propaganda"], respuestaCorrecta: 1, explicacion: "Sin regulación, cualquiera podría vender un implante peligroso o hackeable. ¡Las leyes protegen al usuario! 📋" },
    { titulo: "✅❌ Bioética: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Una prótesis conectada a internet podría ser hackeada.', correct: true, explain: 'Todo dispositivo conectado tiene riesgo de ciberseguridad. Un implante hackeado podría ser peligroso.' }, { text: 'La bioética busca prohibir toda la tecnología biónica.', correct: false, explain: 'La bioética no prohíbe: guía el desarrollo tecnológico para que sea seguro, justo y ético.' }] },
    { titulo: "🧩 Dilemas Bioéticos", tipo: 'matching_game', instruccion: 'Conecta cada dilema con su área ética', pairs: [{ left: '¿Quién accede a los datos de tu implante?', right: 'Privacidad' }, { left: '¿Solo los ricos tendrán prótesis avanzadas?', right: 'Justicia social' }, { left: '¿Hasta dónde es ético mejorar el cuerpo?', right: 'Límites del transhumanismo' }, { left: '¿Quién es responsable si falla un implante?', right: 'Responsabilidad legal' }] },
  ],
  'w3_mod15_diseno_bio': [
    { titulo: "✅ Quiz: Bio-diseño", tipo: 'mini_quiz', pregunta: "¿Qué es el bio-diseño en robótica?", opciones: ["Pintar robots de verde", "Diseñar robots integrando principios biológicos desde la concepción", "Construir robots con madera", "Diseño solo estético"], respuestaCorrecta: 1, explicacion: "Bio-diseño no es solo imitar la forma: es integrar principios de la biología en cada aspecto del diseño del robot. 🌿🤖" },
    { titulo: "✅ Quiz: Diseño Generativo", tipo: 'mini_quiz', pregunta: "¿Qué es el diseño generativo inspirado en la naturaleza?", opciones: ["Diseñar a mano", "Usar algoritmos que imitan la evolución para encontrar la mejor estructura", "Copiar diseños existentes", "Diseño aleatorio"], respuestaCorrecta: 1, explicacion: "Los algoritmos genéticos evolucionan miles de diseños y seleccionan los mejores. ¡Evolución digital! 🧬💻" },
    { titulo: "✅ Quiz: Materiales Biodegradables", tipo: 'mini_quiz', pregunta: "¿Por qué son importantes los materiales biodegradables en robótica?", opciones: ["Son más bonitos", "Para que los robots no generen basura electrónica al final de su vida útil", "Son más baratos", "Son más fuertes"], respuestaCorrecta: 1, explicacion: "Robots que se biodegradan después de cumplir su misión (ej: robots agrícolas) no contaminan. ¡Robótica sostenible! ♻️" },
    { titulo: "✅ Quiz: Proceso de Bio-diseño", tipo: 'mini_quiz', pregunta: "¿Cuál es el primer paso del proceso de bio-diseño?", opciones: ["Construir el robot", "Estudiar el organismo biológico que se quiere imitar y entender sus principios", "Programar", "Comprar materiales"], respuestaCorrecta: 1, explicacion: "Primero observa y entiende la biología: ¿CÓMO lo hace la naturaleza? Luego abstrae los principios y aplícalos al diseño. 🔬" },
    { titulo: "✅ Quiz: Estructura Orgánica", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tienen las estructuras orgánicas (huesos, conchas) para el diseño de robots?", opciones: ["Son bonitas", "Son ligeras pero resistentes gracias a su estructura interna optimizada", "Son más baratas", "Son fáciles de hacer"], respuestaCorrecta: 1, explicacion: "Los huesos son huecos pero fuertes, las conchas tienen estructuras hexagonales. ¡La naturaleza optimiza material vs resistencia! 🦴" },
    { titulo: "✅❌ Bio-diseño: ¿V o F?", tipo: 'true_false', statements: [{ text: 'La estructura del panal de abeja se usa en robótica y aeronáutica por su resistencia y ligereza.', correct: true, explain: 'La estructura hexagonal del panal maximiza la resistencia con el mínimo material. Se usa en chasis de robots y aviones.' }, { text: 'El bio-diseño solo se aplica a robots que tienen forma de animal.', correct: false, explain: 'Se aplica a cualquier robot: los principios biológicos pueden mejorar materiales, estructura, energía y control.' }] },
    { titulo: "🧩 Principios Bio-diseño", tipo: 'matching_game', instruccion: 'Conecta cada principio biológico con su aplicación', pairs: [{ left: 'Estructura de hueso', right: 'Chasis ligero y resistente' }, { left: 'Piel de tiburón', right: 'Superficie con baja resistencia' }, { left: 'Ojo de mosca', right: 'Cámaras de visión amplia' }, { left: 'Hoja de loto', right: 'Superficies autolimpiables' }] },
  ],
  'w3_mod16_proyecto_bio_final': [
    { titulo: "✅ Quiz: Proyecto Biónico", tipo: 'mini_quiz', pregunta: "¿Qué define a un proyecto de robótica biónica?", opciones: ["Usar robots muy grandes", "Integrar principios biológicos en un robot que resuelve un problema real", "Solo hacer un robot bonito", "Copiar otro proyecto"], respuestaCorrecta: 1, explicacion: "Un proyecto biónico combina biología + robótica para resolver un problema real: una mano protésica, un robot polinizador, etc. 🦾🌿" },
    { titulo: "✅ Quiz: Planificación Biónica", tipo: 'mini_quiz', pregunta: "¿Qué debe incluir la fase de planificación de un proyecto biónico?", opciones: ["Solo el presupuesto", "Investigación biológica, diseño del robot, lista de materiales y cronograma", "Solo el código", "Solo dibujos"], respuestaCorrecta: 1, explicacion: "Investiga el organismo, diseña el mecanismo, lista componentes y planifica las fases. ¡Ingeniería profesional! 📋" },
    { titulo: "✅ Quiz: Documentación Científica", tipo: 'mini_quiz', pregunta: "¿Por qué es importante documentar un proyecto biónico como un paper científico?", opciones: ["No es importante", "Para que otros puedan replicar, mejorar y contribuir al conocimiento", "Solo para la calificación", "Para vender más"], respuestaCorrecta: 1, explicacion: "La documentación científica permite: replicabilidad, mejoras futuras y contribuir a la comunidad de robótica. ¡Ciencia abierta! 📝" },
    { titulo: "✅ Quiz: Prototipo Rápido", tipo: 'mini_quiz', pregunta: "¿Qué es un prototipo rápido y por qué es útil en proyectos biónicos?", opciones: ["Un robot final", "Una versión simple para probar ideas rápido antes de invertir en la versión final", "Un robot rápido", "Un robot de carreras"], respuestaCorrecta: 1, explicacion: "¡Falla rápido, aprende rápido! Un prototipo con cartón y servos te muestra si tu idea funciona antes de gastar en la versión final. 🔧" },
    { titulo: "✅ Quiz: Métricas de Éxito", tipo: 'mini_quiz', pregunta: "¿Cómo mides si tu proyecto biónico fue exitoso?", opciones: ["Si se ve bonito", "Comparando las métricas medibles del robot vs los objetivos definidos", "Si funciona a veces", "Si cuesta mucho"], respuestaCorrecta: 1, explicacion: "Define métricas: ¿puede la garra levantar X gramos? ¿la prótesis se mueve en Y grados? ¡Mide y compara con tus objetivos! 📊" },
    { titulo: "✅❌ Proyecto Biónico: ¿V o F?", tipo: 'true_false', statements: [{ text: 'Los mejores proyectos biónicos combinan investigación biológica con ingeniería de robots.', correct: true, explain: 'La fusión de conocimiento biológico e ingeniería robótica produce las soluciones más innovadoras.' }, { text: 'Un proyecto biónico exitoso siempre debe ser comercializable.', correct: false, explain: 'Un proyecto exitoso resuelve un problema o genera conocimiento, no necesariamente tiene que venderse.' }] },
    { titulo: "🧩 Fases del Proyecto Biónico", tipo: 'matching_game', instruccion: 'Ordena las fases del proyecto final biónico', pairs: [{ left: '1️⃣ Investigar', right: 'Estudiar el organismo y el problema' }, { left: '2️⃣ Diseñar', right: 'Crear planos y lista de materiales' }, { left: '3️⃣ Construir', right: 'Montar y programar el robot' }, { left: '4️⃣ Evaluar', right: 'Medir resultados y documentar' }] },
  ],
};

console.log('=== WORLD 3: Nexo Biónico ===');
injectQuestions('src/data/world3Data.js', W3);
console.log('Done with World 3!');
