const fs = require('fs');

let lines = fs.readFileSync('src/data/world3Data.js', 'utf8').split('\n');

const questions = {
  'w3_mod1_biomimetica': [
    `            { titulo: "✅ Quiz: Velcro Biomimético", tipo: 'mini_quiz', pregunta: "¿Qué planta inspiró la invención del Velcro?", opciones: ["Rosa", "Bardana (sus semillas con ganchos microscópicos)", "Girasol", "Cactus"], respuestaCorrecta: 1, explicacion: "George de Mestral observó cómo las semillas de bardana se pegaban al pelo de su perro. Los ganchos microscópicos inspiraron el Velcro. 🐕" },`,
    `            { titulo: "✅ Quiz: Evolución como Diseñadora", tipo: 'mini_quiz', pregunta: "¿Cuántos años de 'prueba y error' tiene la evolución natural?", opciones: ["1,000 años", "1 millón de años", "Más de 3,800 millones de años", "100 años"], respuestaCorrecta: 2, explicacion: "La vida lleva ~3,800 millones de años evolucionando. Cada organismo es un diseño optimizado por selección natural. 🧬" },`,
    `            { titulo: "✅ Quiz: Gecko Robot", tipo: 'mini_quiz', pregunta: "¿Qué tecnología robótica se inspiró en las patas del gecko?", opciones: ["Motores más rápidos", "Adhesivos secos que permiten escalar paredes lisas", "Cámaras infrarrojas", "Paneles solares"], respuestaCorrecta: 1, explicacion: "Las patas del gecko usan fuerzas de Van der Waals con millones de pelos microscópicos. Se replicó en robots escaladores. 🦎" },`,
    `            { titulo: "✅ Quiz: Tren Bala Biomimético", tipo: 'mini_quiz', pregunta: "¿Qué ave inspiró el diseño del tren bala Shinkansen?", opciones: ["Águila", "Martín pescador (su pico reduce la resistencia del aire)", "Pingüino", "Colibrí"], respuestaCorrecta: 1, explicacion: "El pico del martín pescador corta el agua sin salpicar. El tren bala copió esa forma para reducir el boom sónico al salir de túneles. 🚄" },`,
  ],
  'w3_mod2_locomocion': [
    `            { titulo: "✅ Quiz: Patas vs Ruedas", tipo: 'mini_quiz', pregunta: "¿Cuándo son mejores las patas que las ruedas en un robot?", opciones: ["Siempre", "En terreno irregular, escaleras y superficies con obstáculos", "Nunca", "Solo en superficies planas"], respuestaCorrecta: 1, explicacion: "Las patas superan a las ruedas en terreno irregular: pueden pisar sobre obstáculos, subir escaleras y adaptarse al terreno. 🦿" },`,
    `            { titulo: "✅ Quiz: Locomoción Serpentina", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene la locomoción serpentina (como una serpiente)?", opciones: ["Es más rápida", "Puede entrar en espacios estrechos y moverse sin patas", "Es más fácil de programar", "Usa menos energía siempre"], respuestaCorrecta: 1, explicacion: "Los robots serpiente pueden entrar en tuberías, escombros y espacios reducidos donde otros robots no caben. Perfectos para rescate. 🐍" },`,
    `            { titulo: "✅ Quiz: Robot Hexápodo", tipo: 'mini_quiz', pregunta: "¿Por qué muchos robots caminantes usan 6 patas (hexápodos)?", opciones: ["Porque se ven mejor", "Porque pueden mantener siempre 3 patas en el suelo (trípode alterno)", "Porque son más baratos", "Porque van más rápido"], respuestaCorrecta: 1, explicacion: "Con 6 patas, el robot puede caminar con trípode alterno: 3 patas apoyadas, 3 en el aire. Máxima estabilidad sin caerse. 🕷️" },`,
    `            { titulo: "✅ Quiz: Nado Robótico", tipo: 'mini_quiz', pregunta: "¿Qué animal inspiró los robots submarinos más eficientes?", opciones: ["Ballena", "Atún y otros peces que usan la cola para propulsión", "Cangrejo", "Oso polar"], respuestaCorrecta: 1, explicacion: "Los peces como el atún son increíblemente eficientes. El robot RoboTuna del MIT copia su movimiento de cola para nadar con mínima energía. 🐟" },`,
  ],
  'w3_mod3_musculos_artificiales': [
    `            { titulo: "✅ Quiz: SMA (Aleación con Memoria)", tipo: 'mini_quiz', pregunta: "¿Qué hace especial a una aleación con memoria de forma (SMA)?", opciones: ["Brilla en la oscuridad", "Se deforma y vuelve a su forma original al calentarse", "Es más pesada que el acero", "Solo existe en laboratorios"], respuestaCorrecta: 1, explicacion: "Los alambres SMA (como Nitinol) se contraen al calentarse y vuelven a su forma. Son músculos artificiales ligeros y silenciosos. 🔥" },`,
    `            { titulo: "✅ Quiz: Actuadores Neumáticos", tipo: 'mini_quiz', pregunta: "¿Qué usan los músculos neumáticos artificiales (McKibben) para generar fuerza?", opciones: ["Electricidad", "Aire comprimido que infla una malla trenzada", "Imanes", "Resortes"], respuestaCorrecta: 1, explicacion: "Los músculos McKibben se inflan con aire comprimido. La malla trenzada se acorta al inflarse, generando fuerza como un bíceps. 💪" },`,
    `            { titulo: "✅ Quiz: EAP", tipo: 'mini_quiz', pregunta: "¿Qué son los polímeros electroactivos (EAP)?", opciones: ["Plásticos reciclados", "Materiales que cambian de forma al aplicarles voltaje", "Cables eléctricos", "Sensores de presión"], respuestaCorrecta: 1, explicacion: "Los EAP son plásticos que se deforman con electricidad. Son los músculos artificiales más parecidos a los biológicos. Ligeros y flexibles. 🔬" },`,
    `            { titulo: "✅ Quiz: Hidráulica vs Neumática", tipo: 'mini_quiz', pregunta: "¿Cuál es la diferencia principal entre actuadores hidráulicos y neumáticos?", opciones: ["No hay diferencia", "Los hidráulicos usan líquido (más fuerza) y los neumáticos usan aire (más velocidad)", "Los hidráulicos son más baratos", "Los neumáticos son más pesados"], respuestaCorrecta: 1, explicacion: "¡Líquido vs aire! Los hidráulicos dan más fuerza (excavadoras), los neumáticos son más rápidos y limpios (robots industriales). ⚙️" },`,
  ],
  'w3_mod4_sentidos_bio': [
    `            { titulo: "✅ Quiz: Electro-recepción", tipo: 'mini_quiz', pregunta: "¿Qué sentido tiene el tiburón que se ha copiado en robots?", opciones: ["Super vista", "Electro-recepción: detectar campos eléctricos de otros seres vivos", "Super olfato", "Ecolocalización"], respuestaCorrecta: 1, explicacion: "Los tiburones detectan los campos eléctricos de sus presas. Robots submarinos copian esto para navegar y detectar objetos metálicos. ⚡🦈" },`,
    `            { titulo: "✅ Quiz: Visión Compuesta", tipo: 'mini_quiz', pregunta: "¿Qué ventaja tiene la visión compuesta de los insectos para robots?", opciones: ["Ven en color", "Campo visual de casi 360° y detección ultra-rápida de movimiento", "Ven más lejos", "Ven en la oscuridad"], respuestaCorrecta: 1, explicacion: "Los ojos compuestos de las moscas tienen miles de lentes. Detectan movimiento en milisegundos. Inspiraron cámaras robóticas panorámicas. 🪰" },`,
    `            { titulo: "✅ Quiz: Línea Lateral", tipo: 'mini_quiz', pregunta: "¿Qué sentido de los peces se replica en robots submarinos?", opciones: ["Gusto", "Línea lateral: detecta vibraciones y corrientes en el agua", "Tacto", "Oído"], respuestaCorrecta: 1, explicacion: "La línea lateral de los peces detecta presión y movimiento del agua. Robots submarinos la copian para navegar sin visión. 🐠" },`,
    `            { titulo: "✅ Quiz: Bigotes de Rata", tipo: 'mini_quiz', pregunta: "¿Qué sensores robóticos se inspiraron en los bigotes (vibrisas) de las ratas?", opciones: ["Cámaras", "Sensores táctiles de alta sensibilidad para detectar texturas y formas", "Micrófonos", "Sensores de gas"], respuestaCorrecta: 1, explicacion: "Las vibrisas de las ratas detectan textura, forma y movimiento del aire. Robots con bigotes artificiales navegan en oscuridad total. 🐀" },`,
  ],
  'w3_mod5_protesis_intro': [
    `            { titulo: "✅ Quiz: Prótesis Mioeléctricas", tipo: 'mini_quiz', pregunta: "¿Cómo se controlan las prótesis mioeléctricas?", opciones: ["Con botones", "Detectando las señales eléctricas de los músculos del usuario (EMG)", "Con control remoto", "Con la voz"], respuestaCorrecta: 1, explicacion: "Los sensores EMG detectan la actividad eléctrica de los músculos restantes. El usuario piensa en mover la mano y la prótesis responde. 🦾" },`,
    `            { titulo: "✅ Quiz: Retroalimentación Sensorial", tipo: 'mini_quiz', pregunta: "¿Por qué es importante que una prótesis tenga sensores de presión?", opciones: ["Para verse moderna", "Para que el usuario sienta cuánta fuerza aplica y no rompa objetos", "Para conectarse a Internet", "No es importante"], respuestaCorrecta: 1, explicacion: "Sin retroalimentación, el usuario no sabe si aplasta un huevo o sostiene bien una taza. Los sensores cierran el ciclo sensorial. 🥚" },`,
    `            { titulo: "✅ Quiz: Impresión 3D de Prótesis", tipo: 'mini_quiz', pregunta: "¿Cómo ha revolucionado la impresión 3D las prótesis?", opciones: ["No ha cambiado nada", "Reduce el costo de $50,000 a menos de $50 y permite personalización", "Solo las hace más bonitas", "Las hace más pesadas"], respuestaCorrecta: 1, explicacion: "Proyectos como e-NABLE imprimen prótesis de mano por menos de $50. Antes costaban miles de dólares. ¡Acceso para todos! 🖨️" },`,
    `            { titulo: "✅ Quiz: Grados de Libertad Prótesis", tipo: 'mini_quiz', pregunta: "¿Cuántos grados de libertad tiene una mano humana real?", opciones: ["5", "27 (considerando todas las articulaciones)", "10", "3"], respuestaCorrecta: 1, explicacion: "La mano humana tiene 27 grados de libertad. Las mejores prótesis actuales logran 6-8 DOF. ¡Aún hay mucho por mejorar! 🤚" },`,
  ],
  'w3_mod6_exoesqueletos': [
    `            { titulo: "✅ Quiz: Tipos de Exoesqueletos", tipo: 'mini_quiz', pregunta: "¿Para qué se usan los exoesqueletos en rehabilitación médica?", opciones: ["Solo para levantar peso", "Para ayudar a pacientes con lesiones medulares a caminar de nuevo", "Para militares solamente", "Para deportes"], respuestaCorrecta: 1, explicacion: "Exoesqueletos como ReWalk permiten que personas con parálisis caminen. Los motores mueven las piernas siguiendo patrones de marcha. 🚶" },`,
    `            { titulo: "✅ Quiz: Exo Industrial", tipo: 'mini_quiz', pregunta: "¿Qué problema resuelven los exoesqueletos en fábricas?", opciones: ["Que los trabajadores corran más rápido", "Reducen lesiones de espalda al levantar cargas pesadas repetidamente", "Mejoran la vista", "No resuelven nada"], respuestaCorrecta: 1, explicacion: "Los exoesqueletos industriales (como los de Ford para trabajadores) reducen la fatiga muscular un 40% y previenen lesiones laborales. 🏭" },`,
    `            { titulo: "✅ Quiz: HAL Exoesqueleto", tipo: 'mini_quiz', pregunta: "¿Qué hace especial al exoesqueleto HAL de Cyberdyne?", opciones: ["Es el más barato", "Lee señales nerviosas del cerebro antes de que el músculo se mueva", "Solo funciona en agua", "Es invisible"], respuestaCorrecta: 1, explicacion: "HAL detecta las señales bioeléctricas del cerebro 0.01s ANTES de que el músculo actúe. Se anticipa al movimiento del usuario. 🧠" },`,
  ],
  'w3_mod7_wearables': [
    `            { titulo: "✅ Quiz: Sensores Wearables", tipo: 'mini_quiz', pregunta: "¿Qué datos pueden medir los wearables de salud?", opciones: ["Solo la hora", "Ritmo cardíaco, oxígeno en sangre, temperatura y actividad", "Solo los pasos", "Solo la presión"], respuestaCorrecta: 1, explicacion: "Los smartwatches modernos miden: ritmo cardíaco (PPG), SpO2, temperatura, pasos, sueño y hasta ECG. ¡Un hospital en la muñeca! ⌚" },`,
    `            { titulo: "✅ Quiz: PPG Sensor", tipo: 'mini_quiz', pregunta: "¿Cómo mide un smartwatch el ritmo cardíaco?", opciones: ["Con un micrófono", "Con un LED verde que detecta cambios de flujo sanguíneo (fotopletismografía)", "Con presión", "Con ultrasonido"], respuestaCorrecta: 1, explicacion: "PPG: un LED verde ilumina la piel. La sangre absorbe más luz verde cuando el corazón bombea. El sensor detecta los pulsos. 💚" },`,
    `            { titulo: "✅ Quiz: IMU Wearable", tipo: 'mini_quiz', pregunta: "¿Qué es un IMU y para qué se usa en wearables?", opciones: ["Un tipo de batería", "Unidad de Medición Inercial: acelerómetro + giroscopio para detectar movimiento", "Un procesador", "Una pantalla"], respuestaCorrecta: 1, explicacion: "IMU = acelerómetro + giroscopio (+ magnetómetro). Detecta orientación, pasos, caídas y gestos. Esencial en smartwatches y VR. 📐" },`,
    `            { titulo: "✅ Quiz: Textiles Inteligentes", tipo: 'mini_quiz', pregunta: "¿Qué son los e-textiles o textiles inteligentes?", opciones: ["Ropa cara", "Telas con sensores y circuitos integrados que miden datos del cuerpo", "Ropa que brilla", "Telas impermeables"], respuestaCorrecta: 1, explicacion: "Los e-textiles integran sensores y conductores en la tela. Miden movimiento, presión, temperatura y hasta señales musculares. ¡Ropa robótica! 👕" },`,
  ],
  'w3_mod8_interfaz_cerebro': [
    `            { titulo: "✅ Quiz: EEG", tipo: 'mini_quiz', pregunta: "¿Qué mide un electroencefalograma (EEG)?", opciones: ["La presión arterial", "La actividad eléctrica del cerebro mediante electrodos en el cuero cabelludo", "La temperatura", "El oxígeno"], respuestaCorrecta: 1, explicacion: "El EEG detecta ondas cerebrales (alfa, beta, delta, theta). Se usan en BCIs para que personas con parálisis controlen dispositivos. 🧠" },`,
    `            { titulo: "✅ Quiz: BCI Invasivo vs No Invasivo", tipo: 'mini_quiz', pregunta: "¿Cuál es la diferencia entre una BCI invasiva y no invasiva?", opciones: ["No hay diferencia", "La invasiva implanta electrodos en el cerebro; la no invasiva usa sensores externos", "La invasiva es más barata", "La no invasiva es más precisa"], respuestaCorrecta: 1, explicacion: "Las BCIs invasivas (como Neuralink) dan señales más precisas, pero requieren cirugía. Las no invasivas (EEG) son seguras pero menos precisas. ⚕️" },`,
    `            { titulo: "✅ Quiz: Ondas Cerebrales", tipo: 'mini_quiz', pregunta: "¿Qué tipo de onda cerebral indica concentración intensa?", opciones: ["Ondas delta (sueño profundo)", "Ondas beta (actividad mental enfocada)", "Ondas alfa (relajación)", "Ondas theta (somnolencia)"], respuestaCorrecta: 1, explicacion: "Ondas beta (13-30 Hz) = concentración. Las BCIs pueden detectar cuándo te concentras y usar eso como comando. ¡Controlar con la mente! 🎯" },`,
    `            { titulo: "✅ Quiz: Aplicaciones BCI", tipo: 'mini_quiz', pregunta: "¿Qué pueden hacer las interfaces cerebro-computadora actualmente?", opciones: ["Leer pensamientos completos", "Mover cursores, escribir texto, controlar sillas de ruedas y prótesis", "Teletransportar objetos", "Nada práctico todavía"], respuestaCorrecta: 1, explicacion: "Las BCIs actuales permiten escribir texto, mover cursores, controlar prótesis y sillas de ruedas. ¡Revolucionario para personas con discapacidad! 🖥️" },`,
  ],
  'w3_mod9_robots_blandos': [
    `            { titulo: "✅ Quiz: Materiales Blandos", tipo: 'mini_quiz', pregunta: "¿Qué material principal se usa en robots blandos?", opciones: ["Acero", "Silicona y elastómeros flexibles", "Madera", "Vidrio"], respuestaCorrecta: 1, explicacion: "Los robots blandos usan silicona, caucho y elastómeros. Se deforman sin romperse y se adaptan a cualquier forma. ¡Como un pulpo! 🐙" },`,
    `            { titulo: "✅ Quiz: Actuación Neumática Blanda", tipo: 'mini_quiz', pregunta: "¿Cómo se mueve un robot blando neumático?", opciones: ["Con motores eléctricos", "Inflando y desinflando cámaras de aire dentro de su cuerpo flexible", "Con ruedas internas", "Con imanes"], respuestaCorrecta: 1, explicacion: "Las cámaras de aire se inflan selectivamente, causando que el cuerpo flexible se curve o extienda. ¡Como los tentáculos de un pulpo! 🫧" },`,
    `            { titulo: "✅ Quiz: Ventajas de Robots Blandos", tipo: 'mini_quiz', pregunta: "¿En qué situación es mejor un robot blando que uno rígido?", opciones: ["Siempre", "Manipulando objetos frágiles como frutas o trabajando cerca de humanos", "Nunca", "Solo en el espacio"], respuestaCorrecta: 1, explicacion: "Los robots blandos son inherentemente seguros: no pueden lastimar personas ni aplastar objetos delicados. Perfectos para agricultura y medicina. 🍅" },`,
    `            { titulo: "✅ Quiz: Octobot", tipo: 'mini_quiz', pregunta: "¿Qué hizo especial al Octobot de Harvard?", opciones: ["Era muy grande", "Fue el primer robot completamente blando sin ningún componente rígido", "Era el más rápido", "Podía volar"], respuestaCorrecta: 1, explicacion: "El Octobot (2016) fue 100% blando: sin baterías, cables ni chips rígidos. Usa reacciones químicas para moverse. ¡Revolución robótica! 🐙" },`,
  ],
  'w3_mod10_bioimpresion': [
    `            { titulo: "✅ Quiz: Bioink", tipo: 'mini_quiz', pregunta: "¿Qué es el bio-ink (bio-tinta) en bioimpresión 3D?", opciones: ["Tinta de colores", "Una mezcla de células vivas y biomateriales que se imprime capa a capa", "Pintura para robots", "Tinta de impresora normal"], respuestaCorrecta: 1, explicacion: "El bio-ink contiene células vivas mezcladas con hidrogeles. La bioimpresora las deposita capa a capa para crear tejidos. ¡Imprimir vida! 🧬" },`,
    `            { titulo: "✅ Quiz: Aplicaciones Bioimpresión", tipo: 'mini_quiz', pregunta: "¿Qué se ha logrado bioiprimir exitosamente hasta ahora?", opciones: ["Cerebros completos", "Cartílago de oreja, piel, vasos sanguíneos y mini-órganos (organoides)", "Corazones funcionales completos", "Robots vivientes"], respuestaCorrecta: 1, explicacion: "Se han bioimpreso orejas de cartílago, parches de piel, vasos y organoides para pruebas de fármacos. Órganos completos son el futuro. 🖨️" },`,
    `            { titulo: "✅ Quiz: Xenobot", tipo: 'mini_quiz', pregunta: "¿Qué son los Xenobots?", opciones: ["Robots de metal", "Organismos vivos diseñados por computadora a partir de células de rana", "Programa de computadora", "Bacterias genéticamente modificadas"], respuestaCorrecta: 1, explicacion: "Los Xenobots son 'robots vivientes' creados en 2020 con células de rana Xenopus. Pueden moverse, autorrepararse y hasta replicarse. 🐸" },`,
    `            { titulo: "✅ Quiz: Scaffold", tipo: 'mini_quiz', pregunta: "¿Para qué sirve el scaffold (andamiaje) en bioimpresión?", opciones: ["Para decorar", "Como estructura temporal donde las células crecen y forman el tejido", "Para proteger el robot", "Para almacenar datos"], respuestaCorrecta: 1, explicacion: "El scaffold es como los andamios de un edificio: da forma mientras las células crecen y se organizan. Luego el scaffold se degrada. 🏗️" },`,
  ],
  'w3_mod11_ecosistemas': [
    `            { titulo: "✅ Quiz: Robots Ambientales", tipo: 'mini_quiz', pregunta: "¿Cómo ayudan los robots a proteger ecosistemas?", opciones: ["Destruyendo plagas", "Monitoreando fauna, midiendo contaminación y plantando árboles automáticamente", "No ayudan", "Solo en zoológicos"], respuestaCorrecta: 1, explicacion: "Robots como drones plantan 10,000 árboles/día, monitorean especies en peligro y miden calidad del agua y aire. ¡Guardianes tecnológicos! 🌳" },`,
    `            { titulo: "✅ Quiz: Robot Coral", tipo: 'mini_quiz', pregunta: "¿Qué hace el robot LarvalBot en los arrecifes de coral?", opciones: ["Destruye coral", "Distribuye larvas de coral para restaurar arrecifes dañados", "Pesca automáticamente", "Mide la profundidad"], respuestaCorrecta: 1, explicacion: "LarvalBot distribuye larvas de coral sobre arrecifes dañados. Un solo robot puede cubrir áreas enormes, acelerando la restauración marina. 🪸" },`,
    `            { titulo: "✅ Quiz: Robótica Agrícola", tipo: 'mini_quiz', pregunta: "¿Qué tarea agrícola pueden hacer los robots mejor que los humanos?", opciones: ["Ninguna", "Cosecha selectiva 24/7 identificando frutos maduros con visión artificial", "Solo arar", "Solo regar"], respuestaCorrecta: 1, explicacion: "Robots con visión artificial identifican frutas maduras y las cosechan delicadamente. Trabajan 24/7 sin fatiga y reducen desperdicio. 🍓" },`,
    `            { titulo: "✅ Quiz: Drones Antiincendios", tipo: 'mini_quiz', pregunta: "¿Cómo ayudan los drones en la prevención de incendios forestales?", opciones: ["Apagando fuegos con agua", "Detectando puntos calientes con cámaras térmicas antes de que el fuego se propague", "No ayudan", "Cortando árboles"], respuestaCorrecta: 1, explicacion: "Los drones con cámaras térmicas e IR detectan puntos calientes invisibles al ojo humano. Alertan antes de que el fuego crezca. 🔥" },`,
  ],
  'w3_mod12_enjambres': [
    `            { titulo: "✅ Quiz: Reglas de Enjambre", tipo: 'mini_quiz', pregunta: "¿Cuáles son las 3 reglas básicas de comportamiento de enjambre (boids)?", opciones: ["Atacar, defender, huir", "Separación, alineación y cohesión", "Avanzar, girar, parar", "Subir, bajar, flotar"], respuestaCorrecta: 1, explicacion: "Las 3 reglas de Craig Reynolds: separación (no chocar), alineación (ir en la misma dirección) y cohesión (mantenerse juntos). Emerge orden del caos. 🐦" },`,
    `            { titulo: "✅ Quiz: Kilobots", tipo: 'mini_quiz', pregunta: "¿Qué demostró el experimento con 1,024 Kilobots de Harvard?", opciones: ["Que los robots son caros", "Que robots simples pueden formar patrones complejos cooperando sin control central", "Que necesitan GPS", "Que solo funcionan solos"], respuestaCorrecta: 1, explicacion: "1,024 Kilobots simples formaron estrellas, letras y formas complejas SIN ningún líder. Solo comunicación local entre vecinos. ¡Inteligencia emergente! ⭐" },`,
    `            { titulo: "✅ Quiz: Ventajas del Enjambre", tipo: 'mini_quiz', pregunta: "¿Cuál es la mayor ventaja de usar un enjambre de robots en vez de uno grande?", opciones: ["Son más bonitos", "Redundancia: si uno falla, los demás continúan la misión", "Son más rápidos", "Usan menos energía total"], respuestaCorrecta: 1, explicacion: "Si un robot del enjambre falla, los demás se reorganizan y completan la tarea. Un robot grande que falla = misión cancelada. 🔄" },`,
    `            { titulo: "✅ Quiz: Comunicación Local", tipo: 'mini_quiz', pregunta: "¿Cómo se comunican los robots de un enjambre típicamente?", opciones: ["Por Internet", "Solo con sus vecinos cercanos usando IR, radio o WiFi de corto alcance", "Por satélite", "Con cables"], respuestaCorrecta: 1, explicacion: "Cada robot solo 'habla' con sus vecinos inmediatos. No hay un computador central. El comportamiento global emerge de interacciones locales. 📡" },`,
  ],
  'w3_mod13_micro_robots': [
    `            { titulo: "✅ Quiz: Nanorobots Médicos", tipo: 'mini_quiz', pregunta: "¿Cuál es la aplicación más prometedora de los nanorobots?", opciones: ["Construir edificios", "Entregar medicamentos directamente a células enfermas dentro del cuerpo", "Limpiar casas", "Cocinar"], respuestaCorrecta: 1, explicacion: "Los nanorobots médicos podrían llevar quimioterapia directamente a células cancerosas, sin afectar tejido sano. ¡Medicina de precisión! 💊" },`,
    `            { titulo: "✅ Quiz: MEMS", tipo: 'mini_quiz', pregunta: "¿Qué son los MEMS y dónde los encuentras?", opciones: ["Memorias de computador", "Sistemas Micro-Electromecánicos: sensores diminutos en celulares y autos", "Un tipo de robot grande", "Cables microscópicos"], respuestaCorrecta: 1, explicacion: "MEMS = sensores y actuadores microscópicos. Tu celular tiene ~10 MEMS: acelerómetro, giroscopio, micrófono, barómetro... 📱" },`,
    `            { titulo: "✅ Quiz: Propulsión Micro", tipo: 'mini_quiz', pregunta: "¿Cómo se mueven los microrobots dentro del cuerpo humano?", opciones: ["Con ruedas", "Con flagelos magnéticos, reacciones químicas o campos magnéticos externos", "Con hélices", "Con cohetes"], respuestaCorrecta: 1, explicacion: "Los microrobots usan flagelos (como bacterias), burbujas químicas o son guiados por imanes externos. ¡Navegar por el torrente sanguíneo! 🧲" },`,
    `            { titulo: "✅ Quiz: Escala Micro", tipo: 'mini_quiz', pregunta: "¿Qué desafío especial enfrentan los robots a escala micrométrica?", opciones: ["Son muy caros", "Las fuerzas de superficie (adhesión, viscosidad) dominan sobre la gravedad", "No tienen color", "Son demasiado rápidos"], respuestaCorrecta: 1, explicacion: "A escala micro, las fuerzas de Van der Waals y la viscosidad del fluido dominan. Un microrobot 'nada' en fluido como tú nadarías en miel. 🔬" },`,
  ],
  'w3_mod14_bioetica': [
    `            { titulo: "✅ Quiz: Principios Bioéticos", tipo: 'mini_quiz', pregunta: "¿Cuáles son los principios fundamentales de la bioética en robótica?", opciones: ["Solo ganar dinero", "Beneficencia, no maleficencia, autonomía y justicia", "Solo seguridad", "No hay principios"], respuestaCorrecta: 1, explicacion: "Los 4 principios: hacer el bien (beneficencia), no hacer daño (no maleficencia), respetar decisiones (autonomía) y acceso equitativo (justicia). ⚖️" },`,
    `            { titulo: "✅ Quiz: Sesgo en IA", tipo: 'mini_quiz', pregunta: "¿Qué es el sesgo algorítmico en robots con IA?", opciones: ["Un error de hardware", "Cuando la IA toma decisiones injustas basadas en datos de entrenamiento sesgados", "Un tipo de sensor", "No existe"], respuestaCorrecta: 1, explicacion: "Si una IA se entrena con datos sesgados, discrimina. Un robot médico podría dar peor servicio a ciertos grupos. La diversidad en datos es crucial. 🔍" },`,
    `            { titulo: "✅ Quiz: Derecho a la Privacidad", tipo: 'mini_quiz', pregunta: "¿Qué problema ético generan los robots con cámaras y micrófonos en el hogar?", opciones: ["Ninguno", "Pueden grabar y almacenar datos privados sin consentimiento adecuado", "Solo estético", "Usan mucha electricidad"], respuestaCorrecta: 1, explicacion: "Los robots domésticos con sensores pueden recopilar datos íntimos. Es crucial garantizar privacidad, consentimiento y seguridad de datos. 🔒" },`,
    `            { titulo: "✅ Quiz: Responsabilidad Robot", tipo: 'mini_quiz', pregunta: "Si un robot autónomo causa un accidente, ¿quién es responsable?", opciones: ["Nadie", "Es un debate abierto: ¿el fabricante, el programador, el usuario o el propio robot?", "Solo el robot", "Solo el usuario"], respuestaCorrecta: 1, explicacion: "¡Gran debate legal! Si un auto autónomo choca, ¿quién paga? Se necesitan nuevas leyes para la era robótica. La responsabilidad es compartida. 🏛️" },`,
  ],
  'w3_mod15_diseno_bio': [
    `            { titulo: "✅ Quiz: Proceso de Diseño Bio", tipo: 'mini_quiz', pregunta: "¿Cuál es el primer paso en el diseño biomimético?", opciones: ["Construir el robot", "Observar un organismo natural y analizar cómo resuelve el problema", "Comprar materiales", "Programar"], respuestaCorrecta: 1, explicacion: "El diseño biomimético empieza con la naturaleza: observar → abstraer el principio → implementar en ingeniería. ¡La naturaleza primero! 🔬" },`,
    `            { titulo: "✅ Quiz: Prototipado Rápido", tipo: 'mini_quiz', pregunta: "¿Qué tecnología permite crear prototipos de biorobots rápidamente?", opciones: ["Soldadura manual", "Impresión 3D con materiales flexibles como TPU y silicona", "Tallado en madera", "Solo simulación"], respuestaCorrecta: 1, explicacion: "La impresión 3D con TPU (flexible) y silicona permite crear gripers blandos, patas articuladas y cuerpos biomórficos en horas. 🖨️" },`,
    `            { titulo: "✅ Quiz: Simulación", tipo: 'mini_quiz', pregunta: "¿Por qué es importante simular antes de construir un biorobot?", opciones: ["Para perder tiempo", "Para probar diseños virtualmente y ahorrar materiales y tiempo", "No es importante", "Solo para presentaciones"], respuestaCorrecta: 1, explicacion: "La simulación permite probar miles de diseños en minutos sin gastar materiales. Software como Gazebo o V-REP simulan física real. 💻" },`,
    `            { titulo: "✅ Quiz: Iteración Biomimética", tipo: 'mini_quiz', pregunta: "¿Por qué los diseños biomiméticos requieren muchas iteraciones?", opciones: ["Porque los ingenieros son lentos", "Porque la naturaleza es compleja y cada iteración revela nuevos detalles a copiar", "No requieren iteraciones", "Solo hacen 2 versiones"], respuestaCorrecta: 1, explicacion: "Cada prototipo enseña algo nuevo. La naturaleza optimizó durante millones de años, no podemos copiarla en un intento. ¡Iterar es evolucionar! 🔄" },`,
  ],
  'w3_mod16_proyecto_bio_final': [
    `            { titulo: "✅ Quiz: Planificación Bio-Proyecto", tipo: 'mini_quiz', pregunta: "¿Qué debe incluir la propuesta de un proyecto de biorobótica?", opciones: ["Solo el nombre", "Organismo inspirador, problema a resolver, sensores/actuadores y plan de pruebas", "Solo el presupuesto", "Solo fotos"], respuestaCorrecta: 1, explicacion: "Una propuesta completa: ¿qué animal/planta inspira? ¿qué problema resuelve? ¿qué componentes usa? ¿cómo lo pruebas? ¡Planificar es ganar! 📋" },`,
    `            { titulo: "✅ Quiz: Métricas de Éxito", tipo: 'mini_quiz', pregunta: "¿Cómo se mide el éxito de un proyecto de biorobótica?", opciones: ["Solo si se ve bonito", "Comparando el rendimiento del robot con el organismo natural que imita", "Solo por el costo", "No se puede medir"], respuestaCorrecta: 1, explicacion: "El éxito se mide comparando: eficiencia, velocidad, adaptabilidad. Si imitas un gecko, ¿sube paredes? ¿qué tan bien vs el real? 📊" },`,
    `            { titulo: "✅ Quiz: Presentación Científica", tipo: 'mini_quiz', pregunta: "¿Qué secciones debe tener la documentación de un proyecto de biorobótica?", opciones: ["Solo fotos del robot", "Introducción, investigación biológica, diseño, construcción, resultados y conclusiones", "Solo el código", "Solo el circuito"], respuestaCorrecta: 1, explicacion: "Como un paper científico: intro → biología del organismo → diseño del robot → resultados → conclusiones → mejoras futuras. ¡Sé científico! 📄" },`,
    `            { titulo: "✅ Quiz: Futuro de la Biorobótica", tipo: 'mini_quiz', pregunta: "¿Cuál es la frontera más emocionante de la biorobótica actual?", opciones: ["Robots más grandes", "Robots que combinan componentes vivos y artificiales (biohíbridos)", "Robots más baratos", "Robots más ruidosos"], respuestaCorrecta: 1, explicacion: "Los robots biohíbridos usan células musculares vivas + estructuras artificiales. ¡Máquinas que crecen, se reparan y evolucionan! 🧬🤖" },`,
  ],
};

// For each module, find its ID in file, then scan forward for the line ending with },]
const modulePositions = [];
for (const moduleId of Object.keys(questions)) {
  let found = false;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes(`'${moduleId}'`)) {
      for (let j = i + 1; j < lines.length; j++) {
        if (lines[j].replace(/\r$/, '').endsWith('},]')) {
          modulePositions.push({ moduleId, closingLine: j });
          found = true;
          break;
        }
      }
      break;
    }
  }
  if (!found) console.log('NOT FOUND:', moduleId);
}

console.log('Found', modulePositions.length, 'module closing lines');

// Sort by closingLine DESCENDING so insertions don't shift earlier line numbers
modulePositions.sort((a, b) => b.closingLine - a.closingLine);

let total = 0;
for (const { moduleId, closingLine } of modulePositions) {
  const qLines = questions[moduleId];
  if (!qLines) continue;

  // Remove trailing ] from the closing line (keep the },)
  lines[closingLine] = lines[closingLine].replace(/\r$/, '').replace(/\]\s*$/, '');

  // Insert new quiz lines after the closing line, then close the array with ]
  const newLines = [...qLines, '        ]'];
  lines.splice(closingLine + 1, 0, ...newLines);

  total += qLines.length;
  console.log(`${moduleId}: +${qLines.length} questions at line ${closingLine + 1}`);
}

fs.writeFileSync('src/data/world3Data.js', lines.join('\n'));
console.log(`\nTotal: ${total} questions injected into World 3`);
